mod users;

mod patients;
mod practitioners;
mod endocrinology_waiting_list_cards;
mod endocrinology_waiting_list_card_appointments;
mod endocrinology_waiting_list_card_grades;
mod endocrinology_waiting_list_card_grade_rules;
mod endocrinology_waiting_list_card_grade_flags;