import type { PatientRow } from './types.ts';

/** Sample emergency unit (general) patient encounters for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		patientName: 'Adams, Olivia',
		dateOfBirth: '1981-04-22',
		sex: 'F',
		arrivalMode: 'ambulance',
		chiefComplaint: 'Severe chest pain radiating to left arm',
		avpu: 'A',
		highRiskSignsPresent: true,
		disposition: 'admit',
		urgentFlagCount: 3,
		providerName: 'Dr. Mensah',
		dispositionAt: '2026-04-12T10:45:00Z',
	},
	{
		id: '2',
		patientName: 'Bashir, Amir',
		dateOfBirth: '1958-12-03',
		sex: 'M',
		arrivalMode: 'stretcher',
		chiefComplaint: 'Sudden shortness of breath, productive cough',
		avpu: 'V',
		highRiskSignsPresent: true,
		disposition: 'admit',
		urgentFlagCount: 2,
		providerName: 'Dr. Okafor',
		dispositionAt: '2026-04-13T15:20:00Z',
	},
	{
		id: '3',
		patientName: 'Chen, Wei',
		dateOfBirth: '1995-07-15',
		sex: 'F',
		arrivalMode: 'walking',
		chiefComplaint: 'Lower abdominal pain, nausea',
		avpu: 'A',
		highRiskSignsPresent: false,
		disposition: 'discharge',
		urgentFlagCount: 0,
		providerName: 'Dr. Thompson',
		dispositionAt: '2026-04-14T09:10:00Z',
	},
	{
		id: '4',
		patientName: 'Diallo, Mariama',
		dateOfBirth: '1972-09-30',
		sex: 'F',
		arrivalMode: 'wheelchair',
		chiefComplaint: 'Dizziness, palpitations',
		avpu: 'A',
		highRiskSignsPresent: false,
		disposition: 'discharge',
		urgentFlagCount: 1,
		providerName: 'Dr. Mensah',
		dispositionAt: '2026-04-15T11:55:00Z',
	},
	{
		id: '5',
		patientName: 'Engström, Lars',
		dateOfBirth: '1949-02-18',
		sex: 'M',
		arrivalMode: 'ambulance',
		chiefComplaint: 'Altered mental status, fever',
		avpu: 'P',
		highRiskSignsPresent: true,
		disposition: 'admit',
		urgentFlagCount: 4,
		providerName: 'Dr. Okafor',
		dispositionAt: '2026-04-16T07:30:00Z',
	},
	{
		id: '6',
		patientName: 'Fernandes, Carla',
		dateOfBirth: '1988-06-09',
		sex: 'F',
		arrivalMode: 'walking',
		chiefComplaint: 'Severe headache, photophobia',
		avpu: 'A',
		highRiskSignsPresent: true,
		disposition: 'transfer',
		urgentFlagCount: 2,
		providerName: 'Dr. Thompson',
		dispositionAt: '2026-04-17T13:45:00Z',
	},
	{
		id: '7',
		patientName: 'Goldberg, Daniel',
		dateOfBirth: '1965-11-27',
		sex: 'M',
		arrivalMode: 'ambulance',
		chiefComplaint: 'Cardiac arrest, ROSC achieved en route',
		avpu: 'U',
		highRiskSignsPresent: true,
		disposition: 'died',
		urgentFlagCount: 5,
		providerName: 'Dr. Mensah',
		dispositionAt: '2026-04-18T08:00:00Z',
	},
	{
		id: '8',
		patientName: 'Hassan, Layla',
		dateOfBirth: '2001-03-14',
		sex: 'F',
		arrivalMode: 'walking',
		chiefComplaint: 'Sore throat, fever for 3 days',
		avpu: 'A',
		highRiskSignsPresent: false,
		disposition: 'lwbs',
		urgentFlagCount: 0,
		providerName: '',
		dispositionAt: '2026-04-19T16:25:00Z',
	},
	{
		id: '9',
		patientName: 'Ivanov, Sergei',
		dateOfBirth: '1953-08-05',
		sex: 'M',
		arrivalMode: 'stretcher',
		chiefComplaint: 'Hematemesis, melena, weakness',
		avpu: 'V',
		highRiskSignsPresent: true,
		disposition: 'admit',
		urgentFlagCount: 3,
		providerName: 'Dr. Okafor',
		dispositionAt: '2026-04-20T12:15:00Z',
	},
	{
		id: '10',
		patientName: 'Johansson, Astrid',
		dateOfBirth: '1992-01-21',
		sex: 'F',
		arrivalMode: 'walking',
		chiefComplaint: 'Allergic reaction, generalised hives',
		avpu: 'A',
		highRiskSignsPresent: false,
		disposition: 'discharge',
		urgentFlagCount: 1,
		providerName: 'Dr. Thompson',
		dispositionAt: '2026-04-21T14:50:00Z',
	},
	{
		id: '11',
		patientName: 'Kumar, Ravi',
		dateOfBirth: '1976-10-12',
		sex: 'M',
		arrivalMode: 'ambulance',
		chiefComplaint: 'Diabetic ketoacidosis, polyuria, vomiting',
		avpu: 'V',
		highRiskSignsPresent: true,
		disposition: 'admit',
		urgentFlagCount: 3,
		providerName: 'Dr. Mensah',
		dispositionAt: '2026-04-22T10:05:00Z',
	},
	{
		id: '12',
		patientName: 'López, María',
		dateOfBirth: '1944-05-30',
		sex: 'F',
		arrivalMode: 'wheelchair',
		chiefComplaint: 'Dehydration, persistent vomiting',
		avpu: 'A',
		highRiskSignsPresent: false,
		disposition: 'transfer',
		urgentFlagCount: 1,
		providerName: 'Dr. Okafor',
		dispositionAt: '2026-04-23T09:35:00Z',
	},
];
