<!ELEMENT newborn_and_infant_physical_examination (id,created_at,updated_at,deleted_at,patient_id,clinician_id,practitioner_name,practitioner_role,examined_at,examination_context,care_setting,baby_identifier,baby_name,date_of_birth,sex,gestational_age_weeks,birth_weight_grams,breech_presentation,family_history_hip_problems,antenatal_concerns,eyes_red_reflex_right,eyes_red_reflex_left,eyes_appearance,heart_murmur,femoral_pulses_right,femoral_pulses_left,central_cyanosis,oxygen_saturation_preductal,oxygen_saturation_postductal,barlow_test,ortolani_test,hip_abduction,testis_right,testis_left,general_appearance,skin,head_and_fontanelles,face_and_palate,neck_and_clavicles,chest_and_lungs,abdomen,genitalia,anus_and_spine,limbs_and_digits,feet,tone_and_movement,weight_grams,head_circumference_cm,length_cm,eyes_result_recorded,heart_result_recorded,hips_result_recorded,testes_result_recorded,clinical_note)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT practitioner_name (#PCDATA)>
<!ELEMENT practitioner_role (#PCDATA)>
<!ELEMENT examined_at (#PCDATA)>
<!ELEMENT examination_context (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT baby_identifier (#PCDATA)>
<!ELEMENT baby_name (#PCDATA)>
<!ELEMENT date_of_birth (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT gestational_age_weeks (#PCDATA)>
<!ELEMENT birth_weight_grams (#PCDATA)>
<!ELEMENT breech_presentation (#PCDATA)>
<!ELEMENT family_history_hip_problems (#PCDATA)>
<!ELEMENT antenatal_concerns (#PCDATA)>
<!ELEMENT eyes_red_reflex_right (#PCDATA)>
<!ELEMENT eyes_red_reflex_left (#PCDATA)>
<!ELEMENT eyes_appearance (#PCDATA)>
<!ELEMENT heart_murmur (#PCDATA)>
<!ELEMENT femoral_pulses_right (#PCDATA)>
<!ELEMENT femoral_pulses_left (#PCDATA)>
<!ELEMENT central_cyanosis (#PCDATA)>
<!ELEMENT oxygen_saturation_preductal (#PCDATA)>
<!ELEMENT oxygen_saturation_postductal (#PCDATA)>
<!ELEMENT barlow_test (#PCDATA)>
<!ELEMENT ortolani_test (#PCDATA)>
<!ELEMENT hip_abduction (#PCDATA)>
<!ELEMENT testis_right (#PCDATA)>
<!ELEMENT testis_left (#PCDATA)>
<!ELEMENT general_appearance (#PCDATA)>
<!ELEMENT skin (#PCDATA)>
<!ELEMENT head_and_fontanelles (#PCDATA)>
<!ELEMENT face_and_palate (#PCDATA)>
<!ELEMENT neck_and_clavicles (#PCDATA)>
<!ELEMENT chest_and_lungs (#PCDATA)>
<!ELEMENT abdomen (#PCDATA)>
<!ELEMENT genitalia (#PCDATA)>
<!ELEMENT anus_and_spine (#PCDATA)>
<!ELEMENT limbs_and_digits (#PCDATA)>
<!ELEMENT feet (#PCDATA)>
<!ELEMENT tone_and_movement (#PCDATA)>
<!ELEMENT weight_grams (#PCDATA)>
<!ELEMENT head_circumference_cm (#PCDATA)>
<!ELEMENT length_cm (#PCDATA)>
<!ELEMENT eyes_result_recorded (#PCDATA)>
<!ELEMENT heart_result_recorded (#PCDATA)>
<!ELEMENT hips_result_recorded (#PCDATA)>
<!ELEMENT testes_result_recorded (#PCDATA)>
<!ELEMENT clinical_note (#PCDATA)>
