mod users;

mod patients;
mod practitioners;
mod rad_onc_waiting_list_cards;
mod rad_onc_waiting_list_card_appointments;
mod rad_onc_waiting_list_card_grades;
mod rad_onc_waiting_list_card_grade_rules;
mod rad_onc_waiting_list_card_grade_flags;