-- schema.sql
-- Combined schema for form: epilepsy-review
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (8):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_epilepsy_review.sql
--   - 05_create_table_epilepsy_review_grade.sql
--   - 06_create_table_epilepsy_review_grade_rule.sql
--   - 07_create_table_epilepsy_review_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators used by free-text search GIN indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information.

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    hospital_mrn VARCHAR(50),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    allergies_summary TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient demographic information used by the epilepsy annual-review record.';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Full patient name.';
COMMENT ON COLUMN patient.birth_date IS
    'Date of birth.';
COMMENT ON COLUMN patient.sex IS
    'Sex recorded for clinical purposes: female, male, intersex, or unknown.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.hospital_mrn IS
    'Local hospital medical record number (MRN).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height in centimetres.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight in kilograms.';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI), kg/m^2.';
COMMENT ON COLUMN patient.allergies_summary IS
    'Free-text summary of known allergies.';

CREATE INDEX patient_name_trgm_idx
    ON patient
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Clinician employee information used to identify the clinician who
-- conducted the epilepsy annual review.

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN ('gp', 'practice-nurse', 'epilepsy-nurse', 'neurologist', 'other', '')),
    registration_body VARCHAR(20) NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'GPhC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician identifying information for the clinician who conducted the epilepsy annual review.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Clinician full name as recorded in the rota.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code.';
COMMENT ON COLUMN clinician.role IS
    'Primary clinical role of the reviewer: gp, practice-nurse, epilepsy-nurse, neurologist, or other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Professional registration body: GMC, NMC, GPhC, or other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Professional registration number issued by the registration body.';

CREATE INDEX clinician_name_trgm_idx
    ON clinician
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_epilepsy_review.sql
-- ========================================================================

-- Main epilepsy annual-review record: one UK primary-care annual review
-- (NICE NG217) documenting the position since the last review across the
-- epilepsy profile, seizures and anti-seizure medication (ASM), triggers,
-- SUDEP discussion, injuries and status epilepticus, safety (DVLA driving,
-- bathing, occupation), valproate and pregnancy-prevention arrangements for
-- women of childbearing potential, mental health, and the care plan, plus
-- patient / clinician identification and review context. The computed
-- seizure-control classification, completeness grade, the audit trail of
-- fired rules, and the safety flags live in dedicated child tables. This is a
-- documentation and decision-support record, not a numeric score, a
-- diagnostic test, or a prescribing instrument.

CREATE TABLE epilepsy_review (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE RESTRICT,
    clinician_id UUID REFERENCES clinician(id) ON DELETE RESTRICT,

    -- Context and profile
    reviewer_name TEXT NOT NULL DEFAULT '',
    reviewer_role VARCHAR(20) NOT NULL DEFAULT '' CHECK (reviewer_role IN ('gp', 'practice-nurse', 'epilepsy-nurse', 'neurologist', 'other', '')),
    reviewed_at DATE,
    care_setting VARCHAR(20) NOT NULL DEFAULT '' CHECK (care_setting IN ('general-practice', 'epilepsy-clinic', 'community', 'other', '')),
    review_type VARCHAR(10) NOT NULL DEFAULT '' CHECK (review_type IN ('annual', 'interim', '')),
    months_since_last_review NUMERIC(5,1),
    patient_identifier VARCHAR(100) NOT NULL DEFAULT '',
    age_band VARCHAR(10) NOT NULL DEFAULT '' CHECK (age_band IN ('18-39', '40-59', '60-79', '>=80', '')),
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    epilepsy_type VARCHAR(15) NOT NULL DEFAULT '' CHECK (epilepsy_type IN ('focal', 'generalised', 'combined', 'unknown', '')),
    age_at_onset NUMERIC(4,1),
    years_since_diagnosis NUMERIC(4,1),
    learning_disability VARCHAR(5) NOT NULL DEFAULT '' CHECK (learning_disability IN ('yes', 'no', '')),

    -- Seizures and medication
    seizure_types TEXT NOT NULL DEFAULT '',
    seizure_frequency VARCHAR(20) NOT NULL DEFAULT '' CHECK (seizure_frequency IN ('none', 'less-than-monthly', 'monthly', 'weekly', 'daily', '')),
    last_seizure_date DATE,
    seizure_free_months NUMERIC(5,1),
    seizure_trend VARCHAR(15) NOT NULL DEFAULT '' CHECK (seizure_trend IN ('seizure-free', 'decreasing', 'stable', 'increasing', '')),
    current_asms TEXT NOT NULL DEFAULT '',
    asm_adherence VARCHAR(10) NOT NULL DEFAULT '' CHECK (asm_adherence IN ('good', 'partial', 'poor', '')),
    asm_side_effects VARCHAR(15) NOT NULL DEFAULT '' CHECK (asm_side_effects IN ('none', 'mild', 'significant', '')),
    drug_level NUMERIC(6,1),

    -- Risk, safety and review domains
    triggers TEXT NOT NULL DEFAULT '',
    sudep_discussed VARCHAR(5) NOT NULL DEFAULT '' CHECK (sudep_discussed IN ('yes', 'no', '')),
    status_epilepticus VARCHAR(5) NOT NULL DEFAULT '' CHECK (status_epilepticus IN ('yes', 'no', '')),
    seizure_injury VARCHAR(5) NOT NULL DEFAULT '' CHECK (seizure_injury IN ('yes', 'no', '')),
    dvla_eligible VARCHAR(15) NOT NULL DEFAULT '' CHECK (dvla_eligible IN ('eligible', 'not-eligible', 'not-applicable', '')),
    currently_driving VARCHAR(5) NOT NULL DEFAULT '' CHECK (currently_driving IN ('yes', 'no', '')),
    bathing_advice_given VARCHAR(5) NOT NULL DEFAULT '' CHECK (bathing_advice_given IN ('yes', 'no', '')),
    woman_of_childbearing_potential VARCHAR(15) NOT NULL DEFAULT '' CHECK (woman_of_childbearing_potential IN ('yes', 'no', 'not-applicable', '')),
    on_valproate VARCHAR(5) NOT NULL DEFAULT '' CHECK (on_valproate IN ('yes', 'no', '')),
    pregnancy_prevention_programme VARCHAR(15) NOT NULL DEFAULT '' CHECK (pregnancy_prevention_programme IN ('in-place', 'not-in-place', 'not-applicable', '')),
    folic_acid VARCHAR(15) NOT NULL DEFAULT '' CHECK (folic_acid IN ('yes', 'no', 'not-applicable', '')),
    contraception_interaction_reviewed VARCHAR(15) NOT NULL DEFAULT '' CHECK (contraception_interaction_reviewed IN ('yes', 'no', 'not-applicable', '')),
    mental_health_concern VARCHAR(15) NOT NULL DEFAULT '' CHECK (mental_health_concern IN ('none', 'low-mood', 'anxiety', 'depression', 'suicidality', '')),
    specialist_review_needed VARCHAR(5) NOT NULL DEFAULT '' CHECK (specialist_review_needed IN ('yes', 'no', '')),
    next_review_due DATE,

    -- Care plan and free-text context
    care_plan TEXT NOT NULL DEFAULT '',
    review_context TEXT NOT NULL DEFAULT ''
);

CREATE INDEX epilepsy_review_patient_id_idx
    ON epilepsy_review (patient_id);
CREATE INDEX epilepsy_review_clinician_id_idx
    ON epilepsy_review (clinician_id);

CREATE TRIGGER trigger_epilepsy_review_updated_at
    BEFORE UPDATE ON epilepsy_review
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE epilepsy_review IS
    'Main epilepsy annual-review record (NICE NG217): patient and clinician identification, review context, epilepsy profile, seizures and anti-seizure medication with adherence and side effects, triggers, SUDEP discussion, injuries and status epilepticus, safety (DVLA driving, bathing, occupation), valproate and pregnancy-prevention arrangements, mental health, and the care plan. The computed seizure-control classification, completeness grade, fired rules, and safety flags live in child tables.';
COMMENT ON COLUMN epilepsy_review.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN epilepsy_review.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN epilepsy_review.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN epilepsy_review.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN epilepsy_review.patient_id IS
    'Foreign key to the patient this review documents (restrict delete).';
COMMENT ON COLUMN epilepsy_review.clinician_id IS
    'Foreign key to the reviewing clinician (restrict delete); optional.';
COMMENT ON COLUMN epilepsy_review.reviewer_name IS
    'Name of the reviewing clinician as recorded on the review.';
COMMENT ON COLUMN epilepsy_review.reviewer_role IS
    'Reviewing clinician role: gp, practice-nurse, epilepsy-nurse, neurologist, or other.';
COMMENT ON COLUMN epilepsy_review.reviewed_at IS
    'Date the annual review was conducted.';
COMMENT ON COLUMN epilepsy_review.care_setting IS
    'Care setting where the review was conducted: general-practice, epilepsy-clinic, community, or other.';
COMMENT ON COLUMN epilepsy_review.review_type IS
    'Type of review: annual or interim.';
COMMENT ON COLUMN epilepsy_review.months_since_last_review IS
    'Interval in months since the last review; drives the review-overdue flag when greater than 12.';
COMMENT ON COLUMN epilepsy_review.patient_identifier IS
    'NHS number or local patient identifier as recorded on the review.';
COMMENT ON COLUMN epilepsy_review.age_band IS
    'Adult age band: 18-39, 40-59, 60-79, or >=80.';
COMMENT ON COLUMN epilepsy_review.sex IS
    'Patient sex: female, male, intersex, or unknown.';
COMMENT ON COLUMN epilepsy_review.epilepsy_type IS
    'Epilepsy type: focal, generalised, combined, or unknown.';
COMMENT ON COLUMN epilepsy_review.age_at_onset IS
    'Age at epilepsy onset in years.';
COMMENT ON COLUMN epilepsy_review.years_since_diagnosis IS
    'Years since epilepsy diagnosis.';
COMMENT ON COLUMN epilepsy_review.learning_disability IS
    'Whether the patient has a learning disability (yes/no).';
COMMENT ON COLUMN epilepsy_review.seizure_types IS
    'Free-text record of the seizure type(s) present.';
COMMENT ON COLUMN epilepsy_review.seizure_frequency IS
    'Seizure frequency: none, less-than-monthly, monthly, weekly, or daily (weekly/daily drive an uncontrolled classification).';
COMMENT ON COLUMN epilepsy_review.last_seizure_date IS
    'Date of the most recent seizure.';
COMMENT ON COLUMN epilepsy_review.seizure_free_months IS
    'Documented seizure-free duration in months.';
COMMENT ON COLUMN epilepsy_review.seizure_trend IS
    'Seizure trend since the last review: seizure-free, decreasing, stable, or increasing (increasing drives an uncontrolled classification).';
COMMENT ON COLUMN epilepsy_review.current_asms IS
    'Free-text record of current anti-seizure medication(s) and doses.';
COMMENT ON COLUMN epilepsy_review.asm_adherence IS
    'Self-reported ASM adherence: good, partial, or poor (poor drives an adherence flag).';
COMMENT ON COLUMN epilepsy_review.asm_side_effects IS
    'ASM side-effect burden: none, mild, or significant (significant drives a side-effects flag).';
COMMENT ON COLUMN epilepsy_review.drug_level IS
    'Therapeutic ASM drug level where relevant (units per the specific drug).';
COMMENT ON COLUMN epilepsy_review.triggers IS
    'Free-text record of reported seizure triggers.';
COMMENT ON COLUMN epilepsy_review.sudep_discussed IS
    'Whether Sudden Unexpected Death in Epilepsy (SUDEP) risk was discussed (yes/no); a non-yes value drives a SUDEP-not-documented flag.';
COMMENT ON COLUMN epilepsy_review.status_epilepticus IS
    'Whether status epilepticus occurred since the last review (yes/no); yes drives an uncontrolled classification and a high-priority flag.';
COMMENT ON COLUMN epilepsy_review.seizure_injury IS
    'Whether a seizure-related injury occurred since the last review (yes/no).';
COMMENT ON COLUMN epilepsy_review.dvla_eligible IS
    'DVLA driving eligibility: eligible, not-eligible, or not-applicable.';
COMMENT ON COLUMN epilepsy_review.currently_driving IS
    'Whether the patient is currently driving (yes/no); driving while not DVLA-eligible drives a driving-safety flag.';
COMMENT ON COLUMN epilepsy_review.bathing_advice_given IS
    'Whether bathing / showering safety advice was given (yes/no).';
COMMENT ON COLUMN epilepsy_review.woman_of_childbearing_potential IS
    'Whether the patient is a woman of childbearing potential (yes/no/not-applicable); when yes, the valproate/PPP, folic-acid, and contraception domains become required for completeness.';
COMMENT ON COLUMN epilepsy_review.on_valproate IS
    'Whether the patient is prescribed sodium valproate (yes/no).';
COMMENT ON COLUMN epilepsy_review.pregnancy_prevention_programme IS
    'Valproate Pregnancy Prevention Programme status: in-place, not-in-place, or not-applicable.';
COMMENT ON COLUMN epilepsy_review.folic_acid IS
    'Whether folic acid is prescribed: yes, no, or not-applicable.';
COMMENT ON COLUMN epilepsy_review.contraception_interaction_reviewed IS
    'Whether contraception and ASM interactions were reviewed: yes, no, or not-applicable.';
COMMENT ON COLUMN epilepsy_review.mental_health_concern IS
    'Mental-health concern: none, low-mood, anxiety, depression, or suicidality (suicidality high priority; depression/anxiety/low-mood medium).';
COMMENT ON COLUMN epilepsy_review.specialist_review_needed IS
    'Whether specialist (neurology) review is needed (yes/no).';
COMMENT ON COLUMN epilepsy_review.next_review_due IS
    'Date the next review is planned.';
COMMENT ON COLUMN epilepsy_review.care_plan IS
    'Free-text record of the agreed epilepsy care plan.';
COMMENT ON COLUMN epilepsy_review.review_context IS
    'Optional free-text review context or narrative shown in the summary.';

-- ========================================================================
-- END 04_create_table_epilepsy_review.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_epilepsy_review_grade.sql
-- ========================================================================

-- Computed seizure-control classification and completeness grading result for
-- an epilepsy annual review. The engine classifies seizure control from the
-- worst finding (increasing trend, weekly/daily frequency, or any status
-- epilepticus force uncontrolled; no seizures or a seizure-free trend give
-- seizure-free; otherwise controlled), and grades review completeness by
-- counting the documented required domains. A grade reflects the recorded
-- classification and the completeness of the review, not a diagnostic
-- judgement.

CREATE TABLE epilepsy_review_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    epilepsy_review_id UUID NOT NULL UNIQUE
        REFERENCES epilepsy_review(id) ON DELETE CASCADE,

    seizure_control VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (seizure_control IN ('seizure-free', 'controlled', 'uncontrolled', '')),
    review_status VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (review_status IN ('complete', 'partial', 'incomplete', '')),
    completeness_score INTEGER,

    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_epilepsy_review_grade_updated_at
    BEFORE UPDATE ON epilepsy_review_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE epilepsy_review_grade IS
    'Computed seizure-control classification and completeness grading result for an epilepsy annual review: seizure control, review-completeness status, and the count of documented required domains. 1:1 with the parent review.';
COMMENT ON COLUMN epilepsy_review_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN epilepsy_review_grade.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN epilepsy_review_grade.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN epilepsy_review_grade.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN epilepsy_review_grade.epilepsy_review_id IS
    'Foreign key to the parent epilepsy review (unique, 1:1).';
COMMENT ON COLUMN epilepsy_review_grade.seizure_control IS
    'Seizure-control classification: seizure-free, controlled, or uncontrolled.';
COMMENT ON COLUMN epilepsy_review_grade.review_status IS
    'Review completeness: complete, partial, or incomplete.';
COMMENT ON COLUMN epilepsy_review_grade.completeness_score IS
    'Count of documented required review domains.';
COMMENT ON COLUMN epilepsy_review_grade.graded_at IS
    'Timestamp when the engine last computed the grade.';

-- ========================================================================
-- END 05_create_table_epilepsy_review_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_epilepsy_review_grade_rule.sql
-- ========================================================================

-- Audit trail of every classification or completeness rule that fired during
-- grading. Each row records one rule firing with the section it concerns, the
-- category, and a human-readable description.

CREATE TABLE epilepsy_review_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    epilepsy_review_grade_id UUID NOT NULL
        REFERENCES epilepsy_review_grade(id) ON DELETE CASCADE,

    rule_id VARCHAR(40) NOT NULL,
    section VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (section IN ('seizure-control', 'completeness', '')),
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX epilepsy_review_grade_rule_grade_id_idx
    ON epilepsy_review_grade_rule (epilepsy_review_grade_id);

CREATE TRIGGER trigger_epilepsy_review_grade_rule_updated_at
    BEFORE UPDATE ON epilepsy_review_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE epilepsy_review_grade_rule IS
    'Audit trail of every classification or completeness rule that fired during grading: section, category, and description.';
COMMENT ON COLUMN epilepsy_review_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN epilepsy_review_grade_rule.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN epilepsy_review_grade_rule.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN epilepsy_review_grade_rule.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN epilepsy_review_grade_rule.epilepsy_review_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN epilepsy_review_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-SEIZURE-CONTROL-UNCONTROLLED-01).';
COMMENT ON COLUMN epilepsy_review_grade_rule.section IS
    'Section the rule concerns: seizure-control or completeness.';
COMMENT ON COLUMN epilepsy_review_grade_rule.category IS
    'Subject category (e.g. control-classification, required-domain).';
COMMENT ON COLUMN epilepsy_review_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 06_create_table_epilepsy_review_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_epilepsy_review_grade_flag.sql
-- ========================================================================

-- Safety flags that fire independently of the seizure-control class and the
-- completeness status, each with a priority and a suggested action for the
-- clinician or governance team.

CREATE TABLE epilepsy_review_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    epilepsy_review_grade_id UUID NOT NULL
        REFERENCES epilepsy_review_grade(id) ON DELETE CASCADE,

    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(30) NOT NULL DEFAULT ''
        CHECK (category IN (
            'specialist-review',
            'valproate-ppp',
            'status-epilepticus-history',
            'driving-safety',
            'mental-health',
            'sudep-not-documented',
            'poor-adherence',
            'asm-side-effects',
            'folic-acid-missing',
            'incomplete',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX epilepsy_review_grade_flag_grade_id_idx
    ON epilepsy_review_grade_flag (epilepsy_review_grade_id);

CREATE TRIGGER trigger_epilepsy_review_grade_flag_updated_at
    BEFORE UPDATE ON epilepsy_review_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE epilepsy_review_grade_flag IS
    'Safety flags that fire independently of the seizure-control class and the completeness status, with priority and a suggested action for the clinician or governance team.';
COMMENT ON COLUMN epilepsy_review_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN epilepsy_review_grade_flag.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN epilepsy_review_grade_flag.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN epilepsy_review_grade_flag.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN epilepsy_review_grade_flag.epilepsy_review_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN epilepsy_review_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-VALPROATE-PPP-001).';
COMMENT ON COLUMN epilepsy_review_grade_flag.category IS
    'Flag category: specialist-review, valproate-ppp, status-epilepticus-history, driving-safety, mental-health, sudep-not-documented, poor-adherence, asm-side-effects, folic-acid-missing, incomplete, or other.';
COMMENT ON COLUMN epilepsy_review_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN epilepsy_review_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN epilepsy_review_grade_flag.suggested_action IS
    'Suggested clinical or governance action (e.g. "refer to neurology", "arrange valproate pregnancy-prevention programme review").';

-- ========================================================================
-- END 07_create_table_epilepsy_review_grade_flag.sql
-- ========================================================================
