mod users;

mod patients;
mod clinicians;
mod electroencephalogram_test_requests;
mod electroencephalogram_test_request_grades;
mod electroencephalogram_test_request_grade_rules;
mod electroencephalogram_test_request_grade_flags;