mod users;

mod patients;
mod clinicians;
mod diabetes_podiatry_assessments;
mod diabetes_podiatry_assessment_grades;
mod diabetes_podiatry_assessment_grade_rules;
mod diabetes_podiatry_assessment_grade_flags;