mod users;

mod patients;
mod clinicians;
mod national_early_warning_score_2s;
mod national_early_warning_score_2_grades;
mod national_early_warning_score_2_grade_rules;
mod national_early_warning_score_2_grade_flags;