//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::obgyn_waiting_list_card_appointments::Entity as ObgynWaitingListCardAppointments;
pub use super::obgyn_waiting_list_card_grade_flags::Entity as ObgynWaitingListCardGradeFlags;
pub use super::obgyn_waiting_list_card_grade_rules::Entity as ObgynWaitingListCardGradeRules;
pub use super::obgyn_waiting_list_card_grades::Entity as ObgynWaitingListCardGrades;
pub use super::obgyn_waiting_list_cards::Entity as ObgynWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
