use loco_rs::schema::*;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        create_table(m, "medical_information_form_for_air_travels",
            &[
            
            ("id", ColType::PkAuto),
            
            ("deleted_at", ColType::TimestampWithTimeZoneNull),
            ("status", ColType::StringWithDefault("draft".to_string())),
            ("submitter_name", ColType::TextWithDefault(String::new())),
            ("submitter_role", ColType::StringWithDefault(String::new())),
            ("submitter_email", ColType::TextWithDefault(String::new())),
            ("submitter_phone", ColType::TextWithDefault(String::new())),
            ("submitter_organisation", ColType::TextWithDefault(String::new())),
            ("airline_booking_reference", ColType::StringWithDefault(String::new())),
            ("airline_iata_code", ColType::StringWithDefault(String::new())),
            ("airline_name", ColType::TextWithDefault(String::new())),
            ("outbound_flight_number", ColType::StringWithDefault(String::new())),
            ("outbound_date", ColType::DateNull),
            ("outbound_origin_iata", ColType::StringWithDefault(String::new())),
            ("outbound_destination_iata", ColType::StringWithDefault(String::new())),
            ("return_flight_number", ColType::StringWithDefault(String::new())),
            ("return_date", ColType::DateNull),
            ("cabin_class", ColType::StringWithDefault(String::new())),
            ("sector_duration_minutes", ColType::IntegerNull),
            ("transit_airports_iata", ColType::TextWithDefault(String::new())),
            ("special_assistance_codes", ColType::TextWithDefault(String::new())),
            ("reason_equipment", ColType::StringWithDefault(String::new())),
            ("reason_recent_acute_event", ColType::StringWithDefault(String::new())),
            ("reason_unstable_condition", ColType::StringWithDefault(String::new())),
            ("reason_communicable_disease", ColType::StringWithDefault(String::new())),
            ("reason_pregnancy", ColType::StringWithDefault(String::new())),
            ("reason_mobility_escort", ColType::StringWithDefault(String::new())),
            ("reason_psychiatric", ColType::StringWithDefault(String::new())),
            ("primary_diagnosis", ColType::TextWithDefault(String::new())),
            ("icd10_codes", ColType::TextWithDefault(String::new())),
            ("diagnosis_date", ColType::DateNull),
            ("current_treatment", ColType::TextWithDefault(String::new())),
            ("last_admission_date", ColType::DateNull),
            ("last_discharge_date", ColType::DateNull),
            ("last_specialist_review_date", ColType::DateNull),
            ("resting_systolic_bp", ColType::IntegerNull),
            ("resting_diastolic_bp", ColType::IntegerNull),
            ("resting_heart_rate", ColType::IntegerNull),
            ("nyha_class", ColType::StringWithDefault(String::new())),
            ("recent_mi_date", ColType::DateNull),
            ("recent_stent_date", ColType::DateNull),
            ("on_anticoagulant", ColType::StringWithDefault(String::new())),
            ("pacemaker_or_icd", ColType::StringWithDefault(String::new())),
            ("exercise_tolerance_metres", ColType::IntegerNull),
            ("unstable_angina", ColType::StringWithDefault(String::new())),
            ("resting_spo2_percent", ColType::DoubleNull),
            ("predicted_inflight_spo2_percent", ColType::DoubleNull),
            ("hypoxic_challenge_result", ColType::StringWithDefault(String::new())),
            ("recent_pneumothorax_date", ColType::DateNull),
            ("asthma_severity", ColType::StringWithDefault(String::new())),
            ("copd_severity", ColType::StringWithDefault(String::new())),
            ("cpap_or_bipap_use", ColType::StringWithDefault(String::new())),
            ("recent_pulmonary_embolism_date", ColType::DateNull),
            ("last_surgery_date", ColType::DateNull),
            ("last_surgery_site", ColType::TextWithDefault(String::new())),
            ("cabin_gas_risk", ColType::StringWithDefault(String::new())),
            ("recent_fracture_cast", ColType::StringWithDefault(String::new())),
            ("recent_dvt_date", ColType::DateNull),
            ("scuba_diving_within_24h", ColType::StringWithDefault(String::new())),
            ("recent_stroke_date", ColType::DateNull),
            ("is_pregnant", ColType::StringWithDefault(String::new())),
            ("gestation_weeks", ColType::IntegerNull),
            ("pregnancy_type", ColType::StringWithDefault(String::new())),
            ("pregnancy_complications", ColType::TextWithDefault(String::new())),
            ("expected_delivery_date", ColType::DateNull),
            ("obstetrician_contact", ColType::TextWithDefault(String::new())),
            ("communicable_disease_status", ColType::StringWithDefault(String::new())),
            ("last_symptom_date", ColType::DateNull),
            ("isolation_required", ColType::StringWithDefault(String::new())),
            ("vaccination_status", ColType::TextWithDefault(String::new())),
            ("current_antimicrobials", ColType::TextWithDefault(String::new())),
            ("requires_supplemental_oxygen", ColType::StringWithDefault(String::new())),
            ("oxygen_flow_rate_lpm", ColType::DoubleNull),
            ("oxygen_duration", ColType::StringWithDefault(String::new())),
            ("requires_poc", ColType::StringWithDefault(String::new())),
            ("poc_make_model", ColType::TextWithDefault(String::new())),
            ("poc_battery_hours", ColType::DoubleNull),
            ("requires_stretcher", ColType::StringWithDefault(String::new())),
            ("requires_incubator", ColType::StringWithDefault(String::new())),
            ("requires_iv_pump", ColType::StringWithDefault(String::new())),
            ("requires_medical_escort", ColType::StringWithDefault(String::new())),
            ("requires_extra_seat", ColType::StringWithDefault(String::new())),
            ("requires_accessible_lavatory", ColType::StringWithDefault(String::new())),
            ("wheelchair_type", ColType::StringWithDefault(String::new())),
            ("accompanying_carer", ColType::StringWithDefault(String::new())),
            ("regular_medications", ColType::TextWithDefault(String::new())),
            ("controlled_drugs", ColType::TextWithDefault(String::new())),
            ("dangerous_goods_battery_declaration", ColType::StringWithDefault(String::new())),
            ("sharps_in_cabin", ColType::StringWithDefault(String::new())),
            ("refrigerated_medication", ColType::StringWithDefault(String::new())),
            ("customs_documentation_available", ColType::StringWithDefault(String::new())),
            ("haemoglobin_g_per_l", ColType::IntegerNull),
            ("physician_declaration", ColType::StringWithDefault(String::new())),
            ("physician_signature_name", ColType::TextWithDefault(String::new())),
            ("physician_signature_date", ColType::DateNull),
            ("valid_until_date", ColType::DateNull),
            ("additional_notes", ColType::TextWithDefault(String::new())),
            ],
            &[
            ("patient", ""),
            ("clinician", ""),
            ]
        ).await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        drop_table(m, "medical_information_form_for_air_travels").await
    }
}
