<!ELEMENT ambulatory_blood_pressure_test_result (id,created_at,updated_at,deleted_at,patient_id,clinician_id,originating_request_reference,monitoring_type,report_status,performed_date,reported_date,valid_readings_percent,recording_adequate,clinical_history,daytime_average_systolic,daytime_average_diastolic,nighttime_average_systolic,nighttime_average_diastolic,twenty_four_hour_average_systolic,twenty_four_hour_average_diastolic,nocturnal_dip_percent,dipper_status,hypertension_confirmed,white_coat_effect,masked_hypertension,severe_hypertension,nocturnal_hypertension,normal_study,findings_narrative,comparison_with_previous,impression,reporting_category,recommended_follow_up,critical_result_communicated,reported_to)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT originating_request_reference (#PCDATA)>
<!ELEMENT monitoring_type (#PCDATA)>
<!ELEMENT report_status (#PCDATA)>
<!ELEMENT performed_date (#PCDATA)>
<!ELEMENT reported_date (#PCDATA)>
<!ELEMENT valid_readings_percent (#PCDATA)>
<!ELEMENT recording_adequate (#PCDATA)>
<!ELEMENT clinical_history (#PCDATA)>
<!ELEMENT daytime_average_systolic (#PCDATA)>
<!ELEMENT daytime_average_diastolic (#PCDATA)>
<!ELEMENT nighttime_average_systolic (#PCDATA)>
<!ELEMENT nighttime_average_diastolic (#PCDATA)>
<!ELEMENT twenty_four_hour_average_systolic (#PCDATA)>
<!ELEMENT twenty_four_hour_average_diastolic (#PCDATA)>
<!ELEMENT nocturnal_dip_percent (#PCDATA)>
<!ELEMENT dipper_status (#PCDATA)>
<!ELEMENT hypertension_confirmed (#PCDATA)>
<!ELEMENT white_coat_effect (#PCDATA)>
<!ELEMENT masked_hypertension (#PCDATA)>
<!ELEMENT severe_hypertension (#PCDATA)>
<!ELEMENT nocturnal_hypertension (#PCDATA)>
<!ELEMENT normal_study (#PCDATA)>
<!ELEMENT findings_narrative (#PCDATA)>
<!ELEMENT comparison_with_previous (#PCDATA)>
<!ELEMENT impression (#PCDATA)>
<!ELEMENT reporting_category (#PCDATA)>
<!ELEMENT recommended_follow_up (#PCDATA)>
<!ELEMENT critical_result_communicated (#PCDATA)>
<!ELEMENT reported_to (#PCDATA)>
