use loco_rs::schema::*;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        create_table(m, "inpatient_clinical_notes",
            &[

            ("id", ColType::PkAuto),

            ("deleted_at", ColType::TimestampWithTimeZoneNull),
            ("status", ColType::StringWithDefault("draft".to_string())),
            ("note_type", ColType::StringWithDefault(String::new())),
            ("hospital_name", ColType::StringWithDefault(String::new())),
            ("ward_name", ColType::StringWithDefault(String::new())),
            ("bed_number", ColType::StringWithDefault(String::new())),
            ("note_at", ColType::TimestampWithTimeZoneNull),
            ("author_name", ColType::StringWithDefault(String::new())),
            ("author_grade", ColType::StringWithDefault(String::new())),
            ("author_registration_number", ColType::StringWithDefault(String::new())),
            ("parent_specialty", ColType::StringWithDefault(String::new())),
            ("responsible_consultant_name", ColType::StringWithDefault(String::new())),
            ("consult_question", ColType::TextWithDefault(String::new())),
            ("consult_requesting_team", ColType::StringWithDefault(String::new())),
            ("procedure_performed", ColType::StringWithDefault(String::new())),
            ("procedure_detail", ColType::TextWithDefault(String::new())),
            ("procedure_consent", ColType::StringWithDefault(String::new())),
            ("procedure_complications", ColType::TextWithDefault(String::new())),
            ("transfer_from_ward", ColType::StringWithDefault(String::new())),
            ("transfer_to_ward", ColType::StringWithDefault(String::new())),
            ("transfer_reason", ColType::TextWithDefault(String::new())),
            ("admission_at", ColType::TimestampWithTimeZoneNull),
            ("admitting_specialty", ColType::StringWithDefault(String::new())),
            ("admission_method", ColType::StringWithDefault(String::new())),
            ("admission_reason", ColType::TextWithDefault(String::new())),
            ("interval_history", ColType::TextWithDefault(String::new())),
            ("no_interval_events", ColType::StringWithDefault(String::new())),
            ("overnight_events", ColType::TextWithDefault(String::new())),
            ("patient_reported_symptoms", ColType::TextWithDefault(String::new())),
            ("nursing_concerns", ColType::TextWithDefault(String::new())),
            ("pain_score", ColType::IntegerNull),
            ("sleep_quality", ColType::StringWithDefault(String::new())),
            ("oral_intake", ColType::StringWithDefault(String::new())),
            ("bowels_last_opened", ColType::DateNull),
            ("mobility_status", ColType::StringWithDefault(String::new())),
            ("observed_at", ColType::TimestampWithTimeZoneNull),
            ("respiratory_rate", ColType::IntegerNull),
            ("oxygen_saturation", ColType::IntegerNull),
            ("spo2_scale", ColType::StringWithDefault("scale-1".to_string())),
            ("oxygen_delivery", ColType::StringWithDefault(String::new())),
            ("oxygen_flow_litres_per_minute", ColType::DecimalNull),
            ("systolic_blood_pressure", ColType::IntegerNull),
            ("diastolic_blood_pressure", ColType::IntegerNull),
            ("pulse_rate", ColType::IntegerNull),
            ("acvpu", ColType::StringWithDefault(String::new())),
            ("temperature_celsius", ColType::DecimalNull),
            ("news2_total", ColType::IntegerNull),
            ("news2_derived_total", ColType::IntegerNull),
            ("news2_trend", ColType::StringWithDefault(String::new())),
            ("news2_applicable", ColType::StringWithDefault(String::new())),
            ("news2_not_applicable_reason", ColType::StringWithDefault(String::new())),
            ("examination_general", ColType::TextWithDefault(String::new())),
            ("examination_cardiovascular", ColType::TextWithDefault(String::new())),
            ("examination_respiratory", ColType::TextWithDefault(String::new())),
            ("examination_abdominal", ColType::TextWithDefault(String::new())),
            ("examination_neurological", ColType::TextWithDefault(String::new())),
            ("examination_musculoskeletal", ColType::TextWithDefault(String::new())),
            ("examination_skin_and_wounds", ColType::TextWithDefault(String::new())),
            ("examination_lines_and_drains", ColType::TextWithDefault(String::new())),
            ("examination_other", ColType::TextWithDefault(String::new())),
            ("no_investigations_reviewed", ColType::StringWithDefault(String::new())),
            ("no_medication_changes", ColType::StringWithDefault(String::new())),
            ("allergy_checked", ColType::StringWithDefault(String::new())),
            ("medicines_reconciliation_status", ColType::StringWithDefault(String::new())),
            ("antimicrobial_review_status", ColType::StringWithDefault(String::new())),
            ("antimicrobial_review_at", ColType::TimestampWithTimeZoneNull),
            ("vte_status", ColType::StringWithDefault(String::new())),
            ("vte_prophylaxis", ColType::StringWithDefault(String::new())),
            ("vte_assessed_at", ColType::TimestampWithTimeZoneNull),
            ("vte_notes", ColType::TextWithDefault(String::new())),
            ("falls_risk", ColType::StringWithDefault(String::new())),
            ("falls_interventions", ColType::TextWithDefault(String::new())),
            ("pressure_ulcer_risk", ColType::StringWithDefault(String::new())),
            ("skin_integrity", ColType::StringWithDefault(String::new())),
            ("pressure_ulcer_grade", ColType::StringWithDefault(String::new())),
            ("pressure_ulcer_sites", ColType::StringWithDefault(String::new())),
            ("delirium_screen", ColType::StringWithDefault(String::new())),
            ("delirium_4at_score", ColType::IntegerNull),
            ("delirium_notes", ColType::TextWithDefault(String::new())),
            ("nutrition_screen", ColType::StringWithDefault(String::new())),
            ("must_score", ColType::IntegerNull),
            ("nutrition_plan", ColType::TextWithDefault(String::new())),
            ("infection_status", ColType::StringWithDefault(String::new())),
            ("isolation_status", ColType::StringWithDefault(String::new())),
            ("organism", ColType::StringWithDefault(String::new())),
            ("infection_precautions", ColType::TextWithDefault(String::new())),
            ("safeguarding_concern", ColType::StringWithDefault(String::new())),
            ("safeguarding_notes", ColType::TextWithDefault(String::new())),
            ("safeguarding_referral_made", ColType::StringWithDefault(String::new())),
            ("clinical_impression", ColType::TextWithDefault(String::new())),
            ("differential_diagnosis", ColType::TextWithDefault(String::new())),
            ("response_to_treatment", ColType::StringWithDefault(String::new())),
            ("new_oxygen_requirement", ColType::StringWithDefault(String::new())),
            ("new_confusion", ColType::StringWithDefault(String::new())),
            ("sepsis_screen", ColType::StringWithDefault(String::new())),
            ("arrest_call", ColType::StringWithDefault(String::new())),
            ("critical_care_referral", ColType::StringWithDefault(String::new())),
            ("new_organ_support", ColType::StringWithDefault(String::new())),
            ("plan", ColType::TextWithDefault(String::new())),
            ("escalation_status", ColType::StringWithDefault(String::new())),
            ("escalation_action", ColType::TextWithDefault(String::new())),
            ("ceiling_of_care", ColType::StringWithDefault(String::new())),
            ("respect_status", ColType::StringWithDefault(String::new())),
            ("dnacpr_status", ColType::StringWithDefault(String::new())),
            ("senior_review_needed", ColType::StringWithDefault(String::new())),
            ("senior_review_by", ColType::StringWithDefault(String::new())),
            ("senior_review_at", ColType::TimestampWithTimeZoneNull),
            ("estimated_discharge_date", ColType::DateNull),
            ("discharge_planning_notes", ColType::TextWithDefault(String::new())),
            ("family_communication", ColType::TextWithDefault(String::new())),
            ("patient_communication", ColType::TextWithDefault(String::new())),
            ("team_handover", ColType::TextWithDefault(String::new())),
            ("consent_status", ColType::StringWithDefault(String::new())),
            ("capacity_assessed", ColType::StringWithDefault(String::new())),
            ("capacity_notes", ColType::TextWithDefault(String::new())),
            ("author_override_acuity", ColType::StringWithDefault(String::new())),
            ("author_override_reason", ColType::TextWithDefault(String::new())),
            ("attestation_text", ColType::TextWithDefault(String::new())),
            ("electronic_signature", ColType::TextWithDefault(String::new())),
            ("signed_at", ColType::TimestampWithTimeZoneNull),
            ],
            &[
            ("patient", "patient_id"),
            ("clinician", "author_id"),
            ("clinician", "responsible_consultant_id"),
            ]
        ).await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        drop_table(m, "inpatient_clinical_notes").await
    }
}
