<!ELEMENT patient (id,created_at,updated_at,deleted_at,name,birth_date,sex,email,phone,postal_address_as_full_text,country_as_iso_3166_1_alpha_2,postcode,united_kingdom_nhs_number,job_title,role_description,contracted_hours_per_week,shift_pattern,safety_critical_role,dvla_group_1_licence_held,dvla_group_2_licence_held)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT birth_date (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT postal_address_as_full_text (#PCDATA)>
<!ELEMENT country_as_iso_3166_1_alpha_2 (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT united_kingdom_nhs_number (#PCDATA)>
<!ELEMENT job_title (#PCDATA)>
<!ELEMENT role_description (#PCDATA)>
<!ELEMENT contracted_hours_per_week (#PCDATA)>
<!ELEMENT shift_pattern (#PCDATA)>
<!ELEMENT safety_critical_role (#PCDATA)>
<!ELEMENT dvla_group_1_licence_held (#PCDATA)>
<!ELEMENT dvla_group_2_licence_held (#PCDATA)>
