mod users;

mod patients;
mod practitioners;
mod rheumatology_waiting_list_cards;
mod rheumatology_waiting_list_card_appointments;
mod rheumatology_waiting_list_card_grades;
mod rheumatology_waiting_list_card_grade_rules;
mod rheumatology_waiting_list_card_grade_flags;