#!/bin/sh
set -euf

form_kebab_case=vaccinations-assessment
form_snake_case=vaccinations_assessment

createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_development" || :
createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_test" || :
createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_production" || :

loco new --name "${form_snake_case}" --db postgres --bg async --assets none -a
cd "${form_snake_case}"

# Pin time to a version compatible with cookie 0.18.1 (a fresh loco
# starter otherwise resolves time 0.3.52, which fails to compile).
cargo update -p time --precise 0.3.47

cargo loco generate scaffold patient \
    deleted_at:tstz \
    name:string! \
    birth_date:date! \
    email:text \
    phone:text \
    postal_address_as_full_text:text \
    country_as_iso_3166_1_alpha_2:string \
    postcode:text \
    united_kingdom_nhs_number:string^ \
    waist_as_cm:double \
    height_as_cm:double \
    weight_as_kg:double \
    body_mass_index:double \
    waist_height_ratio:double \
    vo2_max:double \
    --api

cargo loco generate scaffold clinician \
    deleted_at:tstz \
    name:text! \
    email:text \
    phone:text \
    postal_address_as_full_text:text \
    country_as_iso_3166_1_alpha_2:string \
    postcode:text \
    role:text! \
    registration_body:text! \
    registration_number:text! \
    united_kingdom_nhs_number:string^ \
    --api

cargo loco generate scaffold assessment \
    deleted_at:tstz \
    patient:references \
    status:string! \
    --api

cargo loco generate scaffold immunization_history \
    deleted_at:tstz \
    assessment:references \
    has_vaccination_record:string! \
    record_source:string! \
    last_review_date:date \
    previous_adverse_reactions:string! \
    adverse_reaction_details:text! \
    immunocompromised:string! \
    immunocompromised_details:text! \
    --api

cargo loco generate scaffold childhood_vaccinations \
    deleted_at:tstz \
    assessment:references \
    dtap_ipv_hib_hepb:int \
    pneumococcal:int \
    rotavirus:int \
    meningitis_b:int \
    mmr:int \
    hib_menc:int \
    preschool_booster:int \
    --api

cargo loco generate scaffold adult_vaccinations \
    deleted_at:tstz \
    assessment:references \
    td_ipv_booster:int \
    hpv:int \
    meningitis_acwy:int \
    influenza_annual:int \
    covid19:int \
    shingles:int \
    pneumococcal_ppv:int \
    --api

cargo loco generate scaffold travel_vaccinations \
    deleted_at:tstz \
    assessment:references \
    travel_planned:string! \
    travel_destination:string! \
    hepatitis_a:int \
    hepatitis_b:int \
    typhoid:int \
    yellow_fever:int \
    rabies:int \
    japanese_encephalitis:int \
    --api

cargo loco generate scaffold occupational_vaccinations \
    deleted_at:tstz \
    assessment:references \
    occupation:string! \
    healthcare_worker:string! \
    hepatitis_b_occupational:int \
    influenza_occupational:int \
    varicella:int \
    bcg_tuberculosis:int \
    --api

cargo loco generate scaffold contraindications_allergies \
    deleted_at:tstz \
    assessment:references \
    egg_allergy:string! \
    gelatin_allergy:string! \
    latex_allergy:string! \
    neomycin_allergy:string! \
    pregnant:string! \
    pregnancy_weeks:string! \
    severe_illness:string! \
    previous_anaphylaxis:string! \
    anaphylaxis_details:text! \
    --api

cargo loco generate scaffold consent_information \
    deleted_at:tstz \
    assessment:references \
    information_provided:int \
    risks_explained:int \
    benefits_explained:int \
    questions_answered:int \
    consent_given:string! \
    consent_date:date \
    guardian_consent:string! \
    --api

cargo loco generate scaffold administration_record \
    deleted_at:tstz \
    assessment:references \
    vaccine_name:string! \
    batch_number:string! \
    expiry_date:date \
    administration_site:string! \
    administration_route:string! \
    dose_number:string! \
    administered_by:string! \
    administration_date:date \
    --api

cargo loco generate scaffold clinical_review \
    deleted_at:tstz \
    assessment:references \
    post_vaccination_observation:int \
    immediate_reaction:string! \
    reaction_details:text! \
    next_dose_due:date \
    catch_up_schedule_needed:string! \
    referral_needed:string! \
    clinician_notes:text! \
    reviewing_clinician:string! \
    --api

cargo loco generate scaffold grade \
    deleted_at:tstz \
    assessment:references \
    vaccination_level:string! \
    vaccination_score:int! \
    graded_at:tstz \
    --api

cargo loco generate scaffold fired_rule \
    deleted_at:tstz \
    grade:references \
    rule_id:string! \
    category:string! \
    description:text! \
    concern_level:string! \
    --api

cargo loco generate scaffold additional_flag \
    deleted_at:tstz \
    grade:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --api
