//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod breast_screening_grade_flags;
pub mod breast_screening_grade_rules;
pub mod breast_screening_grades;
pub mod breast_screenings;
pub mod clinicians;
pub mod patients;
pub mod users;
