// Sample operation-note rows for the medical-operation-note dashboard.
// Spans all four composite-risk bands (routine / complicated / high-risk /
// critical), every Clavien-Dindo grade likely to appear in review, multiple
// specialties, every NCEPOD urgency band, and a mix of signed / unsigned and
// never-event-flagged cases. Patient identifiers are synthetic; do not use
// real NHS numbers.

export type CompositeRisk = 'routine' | 'complicated' | 'high-risk' | 'critical';
export type ClavienDindo = '0' | 'I' | 'II' | 'IIIa' | 'IIIb' | 'IVa' | 'IVb' | 'V';
export type NcepodUrgency = 'elective' | 'expedited' | 'urgent' | 'immediate';
export type AsaPhysicalStatus = 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI';
export type ListType = 'elective' | 'cepod' | 'trauma' | 'obstetric' | 'day-case' | 'endoscopy';
export type RecoveryDestination =
  | 'pacu'
  | 'ward'
  | 'enhanced-care'
  | 'hdu'
  | 'icu'
  | 'day-case-discharge';

export type FlagPriority = 'high' | 'medium' | 'low';

export interface SafetyFlag {
  code: string;
  priority: FlagPriority;
  description: string;
}

export interface OperationNoteRow {
  id: string;
  hospital: string;
  theatre: string;
  listType: ListType;
  specialty: string;
  surgeon: string;
  surgeonGmc: string;
  anaesthetist: string;
  patientLabel: string; // anonymised, e.g. "Pt-001"
  patientAgeYears: number;
  patientSex: 'male' | 'female' | 'other';
  primaryProcedureOpcs4: string; // e.g. "W37.1"
  primaryProcedureName: string;
  urgency: NcepodUrgency;
  compositeRisk: CompositeRisk;
  clavienDindoGrade: ClavienDindo;
  asaPhysicalStatus: AsaPhysicalStatus;
  estimatedBloodLossMl: number;
  transfusionUnitsPrbc: number;
  countsAgreed: boolean;
  neverEventFlagged: boolean;
  conversionToOpen: boolean;
  recoveryDestination: RecoveryDestination;
  knifeToSkinAt: string; // ISO timestamp
  endOfSurgeryAt: string; // ISO timestamp
  durationMinutes: number;
  signedAt: string; // ISO timestamp; empty string when unsigned
  safetyFlags: SafetyFlag[];
}

function flag(code: string, priority: FlagPriority, description: string): SafetyFlag {
  return { code, priority, description };
}

export const SAMPLE_OPERATION_NOTES: OperationNoteRow[] = [
  {
    id: 'op-001',
    hospital: 'Royal United Hospital Bath',
    theatre: 'OR-3',
    listType: 'elective',
    specialty: 'general-surgery',
    surgeon: 'Miss R Adeyemi',
    surgeonGmc: 'GMC 7012345',
    anaesthetist: 'Dr T Begum',
    patientLabel: 'Pt-001',
    patientAgeYears: 42,
    patientSex: 'female',
    primaryProcedureOpcs4: 'J18.3',
    primaryProcedureName: 'Laparoscopic cholecystectomy',
    urgency: 'elective',
    compositeRisk: 'routine',
    clavienDindoGrade: '0',
    asaPhysicalStatus: 'II',
    estimatedBloodLossMl: 30,
    transfusionUnitsPrbc: 0,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'ward',
    knifeToSkinAt: '2026-05-04T09:12:00Z',
    endOfSurgeryAt: '2026-05-04T10:18:00Z',
    durationMinutes: 66,
    signedAt: '2026-05-04T10:42:00Z',
    safetyFlags: [],
  },
  {
    id: 'op-002',
    hospital: 'Royal United Hospital Bath',
    theatre: 'OR-1',
    listType: 'day-case',
    specialty: 'orthopaedics',
    surgeon: 'Mr H Cooper',
    surgeonGmc: 'GMC 6543210',
    anaesthetist: 'Dr P Iqbal',
    patientLabel: 'Pt-002',
    patientAgeYears: 28,
    patientSex: 'male',
    primaryProcedureOpcs4: 'W83.3',
    primaryProcedureName: 'Knee arthroscopy and meniscectomy',
    urgency: 'elective',
    compositeRisk: 'routine',
    clavienDindoGrade: '0',
    asaPhysicalStatus: 'I',
    estimatedBloodLossMl: 10,
    transfusionUnitsPrbc: 0,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'day-case-discharge',
    knifeToSkinAt: '2026-05-04T11:08:00Z',
    endOfSurgeryAt: '2026-05-04T11:46:00Z',
    durationMinutes: 38,
    signedAt: '2026-05-04T12:05:00Z',
    safetyFlags: [],
  },
  {
    id: 'op-003',
    hospital: 'Royal United Hospital Bath',
    theatre: 'OR-2',
    listType: 'elective',
    specialty: 'urology',
    surgeon: 'Mr S Tan',
    surgeonGmc: 'GMC 6112233',
    anaesthetist: 'Dr K Lloyd',
    patientLabel: 'Pt-003',
    patientAgeYears: 64,
    patientSex: 'male',
    primaryProcedureOpcs4: 'M65.3',
    primaryProcedureName: 'Transurethral resection of prostate',
    urgency: 'elective',
    compositeRisk: 'complicated',
    clavienDindoGrade: 'II',
    asaPhysicalStatus: 'III',
    estimatedBloodLossMl: 650,
    transfusionUnitsPrbc: 0,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'enhanced-care',
    knifeToSkinAt: '2026-05-05T08:30:00Z',
    endOfSurgeryAt: '2026-05-05T10:14:00Z',
    durationMinutes: 104,
    signedAt: '2026-05-05T10:55:00Z',
    safetyFlags: [
      flag('moderate-blood-loss', 'medium', 'EBL 650 mL exceeds the 500 mL routine threshold'),
    ],
  },
  {
    id: 'op-004',
    hospital: 'Bristol Royal Infirmary',
    theatre: 'OR-5',
    listType: 'cepod',
    specialty: 'general-surgery',
    surgeon: 'Mr D Okafor',
    surgeonGmc: 'GMC 7233445',
    anaesthetist: 'Dr S Ng',
    patientLabel: 'Pt-004',
    patientAgeYears: 71,
    patientSex: 'female',
    primaryProcedureOpcs4: 'H01.2',
    primaryProcedureName: 'Emergency laparoscopic appendicectomy converted to open',
    urgency: 'urgent',
    compositeRisk: 'complicated',
    clavienDindoGrade: 'II',
    asaPhysicalStatus: 'III',
    estimatedBloodLossMl: 350,
    transfusionUnitsPrbc: 0,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: true,
    recoveryDestination: 'ward',
    knifeToSkinAt: '2026-05-05T22:18:00Z',
    endOfSurgeryAt: '2026-05-06T00:02:00Z',
    durationMinutes: 104,
    signedAt: '2026-05-06T00:34:00Z',
    safetyFlags: [
      flag('conversion-to-open', 'medium', 'Laparoscopic case converted to open'),
    ],
  },
  {
    id: 'op-005',
    hospital: 'Bristol Royal Infirmary',
    theatre: 'OR-6',
    listType: 'trauma',
    specialty: 'orthopaedics',
    surgeon: 'Mr A Patel',
    surgeonGmc: 'GMC 7544221',
    anaesthetist: 'Dr R Mensah',
    patientLabel: 'Pt-005',
    patientAgeYears: 83,
    patientSex: 'female',
    primaryProcedureOpcs4: 'W19.3',
    primaryProcedureName: 'Dynamic hip screw fixation of intertrochanteric fracture',
    urgency: 'urgent',
    compositeRisk: 'high-risk',
    clavienDindoGrade: 'IIIa',
    asaPhysicalStatus: 'IV',
    estimatedBloodLossMl: 1800,
    transfusionUnitsPrbc: 2,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'hdu',
    knifeToSkinAt: '2026-05-06T07:45:00Z',
    endOfSurgeryAt: '2026-05-06T09:32:00Z',
    durationMinutes: 107,
    signedAt: '2026-05-06T10:11:00Z',
    safetyFlags: [
      flag('massive-haemorrhage', 'high', 'EBL 1800 mL exceeds 1500 mL massive-haemorrhage threshold'),
      flag('transfusion-given', 'high', 'Intra-operative transfusion (2 units PRBC)'),
      flag('unplanned-hdu', 'high', 'Post-op disposition stepped up to HDU'),
    ],
  },
  {
    id: 'op-006',
    hospital: 'Bristol Royal Infirmary',
    theatre: 'OR-7',
    listType: 'cepod',
    specialty: 'vascular',
    surgeon: 'Ms L Verma',
    surgeonGmc: 'GMC 6987765',
    anaesthetist: 'Dr E Sanchez',
    patientLabel: 'Pt-006',
    patientAgeYears: 76,
    patientSex: 'male',
    primaryProcedureOpcs4: 'L19.1',
    primaryProcedureName: 'Open repair of ruptured abdominal aortic aneurysm',
    urgency: 'immediate',
    compositeRisk: 'critical',
    clavienDindoGrade: 'IVa',
    asaPhysicalStatus: 'V',
    estimatedBloodLossMl: 4200,
    transfusionUnitsPrbc: 8,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'icu',
    knifeToSkinAt: '2026-05-06T14:02:00Z',
    endOfSurgeryAt: '2026-05-06T17:48:00Z',
    durationMinutes: 226,
    signedAt: '2026-05-06T18:35:00Z',
    safetyFlags: [
      flag('massive-haemorrhage', 'high', 'EBL 4200 mL exceeds critical 3000 mL threshold'),
      flag('massive-transfusion', 'high', '8 units PRBC intra-operative; MHP activated'),
      flag('unplanned-icu', 'high', 'Direct admission to ICU intubated'),
    ],
  },
  {
    id: 'op-007',
    hospital: 'Royal Devon University Hospital',
    theatre: 'OR-4',
    listType: 'elective',
    specialty: 'gynaecology',
    surgeon: 'Miss F Adesina',
    surgeonGmc: 'GMC 7099887',
    anaesthetist: 'Dr O Walsh',
    patientLabel: 'Pt-007',
    patientAgeYears: 47,
    patientSex: 'female',
    primaryProcedureOpcs4: 'Q07.4',
    primaryProcedureName: 'Total laparoscopic hysterectomy',
    urgency: 'elective',
    compositeRisk: 'critical',
    clavienDindoGrade: 'IIIb',
    asaPhysicalStatus: 'II',
    estimatedBloodLossMl: 1200,
    transfusionUnitsPrbc: 1,
    countsAgreed: false,
    neverEventFlagged: true,
    conversionToOpen: true,
    recoveryDestination: 'hdu',
    knifeToSkinAt: '2026-05-07T08:55:00Z',
    endOfSurgeryAt: '2026-05-07T12:40:00Z',
    durationMinutes: 225,
    signedAt: '',
    safetyFlags: [
      flag('incorrect-count', 'high', 'Swab count discrepancy unresolved at sign-out'),
      flag('retained-foreign-body-candidate', 'high', 'Imaging requested for suspected retained swab'),
      flag('never-event-suspicion', 'high', 'NHS England Never Event candidate; statutory report pending'),
      flag('conversion-to-open', 'medium', 'Laparoscopic case converted to open due to bleeding'),
    ],
  },
  {
    id: 'op-008',
    hospital: 'Royal Devon University Hospital',
    theatre: 'OR-2',
    listType: 'obstetric',
    specialty: 'obstetrics',
    surgeon: 'Mr J Khoury',
    surgeonGmc: 'GMC 6443322',
    anaesthetist: 'Dr H Park',
    patientLabel: 'Pt-008',
    patientAgeYears: 31,
    patientSex: 'female',
    primaryProcedureOpcs4: 'R17.1',
    primaryProcedureName: 'Category 1 emergency caesarean section',
    urgency: 'immediate',
    compositeRisk: 'high-risk',
    clavienDindoGrade: 'II',
    asaPhysicalStatus: 'III',
    estimatedBloodLossMl: 1600,
    transfusionUnitsPrbc: 2,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'enhanced-care',
    knifeToSkinAt: '2026-05-07T15:22:00Z',
    endOfSurgeryAt: '2026-05-07T16:10:00Z',
    durationMinutes: 48,
    signedAt: '2026-05-07T16:32:00Z',
    safetyFlags: [
      flag('massive-haemorrhage', 'high', 'Obstetric haemorrhage > 1500 mL'),
      flag('transfusion-given', 'high', '2 units PRBC intra-operative'),
    ],
  },
  {
    id: 'op-009',
    hospital: 'Royal United Hospital Bath',
    theatre: 'Endo-1',
    listType: 'endoscopy',
    specialty: 'gastroenterology',
    surgeon: 'Dr M Reeve',
    surgeonGmc: 'GMC 6651122',
    anaesthetist: 'Dr P Iqbal',
    patientLabel: 'Pt-009',
    patientAgeYears: 58,
    patientSex: 'male',
    primaryProcedureOpcs4: 'H22.1',
    primaryProcedureName: 'Diagnostic colonoscopy with polypectomy',
    urgency: 'elective',
    compositeRisk: 'routine',
    clavienDindoGrade: '0',
    asaPhysicalStatus: 'II',
    estimatedBloodLossMl: 5,
    transfusionUnitsPrbc: 0,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'day-case-discharge',
    knifeToSkinAt: '2026-05-08T09:30:00Z',
    endOfSurgeryAt: '2026-05-08T10:05:00Z',
    durationMinutes: 35,
    signedAt: '2026-05-08T10:18:00Z',
    safetyFlags: [],
  },
  {
    id: 'op-010',
    hospital: 'Royal Devon University Hospital',
    theatre: 'OR-1',
    listType: 'elective',
    specialty: 'cardiothoracic',
    surgeon: 'Mr V Singh',
    surgeonGmc: 'GMC 6776543',
    anaesthetist: 'Dr R Mensah',
    patientLabel: 'Pt-010',
    patientAgeYears: 67,
    patientSex: 'male',
    primaryProcedureOpcs4: 'K40.1',
    primaryProcedureName: 'Coronary artery bypass grafting (×3)',
    urgency: 'expedited',
    compositeRisk: 'high-risk',
    clavienDindoGrade: 'IIIa',
    asaPhysicalStatus: 'IV',
    estimatedBloodLossMl: 2400,
    transfusionUnitsPrbc: 3,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'icu',
    knifeToSkinAt: '2026-05-08T08:10:00Z',
    endOfSurgeryAt: '2026-05-08T13:25:00Z',
    durationMinutes: 315,
    signedAt: '2026-05-08T14:05:00Z',
    safetyFlags: [
      flag('massive-haemorrhage', 'high', 'EBL 2400 mL > 1500 mL'),
      flag('transfusion-given', 'high', '3 units PRBC intra-operative'),
      flag('planned-icu', 'medium', 'ICU admission planned per pre-op pathway'),
    ],
  },
  {
    id: 'op-011',
    hospital: 'Bristol Royal Infirmary',
    theatre: 'OR-3',
    listType: 'elective',
    specialty: 'ent',
    surgeon: 'Miss A Liu',
    surgeonGmc: 'GMC 7321987',
    anaesthetist: 'Dr E Sanchez',
    patientLabel: 'Pt-011',
    patientAgeYears: 6,
    patientSex: 'female',
    primaryProcedureOpcs4: 'F34.1',
    primaryProcedureName: 'Tonsillectomy and adenoidectomy',
    urgency: 'elective',
    compositeRisk: 'complicated',
    clavienDindoGrade: 'I',
    asaPhysicalStatus: 'I',
    estimatedBloodLossMl: 120,
    transfusionUnitsPrbc: 0,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'pacu',
    knifeToSkinAt: '2026-05-08T10:55:00Z',
    endOfSurgeryAt: '2026-05-08T11:42:00Z',
    durationMinutes: 47,
    signedAt: '',
    safetyFlags: [
      flag('anaesthetic-incident', 'high', 'Brief laryngospasm at extubation; resolved with positive pressure'),
    ],
  },
  {
    id: 'op-012',
    hospital: 'Royal United Hospital Bath',
    theatre: 'OR-4',
    listType: 'cepod',
    specialty: 'neurosurgery',
    surgeon: 'Mr K Eriksen',
    surgeonGmc: 'GMC 6234567',
    anaesthetist: 'Dr S Ng',
    patientLabel: 'Pt-012',
    patientAgeYears: 54,
    patientSex: 'male',
    primaryProcedureOpcs4: 'A40.2',
    primaryProcedureName: 'Decompressive craniectomy for traumatic haematoma',
    urgency: 'immediate',
    compositeRisk: 'critical',
    clavienDindoGrade: 'IVb',
    asaPhysicalStatus: 'V',
    estimatedBloodLossMl: 900,
    transfusionUnitsPrbc: 1,
    countsAgreed: true,
    neverEventFlagged: false,
    conversionToOpen: false,
    recoveryDestination: 'icu',
    knifeToSkinAt: '2026-05-09T02:14:00Z',
    endOfSurgeryAt: '2026-05-09T05:38:00Z',
    durationMinutes: 204,
    signedAt: '2026-05-09T06:12:00Z',
    safetyFlags: [
      flag('intra-operative-arrest', 'high', 'Brief PEA arrest; ROSC after 2 minutes CPR'),
      flag('unplanned-icu', 'high', 'Ventilated to ICU'),
    ],
  },
];
