<!ELEMENT grade (id,created_at,updated_at,deleted_at,assessment_id,gaf_score,gaf_category,symptom_severity,functional_impairment,risk_classification,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT assessment_id (#PCDATA)>
<!ELEMENT gaf_score (#PCDATA)>
<!ELEMENT gaf_category (#PCDATA)>
<!ELEMENT symptom_severity (#PCDATA)>
<!ELEMENT functional_impairment (#PCDATA)>
<!ELEMENT risk_classification (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
