//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::child_safeguarding_referral_grade_flags::Entity as ChildSafeguardingReferralGradeFlags;
pub use super::child_safeguarding_referral_grade_rules::Entity as ChildSafeguardingReferralGradeRules;
pub use super::child_safeguarding_referral_grades::Entity as ChildSafeguardingReferralGrades;
pub use super::child_safeguarding_referrals::Entity as ChildSafeguardingReferrals;
pub use super::clinicians::Entity as Clinicians;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
