//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::hematology_waiting_list_card_appointments::Entity as HematologyWaitingListCardAppointments;
pub use super::hematology_waiting_list_card_grade_flags::Entity as HematologyWaitingListCardGradeFlags;
pub use super::hematology_waiting_list_card_grade_rules::Entity as HematologyWaitingListCardGradeRules;
pub use super::hematology_waiting_list_card_grades::Entity as HematologyWaitingListCardGrades;
pub use super::hematology_waiting_list_cards::Entity as HematologyWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
