<!ELEMENT mammography_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,exam_type,primary_indication,clinical_question,relevant_history,laterality,symptom_lump,symptom_pain,symptom_nipple_discharge,symptom_skin_change,symptom_nipple_inversion,previous_mammogram,previous_mammogram_date,family_history_breast_cancer,breast_implants,pregnancy_or_lactating,hormone_replacement_therapy,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT exam_type (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT laterality (#PCDATA)>
<!ELEMENT symptom_lump (#PCDATA)>
<!ELEMENT symptom_pain (#PCDATA)>
<!ELEMENT symptom_nipple_discharge (#PCDATA)>
<!ELEMENT symptom_skin_change (#PCDATA)>
<!ELEMENT symptom_nipple_inversion (#PCDATA)>
<!ELEMENT previous_mammogram (#PCDATA)>
<!ELEMENT previous_mammogram_date (#PCDATA)>
<!ELEMENT family_history_breast_cancer (#PCDATA)>
<!ELEMENT breast_implants (#PCDATA)>
<!ELEMENT pregnancy_or_lactating (#PCDATA)>
<!ELEMENT hormone_replacement_therapy (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
