//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::immunology_waiting_list_card_appointments::Entity as ImmunologyWaitingListCardAppointments;
pub use super::immunology_waiting_list_card_grade_flags::Entity as ImmunologyWaitingListCardGradeFlags;
pub use super::immunology_waiting_list_card_grade_rules::Entity as ImmunologyWaitingListCardGradeRules;
pub use super::immunology_waiting_list_card_grades::Entity as ImmunologyWaitingListCardGrades;
pub use super::immunology_waiting_list_cards::Entity as ImmunologyWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
