mod users;

mod patients;
mod practitioners;
mod neurosurgery_waiting_list_cards;
mod neurosurgery_waiting_list_card_appointments;
mod neurosurgery_waiting_list_card_grades;
mod neurosurgery_waiting_list_card_grade_rules;
mod neurosurgery_waiting_list_card_grade_flags;