<!ELEMENT allergy_skin_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,test_type,allergen_aeroallergens,allergen_food,allergen_drug,allergen_venom,allergen_latex,allergen_contact,primary_indication,clinical_question,clinical_details,previous_anaphylaxis,on_antihistamines,on_beta_blocker,current_skin_disease,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT test_type (#PCDATA)>
<!ELEMENT allergen_aeroallergens (#PCDATA)>
<!ELEMENT allergen_food (#PCDATA)>
<!ELEMENT allergen_drug (#PCDATA)>
<!ELEMENT allergen_venom (#PCDATA)>
<!ELEMENT allergen_latex (#PCDATA)>
<!ELEMENT allergen_contact (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT clinical_details (#PCDATA)>
<!ELEMENT previous_anaphylaxis (#PCDATA)>
<!ELEMENT on_antihistamines (#PCDATA)>
<!ELEMENT on_beta_blocker (#PCDATA)>
<!ELEMENT current_skin_disease (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
