// The canonical blank assessment.
//
// Lives in the engine rather than the store so it can be imported by pure
// code and by the Vitest suite without pulling in SvelteKit's $app modules.

import type { DieticAssessment } from './types';

/**
 * A blank dietetic assessment with every field at its unanswered default:
 * '' for text and enum fields, null for numeric, date, and time fields.
 */
export function createDefaultAssessment(): DieticAssessment {
	return {
		status: 'draft',
		dietitian: {
			dietitianName: '',
			role: '',
			specialty: '',
			registrationBody: '',
			registrationNumber: '',
			assessmentDate: '',
			assessmentTime: '',
			siteName: '',
			serviceName: '',
			setting: '',
			appointmentType: '',
			plannedDurationMinutes: null,
			interpreterRequired: '',
			interpreterLanguage: ''
		},
		patient: {
			firstName: '',
			lastName: '',
			birthDate: '',
			sex: '',
			nhsNumber: '',
			preferredLanguage: '',
			referralSource: '',
			referralDate: '',
			referralReason: '',
			primaryCondition: '',
			consentToRecord: '',
			accompaniedBy: ''
		},
		history: {
			conditionDiabetes: '',
			conditionCoeliac: '',
			conditionInflammatoryBowelDisease: '',
			conditionChronicKidneyDisease: '',
			conditionLiverDisease: '',
			conditionCancer: '',
			conditionCardiovascularDisease: '',
			conditionRespiratoryDisease: '',
			conditionStroke: '',
			conditionDementia: '',
			conditionEatingDisorder: '',
			conditionOther: '',
			recentSurgery: '',
			recentSurgeryType: '',
			recentSurgeryDate: '',
			gastrointestinalSurgery: '',
			currentSymptoms: '',
			familyHistory: '',
			pregnancyStatus: ''
		},
		medication: {
			takesPrescriptionMedicines: '',
			takesOverTheCounterMedicines: '',
			takesVitaminSupplements: '',
			takesMineralSupplements: '',
			takesHerbalProducts: '',
			takesOralNutritionalSupplements: '',
			oralNutritionalSupplementDetail: '',
			enteralNutrition: '',
			enteralRoute: '',
			enteralTubeProblem: '',
			parenteralNutrition: '',
			drugNutrientInteraction: '',
			drugNutrientInteractionDetail: '',
			medicationAdherence: '',
			medicationNotes: ''
		},
		anthropometry: {
			measurementMethod: '',
			heightAsCm: null,
			weightAsKg: null,
			midUpperArmCircumferenceAsCm: null,
			calfCircumferenceAsCm: null,
			waistAsCm: null,
			usualWeightAsKg: null,
			weight3MonthsAgoAsKg: null,
			weight6MonthsAgoAsKg: null,
			weightLossIsIntentional: '',
			weightTrend: '',
			clothesOrJewelleryLooser: '',
			oedemaPresent: '',
			oedemaAdjustmentKg: null,
			ascitesPresent: '',
			amputationPresent: '',
			amputationAdjustmentPercent: null,
			anthropometryNotes: ''
		},
		biochemistry: {
			bloodsSampleDate: '',
			albuminGPerL: null,
			cReactiveProteinMgPerL: null,
			haemoglobinGPerL: null,
			ferritinUgPerL: null,
			vitaminB12NgPerL: null,
			folateUgPerL: null,
			vitaminDNmolPerL: null,
			hba1cMmolPerMol: null,
			sodiumMmolPerL: null,
			potassiumMmolPerL: null,
			magnesiumMmolPerL: null,
			phosphateMmolPerL: null,
			correctedCalciumMmolPerL: null,
			ureaMmolPerL: null,
			creatinineUmolPerL: null,
			egfrMlPerMin: null,
			alanineAminotransferaseUPerL: null,
			bilirubinUmolPerL: null,
			totalCholesterolMmolPerL: null,
			triglyceridesMmolPerL: null,
			biochemistryNotes: ''
		},
		physicalExam: {
			subcutaneousFatLoss: '',
			muscleWastingTemples: '',
			muscleWastingClavicles: '',
			muscleWastingQuadriceps: '',
			muscleWastingSeverity: '',
			peripheralOedemaSeverity: '',
			oralHealth: '',
			dentition: '',
			chewingAbility: '',
			tongueAndMucosa: '',
			skinCondition: '',
			hairCondition: '',
			nailCondition: '',
			pressureUlcerPresent: '',
			pressureUlcerCategory: '',
			handGripStrengthKg: null,
			physicalExamNotes: ''
		},
		dietaryRecall: {
			mealsPerDay: null,
			snacksPerDay: null,
			recallBreakfast: '',
			recallMidMorning: '',
			recallLunch: '',
			recallAfternoon: '',
			recallDinner: '',
			recallEvening: '',
			portionSize: '',
			appetite: '',
			appetiteScore0To10: null,
			proportionOfUsualIntakePercent: null,
			mealsOutPerWeek: null,
			takeawaysPerWeek: null,
			foodDiaryCompleted: '',
			estimatedEnergyIntakeKcal: null,
			estimatedProteinIntakeG: null,
			eatsAlone: '',
			dietaryRecallNotes: ''
		},
		hydration: {
			fluidIntakeMlPerDay: null,
			fluidTypes: '',
			caffeinatedDrinksPerDay: null,
			alcoholUnitsPerWeek: null,
			thickenedFluids: '',
			thickenedFluidsIddsiLevel: '',
			hydrationSigns: '',
			fluidRestriction: '',
			fluidRestrictionMlPerDay: null,
			hydrationNotes: ''
		},
		preferences: {
			hasFoodAllergy: '',
			foodAllergyDetail: '',
			allergySeverity: '',
			hasFoodIntolerance: '',
			foodsAvoided: '',
			avoidanceReason: '',
			dislikes: '',
			therapeuticDiet: '',
			dietaryPattern: '',
			religiousOrCulturalRequirement: '',
			fastingPractice: '',
			textureModifiedDiet: '',
			textureModifiedIddsiLevel: '',
			preferencesNotes: ''
		},
		gastrointestinal: {
			appetiteChange: '',
			earlySatiety: '',
			nausea: '',
			vomiting: '',
			dysphagia: '',
			dysphagiaScreenOutcome: '',
			speechAndLanguageTherapy: '',
			reflux: '',
			abdominalPain: '',
			bloating: '',
			bowelFrequencyPerWeek: null,
			bristolStoolType: '',
			constipation: '',
			diarrhoea: '',
			stomaPresent: '',
			stomaOutputMlPerDay: null,
			malabsorptionSigns: '',
			gastrointestinalNotes: ''
		},
		environment: {
			livingSituation: '',
			whoShops: '',
			whoCooks: '',
			cookingSkills: '',
			cookingConfidence0To10: null,
			hasCooker: '',
			hasFridge: '',
			hasFreezer: '',
			hasMicrowave: '',
			foodBudgetPerWeek: null,
			worriedFoodWouldRunOut: '',
			skippedMealsForMoney: '',
			usesFoodBank: '',
			accessToShops: '',
			hasTransport: '',
			workPattern: '',
			mealSupport: '',
			socialSupport: '',
			environmentNotes: ''
		},
		activity: {
			activityLevel: '',
			exerciseType: '',
			exerciseMinutesPerWeek: null,
			sedentaryHoursPerDay: null,
			mobility: '',
			fallsInLast12Months: null,
			sarcfStrength: null,
			sarcfWalking: null,
			sarcfRisingFromChair: null,
			sarcfClimbingStairs: null,
			sarcfFalls: null,
			eatsIndependently: '',
			feedingAssistanceRequired: '',
			functionNotes: ''
		},
		behavioural: {
			motivation0To10: null,
			stageOfChange: '',
			selfEfficacy0To10: null,
			previousAttempts: '',
			barriers: '',
			scoffMakeYourselfSick: '',
			scoffLostControl: '',
			scoffLostOneStone: '',
			scoffBelieveYourselfFat: '',
			scoffFoodDominates: '',
			mood: '',
			anxiety: '',
			cognitiveImpairment: '',
			capacityConcern: '',
			safeguardingConcern: '',
			healthLiteracy: '',
			preferredLearningStyle: '',
			patientGoalInOwnWords: ''
		},
		screening: {
			acutelyIll: '',
			noNutritionalIntakeOver5Days: '',
			daysOfNegligibleIntake: null,
			nrs2002Score: null,
			energyRequirementKcal: null,
			proteinRequirementG: null,
			fluidRequirementMl: null,
			requirementEquation: '',
			pesProblem: '',
			pesEtiology: '',
			pesSignsSymptoms: ''
		},
		plan: {
			interventionType: '',
			prescribedSupplement: '',
			prescribedSupplementDose: '',
			textureModificationPlan: '',
			goal1: '',
			goal2: '',
			goal3: '',
			educationProvided: '',
			resourcesGiven: '',
			monitoringIndicators: '',
			reviewIntervalWeeks: null,
			reviewDate: '',
			onwardReferral: '',
			overrideCompositeRisk: '',
			overrideReason: '',
			additionalNotes: '',
			signedByName: ''
		}
	};
}
