<!ELEMENT waterlow_pressure_ulcer_risk_assessment (id,created_at,updated_at,deleted_at,patient_id,clinician_id,nurse_name,nurse_role,assessed_at,care_setting,assessment_reason,patient_identifier,age_band,sex,build_weight_for_height,skin_type,continence,mobility,tissue_malnutrition,neurological_deficit,major_surgery_trauma,medication,existing_pressure_damage,clinical_note)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT nurse_name (#PCDATA)>
<!ELEMENT nurse_role (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT assessment_reason (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT age_band (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT build_weight_for_height (#PCDATA)>
<!ELEMENT skin_type (#PCDATA)>
<!ELEMENT continence (#PCDATA)>
<!ELEMENT mobility (#PCDATA)>
<!ELEMENT tissue_malnutrition (#PCDATA)>
<!ELEMENT neurological_deficit (#PCDATA)>
<!ELEMENT major_surgery_trauma (#PCDATA)>
<!ELEMENT medication (#PCDATA)>
<!ELEMENT existing_pressure_damage (#PCDATA)>
<!ELEMENT clinical_note (#PCDATA)>
