<!ELEMENT waterlow_pressure_ulcer_risk_assessment_grade (id,created_at,updated_at,deleted_at,waterlow_pressure_ulcer_risk_assessment_id,build_points,skin_points,sex_points,age_points,continence_points,mobility_points,tissue_malnutrition_points,neurological_deficit_points,major_surgery_trauma_points,medication_points,total_score,risk_band,prevention_actions,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT waterlow_pressure_ulcer_risk_assessment_id (#PCDATA)>
<!ELEMENT build_points (#PCDATA)>
<!ELEMENT skin_points (#PCDATA)>
<!ELEMENT sex_points (#PCDATA)>
<!ELEMENT age_points (#PCDATA)>
<!ELEMENT continence_points (#PCDATA)>
<!ELEMENT mobility_points (#PCDATA)>
<!ELEMENT tissue_malnutrition_points (#PCDATA)>
<!ELEMENT neurological_deficit_points (#PCDATA)>
<!ELEMENT major_surgery_trauma_points (#PCDATA)>
<!ELEMENT medication_points (#PCDATA)>
<!ELEMENT total_score (#PCDATA)>
<!ELEMENT risk_band (#PCDATA)>
<!ELEMENT prevention_actions (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
