<!ELEMENT gen_surgery_waiting_list_card_appointment (id,created_at,updated_at,deleted_at,gen_surgery_waiting_list_card_id,appointment_date,appointment_time,duration_minutes,appointment_type,site_name,site_address,clinic_name,room,clinician_name,clinician_team,status,travel_notes,access_notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT gen_surgery_waiting_list_card_id (#PCDATA)>
<!ELEMENT appointment_date (#PCDATA)>
<!ELEMENT appointment_time (#PCDATA)>
<!ELEMENT duration_minutes (#PCDATA)>
<!ELEMENT appointment_type (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT site_address (#PCDATA)>
<!ELEMENT clinic_name (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT clinician_name (#PCDATA)>
<!ELEMENT clinician_team (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT travel_notes (#PCDATA)>
<!ELEMENT access_notes (#PCDATA)>
