mod users;

mod patients;
mod clinicians;
mod medical_practices;
mod united_kingdom_statement_of_fitness_for_works;
mod united_kingdom_statement_of_fitness_for_work_grades;
mod united_kingdom_statement_of_fitness_for_work_grade_rules;
mod united_kingdom_statement_of_fitness_for_work_grade_flags;