//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clinicians;
pub mod edinburgh_postnatal_depression_scale_grade_flags;
pub mod edinburgh_postnatal_depression_scale_grade_rules;
pub mod edinburgh_postnatal_depression_scale_grades;
pub mod edinburgh_postnatal_depression_scales;
pub mod patients;
pub mod users;
