<!ELEMENT certificate_provider (id,created_at,updated_at,deleted_at,title,given_names,family_name,email,phone,postal_address_as_full_text,country_as_iso_3166_1_alpha_2,postcode,route,profession,profession_registration_number,years_known_donor,relationship_to_donor,declared_not_family,declared_not_employee,declared_not_attorney)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT given_names (#PCDATA)>
<!ELEMENT family_name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT postal_address_as_full_text (#PCDATA)>
<!ELEMENT country_as_iso_3166_1_alpha_2 (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT route (#PCDATA)>
<!ELEMENT profession (#PCDATA)>
<!ELEMENT profession_registration_number (#PCDATA)>
<!ELEMENT years_known_donor (#PCDATA)>
<!ELEMENT relationship_to_donor (#PCDATA)>
<!ELEMENT declared_not_family (#PCDATA)>
<!ELEMENT declared_not_employee (#PCDATA)>
<!ELEMENT declared_not_attorney (#PCDATA)>
