<!ELEMENT donor (id,created_at,updated_at,deleted_at,title,given_names,family_name,other_names_used,birth_date,email,phone,postal_address_as_full_text,country_as_iso_3166_1_alpha_2,postcode,united_kingdom_nhs_number,jurisdiction,preferred_language,capacity_declared,capacity_declared_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT given_names (#PCDATA)>
<!ELEMENT family_name (#PCDATA)>
<!ELEMENT other_names_used (#PCDATA)>
<!ELEMENT birth_date (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT postal_address_as_full_text (#PCDATA)>
<!ELEMENT country_as_iso_3166_1_alpha_2 (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT united_kingdom_nhs_number (#PCDATA)>
<!ELEMENT jurisdiction (#PCDATA)>
<!ELEMENT preferred_language (#PCDATA)>
<!ELEMENT capacity_declared (#PCDATA)>
<!ELEMENT capacity_declared_at (#PCDATA)>
