//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::patients::Entity as Patients;
pub use super::sleep_study_test_request_grade_flags::Entity as SleepStudyTestRequestGradeFlags;
pub use super::sleep_study_test_request_grade_rules::Entity as SleepStudyTestRequestGradeRules;
pub use super::sleep_study_test_request_grades::Entity as SleepStudyTestRequestGrades;
pub use super::sleep_study_test_requests::Entity as SleepStudyTestRequests;
pub use super::users::Entity as Users;
