<!ELEMENT international_certificate_of_vaccination_or_prophylaxis (id,created_at,updated_at,deleted_at,patient_id,clinician_id,center_id,status,issued_at,revoked_at,revocation_reason,certificate_serial_number,issuing_country_as_iso_3166_1_alpha_3,primary_language_as_bcp_47,secondary_language_as_bcp_47,tertiary_language_as_bcp_47,destination_countries_as_iso_3166_1_alpha_3,planned_arrival_date,purpose_of_travel,medical_waiver,medical_waiver_reason,medical_waiver_signed_by_clinician_id,medical_waiver_signed_at,declared_pregnancy,declared_breastfeeding,declared_immunosuppression,electronic_signature_data_url,electronic_signature_signed_at,overall_valid,validity_computed_at,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT center_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT issued_at (#PCDATA)>
<!ELEMENT revoked_at (#PCDATA)>
<!ELEMENT revocation_reason (#PCDATA)>
<!ELEMENT certificate_serial_number (#PCDATA)>
<!ELEMENT issuing_country_as_iso_3166_1_alpha_3 (#PCDATA)>
<!ELEMENT primary_language_as_bcp_47 (#PCDATA)>
<!ELEMENT secondary_language_as_bcp_47 (#PCDATA)>
<!ELEMENT tertiary_language_as_bcp_47 (#PCDATA)>
<!ELEMENT destination_countries_as_iso_3166_1_alpha_3 (#PCDATA)>
<!ELEMENT planned_arrival_date (#PCDATA)>
<!ELEMENT purpose_of_travel (#PCDATA)>
<!ELEMENT medical_waiver (#PCDATA)>
<!ELEMENT medical_waiver_reason (#PCDATA)>
<!ELEMENT medical_waiver_signed_by_clinician_id (#PCDATA)>
<!ELEMENT medical_waiver_signed_at (#PCDATA)>
<!ELEMENT declared_pregnancy (#PCDATA)>
<!ELEMENT declared_breastfeeding (#PCDATA)>
<!ELEMENT declared_immunosuppression (#PCDATA)>
<!ELEMENT electronic_signature_data_url (#PCDATA)>
<!ELEMENT electronic_signature_signed_at (#PCDATA)>
<!ELEMENT overall_valid (#PCDATA)>
<!ELEMENT validity_computed_at (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
