<!ELEMENT records_to_disclose (id,created_at,updated_at,deleted_at,hipaa_authorization_id,include_medical_health,medical_health_initials,include_mental_health,mental_health_initials,include_substance_use,substance_use_initials,part2_redisclosure_notice_included,include_hiv_aids,hiv_aids_initials,hiv_aids_state_consent_included,include_psychotherapy_notes,include_genetic_information,include_reproductive_health,section_7332_notice_included,date_range_specified,date_from,date_to,other_description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT hipaa_authorization_id (#PCDATA)>
<!ELEMENT include_medical_health (#PCDATA)>
<!ELEMENT medical_health_initials (#PCDATA)>
<!ELEMENT include_mental_health (#PCDATA)>
<!ELEMENT mental_health_initials (#PCDATA)>
<!ELEMENT include_substance_use (#PCDATA)>
<!ELEMENT substance_use_initials (#PCDATA)>
<!ELEMENT part2_redisclosure_notice_included (#PCDATA)>
<!ELEMENT include_hiv_aids (#PCDATA)>
<!ELEMENT hiv_aids_initials (#PCDATA)>
<!ELEMENT hiv_aids_state_consent_included (#PCDATA)>
<!ELEMENT include_psychotherapy_notes (#PCDATA)>
<!ELEMENT include_genetic_information (#PCDATA)>
<!ELEMENT include_reproductive_health (#PCDATA)>
<!ELEMENT section_7332_notice_included (#PCDATA)>
<!ELEMENT date_range_specified (#PCDATA)>
<!ELEMENT date_from (#PCDATA)>
<!ELEMENT date_to (#PCDATA)>
<!ELEMENT other_description (#PCDATA)>
