//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod allergies;
pub mod clinicians;
pub mod medications;
pub mod patient_allergies;
pub mod patient_medications;
pub mod patients;
pub mod pre_operative_assessment_by_clinician_grades;
pub mod pre_operative_assessment_by_clinicians;
pub mod users;
