import type { OperationNote } from './types.js';

/**
 * Construct an empty Medical Operation Note. Empty strings for unanswered
 * text / enum fields; null for unanswered numeric / date / time fields.
 */
export function createEmptyOperationNote(): OperationNote {
  return {
    operation: {
      hospital: '',
      theatreNumber: '',
      listType: '',
      caseStartAt: '',
      anaesthesiaStartAt: '',
      knifeToSkinAt: '',
      endOfSurgeryAt: '',
      caseEndAt: '',
    },
    patient: {
      nhsNumber: '',
      mrn: '',
      firstName: '',
      lastName: '',
      dateOfBirth: '',
      sex: '',
      weightKg: null,
      heightCm: null,
      allergiesSummary: '',
      consentStatus: '',
      sideMarked: '',
      whoSignInCompleted: '',
    },
    team: [],
    diagnosesAndProcedures: {
      preOperativeDiagnosis: '',
      postOperativeDiagnosis: '',
      plannedProcedures: '',
      performedProcedures: '',
      opcs4Codes: '',
      urgency: '',
      laterality: '',
      indication: '',
    },
    anaesthesia: {
      type: '',
      airway: '',
      inductionAgent: '',
      maintenanceAgent: '',
      neuromuscularBlockade: '',
      regionalBlockDetails: '',
      linesAndMonitoring: '',
      crystalloidMl: null,
      colloidMl: null,
      bloodMl: null,
      events: '',
    },
    positionPrepApproach: {
      patientPosition: '',
      pressureAreaProtection: '',
      prepSolution: '',
      drapes: '',
      surgicalApproach: '',
      incisionType: '',
      incisionLengthCm: null,
      tableTilt: '',
      tourniquetSite: '',
      tourniquetPressureMmHg: null,
      tourniquetTimeOnAt: '',
      tourniquetTimeOffAt: '',
    },
    operativeFindings: {
      techniqueSteps: '',
      pathologyFound: '',
      anatomicalAnomalies: '',
      intraOpPhotographsTaken: '',
      frozenSectionRequested: '',
    },
    materialsImplants: {
      sutures: '',
      staples: '',
      clips: '',
      mesh: '',
      screwsPlates: '',
      prostheticJoints: '',
      vascularGrafts: '',
      lotSerialBatchExpiry: '',
      manufacturer: '',
      registrySubmitted: '',
    },
    drainsPacksSpecimens: {
      drainsPlaced: '',
      packsLeftInSitu: '',
      packsRemovalByDate: '',
      urinaryCatheter: '',
      ngTube: '',
      specimensSent: '',
      specimensPathologyDestination: '',
      specimensUrgent: '',
    },
    safetyCountsEbl: {
      swabCountFirst: null,
      swabCountFinal: null,
      swabCountAgreed: '',
      needleCountFirst: null,
      needleCountFinal: null,
      needleCountAgreed: '',
      instrumentCountFirst: null,
      instrumentCountFinal: null,
      instrumentCountAgreed: '',
      countDiscrepancyResolution: '',
      estimatedBloodLossMl: null,
      prbcUnits: null,
      ffpUnits: null,
      plateletsUnits: null,
      cryoUnits: null,
      massiveHaemorrhageProtocolActivated: '',
      clavienDindoGrade: '',
      complicationDescription: '',
      conversionToOpen: '',
      retainedForeignBody: '',
      neverEventFlags: '',
      intraOperativeArrest: '',
      specimenLabellingIssue: '',
      equipmentProblem: '',
    },
    postOperativePlan: {
      recoveryDestination: '',
      unplannedEscalation: '',
      monitoringFrequency: '',
      ivFluidsPlan: '',
      analgesiaPlan: '',
      antibioticsPlan: '',
      vteProphylaxis: '',
      diet: '',
      mobilisation: '',
      woundCare: '',
      drainRemovalPlan: '',
      followUpPlan: '',
      specialInstructions: '',
      whoSignOutCompleted: '',
      debriefCompleted: '',
    },
    signOff: {
      asaPhysicalStatus: null,
      surgeonOverrideRisk: '',
      surgeonOverrideReason: '',
      attestation: '',
      electronicSignatureName: '',
      dictationTimestamp: '',
      documentationGap: '',
    },
  };
}
