mod users;

mod patients;
mod practitioners;
mod family_general_waiting_list_cards;
mod family_general_waiting_list_card_appointments;
mod family_general_waiting_list_card_grades;
mod family_general_waiting_list_card_grade_rules;
mod family_general_waiting_list_card_grade_flags;