//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::patients::Entity as Patients;
pub use super::respect::Entity as Respect;
pub use super::respect_grade_flags::Entity as RespectGradeFlags;
pub use super::respect_grade_rules::Entity as RespectGradeRules;
pub use super::respect_grades::Entity as RespectGrades;
pub use super::users::Entity as Users;
