<!ELEMENT cha2ds2_vasc (id,created_at,updated_at,deleted_at,patient_id,clinician_id,clinician_name,clinician_role,assessed_at,care_setting,atrial_fibrillation_type,patient_identifier,age_years,sex,congestive_heart_failure,hypertension,diabetes,stroke_tia_thromboembolism,vascular_disease,clinical_note)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT clinician_name (#PCDATA)>
<!ELEMENT clinician_role (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT atrial_fibrillation_type (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT age_years (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT congestive_heart_failure (#PCDATA)>
<!ELEMENT hypertension (#PCDATA)>
<!ELEMENT diabetes (#PCDATA)>
<!ELEMENT stroke_tia_thromboembolism (#PCDATA)>
<!ELEMENT vascular_disease (#PCDATA)>
<!ELEMENT clinical_note (#PCDATA)>
