<!ELEMENT uk_nhs_digital_technology_assessment_criteria_grade (id,created_at,updated_at,deleted_at,uk_nhs_digital_technology_assessment_criteria_id,outcome,mandatory_total,mandatory_met,advisory_total,advisory_met,section_a_result,section_b_result,section_c_result,section_d_result,section_e_result,section_f_result,section_g_result,assessor_override_reason,final_outcome,signed_at,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT uk_nhs_digital_technology_assessment_criteria_id (#PCDATA)>
<!ELEMENT outcome (#PCDATA)>
<!ELEMENT mandatory_total (#PCDATA)>
<!ELEMENT mandatory_met (#PCDATA)>
<!ELEMENT advisory_total (#PCDATA)>
<!ELEMENT advisory_met (#PCDATA)>
<!ELEMENT section_a_result (#PCDATA)>
<!ELEMENT section_b_result (#PCDATA)>
<!ELEMENT section_c_result (#PCDATA)>
<!ELEMENT section_d_result (#PCDATA)>
<!ELEMENT section_e_result (#PCDATA)>
<!ELEMENT section_f_result (#PCDATA)>
<!ELEMENT section_g_result (#PCDATA)>
<!ELEMENT assessor_override_reason (#PCDATA)>
<!ELEMENT final_outcome (#PCDATA)>
<!ELEMENT signed_at (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
