//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
pub use super::zarit_burden_interview_grade_flags::Entity as ZaritBurdenInterviewGradeFlags;
pub use super::zarit_burden_interview_grade_rules::Entity as ZaritBurdenInterviewGradeRules;
pub use super::zarit_burden_interview_grades::Entity as ZaritBurdenInterviewGrades;
pub use super::zarit_burden_interviews::Entity as ZaritBurdenInterviews;
