//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::rheumatology_waiting_list_card_appointments::Entity as RheumatologyWaitingListCardAppointments;
pub use super::rheumatology_waiting_list_card_grade_flags::Entity as RheumatologyWaitingListCardGradeFlags;
pub use super::rheumatology_waiting_list_card_grade_rules::Entity as RheumatologyWaitingListCardGradeRules;
pub use super::rheumatology_waiting_list_card_grades::Entity as RheumatologyWaitingListCardGrades;
pub use super::rheumatology_waiting_list_cards::Entity as RheumatologyWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
