export const sampleAuthorizations = [
  {
    patientName: 'Alice Anderson',
    recipientOrganization: 'Tennessee Department of Human Services',
    primaryPurpose: 'eligibility-determination',
    categories: ['medical-health', 'mental-health'],
    expirationDate: '2027-05-18',
    validityStatus: 'valid',
    highPriorityFlags: 0,
    signatureDate: '2026-05-18',
  },
  {
    patientName: 'Bob Brown',
    recipientOrganization: 'Pennsylvania DHS',
    primaryPurpose: 'continuing-treatment',
    categories: ['medical-health', 'substance-use'],
    expirationDate: '2027-01-04',
    validityStatus: 'invalid',
    highPriorityFlags: 2,
    signatureDate: '2026-01-04',
  },
  {
    patientName: 'Carla Castillo',
    recipientOrganization: 'Acme Insurance Co.',
    primaryPurpose: 'insurance-claim',
    categories: ['medical-health'],
    expirationDate: '2026-12-31',
    validityStatus: 'valid',
    highPriorityFlags: 0,
    signatureDate: '2026-04-12',
  },
  {
    patientName: 'David Diallo',
    recipientOrganization: 'Memorial Hospital',
    primaryPurpose: 'continuing-treatment',
    categories: ['medical-health', 'hiv-aids'],
    expirationDate: '2026-09-30',
    validityStatus: 'invalid',
    highPriorityFlags: 1,
    signatureDate: '2026-03-30',
  },
];
