<!ELEMENT histopathology_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,specimen_type,specimen_site,number_of_specimens,fixative,primary_indication,clinical_question,clinical_details,provisional_diagnosis,previous_histology,urgent_frozen_section,two_week_wait,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT specimen_type (#PCDATA)>
<!ELEMENT specimen_site (#PCDATA)>
<!ELEMENT number_of_specimens (#PCDATA)>
<!ELEMENT fixative (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT clinical_details (#PCDATA)>
<!ELEMENT provisional_diagnosis (#PCDATA)>
<!ELEMENT previous_histology (#PCDATA)>
<!ELEMENT urgent_frozen_section (#PCDATA)>
<!ELEMENT two_week_wait (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
