use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.create_table(
            Table::create()
                .table(Alias::new("cardiology_requests"))
                .if_not_exists()
                .col(
                    ColumnDef::new(Alias::new("id"))
                        .uuid()
                        .not_null()
                        .default(Expr::cust("gen_random_uuid()"))
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(Alias::new("created_at"))
                        .timestamp_with_time_zone()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Alias::new("updated_at"))
                        .timestamp_with_time_zone()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Alias::new("deleted_at"))
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(ColumnDef::new(Alias::new("patient_id")).uuid().not_null())
                .col(ColumnDef::new(Alias::new("clinician_id")).uuid().not_null())
                .col(ColumnDef::new(Alias::new("status")).string().not_null())
                .col(ColumnDef::new(Alias::new("site_name")).string().not_null())
                .col(ColumnDef::new(Alias::new("setting")).string().not_null())
                .col(ColumnDef::new(Alias::new("referral_date")).date().null())
                .col(ColumnDef::new(Alias::new("requested_by_date")).date().null())
                .col(
                    ColumnDef::new(Alias::new("requested_service"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("referral_reason"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("clinical_question"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("relevant_history"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("symptom_chest_pain"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("chest_pain_character"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("symptom_breathlessness"))
                        .boolean()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("nyha_class")).string().not_null())
                .col(
                    ColumnDef::new(Alias::new("symptom_palpitations"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("symptom_syncope"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("symptom_oedema"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("suspected_acs"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("exertional_syncope"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("new_onset_heart_failure"))
                        .boolean()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("ecg_done")).boolean().not_null())
                .col(
                    ColumnDef::new(Alias::new("ecg_findings"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("troponin_status"))
                        .string()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("bnp_status")).string().not_null())
                .col(
                    ColumnDef::new(Alias::new("known_coronary_artery_disease"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("previous_mi"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("heart_failure"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("valve_disease"))
                        .boolean()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("arrhythmia")).boolean().not_null())
                .col(
                    ColumnDef::new(Alias::new("hypertension"))
                        .boolean()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("diabetes")).boolean().not_null())
                .col(
                    ColumnDef::new(Alias::new("current_medications"))
                        .string()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("urgency")).string().not_null())
                .col(
                    ColumnDef::new(Alias::new("supervising_consultant"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("requester_contact"))
                        .string()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("notes")).string().not_null())
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_cardiology_requests_patient_id")
                        .from(Alias::new("cardiology_requests"), Alias::new("patient_id"))
                        .to(Alias::new("patients"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::Cascade)
                        .on_update(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_cardiology_requests_clinician_id")
                        .from(Alias::new("cardiology_requests"), Alias::new("clinician_id"))
                        .to(Alias::new("clinicians"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::Cascade)
                        .on_update(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

        m.create_index(
            Index::create()
                .if_not_exists()
                .name("index_cardiology_request_patient_id")
                .table(Alias::new("cardiology_requests"))
                .col(Alias::new("patient_id"))
                .to_owned(),
        )
        .await?;

        m.create_index(
            Index::create()
                .if_not_exists()
                .name("index_cardiology_request_clinician_id")
                .table(Alias::new("cardiology_requests"))
                .col(Alias::new("clinician_id"))
                .to_owned(),
        )
        .await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.drop_table(
            Table::drop()
                .table(Alias::new("cardiology_requests"))
                .to_owned(),
        )
        .await
    }
}
