<!ELEMENT soap_note (id,created_at,updated_at,deleted_at,patient_id,clinician_id,encountered_at,care_setting,encounter_type,clinician_role,patient_identifier,presenting_complaint,history_of_presenting_complaint,patient_reported_symptoms,relevant_history,red_flag_symptoms,examination_findings,vital_signs,abnormal_vitals_present,investigation_results,primary_diagnosis,problem_list,differential,clinical_impression,investigations_plan,treatment_plan,referrals,follow_up,safety_netting,managed_at_home,clinical_note)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT encountered_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT encounter_type (#PCDATA)>
<!ELEMENT clinician_role (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT presenting_complaint (#PCDATA)>
<!ELEMENT history_of_presenting_complaint (#PCDATA)>
<!ELEMENT patient_reported_symptoms (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT red_flag_symptoms (#PCDATA)>
<!ELEMENT examination_findings (#PCDATA)>
<!ELEMENT vital_signs (#PCDATA)>
<!ELEMENT abnormal_vitals_present (#PCDATA)>
<!ELEMENT investigation_results (#PCDATA)>
<!ELEMENT primary_diagnosis (#PCDATA)>
<!ELEMENT problem_list (#PCDATA)>
<!ELEMENT differential (#PCDATA)>
<!ELEMENT clinical_impression (#PCDATA)>
<!ELEMENT investigations_plan (#PCDATA)>
<!ELEMENT treatment_plan (#PCDATA)>
<!ELEMENT referrals (#PCDATA)>
<!ELEMENT follow_up (#PCDATA)>
<!ELEMENT safety_netting (#PCDATA)>
<!ELEMENT managed_at_home (#PCDATA)>
<!ELEMENT clinical_note (#PCDATA)>
