<!ELEMENT smoking_alcohol (id,created_at,updated_at,deleted_at,assessment_id,smoking_status,cigarettes_per_day,years_since_quit,alcohol_units_per_week,alcohol_frequency)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT assessment_id (#PCDATA)>
<!ELEMENT smoking_status (#PCDATA)>
<!ELEMENT cigarettes_per_day (#PCDATA)>
<!ELEMENT years_since_quit (#PCDATA)>
<!ELEMENT alcohol_units_per_week (#PCDATA)>
<!ELEMENT alcohol_frequency (#PCDATA)>
