//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::agile_consulting_scorecard_for_hiring_helps::Entity as AgileConsultingScorecardForHiringHelps;
pub use super::organizations::Entity as Organizations;
pub use super::respondents::Entity as Respondents;
pub use super::users::Entity as Users;
