mod users;

mod patients;
mod practitioners;
mod trop_med_waiting_list_cards;
mod trop_med_waiting_list_card_appointments;
mod trop_med_waiting_list_card_grades;
mod trop_med_waiting_list_card_grade_rules;
mod trop_med_waiting_list_card_grade_flags;