//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::mental_state_examination_grade_flags::Entity as MentalStateExaminationGradeFlags;
pub use super::mental_state_examination_grade_rules::Entity as MentalStateExaminationGradeRules;
pub use super::mental_state_examination_grades::Entity as MentalStateExaminationGrades;
pub use super::mental_state_examinations::Entity as MentalStateExaminations;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
