<!ELEMENT patient_reported_outcome_measures_score (id,created_at,updated_at,deleted_at,patient_reported_outcome_measures_id,sf36_pf,sf36_rp,sf36_bp,sf36_gh,sf36_vt,sf36_sf,sf36_re,sf36_mh,sf36_pcs_approx,sf36_mcs_approx,ndi_raw_score,ndi_answered_sections,ndi_percentage_score,ndi_band,mjoa_total_score,mjoa_band,eq5d_health_state_descriptor,eq5d_uk_index_value,eq5d_vas_score)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_reported_outcome_measures_id (#PCDATA)>
<!ELEMENT sf36_pf (#PCDATA)>
<!ELEMENT sf36_rp (#PCDATA)>
<!ELEMENT sf36_bp (#PCDATA)>
<!ELEMENT sf36_gh (#PCDATA)>
<!ELEMENT sf36_vt (#PCDATA)>
<!ELEMENT sf36_sf (#PCDATA)>
<!ELEMENT sf36_re (#PCDATA)>
<!ELEMENT sf36_mh (#PCDATA)>
<!ELEMENT sf36_pcs_approx (#PCDATA)>
<!ELEMENT sf36_mcs_approx (#PCDATA)>
<!ELEMENT ndi_raw_score (#PCDATA)>
<!ELEMENT ndi_answered_sections (#PCDATA)>
<!ELEMENT ndi_percentage_score (#PCDATA)>
<!ELEMENT ndi_band (#PCDATA)>
<!ELEMENT mjoa_total_score (#PCDATA)>
<!ELEMENT mjoa_band (#PCDATA)>
<!ELEMENT eq5d_health_state_descriptor (#PCDATA)>
<!ELEMENT eq5d_uk_index_value (#PCDATA)>
<!ELEMENT eq5d_vas_score (#PCDATA)>
