<!ELEMENT bronchoscopy_test_result (id,created_at,updated_at,deleted_at,patient_id,clinician_id,originating_request_reference,report_status,performed_date,reported_date,procedure,sedation_used,extent_examined,clinical_history,endobronchial_lesion,mucosal_abnormality,extrinsic_compression,bleeding,foreign_body,secretions_purulent,normal_examination,lesion_location,samples_taken,complication,findings_narrative,impression,reporting_category,recommended_follow_up,critical_result_communicated,reported_to)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT originating_request_reference (#PCDATA)>
<!ELEMENT report_status (#PCDATA)>
<!ELEMENT performed_date (#PCDATA)>
<!ELEMENT reported_date (#PCDATA)>
<!ELEMENT procedure (#PCDATA)>
<!ELEMENT sedation_used (#PCDATA)>
<!ELEMENT extent_examined (#PCDATA)>
<!ELEMENT clinical_history (#PCDATA)>
<!ELEMENT endobronchial_lesion (#PCDATA)>
<!ELEMENT mucosal_abnormality (#PCDATA)>
<!ELEMENT extrinsic_compression (#PCDATA)>
<!ELEMENT bleeding (#PCDATA)>
<!ELEMENT foreign_body (#PCDATA)>
<!ELEMENT secretions_purulent (#PCDATA)>
<!ELEMENT normal_examination (#PCDATA)>
<!ELEMENT lesion_location (#PCDATA)>
<!ELEMENT samples_taken (#PCDATA)>
<!ELEMENT complication (#PCDATA)>
<!ELEMENT findings_narrative (#PCDATA)>
<!ELEMENT impression (#PCDATA)>
<!ELEMENT reporting_category (#PCDATA)>
<!ELEMENT recommended_follow_up (#PCDATA)>
<!ELEMENT critical_result_communicated (#PCDATA)>
<!ELEMENT reported_to (#PCDATA)>
