mod users;

mod patients;
mod practitioners;
mod neurology_waiting_list_cards;
mod neurology_waiting_list_card_appointments;
mod neurology_waiting_list_card_grades;
mod neurology_waiting_list_card_grade_rules;
mod neurology_waiting_list_card_grade_flags;