<!ELEMENT lumbar_puncture_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,procedure_intent,primary_indication,clinical_question,relevant_history,suspected_raised_intracranial_pressure,focal_neurological_signs,reduced_consciousness,ct_head_status,taking_anticoagulant,anticoagulant_agent,taking_antiplatelet,antiplatelet_agent,inr,platelet_count,bleeding_disorder,local_skin_infection,opening_pressure_required,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT procedure_intent (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT suspected_raised_intracranial_pressure (#PCDATA)>
<!ELEMENT focal_neurological_signs (#PCDATA)>
<!ELEMENT reduced_consciousness (#PCDATA)>
<!ELEMENT ct_head_status (#PCDATA)>
<!ELEMENT taking_anticoagulant (#PCDATA)>
<!ELEMENT anticoagulant_agent (#PCDATA)>
<!ELEMENT taking_antiplatelet (#PCDATA)>
<!ELEMENT antiplatelet_agent (#PCDATA)>
<!ELEMENT inr (#PCDATA)>
<!ELEMENT platelet_count (#PCDATA)>
<!ELEMENT bleeding_disorder (#PCDATA)>
<!ELEMENT local_skin_infection (#PCDATA)>
<!ELEMENT opening_pressure_required (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
