<!ELEMENT cardiology_response (id,created_at,updated_at,deleted_at,patient_id,clinician_id,originating_request_reference,response_status,consultation_type,assessed_date,responded_date,clinical_summary,examination_findings,investigations_performed,ischaemia_or_cad,significant_arrhythmia,reduced_ejection_fraction,significant_valve_disease,structural_abnormality,uncontrolled_hypertension,non_cardiac_cause,primary_diagnosis_category,diagnosis_narrative,lv_ejection_fraction_percent,management_plan,medication_changes,recommended_follow_up,critical_result,critical_result_communicated,reported_to)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT originating_request_reference (#PCDATA)>
<!ELEMENT response_status (#PCDATA)>
<!ELEMENT consultation_type (#PCDATA)>
<!ELEMENT assessed_date (#PCDATA)>
<!ELEMENT responded_date (#PCDATA)>
<!ELEMENT clinical_summary (#PCDATA)>
<!ELEMENT examination_findings (#PCDATA)>
<!ELEMENT investigations_performed (#PCDATA)>
<!ELEMENT ischaemia_or_cad (#PCDATA)>
<!ELEMENT significant_arrhythmia (#PCDATA)>
<!ELEMENT reduced_ejection_fraction (#PCDATA)>
<!ELEMENT significant_valve_disease (#PCDATA)>
<!ELEMENT structural_abnormality (#PCDATA)>
<!ELEMENT uncontrolled_hypertension (#PCDATA)>
<!ELEMENT non_cardiac_cause (#PCDATA)>
<!ELEMENT primary_diagnosis_category (#PCDATA)>
<!ELEMENT diagnosis_narrative (#PCDATA)>
<!ELEMENT lv_ejection_fraction_percent (#PCDATA)>
<!ELEMENT management_plan (#PCDATA)>
<!ELEMENT medication_changes (#PCDATA)>
<!ELEMENT recommended_follow_up (#PCDATA)>
<!ELEMENT critical_result (#PCDATA)>
<!ELEMENT critical_result_communicated (#PCDATA)>
<!ELEMENT reported_to (#PCDATA)>
