//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::cervical_screening_grade_flags::Entity as CervicalScreeningGradeFlags;
pub use super::cervical_screening_grade_rules::Entity as CervicalScreeningGradeRules;
pub use super::cervical_screening_grades::Entity as CervicalScreeningGrades;
pub use super::cervical_screenings::Entity as CervicalScreenings;
pub use super::clinicians::Entity as Clinicians;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
