// Sample patient data for the clinician dashboard.
//
// Mirrors the SvelteKit dashboard's `src/lib/data.ts` so the two
// implementations show identical demo content when the backend is offline.
// Twelve realistic rows: spans every eligibility outcome
// (Eligible / Conditional / Ineligible), every BMI band relevant to GLP-1
// review, and a mix of weight-management comorbidities (T2DM, hypertension,
// dyslipidaemia, OSA) and exclusions (pregnancy, MTC/MEN2 history, severe
// GI disease, hypersensitivity). NHS numbers are in the canonical
// "NNN NNN NNNN" display form.

/** @type {import('./types.js').PatientRow[]} */
const samplePatients = [
  {
    id: '1',
    nhsNumber: '943 476 5919',
    patientName: 'Smith, John',
    eligibilityStatus: 'Eligible',
    primaryIndication: 'Type 2 Diabetes',
    bmi: 32.4,
    bmiBand: 'Obesity I',
    weightLossTargetPercent: 10,
    comorbidityT2DM: true,
    comorbidityHypertension: true,
    comorbidityDyslipidaemia: false,
    comorbidityOSA: false,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  },
  {
    id: '2',
    nhsNumber: '721 938 4102',
    patientName: 'Patel, Priya',
    eligibilityStatus: 'Eligible',
    primaryIndication: 'Weight Management',
    bmi: 35.1,
    bmiBand: 'Obesity II',
    weightLossTargetPercent: 15,
    comorbidityT2DM: false,
    comorbidityHypertension: true,
    comorbidityDyslipidaemia: true,
    comorbidityOSA: false,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  },
  {
    id: '3',
    nhsNumber: '384 615 7230',
    patientName: 'Jones, Margaret',
    eligibilityStatus: 'Conditional',
    primaryIndication: 'Type 2 Diabetes',
    bmi: 29.8,
    bmiBand: 'Pre-Obesity',
    weightLossTargetPercent: 7,
    comorbidityT2DM: true,
    comorbidityHypertension: false,
    comorbidityDyslipidaemia: true,
    comorbidityOSA: false,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: true,
    exclusionHypersensitivity: false
  },
  {
    id: '4',
    nhsNumber: '512 847 9063',
    patientName: 'Williams, David',
    eligibilityStatus: 'Eligible',
    primaryIndication: 'Weight Management',
    bmi: 38.6,
    bmiBand: 'Obesity II',
    weightLossTargetPercent: 20,
    comorbidityT2DM: false,
    comorbidityHypertension: true,
    comorbidityDyslipidaemia: false,
    comorbidityOSA: true,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  },
  {
    id: '5',
    nhsNumber: '167 293 8451',
    patientName: 'Brown, Sarah',
    eligibilityStatus: 'Ineligible',
    primaryIndication: 'Weight Management',
    bmi: 24.2,
    bmiBand: 'Normal',
    weightLossTargetPercent: 5,
    comorbidityT2DM: false,
    comorbidityHypertension: false,
    comorbidityDyslipidaemia: false,
    comorbidityOSA: false,
    exclusionPregnancy: true,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  },
  {
    id: '6',
    nhsNumber: '835 162 4097',
    patientName: 'Taylor, James',
    eligibilityStatus: 'Eligible',
    primaryIndication: 'Cardiovascular Risk Reduction',
    bmi: 31.0,
    bmiBand: 'Obesity I',
    weightLossTargetPercent: 10,
    comorbidityT2DM: true,
    comorbidityHypertension: true,
    comorbidityDyslipidaemia: true,
    comorbidityOSA: false,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  },
  {
    id: '7',
    nhsNumber: '294 708 5316',
    patientName: 'Davies, Helen',
    eligibilityStatus: 'Conditional',
    primaryIndication: 'Type 2 Diabetes',
    bmi: 33.5,
    bmiBand: 'Obesity I',
    weightLossTargetPercent: 12,
    comorbidityT2DM: true,
    comorbidityHypertension: false,
    comorbidityDyslipidaemia: false,
    comorbidityOSA: true,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: true,
    exclusionHypersensitivity: false
  },
  {
    id: '8',
    nhsNumber: '608 341 2975',
    patientName: 'Wilson, Robert',
    eligibilityStatus: 'Ineligible',
    primaryIndication: 'Type 2 Diabetes',
    bmi: 30.2,
    bmiBand: 'Obesity I',
    weightLossTargetPercent: null,
    comorbidityT2DM: true,
    comorbidityHypertension: true,
    comorbidityDyslipidaemia: false,
    comorbidityOSA: false,
    exclusionPregnancy: false,
    exclusionMTC: true,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  },
  {
    id: '9',
    nhsNumber: '473 926 1084',
    patientName: 'Evans, Catherine',
    eligibilityStatus: 'Conditional',
    primaryIndication: 'Weight Management',
    bmi: 41.3,
    bmiBand: 'Obesity III',
    weightLossTargetPercent: 25,
    comorbidityT2DM: false,
    comorbidityHypertension: true,
    comorbidityDyslipidaemia: true,
    comorbidityOSA: true,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  },
  {
    id: '10',
    nhsNumber: '159 684 7302',
    patientName: 'Thomas, Michael',
    eligibilityStatus: 'Eligible',
    primaryIndication: 'Type 2 Diabetes',
    bmi: 28.9,
    bmiBand: 'Pre-Obesity',
    weightLossTargetPercent: 8,
    comorbidityT2DM: true,
    comorbidityHypertension: false,
    comorbidityDyslipidaemia: true,
    comorbidityOSA: false,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  },
  {
    id: '11',
    nhsNumber: '742 051 3896',
    patientName: 'Robinson, Emma',
    eligibilityStatus: 'Ineligible',
    primaryIndication: 'Weight Management',
    bmi: 22.1,
    bmiBand: 'Normal',
    weightLossTargetPercent: null,
    comorbidityT2DM: false,
    comorbidityHypertension: false,
    comorbidityDyslipidaemia: false,
    comorbidityOSA: false,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: true
  },
  {
    id: '12',
    nhsNumber: '386 219 5740',
    patientName: 'Clark, George',
    eligibilityStatus: 'Eligible',
    primaryIndication: 'Cardiovascular Risk Reduction',
    bmi: 26.4,
    bmiBand: 'Overweight',
    weightLossTargetPercent: 5,
    comorbidityT2DM: false,
    comorbidityHypertension: true,
    comorbidityDyslipidaemia: true,
    comorbidityOSA: false,
    exclusionPregnancy: false,
    exclusionMTC: false,
    exclusionSevereGI: false,
    exclusionHypersensitivity: false
  }
];

export { samplePatients };
