mod users;

mod patients;
mod practitioners;
mod public_health_waiting_list_cards;
mod public_health_waiting_list_card_appointments;
mod public_health_waiting_list_card_grades;
mod public_health_waiting_list_card_grade_rules;
mod public_health_waiting_list_card_grade_flags;