<!ELEMENT nerve_conduction_study_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,study_type,region,laterality,primary_indication,clinical_question,relevant_history,symptom_numbness,symptom_weakness,symptom_pain,symptom_tingling,symptom_duration,diabetes,taking_anticoagulant,pacemaker_or_icd,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT study_type (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT laterality (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT symptom_numbness (#PCDATA)>
<!ELEMENT symptom_weakness (#PCDATA)>
<!ELEMENT symptom_pain (#PCDATA)>
<!ELEMENT symptom_tingling (#PCDATA)>
<!ELEMENT symptom_duration (#PCDATA)>
<!ELEMENT diabetes (#PCDATA)>
<!ELEMENT taking_anticoagulant (#PCDATA)>
<!ELEMENT pacemaker_or_icd (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
