mod users;

mod patients;
mod practitioners;
mod orthopaedics_waiting_list_cards;
mod orthopaedics_waiting_list_card_appointments;
mod orthopaedics_waiting_list_card_grades;
mod orthopaedics_waiting_list_card_grade_rules;
mod orthopaedics_waiting_list_card_grade_flags;