<!ELEMENT urinalysis_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,dipstick,microscopy_culture_sensitivity,albumin_creatinine_ratio,protein_creatinine_ratio,pregnancy_test,drug_screen,cytology,twenty_four_hour_collection,primary_indication,clinical_details,symptom_dysuria,symptom_frequency,symptom_visible_haematuria,symptom_loin_pain,symptom_fever,specimen_type,specimen_collected,collection_datetime,pregnant,catheterised,current_antibiotics,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT dipstick (#PCDATA)>
<!ELEMENT microscopy_culture_sensitivity (#PCDATA)>
<!ELEMENT albumin_creatinine_ratio (#PCDATA)>
<!ELEMENT protein_creatinine_ratio (#PCDATA)>
<!ELEMENT pregnancy_test (#PCDATA)>
<!ELEMENT drug_screen (#PCDATA)>
<!ELEMENT cytology (#PCDATA)>
<!ELEMENT twenty_four_hour_collection (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_details (#PCDATA)>
<!ELEMENT symptom_dysuria (#PCDATA)>
<!ELEMENT symptom_frequency (#PCDATA)>
<!ELEMENT symptom_visible_haematuria (#PCDATA)>
<!ELEMENT symptom_loin_pain (#PCDATA)>
<!ELEMENT symptom_fever (#PCDATA)>
<!ELEMENT specimen_type (#PCDATA)>
<!ELEMENT specimen_collected (#PCDATA)>
<!ELEMENT collection_datetime (#PCDATA)>
<!ELEMENT pregnant (#PCDATA)>
<!ELEMENT catheterised (#PCDATA)>
<!ELEMENT current_antibiotics (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
