<!ELEMENT arc42_documentation_grade (id,created_at,updated_at,deleted_at,arc42_documentation_id,computed_maturity,final_maturity,override_reason,completeness_section_1,completeness_section_2,completeness_section_3,completeness_section_4,completeness_section_5,completeness_section_6,completeness_section_7,completeness_section_8,completeness_section_9,completeness_section_10,completeness_section_11,completeness_section_12)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT arc42_documentation_id (#PCDATA)>
<!ELEMENT computed_maturity (#PCDATA)>
<!ELEMENT final_maturity (#PCDATA)>
<!ELEMENT override_reason (#PCDATA)>
<!ELEMENT completeness_section_1 (#PCDATA)>
<!ELEMENT completeness_section_2 (#PCDATA)>
<!ELEMENT completeness_section_3 (#PCDATA)>
<!ELEMENT completeness_section_4 (#PCDATA)>
<!ELEMENT completeness_section_5 (#PCDATA)>
<!ELEMENT completeness_section_6 (#PCDATA)>
<!ELEMENT completeness_section_7 (#PCDATA)>
<!ELEMENT completeness_section_8 (#PCDATA)>
<!ELEMENT completeness_section_9 (#PCDATA)>
<!ELEMENT completeness_section_10 (#PCDATA)>
<!ELEMENT completeness_section_11 (#PCDATA)>
<!ELEMENT completeness_section_12 (#PCDATA)>
