<!ELEMENT grace_score_for_acute_coronary_syndrome_grade_rule (id,created_at,updated_at,deleted_at,grace_score_for_acute_coronary_syndrome_grade_id,rule_id,variable,points,category,description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT grace_score_for_acute_coronary_syndrome_grade_id (#PCDATA)>
<!ELEMENT rule_id (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT points (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT description (#PCDATA)>
