<!ELEMENT qrisk3_cardiovascular_disease_risk_score (id,created_at,updated_at,deleted_at,patient_id,clinician_id,clinician_name,clinician_role,assessed_at,care_setting,patient_identifier,age,sex,ethnicity,townsend_score,postcode,smoking_status,body_mass_index,diabetes_status,cholesterol_hdl_ratio,systolic_blood_pressure,systolic_blood_pressure_sd,on_blood_pressure_treatment,family_history_chd,atrial_fibrillation,chronic_kidney_disease_stage,migraine,rheumatoid_arthritis,systemic_lupus_erythematosus,severe_mental_illness,erectile_dysfunction,on_atypical_antipsychotics,on_corticosteroids,has_established_cvd,has_familial_hypercholesterolaemia,clinical_note)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT clinician_name (#PCDATA)>
<!ELEMENT clinician_role (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT ethnicity (#PCDATA)>
<!ELEMENT townsend_score (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT smoking_status (#PCDATA)>
<!ELEMENT body_mass_index (#PCDATA)>
<!ELEMENT diabetes_status (#PCDATA)>
<!ELEMENT cholesterol_hdl_ratio (#PCDATA)>
<!ELEMENT systolic_blood_pressure (#PCDATA)>
<!ELEMENT systolic_blood_pressure_sd (#PCDATA)>
<!ELEMENT on_blood_pressure_treatment (#PCDATA)>
<!ELEMENT family_history_chd (#PCDATA)>
<!ELEMENT atrial_fibrillation (#PCDATA)>
<!ELEMENT chronic_kidney_disease_stage (#PCDATA)>
<!ELEMENT migraine (#PCDATA)>
<!ELEMENT rheumatoid_arthritis (#PCDATA)>
<!ELEMENT systemic_lupus_erythematosus (#PCDATA)>
<!ELEMENT severe_mental_illness (#PCDATA)>
<!ELEMENT erectile_dysfunction (#PCDATA)>
<!ELEMENT on_atypical_antipsychotics (#PCDATA)>
<!ELEMENT on_corticosteroids (#PCDATA)>
<!ELEMENT has_established_cvd (#PCDATA)>
<!ELEMENT has_familial_hypercholesterolaemia (#PCDATA)>
<!ELEMENT clinical_note (#PCDATA)>
