-- schema.sql
-- Combined schema for form: recommended-summary-plan-for-emergency-care-and-treatment
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (8):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_respect.sql
--   - 05_create_table_respect_grade.sql
--   - 06_create_table_respect_grade_rule.sql
--   - 07_create_table_respect_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators used by free-text search GIN indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information for the person the ReSPECT plan is about.

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    hospital_mrn VARCHAR(50),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    allergies_summary TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient demographic information for the person the ReSPECT emergency care and treatment plan is about.';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Full patient name.';
COMMENT ON COLUMN patient.birth_date IS
    'Date of birth.';
COMMENT ON COLUMN patient.sex IS
    'Sex recorded for clinical purposes: female, male, intersex, or unknown.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.hospital_mrn IS
    'Local hospital medical record number (MRN).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height in centimetres.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight in kilograms.';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI), kg/m^2.';
COMMENT ON COLUMN patient.allergies_summary IS
    'Free-text summary of known allergies.';

CREATE INDEX patient_name_trgm_idx
    ON patient
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Clinician information used to identify the clinician who completed and
-- signed the ReSPECT plan and any senior clinician who endorsed it.

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN ('doctor', 'nurse', 'paramedic', 'other', '')),
    registration_body VARCHAR(20) NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician identifying information for the clinician who completed and signed the ReSPECT plan and any senior clinician who endorsed it.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Clinician full name as recorded on the plan.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code.';
COMMENT ON COLUMN clinician.role IS
    'Primary clinical role: doctor, nurse, paramedic, or other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Professional registration body: GMC, NMC, HCPC, or other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Professional registration number issued by the registration body.';

CREATE INDEX clinician_name_trgm_idx
    ON clinician
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_respect.sql
-- ========================================================================

-- Main ReSPECT record: one personalised emergency care and treatment plan
-- created through shared decision-making. Records the person's summary of
-- relevant health, their preferences and what matters, agreed clinical
-- recommendations, an explicit CPR recommendation, agreed ceilings of
-- treatment, a record of capacity and involvement, and clinician sign-off.
-- The completeness grade, the audit trail of fired mandatory rules, and the
-- safety / governance flags live in dedicated child tables. Presence of a
-- component is detected by a non-empty field, not by semantic analysis.
--
-- The short base name `respect` is used for this form's tables, columns,
-- indexes, and triggers because the full slug
-- (recommended_summary_plan_for_emergency_care_and_treatment) would exceed
-- PostgreSQL's 63-byte identifier limit for derived index and trigger names.

CREATE TABLE respect (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE RESTRICT,
    clinician_id UUID REFERENCES clinician(id) ON DELETE RESTRICT,

    -- Personal details
    person_name TEXT NOT NULL DEFAULT '',
    date_of_birth DATE,
    identifier TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    key_contact TEXT NOT NULL DEFAULT '',

    -- Summary of relevant health
    health_summary TEXT NOT NULL DEFAULT '',
    diagnoses TEXT NOT NULL DEFAULT '',
    existing_documents TEXT NOT NULL DEFAULT '',

    -- Preferences and what matters
    what_matters TEXT NOT NULL DEFAULT '',
    care_preferences TEXT NOT NULL DEFAULT '',

    -- Clinical recommendations
    priority_balance VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (priority_balance IN ('sustain-life', 'balanced', 'comfort', '')),
    recommended_interventions TEXT NOT NULL DEFAULT '',
    not_recommended_interventions TEXT NOT NULL DEFAULT '',

    -- CPR recommendation
    cpr_recommendation VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (cpr_recommendation IN ('attempt', 'do-not-attempt', '')),
    cpr_rationale TEXT NOT NULL DEFAULT '',
    cpr_discussed VARCHAR(5) NOT NULL DEFAULT ''
        CHECK (cpr_discussed IN ('yes', 'no', '')),

    -- Ceilings of treatment
    hospital_transfer VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (hospital_transfer IN ('appropriate', 'not-appropriate', '')),
    critical_care_admission VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (critical_care_admission IN ('appropriate', 'not-appropriate', '')),
    treatment_ceilings TEXT NOT NULL DEFAULT '',

    -- Capacity and involvement
    has_capacity VARCHAR(5) NOT NULL DEFAULT ''
        CHECK (has_capacity IN ('yes', 'no', '')),
    capacity_assessment TEXT NOT NULL DEFAULT '',
    involvement VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (involvement IN ('person', 'legal-proxy', 'consultees', '')),
    proxy_details TEXT NOT NULL DEFAULT '',

    -- Clinician sign-off
    clinician_name TEXT NOT NULL DEFAULT '',
    clinician_role VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (clinician_role IN ('doctor', 'nurse', 'paramedic', 'other', '')),
    clinician_registration TEXT NOT NULL DEFAULT '',
    signature TEXT NOT NULL DEFAULT '',
    signed_at TIMESTAMPTZ,
    senior_endorsement TEXT NOT NULL DEFAULT '',
    emergency_contacts TEXT NOT NULL DEFAULT '',
    review_date DATE
);

CREATE INDEX respect_patient_id_idx
    ON respect (patient_id);
CREATE INDEX respect_clinician_id_idx
    ON respect (clinician_id);
CREATE INDEX respect_person_name_trgm_idx
    ON respect
    USING GIN (person_name gin_trgm_ops);

CREATE TRIGGER trigger_respect_updated_at
    BEFORE UPDATE ON respect
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE respect IS
    'Main ReSPECT record: one personalised emergency care and treatment plan created through shared decision-making, covering the person''s summary of health, preferences, agreed clinical recommendations, CPR recommendation, ceilings of treatment, capacity and involvement, and clinician sign-off. Completeness grade, fired rules, and flags live in child tables. The short base name `respect` is used because the full slug would exceed PostgreSQL''s 63-byte identifier limit.';
COMMENT ON COLUMN respect.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN respect.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN respect.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN respect.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN respect.patient_id IS
    'Foreign key to the patient this plan is about (restrict delete).';
COMMENT ON COLUMN respect.clinician_id IS
    'Foreign key to the clinician who completed and signed the plan (restrict delete); optional.';
COMMENT ON COLUMN respect.person_name IS
    'Personal details: name of the person the plan is about.';
COMMENT ON COLUMN respect.date_of_birth IS
    'Personal details: the person''s date of birth.';
COMMENT ON COLUMN respect.identifier IS
    'Personal details: NHS / CHI number or local identifier.';
COMMENT ON COLUMN respect.address IS
    'Personal details: usual residence.';
COMMENT ON COLUMN respect.key_contact IS
    'Personal details: key contact / next-of-kin details.';
COMMENT ON COLUMN respect.health_summary IS
    'Summary of relevant health: brief clinical summary (mandatory content).';
COMMENT ON COLUMN respect.diagnoses IS
    'Summary of relevant health: relevant diagnoses.';
COMMENT ON COLUMN respect.existing_documents IS
    'Summary of relevant health: existing documents such as ADRT, LPA, or organ-donation wishes.';
COMMENT ON COLUMN respect.what_matters IS
    'Preferences: the person''s values, priorities, and fears.';
COMMENT ON COLUMN respect.care_preferences IS
    'Preferences: the person''s preferences for care.';
COMMENT ON COLUMN respect.priority_balance IS
    'Clinical recommendations: balance of priorities from life-sustaining to comfort (sustain-life, balanced, or comfort).';
COMMENT ON COLUMN respect.recommended_interventions IS
    'Clinical recommendations: interventions recommended.';
COMMENT ON COLUMN respect.not_recommended_interventions IS
    'Clinical recommendations: interventions not recommended.';
COMMENT ON COLUMN respect.cpr_recommendation IS
    'CPR recommendation: attempt CPR, do-not-attempt CPR, or empty when undocumented (the most safety-critical field).';
COMMENT ON COLUMN respect.cpr_rationale IS
    'CPR recommendation: clinical rationale for the recommendation.';
COMMENT ON COLUMN respect.cpr_discussed IS
    'CPR recommendation: whether the recommendation was discussed with the person or their proxy (yes/no).';
COMMENT ON COLUMN respect.hospital_transfer IS
    'Ceilings of treatment: whether hospital transfer is appropriate or not-appropriate.';
COMMENT ON COLUMN respect.critical_care_admission IS
    'Ceilings of treatment: whether critical-care admission is appropriate or not-appropriate.';
COMMENT ON COLUMN respect.treatment_ceilings IS
    'Ceilings of treatment: other agreed limits on treatment.';
COMMENT ON COLUMN respect.has_capacity IS
    'Capacity and involvement: whether the person has capacity for this decision (yes/no); drives the conditional capacity rule.';
COMMENT ON COLUMN respect.capacity_assessment IS
    'Capacity and involvement: assessment recorded where the person lacks capacity (Mental Capacity Act 2005).';
COMMENT ON COLUMN respect.involvement IS
    'Capacity and involvement: who was involved in the decision (person, legal-proxy, or consultees).';
COMMENT ON COLUMN respect.proxy_details IS
    'Capacity and involvement: welfare attorney, deputy, or consultee details.';
COMMENT ON COLUMN respect.clinician_name IS
    'Clinician sign-off: name of the completing clinician.';
COMMENT ON COLUMN respect.clinician_role IS
    'Clinician sign-off: role of the completing clinician (doctor, nurse, paramedic, or other).';
COMMENT ON COLUMN respect.clinician_registration IS
    'Clinician sign-off: GMC / NMC / HCPC registration number.';
COMMENT ON COLUMN respect.signature IS
    'Clinician sign-off: electronic signature; required for the plan to be valid.';
COMMENT ON COLUMN respect.signed_at IS
    'Clinician sign-off: date and time the plan was signed.';
COMMENT ON COLUMN respect.senior_endorsement IS
    'Clinician sign-off: senior clinician endorsement.';
COMMENT ON COLUMN respect.emergency_contacts IS
    'Clinician sign-off: emergency contacts.';
COMMENT ON COLUMN respect.review_date IS
    'Clinician sign-off: planned review date; drives the review-date-passed flag.';

-- ========================================================================
-- END 04_create_table_respect.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_respect_grade.sql
-- ========================================================================

-- Computed documentation-completeness result for a ReSPECT plan. The engine
-- classifies the plan as complete (every mandatory rule satisfied) or
-- incomplete, and reports a completeness percentage counting populated
-- mandatory fields. A completeness grade reflects the quality of the record,
-- not any clinical score or the correctness of the care.

CREATE TABLE respect_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    respect_id UUID NOT NULL UNIQUE
        REFERENCES respect(id) ON DELETE CASCADE,

    status VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (status IN ('complete', 'incomplete', '')),
    completeness_percent INTEGER,

    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_respect_grade_updated_at
    BEFORE UPDATE ON respect_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE respect_grade IS
    'Computed documentation-completeness result for a ReSPECT plan: status (complete when all eight mandatory rules are satisfied, otherwise incomplete) and completeness percentage.';
COMMENT ON COLUMN respect_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN respect_grade.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN respect_grade.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN respect_grade.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN respect_grade.respect_id IS
    'Foreign key to the parent ReSPECT plan (unique, 1:1).';
COMMENT ON COLUMN respect_grade.status IS
    'Completeness status: complete (all mandatory rules satisfied) or incomplete.';
COMMENT ON COLUMN respect_grade.completeness_percent IS
    'Completeness percentage (0..100): populated mandatory fields / total mandatory fields x 100, reported for both statuses.';
COMMENT ON COLUMN respect_grade.graded_at IS
    'Timestamp when the engine last computed the grade.';

-- ========================================================================
-- END 05_create_table_respect_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_respect_grade_rule.sql
-- ========================================================================

-- Audit trail of every mandatory rule evaluated during grading. Each row
-- records one mandatory rule (spec section 4, R1..R8), the plan section it
-- concerns, whether it was satisfied, and a human-readable description.

CREATE TABLE respect_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    respect_grade_id UUID NOT NULL
        REFERENCES respect_grade(id) ON DELETE CASCADE,

    rule_id VARCHAR(40) NOT NULL,
    section VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (section IN (
            'identity',
            'health',
            'preferences',
            'recommendations',
            'cpr',
            'ceilings',
            'capacity',
            'sign-off',
            'completeness',
            ''
        )),
    satisfied VARCHAR(5) NOT NULL DEFAULT ''
        CHECK (satisfied IN ('yes', 'no', '')),
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX respect_grade_rule_grade_id_idx
    ON respect_grade_rule (respect_grade_id);

CREATE TRIGGER trigger_respect_grade_rule_updated_at
    BEFORE UPDATE ON respect_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE respect_grade_rule IS
    'Audit trail of every mandatory rule evaluated during grading: rule identifier, plan section, whether it was satisfied, category, and description.';
COMMENT ON COLUMN respect_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN respect_grade_rule.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN respect_grade_rule.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN respect_grade_rule.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN respect_grade_rule.respect_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN respect_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R1-IDENTITY, R5-CPR).';
COMMENT ON COLUMN respect_grade_rule.section IS
    'Plan section the rule concerns: identity, health, preferences, recommendations, cpr, ceilings, capacity, sign-off, or completeness.';
COMMENT ON COLUMN respect_grade_rule.satisfied IS
    'Whether the mandatory rule was satisfied (yes/no).';
COMMENT ON COLUMN respect_grade_rule.category IS
    'Subject category (e.g. mandatory-rule, conditional-requirement).';
COMMENT ON COLUMN respect_grade_rule.description IS
    'Human-readable description of the rule and why it passed or failed.';

-- ========================================================================
-- END 06_create_table_respect_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_respect_grade_flag.sql
-- ========================================================================

-- Safety and governance flags that fire independently of the completeness
-- status (spec section 5), each with a priority and a suggested action for
-- the clinician or governance team.

CREATE TABLE respect_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    respect_grade_id UUID NOT NULL
        REFERENCES respect_grade(id) ON DELETE CASCADE,

    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT ''
        CHECK (category IN (
            'cpr-not-documented',
            'capacity-missing',
            'no-clinician-signature',
            'dnacpr-without-discussion',
            'review-date-passed',
            'health-summary-missing',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX respect_grade_flag_grade_id_idx
    ON respect_grade_flag (respect_grade_id);

CREATE TRIGGER trigger_respect_grade_flag_updated_at
    BEFORE UPDATE ON respect_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE respect_grade_flag IS
    'Safety and governance flags that fire independently of the completeness status, with priority and a suggested action for the clinician or governance team.';
COMMENT ON COLUMN respect_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN respect_grade_flag.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN respect_grade_flag.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN respect_grade_flag.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN respect_grade_flag.respect_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN respect_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-CPR-NOT-DOCUMENTED-001).';
COMMENT ON COLUMN respect_grade_flag.category IS
    'Flag category: cpr-not-documented, capacity-missing, no-clinician-signature, dnacpr-without-discussion, review-date-passed, health-summary-missing, or other.';
COMMENT ON COLUMN respect_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN respect_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN respect_grade_flag.suggested_action IS
    'Suggested clinical or governance action (e.g. "document a CPR recommendation", "obtain a clinician signature").';

-- ========================================================================
-- END 07_create_table_respect_grade_flag.sql
-- ========================================================================
