<!ELEMENT lpa_registration_application (id,created_at,updated_at,deleted_at,lpa_id,applicant_kind,payment_method,card_payment_phone,reduced_fee_requested,has_lpa120a_evidence,is_repeat_application,repeat_case_number,payment_reference,payment_date,payment_amount)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT lpa_id (#PCDATA)>
<!ELEMENT applicant_kind (#PCDATA)>
<!ELEMENT payment_method (#PCDATA)>
<!ELEMENT card_payment_phone (#PCDATA)>
<!ELEMENT reduced_fee_requested (#PCDATA)>
<!ELEMENT has_lpa120a_evidence (#PCDATA)>
<!ELEMENT is_repeat_application (#PCDATA)>
<!ELEMENT repeat_case_number (#PCDATA)>
<!ELEMENT payment_reference (#PCDATA)>
<!ELEMENT payment_date (#PCDATA)>
<!ELEMENT payment_amount (#PCDATA)>
