<!ELEMENT issue_tracker_grade (id,created_at,updated_at,deleted_at,issue_tracker_id,score_by_priority_rank,score_by_severity_of_impact,score_by_magnitude_of_damage,score_by_harm_grade,score_by_failure_condition,score_by_moscow_requirement,score_by_frequency_percent,computed_composite_priority,final_composite_priority,override_reason,recommendation,triage_notes,signed_by,signed_at,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT issue_tracker_id (#PCDATA)>
<!ELEMENT score_by_priority_rank (#PCDATA)>
<!ELEMENT score_by_severity_of_impact (#PCDATA)>
<!ELEMENT score_by_magnitude_of_damage (#PCDATA)>
<!ELEMENT score_by_harm_grade (#PCDATA)>
<!ELEMENT score_by_failure_condition (#PCDATA)>
<!ELEMENT score_by_moscow_requirement (#PCDATA)>
<!ELEMENT score_by_frequency_percent (#PCDATA)>
<!ELEMENT computed_composite_priority (#PCDATA)>
<!ELEMENT final_composite_priority (#PCDATA)>
<!ELEMENT override_reason (#PCDATA)>
<!ELEMENT recommendation (#PCDATA)>
<!ELEMENT triage_notes (#PCDATA)>
<!ELEMENT signed_by (#PCDATA)>
<!ELEMENT signed_at (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
