<!ELEMENT reporter (id,created_at,updated_at,deleted_at,name,email,phone,role,organisation,team,location,timezone,preferred_contact)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT organisation (#PCDATA)>
<!ELEMENT team (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT timezone (#PCDATA)>
<!ELEMENT preferred_contact (#PCDATA)>
