<!ELEMENT pulmonary_function_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,test_type,primary_indication,clinical_question,relevant_history,symptom_breathlessness,symptom_cough,symptom_wheeze,smoking_status,current_inhalers,recent_respiratory_infection,recent_mi_or_eye_abdominal_surgery,suspected_active_tuberculosis,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT test_type (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT symptom_breathlessness (#PCDATA)>
<!ELEMENT symptom_cough (#PCDATA)>
<!ELEMENT symptom_wheeze (#PCDATA)>
<!ELEMENT smoking_status (#PCDATA)>
<!ELEMENT current_inhalers (#PCDATA)>
<!ELEMENT recent_respiratory_infection (#PCDATA)>
<!ELEMENT recent_mi_or_eye_abdominal_surgery (#PCDATA)>
<!ELEMENT suspected_active_tuberculosis (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
