mod users;

mod patients;
mod clinicians;
mod medical_information_form_for_air_travels;
mod medical_information_form_for_air_travel_grades;
mod medical_information_form_for_air_travel_grade_rules;
mod medical_information_form_for_air_travel_grade_flags;