//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clinicians;
pub mod columbia_suicide_severity_rating_scale_grade_flags;
pub mod columbia_suicide_severity_rating_scale_grade_rules;
pub mod columbia_suicide_severity_rating_scale_grades;
pub mod columbia_suicide_severity_rating_scales;
pub mod patients;
pub mod users;
