mod users;

mod patients;
mod clinicians;
mod general_practitioner_referral_letters;
mod general_practitioner_referral_letter_grades;
mod general_practitioner_referral_letter_grade_rules;
mod general_practitioner_referral_letter_grade_flags;