use loco_rs::schema::*;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        create_table(m, "pre_operative_assessment_by_patients",
            &[
            
            ("id", ColType::PkAuto),
            
            ("deleted_at", ColType::TimestampWithTimeZoneNull),
            ("weight", ColType::DoubleNull),
            ("height", ColType::DoubleNull),
            ("bmi", ColType::DoubleNull),
            ("planned_procedure", ColType::TextWithDefault(String::new())),
            ("procedure_urgency", ColType::TextWithDefault(String::new())),
            ("status", ColType::TextWithDefault("in_progress".to_string())),
            ("hypertension", ColType::TextWithDefault(String::new())),
            ("hypertension_controlled", ColType::TextWithDefault(String::new())),
            ("ischemic_heart_disease", ColType::TextWithDefault(String::new())),
            ("ihd_details", ColType::TextWithDefault(String::new())),
            ("heart_failure", ColType::TextWithDefault(String::new())),
            ("heart_failure_nyha", ColType::TextWithDefault(String::new())),
            ("valvular_disease", ColType::TextWithDefault(String::new())),
            ("valvular_details", ColType::TextWithDefault(String::new())),
            ("arrhythmia", ColType::TextWithDefault(String::new())),
            ("arrhythmia_type", ColType::TextWithDefault(String::new())),
            ("pacemaker", ColType::TextWithDefault(String::new())),
            ("recent_mi", ColType::TextWithDefault(String::new())),
            ("recent_mi_weeks", ColType::IntegerNull),
            ("asthma", ColType::TextWithDefault(String::new())),
            ("asthma_frequency", ColType::TextWithDefault(String::new())),
            ("copd", ColType::TextWithDefault(String::new())),
            ("copd_severity", ColType::TextWithDefault(String::new())),
            ("osa", ColType::TextWithDefault(String::new())),
            ("osa_cpap", ColType::TextWithDefault(String::new())),
            ("smoking", ColType::TextWithDefault(String::new())),
            ("smoking_pack_years", ColType::IntegerNull),
            ("recent_urti", ColType::TextWithDefault(String::new())),
            ("ckd", ColType::TextWithDefault(String::new())),
            ("ckd_stage", ColType::TextWithDefault(String::new())),
            ("dialysis", ColType::TextWithDefault(String::new())),
            ("dialysis_type", ColType::TextWithDefault(String::new())),
            ("liver_disease", ColType::TextWithDefault(String::new())),
            ("cirrhosis", ColType::TextWithDefault(String::new())),
            ("child_pugh_score", ColType::TextWithDefault(String::new())),
            ("hepatitis", ColType::TextWithDefault(String::new())),
            ("hepatitis_type", ColType::TextWithDefault(String::new())),
            ("diabetes", ColType::TextWithDefault(String::new())),
            ("diabetes_control", ColType::TextWithDefault(String::new())),
            ("diabetes_on_insulin", ColType::TextWithDefault(String::new())),
            ("thyroid_disease", ColType::TextWithDefault(String::new())),
            ("thyroid_type", ColType::TextWithDefault(String::new())),
            ("adrenal_insufficiency", ColType::TextWithDefault(String::new())),
            ("stroke_or_tia", ColType::TextWithDefault(String::new())),
            ("stroke_details", ColType::TextWithDefault(String::new())),
            ("epilepsy", ColType::TextWithDefault(String::new())),
            ("epilepsy_controlled", ColType::TextWithDefault(String::new())),
            ("neuromuscular_disease", ColType::TextWithDefault(String::new())),
            ("neuromuscular_details", ColType::TextWithDefault(String::new())),
            ("raised_icp", ColType::TextWithDefault(String::new())),
            ("bleeding_disorder", ColType::TextWithDefault(String::new())),
            ("bleeding_details", ColType::TextWithDefault(String::new())),
            ("on_anticoagulants", ColType::TextWithDefault(String::new())),
            ("anticoagulant_type", ColType::TextWithDefault(String::new())),
            ("sickle_cell_disease", ColType::TextWithDefault(String::new())),
            ("sickle_cell_trait", ColType::TextWithDefault(String::new())),
            ("anaemia", ColType::TextWithDefault(String::new())),
            ("rheumatoid_arthritis", ColType::TextWithDefault(String::new())),
            ("cervical_spine_issues", ColType::TextWithDefault(String::new())),
            ("limited_neck_movement", ColType::TextWithDefault(String::new())),
            ("limited_mouth_opening", ColType::TextWithDefault(String::new())),
            ("dental_issues", ColType::TextWithDefault(String::new())),
            ("dental_details", ColType::TextWithDefault(String::new())),
            ("previous_difficult_airway", ColType::TextWithDefault(String::new())),
            ("mallampati_score", ColType::TextWithDefault(String::new())),
            ("gord", ColType::TextWithDefault(String::new())),
            ("hiatus_hernia", ColType::TextWithDefault(String::new())),
            ("nausea", ColType::TextWithDefault(String::new())),
            ("name", ColType::TextWithDefault(String::new())),
            ("dose", ColType::TextWithDefault(String::new())),
            ("frequency", ColType::TextWithDefault(String::new())),
            ("sort_order", ColType::IntegerWithDefault(0)),
            ("allergen", ColType::TextWithDefault(String::new())),
            ("reaction", ColType::TextWithDefault(String::new())),
            ("severity", ColType::TextWithDefault(String::new())),
            ("allergy_sort_order", ColType::IntegerWithDefault(0)),
            ("previous_anaesthesia", ColType::TextWithDefault(String::new())),
            ("anaesthesia_problems", ColType::TextWithDefault(String::new())),
            ("anaesthesia_problem_details", ColType::TextWithDefault(String::new())),
            ("family_mh_history", ColType::TextWithDefault(String::new())),
            ("family_mh_details", ColType::TextWithDefault(String::new())),
            ("ponv", ColType::TextWithDefault(String::new())),
            ("alcohol", ColType::TextWithDefault(String::new())),
            ("alcohol_units_per_week", ColType::IntegerNull),
            ("recreational_drugs", ColType::TextWithDefault(String::new())),
            ("drug_details", ColType::TextWithDefault(String::new())),
            ("exercise_tolerance", ColType::TextWithDefault(String::new())),
            ("estimated_mets", ColType::DoubleNull),
            ("mobility_aids", ColType::TextWithDefault(String::new())),
            ("recent_decline", ColType::TextWithDefault(String::new())),
            ("possibly_pregnant", ColType::TextWithDefault(String::new())),
            ("pregnancy_confirmed", ColType::TextWithDefault(String::new())),
            ("gestation_weeks", ColType::IntegerNull),
            ],
            &[
            ("patient", ""),
            ]
        ).await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        drop_table(m, "pre_operative_assessment_by_patients").await
    }
}
