use loco_rs::schema::*;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        create_table(m, "pre_operative_assessment_by_patients",
            &[
            
            ("id", ColType::PkAuto),
            
            ("deleted_at", ColType::TimestampWithTimeZoneNull),
            ("weight", ColType::DoubleNull),
            ("height", ColType::DoubleNull),
            ("bmi", ColType::DoubleNull),
            ("planned_procedure", ColType::Text),
            ("procedure_urgency", ColType::Text),
            ("status", ColType::Text),
            ("hypertension", ColType::Text),
            ("hypertension_controlled", ColType::Text),
            ("ischemic_heart_disease", ColType::Text),
            ("ihd_details", ColType::Text),
            ("heart_failure", ColType::Text),
            ("heart_failure_nyha", ColType::Text),
            ("valvular_disease", ColType::Text),
            ("valvular_details", ColType::Text),
            ("arrhythmia", ColType::Text),
            ("arrhythmia_type", ColType::Text),
            ("pacemaker", ColType::Text),
            ("recent_mi", ColType::Text),
            ("recent_mi_weeks", ColType::IntegerNull),
            ("asthma", ColType::Text),
            ("asthma_frequency", ColType::Text),
            ("copd", ColType::Text),
            ("copd_severity", ColType::Text),
            ("osa", ColType::Text),
            ("osa_cpap", ColType::Text),
            ("smoking", ColType::Text),
            ("smoking_pack_years", ColType::IntegerNull),
            ("recent_urti", ColType::Text),
            ("ckd", ColType::Text),
            ("ckd_stage", ColType::Text),
            ("dialysis", ColType::Text),
            ("dialysis_type", ColType::Text),
            ("liver_disease", ColType::Text),
            ("cirrhosis", ColType::Text),
            ("child_pugh_score", ColType::Text),
            ("hepatitis", ColType::Text),
            ("hepatitis_type", ColType::Text),
            ("diabetes", ColType::Text),
            ("diabetes_control", ColType::Text),
            ("diabetes_on_insulin", ColType::Text),
            ("thyroid_disease", ColType::Text),
            ("thyroid_type", ColType::Text),
            ("adrenal_insufficiency", ColType::Text),
            ("stroke_or_tia", ColType::Text),
            ("stroke_details", ColType::Text),
            ("epilepsy", ColType::Text),
            ("epilepsy_controlled", ColType::Text),
            ("neuromuscular_disease", ColType::Text),
            ("neuromuscular_details", ColType::Text),
            ("raised_icp", ColType::Text),
            ("bleeding_disorder", ColType::Text),
            ("bleeding_details", ColType::Text),
            ("on_anticoagulants", ColType::Text),
            ("anticoagulant_type", ColType::Text),
            ("sickle_cell_disease", ColType::Text),
            ("sickle_cell_trait", ColType::Text),
            ("anaemia", ColType::Text),
            ("rheumatoid_arthritis", ColType::Text),
            ("cervical_spine_issues", ColType::Text),
            ("limited_neck_movement", ColType::Text),
            ("limited_mouth_opening", ColType::Text),
            ("dental_issues", ColType::Text),
            ("dental_details", ColType::Text),
            ("previous_difficult_airway", ColType::Text),
            ("mallampati_score", ColType::Text),
            ("gord", ColType::Text),
            ("hiatus_hernia", ColType::Text),
            ("nausea", ColType::Text),
            ("name", ColType::Text),
            ("dose", ColType::Text),
            ("frequency", ColType::Text),
            ("sort_order", ColType::Integer),
            ("allergen", ColType::Text),
            ("reaction", ColType::Text),
            ("severity", ColType::Text),
            ("allergy_sort_order", ColType::Integer),
            ("previous_anaesthesia", ColType::Text),
            ("anaesthesia_problems", ColType::Text),
            ("anaesthesia_problem_details", ColType::Text),
            ("family_mh_history", ColType::Text),
            ("family_mh_details", ColType::Text),
            ("ponv", ColType::Text),
            ("alcohol", ColType::Text),
            ("alcohol_units_per_week", ColType::IntegerNull),
            ("recreational_drugs", ColType::Text),
            ("drug_details", ColType::Text),
            ("exercise_tolerance", ColType::Text),
            ("estimated_mets", ColType::DoubleNull),
            ("mobility_aids", ColType::Text),
            ("recent_decline", ColType::Text),
            ("possibly_pregnant", ColType::Text),
            ("pregnancy_confirmed", ColType::Text),
            ("gestation_weeks", ColType::IntegerNull),
            ],
            &[
            ("patient", ""),
            ]
        ).await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        drop_table(m, "pre_operative_assessment_by_patients").await
    }
}
