mod users;

mod patients;
mod practitioners;
mod gen_practice_waiting_list_cards;
mod gen_practice_waiting_list_card_appointments;
mod gen_practice_waiting_list_card_grades;
mod gen_practice_waiting_list_card_grade_rules;
mod gen_practice_waiting_list_card_grade_flags;