mod users;

mod patients;
mod clinicians;
mod centor_score_for_streptococcal_pharyngitis;
mod centor_score_for_streptococcal_pharyngitis_grades;
mod centor_score_for_streptococcal_pharyngitis_grade_rules;
mod centor_score_for_streptococcal_pharyngitis_grade_flags;