//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clinicians;
pub mod hypertension_review_grade_flags;
pub mod hypertension_review_grade_rules;
pub mod hypertension_review_grades;
pub mod hypertension_reviews;
pub mod patients;
pub mod users;
