-- schema.sql
-- Combined schema for form: urinalysis-test-request
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (8):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_urinalysis_test_request.sql
--   - 05_create_table_urinalysis_test_request_grade.sql
--   - 06_create_table_urinalysis_test_request_grade_rule.sql
--   - 07_create_table_urinalysis_test_request_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- pg_trgm provides gin_trgm_ops for trigram GIN indexes on text columns.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    waist_as_cm NUMERIC(5,1),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    waist_height_ratio NUMERIC(4,1),
    vo2_max  NUMERIC(4,1)
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Name.';
COMMENT ON COLUMN patient.birth_date IS
    'Birth date.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as full text.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2 format, such as for validating the postal address.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code, such as for validating the postal address.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.waist_as_cm IS
    'Waist circumference measurement in cm, such as for calculating waist-height ratio (WHR).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height measurement in cm, such as for calculating waist-height ratio (WHR).';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI) measurement.';
COMMENT ON COLUMN patient.waist_height_ratio IS
    'Waist-height ratio (WHR) measurement.';
COMMENT ON COLUMN patient.vo2_max IS
    'VO2 max measurement.';

CREATE INDEX patient_index_gto
    ON patient
    USING GIN ((
        name
    ) gin_trgm_ops);

COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight as kg.';

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Requesting clinician (referrer) information.

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role TEXT NOT NULL DEFAULT '' CHECK (role IN ('gp', 'hospital-doctor', 'nurse', 'urologist', 'other', '')),
    registration_body TEXT NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT '',
    united_kingdom_nhs_number CHAR(12) UNIQUE
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Requesting clinician (referrer) who completes the urinalysis test request.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Name.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as full text.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2 format, such as for validating the postal address.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code, such as for validating the postal address.';
COMMENT ON COLUMN clinician.role IS
    'Clinician role: gp, hospital-doctor, nurse, urologist, other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Clinician registration body: GMC, NMC, HCPC, other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Clinician registration number.';
COMMENT ON COLUMN clinician.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';

CREATE INDEX clinician_index_gto
    ON clinician
    USING GIN ((
        name
    ) gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_urinalysis_test_request.sql
-- ========================================================================

-- Urinalysis (urine pathology) test request (order) — the source-of-truth record.
-- The form ORDERS multiple urine tests; each requested test is modelled as a
-- BOOLEAN column. At least one test should be selected; a request with no test
-- selected fires a safety flag.

CREATE TABLE urinalysis_test_request (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,
    clinician_id UUID NOT NULL REFERENCES clinician(id) ON DELETE CASCADE,

    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'submitted', 'vetted', 'scheduled', 'rejected', '')),
    site_name VARCHAR(255) NOT NULL DEFAULT '',
    setting VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (setting IN ('outpatient', 'inpatient', 'community', 'emergency', '')),
    referral_date DATE,

    -- Requested tests (urine test panel; each test is a boolean order line)
    dipstick BOOLEAN NOT NULL DEFAULT FALSE,
    microscopy_culture_sensitivity BOOLEAN NOT NULL DEFAULT FALSE,
    albumin_creatinine_ratio BOOLEAN NOT NULL DEFAULT FALSE,
    protein_creatinine_ratio BOOLEAN NOT NULL DEFAULT FALSE,
    pregnancy_test BOOLEAN NOT NULL DEFAULT FALSE,
    drug_screen BOOLEAN NOT NULL DEFAULT FALSE,
    cytology BOOLEAN NOT NULL DEFAULT FALSE,
    twenty_four_hour_collection BOOLEAN NOT NULL DEFAULT FALSE,

    -- Clinical context
    primary_indication VARCHAR(40) NOT NULL DEFAULT ''
        CHECK (primary_indication IN ('suspected-uti', 'haematuria', 'proteinuria', 'diabetes-monitoring', 'renal-monitoring', 'pregnancy-screen', 'pre-operative', 'catheter-related', 'suspected-malignancy', 'drug-monitoring', 'other', '')),
    clinical_details VARCHAR(1000) NOT NULL DEFAULT '',

    -- Symptoms / red flags
    symptom_dysuria BOOLEAN NOT NULL DEFAULT FALSE,
    symptom_frequency BOOLEAN NOT NULL DEFAULT FALSE,
    symptom_visible_haematuria BOOLEAN NOT NULL DEFAULT FALSE,
    symptom_loin_pain BOOLEAN NOT NULL DEFAULT FALSE,
    symptom_fever BOOLEAN NOT NULL DEFAULT FALSE,

    -- Specimen (preanalytical)
    specimen_type VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (specimen_type IN ('midstream', 'catheter', 'clean-catch', '24h', 'random', '')),
    specimen_collected VARCHAR(5) NOT NULL DEFAULT ''
        CHECK (specimen_collected IN ('yes', 'no', '')),
    collection_datetime TIMESTAMPTZ,

    -- Modifiers
    pregnant BOOLEAN NOT NULL DEFAULT FALSE,
    catheterised BOOLEAN NOT NULL DEFAULT FALSE,
    current_antibiotics BOOLEAN NOT NULL DEFAULT FALSE,

    -- Requester / triage
    urgency VARCHAR(15) NOT NULL DEFAULT 'routine'
        CHECK (urgency IN ('routine', 'urgent', 'stat', '')),
    supervising_consultant VARCHAR(255) NOT NULL DEFAULT '',
    requester_contact VARCHAR(255) NOT NULL DEFAULT '',
    notes VARCHAR(1000) NOT NULL DEFAULT ''
);

CREATE INDEX index_urinalysis_test_request_patient_id
    ON urinalysis_test_request(patient_id);
CREATE INDEX index_urinalysis_test_request_clinician_id
    ON urinalysis_test_request(clinician_id);

CREATE TRIGGER trigger_urinalysis_test_request_updated_at
    BEFORE UPDATE ON urinalysis_test_request
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE urinalysis_test_request IS
    'Urinalysis (urine pathology) test request (order). Captures the requested urine test panel, the clinical indication and details, symptoms / red flags, specimen preanalytical data, modifiers, and triage urgency.';
COMMENT ON COLUMN urinalysis_test_request.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN urinalysis_test_request.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN urinalysis_test_request.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN urinalysis_test_request.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN urinalysis_test_request.patient_id IS
    'Foreign key to the patient.';
COMMENT ON COLUMN urinalysis_test_request.clinician_id IS
    'Foreign key to the requesting clinician (referrer).';
COMMENT ON COLUMN urinalysis_test_request.status IS
    'Request lifecycle status: draft, submitted, vetted, scheduled, rejected.';
COMMENT ON COLUMN urinalysis_test_request.site_name IS
    'Name of the requesting site or clinic.';
COMMENT ON COLUMN urinalysis_test_request.setting IS
    'Care setting: outpatient, inpatient, community, emergency.';
COMMENT ON COLUMN urinalysis_test_request.referral_date IS
    'Date the request was made.';
COMMENT ON COLUMN urinalysis_test_request.dipstick IS
    'Requested test: urine dipstick (reagent strip) for leucocytes, nitrites, blood, protein, glucose.';
COMMENT ON COLUMN urinalysis_test_request.microscopy_culture_sensitivity IS
    'Requested test: microscopy, culture and sensitivity (MC&S) for confirmed / complicated UTI.';
COMMENT ON COLUMN urinalysis_test_request.albumin_creatinine_ratio IS
    'Requested test: urine albumin-to-creatinine ratio (ACR) for albuminuria / CKD / diabetes monitoring.';
COMMENT ON COLUMN urinalysis_test_request.protein_creatinine_ratio IS
    'Requested test: urine protein-to-creatinine ratio (PCR) for proteinuria quantification.';
COMMENT ON COLUMN urinalysis_test_request.pregnancy_test IS
    'Requested test: urine pregnancy test (hCG).';
COMMENT ON COLUMN urinalysis_test_request.drug_screen IS
    'Requested test: urine drug screen / toxicology.';
COMMENT ON COLUMN urinalysis_test_request.cytology IS
    'Requested test: urine cytology for suspected urothelial malignancy.';
COMMENT ON COLUMN urinalysis_test_request.twenty_four_hour_collection IS
    'Requested test: 24-hour urine collection (e.g. protein, creatinine clearance, metanephrines).';
COMMENT ON COLUMN urinalysis_test_request.primary_indication IS
    'Primary clinical indication, used for appropriateness scoring: suspected-uti, haematuria, proteinuria, diabetes-monitoring, renal-monitoring, pregnancy-screen, pre-operative, catheter-related, suspected-malignancy, drug-monitoring, other.';
COMMENT ON COLUMN urinalysis_test_request.clinical_details IS
    'Relevant clinical details and history supporting the request (highest-value field).';
COMMENT ON COLUMN urinalysis_test_request.symptom_dysuria IS
    'Whether the patient reports dysuria (painful urination).';
COMMENT ON COLUMN urinalysis_test_request.symptom_frequency IS
    'Whether the patient reports urinary frequency / urgency.';
COMMENT ON COLUMN urinalysis_test_request.symptom_visible_haematuria IS
    'Whether the patient reports visible (macroscopic) haematuria (red flag).';
COMMENT ON COLUMN urinalysis_test_request.symptom_loin_pain IS
    'Whether the patient reports loin / flank pain (possible upper-tract involvement).';
COMMENT ON COLUMN urinalysis_test_request.symptom_fever IS
    'Whether the patient reports fever / systemic symptoms (possible pyelonephritis / urosepsis).';
COMMENT ON COLUMN urinalysis_test_request.specimen_type IS
    'Specimen type: midstream (MSU), catheter (CSU), clean-catch, 24h, random.';
COMMENT ON COLUMN urinalysis_test_request.specimen_collected IS
    'Whether the specimen has already been collected: yes, no.';
COMMENT ON COLUMN urinalysis_test_request.collection_datetime IS
    'Date and time the specimen was collected (preanalytical timing).';
COMMENT ON COLUMN urinalysis_test_request.pregnant IS
    'Whether the patient is pregnant (alters UTI MSU / culture pathway).';
COMMENT ON COLUMN urinalysis_test_request.catheterised IS
    'Whether the patient is catheterised (CSU; asymptomatic bacteriuria caveats).';
COMMENT ON COLUMN urinalysis_test_request.current_antibiotics IS
    'Whether the patient is currently taking antibiotics (may suppress culture growth).';
COMMENT ON COLUMN urinalysis_test_request.urgency IS
    'Requested triage urgency: routine, urgent, stat.';
COMMENT ON COLUMN urinalysis_test_request.supervising_consultant IS
    'Name of the supervising / responsible consultant.';
COMMENT ON COLUMN urinalysis_test_request.requester_contact IS
    'Contact details (bleep / phone) for the requester.';
COMMENT ON COLUMN urinalysis_test_request.notes IS
    'Free-text additional notes.';

-- ========================================================================
-- END 04_create_table_urinalysis_test_request.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_urinalysis_test_request_grade.sql
-- ========================================================================

-- Computed grading result for a urinalysis test request (four-axis engine).

CREATE TABLE urinalysis_test_request_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    urinalysis_test_request_id UUID NOT NULL UNIQUE
        REFERENCES urinalysis_test_request(id) ON DELETE CASCADE,

    -- Axis A: appropriateness (indication match / NICE UTI; 1-9 ordinal).
    -- Note: there is no single published 1-9 score for urinalysis. The 1-9 is
    -- anchored on indication-to-test match and guideline appropriateness
    -- (NICE NG109 UTI, NICE NG12 haematuria, UK SMI B41 urine investigation).
    appropriateness_score INTEGER
        CHECK (appropriateness_score IS NULL OR appropriateness_score BETWEEN 1 AND 9),
    appropriateness_band VARCHAR(25) NOT NULL DEFAULT ''
        CHECK (appropriateness_band IN ('usually-appropriate', 'may-be-appropriate', 'usually-not-appropriate', '')),

    -- Axis B: preanalytical (specimen suitability) — specimen type / collected
    -- / timing / contamination risk.
    preanalytical_band VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (preanalytical_band IN ('ok', 'caution', 'reject-risk', '')),
    fasting_or_specimen VARCHAR(500) NOT NULL DEFAULT '',

    -- Axis C: request completeness
    completeness_percent INTEGER
        CHECK (completeness_percent IS NULL OR completeness_percent BETWEEN 0 AND 100),

    -- Axis D: triage priority
    triage_tier VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (triage_tier IN ('routine', 'urgent', 'stat', '')),
    target_timeframe VARCHAR(50) NOT NULL DEFAULT '',

    recommendation VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (recommendation IN ('accept', 'query-referrer', 'redirect', 'reject', '')),
    clinician_notes TEXT NOT NULL DEFAULT '',
    signed_at TIMESTAMPTZ,
    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_urinalysis_test_request_grade_updated_at
    BEFORE UPDATE ON urinalysis_test_request_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE urinalysis_test_request_grade IS
    'Computed four-axis grading result: appropriateness (indication match / NICE UTI, 1-9), preanalytical specimen suitability, request completeness, and triage priority.';
COMMENT ON COLUMN urinalysis_test_request_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN urinalysis_test_request_grade.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN urinalysis_test_request_grade.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN urinalysis_test_request_grade.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN urinalysis_test_request_grade.urinalysis_test_request_id IS
    'Foreign key to the parent request (unique, 1:1).';
COMMENT ON COLUMN urinalysis_test_request_grade.appropriateness_score IS
    'Appropriateness score (1-9) anchored on indication-to-test match and guideline appropriateness (no single published urinalysis score exists).';
COMMENT ON COLUMN urinalysis_test_request_grade.appropriateness_band IS
    'Appropriateness band: usually-appropriate (7-9), may-be-appropriate (4-6), usually-not-appropriate (1-3).';
COMMENT ON COLUMN urinalysis_test_request_grade.preanalytical_band IS
    'Preanalytical specimen-suitability band: ok, caution, reject-risk (driven by specimen type / collected / timing / contamination risk per UK SMI B41).';
COMMENT ON COLUMN urinalysis_test_request_grade.fasting_or_specimen IS
    'Specimen / preanalytical advisory note (e.g. "MSU not yet collected; refrigerate or use boric acid if >4 h to lab").';
COMMENT ON COLUMN urinalysis_test_request_grade.completeness_percent IS
    'Request completeness as a percentage of mandatory fields, clinical details and indication weighted highest (0-100).';
COMMENT ON COLUMN urinalysis_test_request_grade.triage_tier IS
    'Assigned triage tier: routine, urgent, stat.';
COMMENT ON COLUMN urinalysis_test_request_grade.target_timeframe IS
    'Target timeframe for the test implied by the triage tier.';
COMMENT ON COLUMN urinalysis_test_request_grade.recommendation IS
    'Vetting recommendation: accept, query-referrer, redirect, reject.';
COMMENT ON COLUMN urinalysis_test_request_grade.clinician_notes IS
    'Free-text vetting notes.';
COMMENT ON COLUMN urinalysis_test_request_grade.signed_at IS
    'Timestamp of vetting clinician electronic signature.';
COMMENT ON COLUMN urinalysis_test_request_grade.graded_at IS
    'Timestamp when the engine last computed the result.';

-- ========================================================================
-- END 05_create_table_urinalysis_test_request_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_urinalysis_test_request_grade_rule.sql
-- ========================================================================

-- Audit trail of every scoring rule that fired for a urinalysis test request.

CREATE TABLE urinalysis_test_request_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    urinalysis_test_request_grade_id UUID NOT NULL
        REFERENCES urinalysis_test_request_grade(id) ON DELETE CASCADE,
    rule_id VARCHAR(40) NOT NULL,
    axis VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (axis IN ('appropriateness', 'preanalytical', 'completeness', 'triage', '')),
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX index_urinalysis_test_request_grade_rule_grade_id
    ON urinalysis_test_request_grade_rule(urinalysis_test_request_grade_id);

CREATE TRIGGER trigger_urinalysis_test_request_grade_rule_updated_at
    BEFORE UPDATE ON urinalysis_test_request_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE urinalysis_test_request_grade_rule IS
    'Audit trail of every appropriateness / preanalytical / completeness / triage rule that fired for this request.';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.urinalysis_test_request_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-APPROP-UTI-01).';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.axis IS
    'Scoring axis the rule belongs to: appropriateness, preanalytical, completeness, triage.';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.category IS
    'Category or indication the rule relates to.';
COMMENT ON COLUMN urinalysis_test_request_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 06_create_table_urinalysis_test_request_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_urinalysis_test_request_grade_flag.sql
-- ========================================================================

-- Safety-critical flags for a urinalysis test request, independent of the axes.

CREATE TABLE urinalysis_test_request_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    urinalysis_test_request_grade_id UUID NOT NULL
        REFERENCES urinalysis_test_request_grade(id) ON DELETE CASCADE,
    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(40) NOT NULL DEFAULT ''
        CHECK (category IN (
            'visible-haematuria-2ww',
            'suspected-pyelonephritis',
            'specimen-not-collected',
            'missing-clinical-details',
            'missing-indication',
            'no-test-selected',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX index_urinalysis_test_request_grade_flag_grade_id
    ON urinalysis_test_request_grade_flag(urinalysis_test_request_grade_id);

CREATE TRIGGER trigger_urinalysis_test_request_grade_flag_updated_at
    BEFORE UPDATE ON urinalysis_test_request_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE urinalysis_test_request_grade_flag IS
    'Safety-critical flags that fire independently of the four axes, with priority and a suggested action for the pathology / vetting team.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.urinalysis_test_request_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-VISIBLE-HAEMATURIA-2WW-001).';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.category IS
    'Flag category: visible-haematuria-2ww, suspected-pyelonephritis, specimen-not-collected, missing-clinical-details, missing-indication, no-test-selected, other.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN urinalysis_test_request_grade_flag.suggested_action IS
    'Suggested clinical action (e.g. "consider NICE NG12 suspected-cancer (2WW) referral").';

-- ========================================================================
-- END 07_create_table_urinalysis_test_request_grade_flag.sql
-- ========================================================================
