//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod action_items;
pub mod agenda_items;
pub mod meeting_outputs;
pub mod meetings;
pub mod organizers;
pub mod participants;
pub mod recurring_rules;
pub mod resources;
pub mod users;
