// LPA controller — landing route. Per-resource controllers (lpa, person,
// address, lpa_attorney, lpa_replacement_attorney, lpa_certificate_provider,
// lpa_person_to_notify, lpa_preferences_and_instructions, lpa_signature,
// lpa_witness, lpa_continuation_sheet, lpa_registration_application,
// lpa_registration_recipient, lpa_validation_result, lpa_validation_rule,
// lpa_validation_flag) will be generated by
// `cargo loco generate scaffold ... --htmx` via the form-level setup
// script. See AGENTS.md for details.

use loco_rs::prelude::*;

#[debug_handler]
async fn index() -> Result<Response> {
    format::text("UK Lasting Power of Attorney for Financial Decisions — Loco backend")
}

pub fn routes() -> Routes {
    Routes::new().prefix("/lpa").add("/", get(index))
}
