import type { OutcomeRow, OocgGrade, Modality, AttendanceOutcome, SubmissionStatus } from './types.ts';

const grades: OocgGrade[] = ['A', 'B', 'C', 'D', 'E'];
const modalities: Modality[] = ['in_person', 'telephone', 'video'];
const attendances: AttendanceOutcome[] = ['attended', 'dna', 'cancelled_patient', 'cancelled_provider', 'rescheduled'];
const statuses: SubmissionStatus[] = ['draft', 'submitted', 'reviewed', 'urgent'];

const specialties = [
	'Cardiology',
	'Neurology',
	'Orthopaedics',
	'Oncology',
	'Gastroenterology',
	'Respiratory',
	'Rheumatology',
	'Endocrinology',
	'Urology',
	'Ophthalmology',
];

function worst(a: OocgGrade, b: OocgGrade, c: OocgGrade, d: OocgGrade): OocgGrade {
	const order: OocgGrade[] = ['A', 'B', 'C', 'D', 'E'];
	return [a, b, c, d].reduce(
		(acc, g) => (order.indexOf(g) > order.indexOf(acc) ? g : acc),
		'A' as OocgGrade
	);
}

/** 20 plausible OOCG outcome rows for dashboard demonstration */
export const outcomes: OutcomeRow[] = [
	{
		id: '1',
		patient: 'James Smith',
		nhsNumber: '943 476 5919',
		clinicDate: '2026-01-15',
		specialty: 'Cardiology',
		modality: 'in_person',
		waitTimeDays: 42,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'A',
		promGrade: 'B',
		premGrade: 'A',
		operationalGrade: 'B',
		overallGrade: 'B',
		flagCount: 0,
		status: 'reviewed',
	},
	{
		id: '2',
		patient: 'Priya Patel',
		nhsNumber: '721 938 4102',
		clinicDate: '2026-01-22',
		specialty: 'Neurology',
		modality: 'telephone',
		waitTimeDays: 78,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'B',
		promGrade: 'C',
		premGrade: 'B',
		operationalGrade: 'C',
		overallGrade: 'C',
		flagCount: 1,
		status: 'submitted',
	},
	{
		id: '3',
		patient: 'Margaret Jones',
		nhsNumber: '384 615 7230',
		clinicDate: '2026-02-03',
		specialty: 'Orthopaedics',
		modality: 'in_person',
		waitTimeDays: 120,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'C',
		promGrade: 'D',
		premGrade: 'C',
		operationalGrade: 'D',
		overallGrade: 'D',
		flagCount: 3,
		status: 'urgent',
	},
	{
		id: '4',
		patient: 'David Williams',
		nhsNumber: '512 847 9063',
		clinicDate: '2026-02-10',
		specialty: 'Oncology',
		modality: 'video',
		waitTimeDays: 14,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'A',
		promGrade: 'A',
		premGrade: 'A',
		operationalGrade: 'A',
		overallGrade: 'A',
		flagCount: 0,
		status: 'reviewed',
	},
	{
		id: '5',
		patient: 'Sarah Brown',
		nhsNumber: '167 293 8451',
		clinicDate: '2026-02-14',
		specialty: 'Gastroenterology',
		modality: 'in_person',
		waitTimeDays: 56,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'B',
		promGrade: 'B',
		premGrade: 'C',
		operationalGrade: 'B',
		overallGrade: 'C',
		flagCount: 1,
		status: 'reviewed',
	},
	{
		id: '6',
		patient: 'James Taylor',
		nhsNumber: '835 162 4097',
		clinicDate: '2026-02-20',
		specialty: 'Respiratory',
		modality: 'telephone',
		waitTimeDays: 35,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'A',
		promGrade: 'B',
		premGrade: 'B',
		operationalGrade: 'A',
		overallGrade: 'B',
		flagCount: 0,
		status: 'submitted',
	},
	{
		id: '7',
		patient: 'Helen Davies',
		nhsNumber: '294 708 5316',
		clinicDate: '2026-02-25',
		specialty: 'Rheumatology',
		modality: 'in_person',
		waitTimeDays: 95,
		nhsAttendanceOutcome: 'dna',
		clinicalGrade: 'D',
		promGrade: 'D',
		premGrade: 'E',
		operationalGrade: 'D',
		overallGrade: 'E',
		flagCount: 5,
		status: 'urgent',
	},
	{
		id: '8',
		patient: 'Robert Wilson',
		nhsNumber: '608 341 2975',
		clinicDate: '2026-03-07',
		specialty: 'Endocrinology',
		modality: 'video',
		waitTimeDays: 28,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'B',
		promGrade: 'A',
		premGrade: 'A',
		operationalGrade: 'B',
		overallGrade: 'B',
		flagCount: 0,
		status: 'reviewed',
	},
	{
		id: '9',
		patient: 'Catherine Evans',
		nhsNumber: '473 926 1084',
		clinicDate: '2026-03-12',
		specialty: 'Urology',
		modality: 'in_person',
		waitTimeDays: 67,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'C',
		promGrade: 'C',
		premGrade: 'B',
		operationalGrade: 'C',
		overallGrade: 'C',
		flagCount: 2,
		status: 'submitted',
	},
	{
		id: '10',
		patient: 'Michael Thomas',
		nhsNumber: '159 684 7302',
		clinicDate: '2026-03-18',
		specialty: 'Ophthalmology',
		modality: 'in_person',
		waitTimeDays: 0,
		nhsAttendanceOutcome: 'cancelled_patient',
		clinicalGrade: 'B',
		promGrade: 'B',
		premGrade: 'C',
		operationalGrade: 'C',
		overallGrade: 'C',
		flagCount: 2,
		status: 'draft',
	},
	{
		id: '11',
		patient: 'Emma Robinson',
		nhsNumber: '742 051 3896',
		clinicDate: '2026-03-22',
		specialty: 'Cardiology',
		modality: 'telephone',
		waitTimeDays: 21,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'A',
		promGrade: 'A',
		premGrade: 'B',
		operationalGrade: 'A',
		overallGrade: 'B',
		flagCount: 0,
		status: 'reviewed',
	},
	{
		id: '12',
		patient: 'George Clark',
		nhsNumber: '386 219 5740',
		clinicDate: '2026-03-28',
		specialty: 'Neurology',
		modality: 'video',
		waitTimeDays: 140,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'D',
		promGrade: 'C',
		premGrade: 'D',
		operationalGrade: 'E',
		overallGrade: 'E',
		flagCount: 4,
		status: 'urgent',
	},
	{
		id: '13',
		patient: 'Susan Walker',
		nhsNumber: '925 473 0168',
		clinicDate: '2026-04-01',
		specialty: 'Gastroenterology',
		modality: 'in_person',
		waitTimeDays: 49,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'B',
		promGrade: 'B',
		premGrade: 'A',
		operationalGrade: 'B',
		overallGrade: 'B',
		flagCount: 0,
		status: 'submitted',
	},
	{
		id: '14',
		patient: 'Richard Hall',
		nhsNumber: '618 305 9247',
		clinicDate: '2026-04-05',
		specialty: 'Orthopaedics',
		modality: 'in_person',
		waitTimeDays: 85,
		nhsAttendanceOutcome: 'rescheduled',
		clinicalGrade: 'C',
		promGrade: 'D',
		premGrade: 'C',
		operationalGrade: 'D',
		overallGrade: 'D',
		flagCount: 3,
		status: 'urgent',
	},
	{
		id: '15',
		patient: 'Elizabeth Young',
		nhsNumber: '057 842 6139',
		clinicDate: '2026-04-09',
		specialty: 'Respiratory',
		modality: 'video',
		waitTimeDays: 17,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'A',
		promGrade: 'B',
		premGrade: 'A',
		operationalGrade: 'A',
		overallGrade: 'B',
		flagCount: 0,
		status: 'reviewed',
	},
	{
		id: '16',
		patient: 'Ahmed Hassan',
		nhsNumber: '310 562 7894',
		clinicDate: '2026-04-12',
		specialty: 'Rheumatology',
		modality: 'telephone',
		waitTimeDays: 63,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'B',
		promGrade: 'C',
		premGrade: 'B',
		operationalGrade: 'B',
		overallGrade: 'C',
		flagCount: 1,
		status: 'submitted',
	},
	{
		id: '17',
		patient: 'Fiona MacLeod',
		nhsNumber: '487 139 2605',
		clinicDate: '2026-04-14',
		specialty: 'Endocrinology',
		modality: 'in_person',
		waitTimeDays: 31,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'C',
		promGrade: 'B',
		premGrade: 'B',
		operationalGrade: 'C',
		overallGrade: 'C',
		flagCount: 1,
		status: 'submitted',
	},
	{
		id: '18',
		patient: 'Liam O\'Brien',
		nhsNumber: '763 258 0413',
		clinicDate: '2026-04-16',
		specialty: 'Oncology',
		modality: 'in_person',
		waitTimeDays: 9,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'A',
		promGrade: 'A',
		premGrade: 'A',
		operationalGrade: 'A',
		overallGrade: 'A',
		flagCount: 0,
		status: 'reviewed',
	},
	{
		id: '19',
		patient: 'Nadia Kowalski',
		nhsNumber: '541 870 3296',
		clinicDate: '2026-04-18',
		specialty: 'Urology',
		modality: 'video',
		waitTimeDays: 0,
		nhsAttendanceOutcome: 'cancelled_provider',
		clinicalGrade: 'C',
		promGrade: 'C',
		premGrade: 'D',
		operationalGrade: 'D',
		overallGrade: 'D',
		flagCount: 3,
		status: 'draft',
	},
	{
		id: '20',
		patient: 'Tariq Mahmood',
		nhsNumber: '892 047 6153',
		clinicDate: '2026-04-20',
		specialty: 'Ophthalmology',
		modality: 'in_person',
		waitTimeDays: 52,
		nhsAttendanceOutcome: 'attended',
		clinicalGrade: 'B',
		promGrade: 'B',
		premGrade: 'B',
		operationalGrade: 'B',
		overallGrade: 'B',
		flagCount: 0,
		status: 'submitted',
	},
];
