-- schema.sql
-- Combined schema for form: medication-reconciliation
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (12):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_medication_reconciliation.sql
--   - 05_create_table_medication_reconciliation_line_item.sql
--   - 06_create_table_medication_reconciliation_information_source.sql
--   - 07_create_table_medication_reconciliation_allergy.sql
--   - 08_create_table_medication_reconciliation_discrepancy.sql
--   - 09_create_table_medication_reconciliation_grade.sql
--   - 10_create_table_medication_reconciliation_grade_rule.sql
--   - 11_create_table_medication_reconciliation_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators used by free-text search GIN indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information.

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    hospital_mrn VARCHAR(50),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    allergies_summary TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient demographic information used by the medication-reconciliation record.';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Full patient name as recorded on the wristband.';
COMMENT ON COLUMN patient.birth_date IS
    'Date of birth.';
COMMENT ON COLUMN patient.sex IS
    'Sex recorded for clinical purposes: female, male, intersex, or unknown.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.hospital_mrn IS
    'Local hospital medical record number (MRN).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height in centimetres.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight in kilograms.';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI), kg/m^2.';
COMMENT ON COLUMN patient.allergies_summary IS
    'Free-text summary of the patient''s known drug allergies.';

CREATE INDEX patient_name_trgm_idx
    ON patient
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Clinician employee information used to identify the professional who
-- carried out the medication reconciliation (pharmacist, pharmacy
-- technician, prescriber, or nurse).

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN ('pharmacist', 'pharmacy-technician', 'prescriber', 'nurse', 'other', '')),
    registration_body VARCHAR(20) NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'GPhC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician identifying information for the professional who reconciled the patient''s medicines.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Clinician full name as recorded in the rota.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code.';
COMMENT ON COLUMN clinician.role IS
    'Primary clinical role for the reconciliation: pharmacist, pharmacy-technician, prescriber, nurse, or other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Professional registration body: GMC, NMC, HCPC, GPhC, or other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Professional registration number issued by the registration body.';

CREATE INDEX clinician_name_trgm_idx
    ON clinician
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_medication_reconciliation.sql
-- ========================================================================

-- Parent medication-reconciliation header. Records the transition-of-care
-- context (admission / transfer / discharge), the care setting, the
-- reconciling clinician, patient identification, and the patient-level
-- allergy status. The information sources, allergies, medication line items
-- (best-possible medication history and inpatient list), and reconciliation
-- discrepancies are held in child tables that cascade from this parent.

CREATE TABLE medication_reconciliation (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE RESTRICT,
    clinician_id UUID REFERENCES clinician(id) ON DELETE RESTRICT,

    reconciliation_type VARCHAR(15) NOT NULL DEFAULT '' CHECK (reconciliation_type IN ('admission', 'transfer', 'discharge', '')),
    care_setting VARCHAR(25) NOT NULL DEFAULT '' CHECK (care_setting IN ('emergency-department', 'acute-medical-unit', 'surgical-admissions', 'ward', 'critical-care', 'other', '')),
    reconciled_at TIMESTAMPTZ,

    clinician_name TEXT NOT NULL DEFAULT '',
    clinician_role VARCHAR(20) NOT NULL DEFAULT '' CHECK (clinician_role IN ('pharmacist', 'pharmacy-technician', 'prescriber', 'nurse', 'other', '')),

    patient_identifier TEXT NOT NULL DEFAULT '',
    age_band VARCHAR(15) NOT NULL DEFAULT '' CHECK (age_band IN ('adult', 'paediatric', '')),
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    weight_kg NUMERIC(5,1),

    allergy_status VARCHAR(25) NOT NULL DEFAULT '' CHECK (allergy_status IN ('documented', 'no-known-drug-allergies', 'not-documented', ''))
);

CREATE INDEX medication_reconciliation_patient_id_idx
    ON medication_reconciliation (patient_id);
CREATE INDEX medication_reconciliation_clinician_id_idx
    ON medication_reconciliation (clinician_id);

CREATE TRIGGER trigger_medication_reconciliation_updated_at
    BEFORE UPDATE ON medication_reconciliation
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE medication_reconciliation IS
    'Parent medication-reconciliation header: transition-of-care context, care setting, reconciling clinician, patient identification, and patient-level allergy status.';
COMMENT ON COLUMN medication_reconciliation.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN medication_reconciliation.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN medication_reconciliation.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN medication_reconciliation.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN medication_reconciliation.patient_id IS
    'Foreign key to the patient this reconciliation is for (restricted delete).';
COMMENT ON COLUMN medication_reconciliation.clinician_id IS
    'Foreign key to the reconciling clinician (restricted delete); optional.';
COMMENT ON COLUMN medication_reconciliation.reconciliation_type IS
    'Transition of care at which the reconciliation is performed: admission, transfer, or discharge.';
COMMENT ON COLUMN medication_reconciliation.care_setting IS
    'Care setting: emergency-department, acute-medical-unit, surgical-admissions, ward, critical-care, or other.';
COMMENT ON COLUMN medication_reconciliation.reconciled_at IS
    'Date and time the reconciliation was carried out.';
COMMENT ON COLUMN medication_reconciliation.clinician_name IS
    'Name of the reconciling clinician as entered on the form.';
COMMENT ON COLUMN medication_reconciliation.clinician_role IS
    'Role of the reconciling clinician: pharmacist, pharmacy-technician, prescriber, nurse, or other.';
COMMENT ON COLUMN medication_reconciliation.patient_identifier IS
    'Local patient identifier as entered on the form.';
COMMENT ON COLUMN medication_reconciliation.age_band IS
    'Patient age band for dosing context: adult or paediatric.';
COMMENT ON COLUMN medication_reconciliation.sex IS
    'Patient sex: female, male, intersex, or unknown.';
COMMENT ON COLUMN medication_reconciliation.weight_kg IS
    'Patient weight in kilograms for weight-based dosing (nullable).';
COMMENT ON COLUMN medication_reconciliation.allergy_status IS
    'Patient allergy status: documented, no-known-drug-allergies, or not-documented.';

-- ========================================================================
-- END 04_create_table_medication_reconciliation.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_medication_reconciliation_line_item.sql
-- ========================================================================

-- Medication line items on either list. Each medicine is one row and cascades
-- from the parent medication_reconciliation. The list_source discriminator
-- distinguishes a best-possible-medication-history (BPMH) line from a current
-- inpatient-list line. A row carries the drug name, form, dose, route,
-- frequency, indication, high-risk class, adherence, originating information
-- source, and (for inpatient rows) the prescribing status.

CREATE TABLE medication_reconciliation_line_item (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    medication_reconciliation_id UUID NOT NULL REFERENCES medication_reconciliation(id) ON DELETE CASCADE,

    list_source VARCHAR(10) NOT NULL DEFAULT '' CHECK (list_source IN ('bpmh', 'inpatient', '')),
    drug_name TEXT NOT NULL DEFAULT '',
    form TEXT NOT NULL DEFAULT '',
    dose TEXT NOT NULL DEFAULT '',
    route VARCHAR(15) NOT NULL DEFAULT '' CHECK (route IN ('oral', 'iv', 'im', 'subcutaneous', 'topical', 'inhaled', 'other', '')),
    frequency TEXT NOT NULL DEFAULT '',
    indication TEXT NOT NULL DEFAULT '',
    high_risk_class VARCHAR(15) NOT NULL DEFAULT '' CHECK (high_risk_class IN ('none', 'anticoagulant', 'insulin', 'opioid', 'other', '')),
    adherence VARCHAR(15) NOT NULL DEFAULT '' CHECK (adherence IN ('taking', 'not-taking', 'intermittent', 'unknown', '')),
    source_type VARCHAR(30) NOT NULL DEFAULT '' CHECK (source_type IN ('patient-interview', 'carer-interview', 'gp-record', 'repeat-prescription', 'community-pharmacy', 'dispensing-history', 'previous-discharge-summary', 'own-drugs-bag', 'care-home-mar', '')),
    status VARCHAR(15) NOT NULL DEFAULT '' CHECK (status IN ('active', 'held', 'stopped', 'suspended', ''))
);

CREATE INDEX medication_reconciliation_line_item_reconciliation_id_idx
    ON medication_reconciliation_line_item (medication_reconciliation_id);

CREATE TRIGGER trigger_medication_reconciliation_line_item_updated_at
    BEFORE UPDATE ON medication_reconciliation_line_item
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE medication_reconciliation_line_item IS
    'Medication line items on either list (BPMH or inpatient), discriminated by list_source, cascading from the parent reconciliation.';
COMMENT ON COLUMN medication_reconciliation_line_item.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN medication_reconciliation_line_item.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN medication_reconciliation_line_item.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN medication_reconciliation_line_item.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN medication_reconciliation_line_item.medication_reconciliation_id IS
    'Foreign key to the parent medication reconciliation.';
COMMENT ON COLUMN medication_reconciliation_line_item.list_source IS
    'Which list this line belongs to: bpmh (best-possible medication history) or inpatient.';
COMMENT ON COLUMN medication_reconciliation_line_item.drug_name IS
    'Generic (preferred) or brand name of the medicine.';
COMMENT ON COLUMN medication_reconciliation_line_item.form IS
    'Pharmaceutical form, e.g. tablet, capsule, injection, patch.';
COMMENT ON COLUMN medication_reconciliation_line_item.dose IS
    'Dose as free text to preserve units, e.g. "5 mg".';
COMMENT ON COLUMN medication_reconciliation_line_item.route IS
    'Route of administration: oral, iv, im, subcutaneous, topical, inhaled, or other.';
COMMENT ON COLUMN medication_reconciliation_line_item.frequency IS
    'Dosing frequency as free text, e.g. "once daily", "BD", "PRN".';
COMMENT ON COLUMN medication_reconciliation_line_item.indication IS
    'Reason the medicine is prescribed.';
COMMENT ON COLUMN medication_reconciliation_line_item.high_risk_class IS
    'High-risk medicine class: none, anticoagulant, insulin, opioid, or other.';
COMMENT ON COLUMN medication_reconciliation_line_item.adherence IS
    'Patient adherence: taking, not-taking, intermittent, or unknown.';
COMMENT ON COLUMN medication_reconciliation_line_item.source_type IS
    'Information source this line came from: patient-interview, carer-interview, gp-record, repeat-prescription, community-pharmacy, dispensing-history, previous-discharge-summary, own-drugs-bag, or care-home-mar.';
COMMENT ON COLUMN medication_reconciliation_line_item.status IS
    'Prescribing status for inpatient rows: active, held, stopped, or suspended.';

-- ========================================================================
-- END 05_create_table_medication_reconciliation_line_item.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_medication_reconciliation_information_source.sql
-- ========================================================================

-- Information sources used to build the best-possible medication history
-- (BPMH). Each source is one row and cascades from the parent
-- medication_reconciliation. Two or more independent, verified sources are
-- required for a complete reconciliation.

CREATE TABLE medication_reconciliation_information_source (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    medication_reconciliation_id UUID NOT NULL REFERENCES medication_reconciliation(id) ON DELETE CASCADE,

    source_type VARCHAR(30) NOT NULL DEFAULT '' CHECK (source_type IN ('patient-interview', 'carer-interview', 'gp-record', 'repeat-prescription', 'community-pharmacy', 'dispensing-history', 'previous-discharge-summary', 'own-drugs-bag', 'care-home-mar', '')),
    verified BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX medication_reconciliation_information_source_reconciliation_id_idx
    ON medication_reconciliation_information_source (medication_reconciliation_id);

CREATE TRIGGER trigger_medication_reconciliation_information_source_updated_at
    BEFORE UPDATE ON medication_reconciliation_information_source
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE medication_reconciliation_information_source IS
    'Information sources used to build the best-possible medication history (BPMH), cascading from the parent reconciliation.';
COMMENT ON COLUMN medication_reconciliation_information_source.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN medication_reconciliation_information_source.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN medication_reconciliation_information_source.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN medication_reconciliation_information_source.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN medication_reconciliation_information_source.medication_reconciliation_id IS
    'Foreign key to the parent medication reconciliation.';
COMMENT ON COLUMN medication_reconciliation_information_source.source_type IS
    'Type of source: patient-interview, carer-interview, gp-record, repeat-prescription, community-pharmacy, dispensing-history, previous-discharge-summary, own-drugs-bag, or care-home-mar.';
COMMENT ON COLUMN medication_reconciliation_information_source.verified IS
    'Whether the source was directly checked by the reconciling clinician.';

-- ========================================================================
-- END 06_create_table_medication_reconciliation_information_source.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_medication_reconciliation_allergy.sql
-- ========================================================================

-- Drug allergies and adverse reactions recorded for the patient. Each
-- allergy is one row and cascades from the parent medication_reconciliation.
-- Allergy substances are cross-checked against reconciled medicines to raise
-- the allergy-conflict safety flag.

CREATE TABLE medication_reconciliation_allergy (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    medication_reconciliation_id UUID NOT NULL REFERENCES medication_reconciliation(id) ON DELETE CASCADE,

    substance TEXT NOT NULL DEFAULT '',
    reaction_type VARCHAR(15) NOT NULL DEFAULT '' CHECK (reaction_type IN ('allergy', 'intolerance', 'adverse-effect', 'unknown', '')),
    severity VARCHAR(15) NOT NULL DEFAULT '' CHECK (severity IN ('mild', 'moderate', 'severe', 'anaphylaxis', ''))
);

CREATE INDEX medication_reconciliation_allergy_reconciliation_id_idx
    ON medication_reconciliation_allergy (medication_reconciliation_id);

CREATE TRIGGER trigger_medication_reconciliation_allergy_updated_at
    BEFORE UPDATE ON medication_reconciliation_allergy
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE medication_reconciliation_allergy IS
    'Drug allergies and adverse reactions recorded for the patient, cascading from the parent reconciliation.';
COMMENT ON COLUMN medication_reconciliation_allergy.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN medication_reconciliation_allergy.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN medication_reconciliation_allergy.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN medication_reconciliation_allergy.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN medication_reconciliation_allergy.medication_reconciliation_id IS
    'Foreign key to the parent medication reconciliation.';
COMMENT ON COLUMN medication_reconciliation_allergy.substance IS
    'Drug or drug class the patient reacts to.';
COMMENT ON COLUMN medication_reconciliation_allergy.reaction_type IS
    'Reaction type: allergy, intolerance, adverse-effect, or unknown.';
COMMENT ON COLUMN medication_reconciliation_allergy.severity IS
    'Reaction severity: mild, moderate, severe, or anaphylaxis.';

-- ========================================================================
-- END 07_create_table_medication_reconciliation_allergy.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 08_create_table_medication_reconciliation_discrepancy.sql
-- ========================================================================

-- Reconciliation discrepancies between the best-possible medication history
-- (BPMH) and the current inpatient list. Each difference is one row and
-- cascades from the parent medication_reconciliation. A discrepancy is
-- classified by type, matched to the BPMH and/or inpatient line it relates
-- to, and marked intentional (a documented decision carrying an intended
-- action and rationale) or unintentional (an unexplained error).

CREATE TABLE medication_reconciliation_discrepancy (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    medication_reconciliation_id UUID NOT NULL REFERENCES medication_reconciliation(id) ON DELETE CASCADE,

    discrepancy_type VARCHAR(15) NOT NULL DEFAULT '' CHECK (discrepancy_type IN ('omission', 'commission', 'duplication', 'dose', 'frequency', 'route', 'formulation', '')),
    bpmh_item_ref TEXT NOT NULL DEFAULT '',
    inpatient_item_ref TEXT NOT NULL DEFAULT '',
    intended_action VARCHAR(15) NOT NULL DEFAULT '' CHECK (intended_action IN ('continue', 'hold', 'stop', 'change', 'start', '')),
    rationale TEXT NOT NULL DEFAULT '',
    intentional BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX medication_reconciliation_discrepancy_reconciliation_id_idx
    ON medication_reconciliation_discrepancy (medication_reconciliation_id);

CREATE TRIGGER trigger_medication_reconciliation_discrepancy_updated_at
    BEFORE UPDATE ON medication_reconciliation_discrepancy
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE medication_reconciliation_discrepancy IS
    'Reconciliation discrepancies between the BPMH and the inpatient list, classified by type and by intentional / unintentional, cascading from the parent reconciliation.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.medication_reconciliation_id IS
    'Foreign key to the parent medication reconciliation.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.discrepancy_type IS
    'Type of difference: omission, commission, duplication, dose, frequency, route, or formulation.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.bpmh_item_ref IS
    'Reference to the matched BPMH line item (free text; empty when not applicable).';
COMMENT ON COLUMN medication_reconciliation_discrepancy.inpatient_item_ref IS
    'Reference to the matched inpatient line item (free text; empty when not applicable).';
COMMENT ON COLUMN medication_reconciliation_discrepancy.intended_action IS
    'Documented action for an intentional discrepancy: continue, hold, stop, change, or start.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.rationale IS
    'Clinical reason for the intended action.';
COMMENT ON COLUMN medication_reconciliation_discrepancy.intentional IS
    'True when the discrepancy is a documented decision; false when unexplained (an error).';

-- ========================================================================
-- END 08_create_table_medication_reconciliation_discrepancy.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 09_create_table_medication_reconciliation_grade.sql
-- ========================================================================

-- Computed reconciliation grading result. Stores the overall status
-- (Complete / Discrepancies-outstanding / Incomplete) and the derived counts
-- the engine produced from the information sources, line items, and
-- discrepancies. One row per reconciliation (1:1).

CREATE TABLE medication_reconciliation_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    medication_reconciliation_id UUID NOT NULL UNIQUE
        REFERENCES medication_reconciliation(id) ON DELETE CASCADE,

    status VARCHAR(25) NOT NULL DEFAULT ''
        CHECK (status IN ('complete', 'discrepancies-outstanding', 'incomplete', '')),
    source_count INTEGER NOT NULL DEFAULT 0
        CHECK (source_count >= 0),
    unintentional_count INTEGER NOT NULL DEFAULT 0
        CHECK (unintentional_count >= 0),
    high_risk_unintentional_count INTEGER NOT NULL DEFAULT 0
        CHECK (high_risk_unintentional_count >= 0),
    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_medication_reconciliation_grade_updated_at
    BEFORE UPDATE ON medication_reconciliation_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE medication_reconciliation_grade IS
    'Computed reconciliation grading result: overall status and the derived source / unintentional / high-risk-unintentional counts.';
COMMENT ON COLUMN medication_reconciliation_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN medication_reconciliation_grade.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN medication_reconciliation_grade.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN medication_reconciliation_grade.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN medication_reconciliation_grade.medication_reconciliation_id IS
    'Foreign key to the parent medication reconciliation (unique, 1:1).';
COMMENT ON COLUMN medication_reconciliation_grade.status IS
    'Overall reconciliation status: complete, discrepancies-outstanding, or incomplete.';
COMMENT ON COLUMN medication_reconciliation_grade.source_count IS
    'Number of independent information sources used to build the BPMH.';
COMMENT ON COLUMN medication_reconciliation_grade.unintentional_count IS
    'Number of unintentional (unexplained) discrepancies outstanding.';
COMMENT ON COLUMN medication_reconciliation_grade.high_risk_unintentional_count IS
    'Number of unintentional discrepancies on a high-risk medicine (anticoagulant, insulin, or opioid).';
COMMENT ON COLUMN medication_reconciliation_grade.graded_at IS
    'Timestamp when the engine last computed the grade.';

-- ========================================================================
-- END 09_create_table_medication_reconciliation_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 10_create_table_medication_reconciliation_grade_rule.sql
-- ========================================================================

-- Audit trail of every reconciliation rule that fired during grading. Each row
-- records one rule firing with a category and a human-readable description.

CREATE TABLE medication_reconciliation_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    medication_reconciliation_grade_id UUID NOT NULL
        REFERENCES medication_reconciliation_grade(id) ON DELETE CASCADE,

    rule_id VARCHAR(40) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX medication_reconciliation_grade_rule_grade_id_idx
    ON medication_reconciliation_grade_rule (medication_reconciliation_grade_id);

CREATE TRIGGER trigger_medication_reconciliation_grade_rule_updated_at
    BEFORE UPDATE ON medication_reconciliation_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE medication_reconciliation_grade_rule IS
    'Audit trail of every reconciliation rule that fired during grading: category and description.';
COMMENT ON COLUMN medication_reconciliation_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN medication_reconciliation_grade_rule.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN medication_reconciliation_grade_rule.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN medication_reconciliation_grade_rule.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN medication_reconciliation_grade_rule.medication_reconciliation_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN medication_reconciliation_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-STATUS-INCOMPLETE-01).';
COMMENT ON COLUMN medication_reconciliation_grade_rule.category IS
    'Subject category (e.g. status, discrepancy-classification).';
COMMENT ON COLUMN medication_reconciliation_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 10_create_table_medication_reconciliation_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 11_create_table_medication_reconciliation_grade_flag.sql
-- ========================================================================

-- Safety flags raised independently of the reconciliation status, with a
-- priority, a description, and a suggested action for the pharmacy or
-- prescribing team.

CREATE TABLE medication_reconciliation_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    medication_reconciliation_grade_id UUID NOT NULL
        REFERENCES medication_reconciliation_grade(id) ON DELETE CASCADE,

    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(40) NOT NULL DEFAULT ''
        CHECK (category IN (
            'high-risk-unintentional-discrepancy',
            'insufficient-sources',
            'allergy-conflict',
            'interaction',
            'therapeutic-duplication',
            'unintentional-discrepancy-outstanding',
            'allergy-status-not-documented',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX medication_reconciliation_grade_flag_grade_id_idx
    ON medication_reconciliation_grade_flag (medication_reconciliation_grade_id);

CREATE TRIGGER trigger_medication_reconciliation_grade_flag_updated_at
    BEFORE UPDATE ON medication_reconciliation_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE medication_reconciliation_grade_flag IS
    'Safety flags raised independently of the reconciliation status, with priority, description, and a suggested action for the pharmacy or prescribing team.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.medication_reconciliation_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-HIGH-RISK-UNINTENTIONAL-DISCREPANCY-001).';
COMMENT ON COLUMN medication_reconciliation_grade_flag.category IS
    'Flag category: high-risk-unintentional-discrepancy, insufficient-sources, allergy-conflict, interaction, therapeutic-duplication, unintentional-discrepancy-outstanding, allergy-status-not-documented, or other.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN medication_reconciliation_grade_flag.suggested_action IS
    'Suggested action (e.g. "resolve the unintentional anticoagulant discrepancy with the prescriber").';

-- ========================================================================
-- END 11_create_table_medication_reconciliation_grade_flag.sql
-- ========================================================================
