<!ELEMENT lpa_registration_recipient (id,created_at,updated_at,deleted_at,lpa_id,recipient_kind,recipient_person_id,company_name,prefers_post,prefers_phone,prefers_email,prefers_welsh,contact_phone,contact_email,other_first_names,other_last_name,other_address_line_1,other_address_line_2,other_address_line_3,other_postcode)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT lpa_id (#PCDATA)>
<!ELEMENT recipient_kind (#PCDATA)>
<!ELEMENT recipient_person_id (#PCDATA)>
<!ELEMENT company_name (#PCDATA)>
<!ELEMENT prefers_post (#PCDATA)>
<!ELEMENT prefers_phone (#PCDATA)>
<!ELEMENT prefers_email (#PCDATA)>
<!ELEMENT prefers_welsh (#PCDATA)>
<!ELEMENT contact_phone (#PCDATA)>
<!ELEMENT contact_email (#PCDATA)>
<!ELEMENT other_first_names (#PCDATA)>
<!ELEMENT other_last_name (#PCDATA)>
<!ELEMENT other_address_line_1 (#PCDATA)>
<!ELEMENT other_address_line_2 (#PCDATA)>
<!ELEMENT other_address_line_3 (#PCDATA)>
<!ELEMENT other_postcode (#PCDATA)>
