mod users;

mod patients;
mod clinicians;
mod modified_early_warning_scores;
mod modified_early_warning_score_grades;
mod modified_early_warning_score_grade_rules;
mod modified_early_warning_score_grade_flags;