<!ELEMENT neurodiversity_adjustment_review (id,created_at,updated_at,deleted_at,worker_id,manager_id,review_status,response_reference,review_method,review_date,next_review_date,effectiveness_working_environment,effectiveness_equipment_technology,effectiveness_working_arrangements,effectiveness_communication,effectiveness_support_mentoring,effectiveness_recruitment_process,effectiveness_policy_dress,effectiveness_other,worker_feedback,worker_satisfied,wellbeing_change,barriers_detail,changes_needed,changes_detail,updated_adjustments_detail,occupational_health_rereferral,escalated,escalation_detail,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT worker_id (#PCDATA)>
<!ELEMENT manager_id (#PCDATA)>
<!ELEMENT review_status (#PCDATA)>
<!ELEMENT response_reference (#PCDATA)>
<!ELEMENT review_method (#PCDATA)>
<!ELEMENT review_date (#PCDATA)>
<!ELEMENT next_review_date (#PCDATA)>
<!ELEMENT effectiveness_working_environment (#PCDATA)>
<!ELEMENT effectiveness_equipment_technology (#PCDATA)>
<!ELEMENT effectiveness_working_arrangements (#PCDATA)>
<!ELEMENT effectiveness_communication (#PCDATA)>
<!ELEMENT effectiveness_support_mentoring (#PCDATA)>
<!ELEMENT effectiveness_recruitment_process (#PCDATA)>
<!ELEMENT effectiveness_policy_dress (#PCDATA)>
<!ELEMENT effectiveness_other (#PCDATA)>
<!ELEMENT worker_feedback (#PCDATA)>
<!ELEMENT worker_satisfied (#PCDATA)>
<!ELEMENT wellbeing_change (#PCDATA)>
<!ELEMENT barriers_detail (#PCDATA)>
<!ELEMENT changes_needed (#PCDATA)>
<!ELEMENT changes_detail (#PCDATA)>
<!ELEMENT updated_adjustments_detail (#PCDATA)>
<!ELEMENT occupational_health_rereferral (#PCDATA)>
<!ELEMENT escalated (#PCDATA)>
<!ELEMENT escalation_detail (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
