<!ELEMENT okr_objective (id,created_at,updated_at,deleted_at,reporter_id,parent_objective_id,status,level,cycle,cycle_start_date,cycle_end_date,team_or_org_name,strategic_theme,external_reference,obj_title,obj_long_description,sa_parent_summary,sa_business_value_statement,in_initiatives,in_supporting_links,rk_known_risks,rk_dependencies,rk_blockers,rk_mitigation_plans,fc_expected_end_state,fc_residual_risk,score_by_progress_percent,score_by_confidence_decile,score_by_stretch_tier,score_by_alignment_grade,score_by_impact_tier,score_by_smart_quality,score_by_pace_deviation_percent)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT reporter_id (#PCDATA)>
<!ELEMENT parent_objective_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT cycle (#PCDATA)>
<!ELEMENT cycle_start_date (#PCDATA)>
<!ELEMENT cycle_end_date (#PCDATA)>
<!ELEMENT team_or_org_name (#PCDATA)>
<!ELEMENT strategic_theme (#PCDATA)>
<!ELEMENT external_reference (#PCDATA)>
<!ELEMENT obj_title (#PCDATA)>
<!ELEMENT obj_long_description (#PCDATA)>
<!ELEMENT sa_parent_summary (#PCDATA)>
<!ELEMENT sa_business_value_statement (#PCDATA)>
<!ELEMENT in_initiatives (#PCDATA)>
<!ELEMENT in_supporting_links (#PCDATA)>
<!ELEMENT rk_known_risks (#PCDATA)>
<!ELEMENT rk_dependencies (#PCDATA)>
<!ELEMENT rk_blockers (#PCDATA)>
<!ELEMENT rk_mitigation_plans (#PCDATA)>
<!ELEMENT fc_expected_end_state (#PCDATA)>
<!ELEMENT fc_residual_risk (#PCDATA)>
<!ELEMENT score_by_progress_percent (#PCDATA)>
<!ELEMENT score_by_confidence_decile (#PCDATA)>
<!ELEMENT score_by_stretch_tier (#PCDATA)>
<!ELEMENT score_by_alignment_grade (#PCDATA)>
<!ELEMENT score_by_impact_tier (#PCDATA)>
<!ELEMENT score_by_smart_quality (#PCDATA)>
<!ELEMENT score_by_pace_deviation_percent (#PCDATA)>
