mod users;

mod patients;
mod practitioners;
mod paediatrics_waiting_list_cards;
mod paediatrics_waiting_list_card_appointments;
mod paediatrics_waiting_list_card_grades;
mod paediatrics_waiting_list_card_grade_rules;
mod paediatrics_waiting_list_card_grade_flags;