mod users;

mod patients;
mod practitioners;
mod occ_med_waiting_list_cards;
mod occ_med_waiting_list_card_appointments;
mod occ_med_waiting_list_card_grades;
mod occ_med_waiting_list_card_grade_rules;
mod occ_med_waiting_list_card_grade_flags;