<!ELEMENT pulmonary_embolism_rule_out_criteria_grade_rule (id,created_at,updated_at,deleted_at,pulmonary_embolism_rule_out_criteria_grade_id,rule_id,instrument,satisfied,outcome,category,description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT pulmonary_embolism_rule_out_criteria_grade_id (#PCDATA)>
<!ELEMENT rule_id (#PCDATA)>
<!ELEMENT instrument (#PCDATA)>
<!ELEMENT satisfied (#PCDATA)>
<!ELEMENT outcome (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT description (#PCDATA)>
