<!ELEMENT perioperative_optimization_grade_domain (id,created_at,updated_at,deleted_at,perioperative_optimization_grade_id,domain,status,triggered,lead_time_weeks,weeks_shortfall,rule_id,finding,intervention,intervention_started,referral_made,target_value,start_date)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT perioperative_optimization_grade_id (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT triggered (#PCDATA)>
<!ELEMENT lead_time_weeks (#PCDATA)>
<!ELEMENT weeks_shortfall (#PCDATA)>
<!ELEMENT rule_id (#PCDATA)>
<!ELEMENT finding (#PCDATA)>
<!ELEMENT intervention (#PCDATA)>
<!ELEMENT intervention_started (#PCDATA)>
<!ELEMENT referral_made (#PCDATA)>
<!ELEMENT target_value (#PCDATA)>
<!ELEMENT start_date (#PCDATA)>
