<!ELEMENT perioperative_optimization_grade (id,created_at,updated_at,deleted_at,perioperative_optimization_id,weeks_to_surgery,gating_applied,must_score,must_risk,audit_c_score,stop_bang_score,duke_activity_status_index,clinical_frailty_scale,fried_phenotype_score,fried_frailty_category,domains_optimized,domains_in_progress,domains_action_required,domains_insufficient_time,computed_readiness,final_readiness,override_reason,gate_decision,recommended_earliest_surgery_date,clinician_notes,signed_by_name,signed_at,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT perioperative_optimization_id (#PCDATA)>
<!ELEMENT weeks_to_surgery (#PCDATA)>
<!ELEMENT gating_applied (#PCDATA)>
<!ELEMENT must_score (#PCDATA)>
<!ELEMENT must_risk (#PCDATA)>
<!ELEMENT audit_c_score (#PCDATA)>
<!ELEMENT stop_bang_score (#PCDATA)>
<!ELEMENT duke_activity_status_index (#PCDATA)>
<!ELEMENT clinical_frailty_scale (#PCDATA)>
<!ELEMENT fried_phenotype_score (#PCDATA)>
<!ELEMENT fried_frailty_category (#PCDATA)>
<!ELEMENT domains_optimized (#PCDATA)>
<!ELEMENT domains_in_progress (#PCDATA)>
<!ELEMENT domains_action_required (#PCDATA)>
<!ELEMENT domains_insufficient_time (#PCDATA)>
<!ELEMENT computed_readiness (#PCDATA)>
<!ELEMENT final_readiness (#PCDATA)>
<!ELEMENT override_reason (#PCDATA)>
<!ELEMENT gate_decision (#PCDATA)>
<!ELEMENT recommended_earliest_surgery_date (#PCDATA)>
<!ELEMENT clinician_notes (#PCDATA)>
<!ELEMENT signed_by_name (#PCDATA)>
<!ELEMENT signed_at (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
