pub mod _entities;
pub mod users;
pub mod patients;
pub mod clinicians;
pub mod caprini_venous_thromboembolism_risk_assessments;
pub mod caprini_venous_thromboembolism_risk_assessment_grades;
pub mod caprini_venous_thromboembolism_risk_assessment_grade_rules;
pub mod caprini_venous_thromboembolism_risk_assessment_grade_flags;
