<!ELEMENT diabetes_eye_screening_grade (id,created_at,updated_at,deleted_at,diabetes_eye_screening_id,worst_retinopathy,worst_maculopathy,any_ungradable,outcome,referral,recall_interval_months,status,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT diabetes_eye_screening_id (#PCDATA)>
<!ELEMENT worst_retinopathy (#PCDATA)>
<!ELEMENT worst_maculopathy (#PCDATA)>
<!ELEMENT any_ungradable (#PCDATA)>
<!ELEMENT outcome (#PCDATA)>
<!ELEMENT referral (#PCDATA)>
<!ELEMENT recall_interval_months (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
