<!ELEMENT patient (id,created_at,updated_at,deleted_at,name,birth_date,sex_at_birth,nationality_as_iso_3166_1_alpha_2,passport_number,united_kingdom_nhs_number,national_health_id,email,phone,postal_address_as_full_text,country_as_iso_3166_1_alpha_2,postcode,emergency_contact_name,emergency_contact_relationship,emergency_contact_phone,weight_as_kg,height_as_cm)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT birth_date (#PCDATA)>
<!ELEMENT sex_at_birth (#PCDATA)>
<!ELEMENT nationality_as_iso_3166_1_alpha_2 (#PCDATA)>
<!ELEMENT passport_number (#PCDATA)>
<!ELEMENT united_kingdom_nhs_number (#PCDATA)>
<!ELEMENT national_health_id (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT postal_address_as_full_text (#PCDATA)>
<!ELEMENT country_as_iso_3166_1_alpha_2 (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT emergency_contact_name (#PCDATA)>
<!ELEMENT emergency_contact_relationship (#PCDATA)>
<!ELEMENT emergency_contact_phone (#PCDATA)>
<!ELEMENT weight_as_kg (#PCDATA)>
<!ELEMENT height_as_cm (#PCDATA)>
