-- schema.sql
-- Combined schema for form: meeting
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (14):
--   - 00_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_organizer.sql
--   - 03_create_table_meeting.sql
--   - 04_create_table_agenda_item.sql
--   - 05_create_table_participant.sql
--   - 06_create_table_resource.sql
--   - 07_create_table_recurring_rule.sql
--   - 08_create_table_action_item.sql
--   - 09_create_table_meeting_output.sql
--   - 10_create_table_meeting_outcome.sql
--   - 11_create_table_meeting_grade.sql
--   - 12_create_table_meeting_grade_rule.sql
--   - 13_create_table_meeting_grade_flag.sql


-- ========================================================================
-- BEGIN 00_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram indexes used for free-text search across the
-- meeting title, summary, agenda items, and action item descriptions.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_organizer.sql
-- ========================================================================

-- Organizer is the person who schedules a meeting and signs the record.
-- One organizer may run many meetings; the analogue of "patient" in a
-- clinical assessment.

CREATE TABLE organizer (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL DEFAULT '',
    email VARCHAR(320) NOT NULL DEFAULT '',
    phone VARCHAR(64) NOT NULL DEFAULT '',
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN (
        'organizer', 'secretary', 'chair', 'facilitator',
        'project-manager', 'scrum-master', 'assistant',
        'team-lead', 'executive', 'clinician', 'other', ''
    )),
    organisation VARCHAR(255) NOT NULL DEFAULT '',
    team VARCHAR(255) NOT NULL DEFAULT '',
    location VARCHAR(255) NOT NULL DEFAULT '',
    timezone VARCHAR(64) NOT NULL DEFAULT '',
    preferred_contact VARCHAR(20) NOT NULL DEFAULT '' CHECK (preferred_contact IN (
        'email', 'phone', 'chat', 'in-person', ''
    ))
);

CREATE TRIGGER trigger_organizer_updated_at
    BEFORE UPDATE ON organizer
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE organizer IS
    'Person who schedules a meeting and signs the record. The analogue of patient in a clinical form: the subject of the assessment is the meeting itself, but the organizer is the human who scheduled it.';
COMMENT ON COLUMN organizer.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN organizer.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN organizer.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN organizer.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN organizer.name IS
    'Organizer full name.';
COMMENT ON COLUMN organizer.email IS
    'Organizer email address.';
COMMENT ON COLUMN organizer.phone IS
    'Organizer phone number.';
COMMENT ON COLUMN organizer.role IS
    'Organizer role: organizer, secretary, chair, facilitator, project-manager, scrum-master, etc.';
COMMENT ON COLUMN organizer.organisation IS
    'Organisation, company, or trust the organizer belongs to.';
COMMENT ON COLUMN organizer.team IS
    'Team or department within the organisation.';
COMMENT ON COLUMN organizer.location IS
    'Physical or virtual base location of the organizer.';
COMMENT ON COLUMN organizer.timezone IS
    'IANA timezone identifier (e.g. Europe/London).';
COMMENT ON COLUMN organizer.preferred_contact IS
    'Preferred contact channel: email, phone, chat, or in-person.';

CREATE INDEX organizer_index_name_trgm
    ON organizer
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_organizer.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_meeting.sql
-- ========================================================================

-- The main meeting record. Holds the invitation, plan-side metadata, and
-- the 250-character results summary. Child tables carry the variable-length
-- collections (agenda_item, participant, resource, recurring_rule,
-- action_item, meeting_output, meeting_outcome).

CREATE TABLE meeting (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    organizer_id UUID NOT NULL REFERENCES organizer(id) ON DELETE CASCADE,

    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'scheduled', 'in-progress', 'completed', 'cancelled', 'no-show')),

    title VARCHAR(255) NOT NULL DEFAULT '',
    purpose VARCHAR(500) NOT NULL DEFAULT '',
    long_description TEXT NOT NULL DEFAULT '',
    category VARCHAR(40) NOT NULL DEFAULT ''
        CHECK (category IN (
            'stand-up', 'review', 'planning', 'retrospective',
            'training', 'one-to-one', 'interview', 'governance',
            'multidisciplinary-team', 'social', 'kickoff',
            'all-hands', 'workshop', 'demo', 'other', ''
        )),
    visibility VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (visibility IN ('public', 'internal', 'confidential', 'restricted', '')),

    -- Invitation
    scheduled_start_at TIMESTAMPTZ,
    scheduled_end_at TIMESTAMPTZ,
    timezone VARCHAR(64) NOT NULL DEFAULT '',
    location VARCHAR(255) NOT NULL DEFAULT '',
    video_url VARCHAR(500) NOT NULL DEFAULT '',
    phone_number VARCHAR(64) NOT NULL DEFAULT '',
    dial_in_code VARCHAR(64) NOT NULL DEFAULT '',
    joining_instructions TEXT NOT NULL DEFAULT '',
    calendar_uid VARCHAR(255) NOT NULL DEFAULT '',

    -- Results: summary capped at 250 characters per the seed
    summary VARCHAR(250) NOT NULL DEFAULT ''
        CHECK (char_length(summary) <= 250),

    -- Sign-off
    actual_start_at TIMESTAMPTZ,
    actual_end_at TIMESTAMPTZ,
    overall_result VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (overall_result IN ('productive', 'partial', 'unproductive', 'cancelled', '')),
    additional_notes TEXT NOT NULL DEFAULT '',
    signed_by_name VARCHAR(255) NOT NULL DEFAULT '',
    signed_at TIMESTAMPTZ
);

CREATE TRIGGER trigger_meeting_updated_at
    BEFORE UPDATE ON meeting
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE meeting IS
    'A meeting record captured via a 10-step single-page wizard. Holds the invitation metadata, the 250-character summary, and the sign-off. Variable-length collections live in child tables.';
COMMENT ON COLUMN meeting.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN meeting.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN meeting.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN meeting.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN meeting.organizer_id IS
    'Foreign key to the organizer who scheduled the meeting.';
COMMENT ON COLUMN meeting.status IS
    'Lifecycle status: draft, scheduled, in-progress, completed, cancelled, no-show.';
COMMENT ON COLUMN meeting.title IS
    'Meeting title shown in calendar invites and dashboards.';
COMMENT ON COLUMN meeting.purpose IS
    'One-sentence purpose statement.';
COMMENT ON COLUMN meeting.long_description IS
    'Free-text long description of the meeting context.';
COMMENT ON COLUMN meeting.category IS
    'Meeting category: stand-up, review, planning, retrospective, training, one-to-one, interview, governance, multidisciplinary-team, social, kickoff, all-hands, workshop, demo, other.';
COMMENT ON COLUMN meeting.visibility IS
    'Information classification: public, internal, confidential, restricted.';
COMMENT ON COLUMN meeting.scheduled_start_at IS
    'Scheduled start timestamp (UTC).';
COMMENT ON COLUMN meeting.scheduled_end_at IS
    'Scheduled end timestamp (UTC).';
COMMENT ON COLUMN meeting.timezone IS
    'IANA timezone identifier the meeting is presented in (e.g. Europe/London).';
COMMENT ON COLUMN meeting.location IS
    'Physical location, room name, or address.';
COMMENT ON COLUMN meeting.video_url IS
    'Video conference URL (Zoom, Teams, Google Meet, Whereby, etc.).';
COMMENT ON COLUMN meeting.phone_number IS
    'Dial-in phone number for audio attendees.';
COMMENT ON COLUMN meeting.dial_in_code IS
    'Dial-in PIN or meeting code for audio attendees.';
COMMENT ON COLUMN meeting.joining_instructions IS
    'Free-text joining instructions — e.g. parking, lobby access, breakout-room links.';
COMMENT ON COLUMN meeting.calendar_uid IS
    'External calendar UID used when round-tripping with iCalendar / Google Calendar / Outlook.';
COMMENT ON COLUMN meeting.summary IS
    'Results section: single paragraph summary, hard-capped at 250 characters per the form specification.';
COMMENT ON COLUMN meeting.actual_start_at IS
    'Actual start timestamp recorded after the meeting.';
COMMENT ON COLUMN meeting.actual_end_at IS
    'Actual end timestamp recorded after the meeting.';
COMMENT ON COLUMN meeting.overall_result IS
    'Sign-off result: productive, partial, unproductive, cancelled.';
COMMENT ON COLUMN meeting.additional_notes IS
    'Free-text additional notes from the organizer at sign-off.';
COMMENT ON COLUMN meeting.signed_by_name IS
    'Name of the person who signed the record.';
COMMENT ON COLUMN meeting.signed_at IS
    'Timestamp the record was signed.';

CREATE INDEX meeting_index_organizer_id
    ON meeting(organizer_id);
CREATE INDEX meeting_index_status
    ON meeting(status);
CREATE INDEX meeting_index_scheduled_start_at
    ON meeting(scheduled_start_at);
CREATE INDEX meeting_index_title_trgm
    ON meeting
    USING GIN (title gin_trgm_ops);
CREATE INDEX meeting_index_summary_trgm
    ON meeting
    USING GIN (summary gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_meeting.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_agenda_item.sql
-- ========================================================================

-- Agenda item — one row per topic on the meeting agenda. Ordered by
-- position to preserve the order the organizer entered.

CREATE TABLE agenda_item (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_id UUID NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0
        CHECK (position >= 0),
    title VARCHAR(255) NOT NULL DEFAULT '',
    duration_minutes INTEGER
        CHECK (duration_minutes IS NULL OR duration_minutes BETWEEN 0 AND 1440),
    presenter VARCHAR(255) NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (status IN ('planned', 'discussed', 'skipped', 'deferred', ''))
);

CREATE TRIGGER trigger_agenda_item_updated_at
    BEFORE UPDATE ON agenda_item
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE agenda_item IS
    'One topic on the meeting agenda. Ordered by position. Captures presenter, planned duration, and free-text notes.';
COMMENT ON COLUMN agenda_item.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN agenda_item.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN agenda_item.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN agenda_item.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN agenda_item.meeting_id IS
    'Foreign key to the parent meeting.';
COMMENT ON COLUMN agenda_item.position IS
    'Zero-based ordinal of the item in the agenda list.';
COMMENT ON COLUMN agenda_item.title IS
    'Title of the agenda topic.';
COMMENT ON COLUMN agenda_item.duration_minutes IS
    'Planned duration in minutes (0 to 1440).';
COMMENT ON COLUMN agenda_item.presenter IS
    'Name of the person presenting or leading the discussion.';
COMMENT ON COLUMN agenda_item.notes IS
    'Free-text notes attached to the agenda item.';
COMMENT ON COLUMN agenda_item.status IS
    'Outcome of the agenda item: planned, discussed, skipped, deferred.';

CREATE INDEX agenda_item_index_meeting_id
    ON agenda_item(meeting_id);
CREATE INDEX agenda_item_index_meeting_id_position
    ON agenda_item(meeting_id, position);

-- ========================================================================
-- END 04_create_table_agenda_item.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_participant.sql
-- ========================================================================

-- Participant — one row per invited attendee. Captures role on the
-- invitation, response status, and actual attendance.

CREATE TABLE participant (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_id UUID NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0
        CHECK (position >= 0),
    name VARCHAR(255) NOT NULL DEFAULT '',
    email VARCHAR(320) NOT NULL DEFAULT '',
    organisation VARCHAR(255) NOT NULL DEFAULT '',
    role VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (role IN ('organizer', 'chair', 'required', 'optional', 'observer', 'presenter', 'note-taker', '')),
    response_status VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (response_status IN ('no-response', 'accepted', 'declined', 'tentative', 'delegated', '')),
    attendance_status VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (attendance_status IN ('present', 'late', 'absent', 'partial', 'remote', 'unknown', '')),
    notes TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_participant_updated_at
    BEFORE UPDATE ON participant
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE participant IS
    'One invited attendee for a meeting. Captures role on the invitation (required/optional/observer), the RSVP response, and the actual attendance status.';
COMMENT ON COLUMN participant.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN participant.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN participant.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN participant.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN participant.meeting_id IS
    'Foreign key to the parent meeting.';
COMMENT ON COLUMN participant.position IS
    'Zero-based ordinal of the participant in the invitation list.';
COMMENT ON COLUMN participant.name IS
    'Participant full name.';
COMMENT ON COLUMN participant.email IS
    'Participant email address.';
COMMENT ON COLUMN participant.organisation IS
    'Participant organisation or team.';
COMMENT ON COLUMN participant.role IS
    'Role on the invitation: organizer, chair, required, optional, observer, presenter, note-taker.';
COMMENT ON COLUMN participant.response_status IS
    'RSVP response: no-response, accepted, declined, tentative, delegated.';
COMMENT ON COLUMN participant.attendance_status IS
    'Actual attendance: present, late, absent, partial, remote, unknown.';
COMMENT ON COLUMN participant.notes IS
    'Free-text notes — apologies, delegated representative, partial attendance window.';

CREATE INDEX participant_index_meeting_id
    ON participant(meeting_id);
CREATE INDEX participant_index_meeting_id_position
    ON participant(meeting_id, position);
CREATE INDEX participant_index_email
    ON participant(email);

-- ========================================================================
-- END 05_create_table_participant.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_resource.sql
-- ========================================================================

-- Resource — anything required for the meeting to succeed: a room, a piece
-- of equipment, a document, a URL, a budget line, catering, an interpreter.

CREATE TABLE resource (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_id UUID NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0
        CHECK (position >= 0),
    resource_type VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (resource_type IN (
            'room', 'equipment', 'document', 'link', 'budget',
            'catering', 'interpreter', 'transport', 'other', ''
        )),
    name VARCHAR(255) NOT NULL DEFAULT '',
    quantity INTEGER
        CHECK (quantity IS NULL OR quantity >= 0),
    unit VARCHAR(40) NOT NULL DEFAULT '',
    url VARCHAR(500) NOT NULL DEFAULT '',
    cost_amount NUMERIC(12, 2)
        CHECK (cost_amount IS NULL OR cost_amount >= 0),
    cost_currency VARCHAR(3) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (status IN ('requested', 'reserved', 'confirmed', 'unavailable', 'cancelled', '')),
    notes TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_resource_updated_at
    BEFORE UPDATE ON resource
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE resource IS
    'A resource required for the meeting: room, equipment, document, link, budget line, catering, interpreter, transport. Tracks quantity, cost, reservation status.';
COMMENT ON COLUMN resource.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN resource.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN resource.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN resource.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN resource.meeting_id IS
    'Foreign key to the parent meeting.';
COMMENT ON COLUMN resource.position IS
    'Zero-based ordinal of the resource in the list.';
COMMENT ON COLUMN resource.resource_type IS
    'Type of resource: room, equipment, document, link, budget, catering, interpreter, transport, other.';
COMMENT ON COLUMN resource.name IS
    'Name or short identifier of the resource.';
COMMENT ON COLUMN resource.quantity IS
    'Quantity required (e.g. 12 chairs, 1 projector).';
COMMENT ON COLUMN resource.unit IS
    'Unit of quantity (e.g. seats, licences, GBP, USD).';
COMMENT ON COLUMN resource.url IS
    'URL of the resource (document link, room booking page, equipment record).';
COMMENT ON COLUMN resource.cost_amount IS
    'Cost amount in the cost_currency.';
COMMENT ON COLUMN resource.cost_currency IS
    'ISO 4217 currency code (e.g. GBP, USD, EUR).';
COMMENT ON COLUMN resource.status IS
    'Reservation status: requested, reserved, confirmed, unavailable, cancelled.';
COMMENT ON COLUMN resource.notes IS
    'Free-text notes — e.g. supplier, vendor, point of contact.';

CREATE INDEX resource_index_meeting_id
    ON resource(meeting_id);
CREATE INDEX resource_index_meeting_id_position
    ON resource(meeting_id, position);

-- ========================================================================
-- END 06_create_table_resource.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_recurring_rule.sql
-- ========================================================================

-- Recurring rule — at most one per meeting, modelled on RFC 5545 RRULE
-- but restricted to the seven frequencies a non-technical user is likely
-- to need (none / daily / weekday / weekly / monthly / quarterly / yearly).

CREATE TABLE recurring_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_id UUID NOT NULL UNIQUE REFERENCES meeting(id) ON DELETE CASCADE,

    frequency VARCHAR(20) NOT NULL DEFAULT 'none'
        CHECK (frequency IN ('none', 'daily', 'weekday', 'weekly', 'monthly', 'quarterly', 'yearly')),
    interval_count INTEGER NOT NULL DEFAULT 1
        CHECK (interval_count >= 1),

    by_day_of_week VARCHAR(40) NOT NULL DEFAULT ''
        CHECK (by_day_of_week ~ '^(|((MO|TU|WE|TH|FR|SA|SU)(,(MO|TU|WE|TH|FR|SA|SU))*))$'),
    by_day_of_month INTEGER
        CHECK (by_day_of_month IS NULL OR by_day_of_month BETWEEN -31 AND 31),
    by_set_position INTEGER
        CHECK (by_set_position IS NULL OR by_set_position BETWEEN -4 AND 4),
    by_month_of_year INTEGER
        CHECK (by_month_of_year IS NULL OR by_month_of_year BETWEEN 1 AND 12),

    series_count INTEGER
        CHECK (series_count IS NULL OR series_count >= 1),
    series_until TIMESTAMPTZ,

    timezone VARCHAR(64) NOT NULL DEFAULT '',
    rrule_text VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_recurring_rule_updated_at
    BEFORE UPDATE ON recurring_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE recurring_rule IS
    'Optional recurrence rule for a meeting, modelled on RFC 5545 RRULE but restricted to the seven frequencies a non-technical user is likely to need.';
COMMENT ON COLUMN recurring_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN recurring_rule.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN recurring_rule.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN recurring_rule.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN recurring_rule.meeting_id IS
    'Foreign key to the parent meeting; UNIQUE so at most one rule per meeting.';
COMMENT ON COLUMN recurring_rule.frequency IS
    'Recurrence frequency: none, daily, weekday, weekly, monthly, quarterly, yearly.';
COMMENT ON COLUMN recurring_rule.interval_count IS
    'Interval between occurrences; e.g. interval_count = 2 with frequency = weekly means every fortnight.';
COMMENT ON COLUMN recurring_rule.by_day_of_week IS
    'Comma-separated iCalendar weekday codes (MO,TU,WE,TH,FR,SA,SU). Empty when not constrained.';
COMMENT ON COLUMN recurring_rule.by_day_of_month IS
    'Day of month for monthly / quarterly / yearly rules. Negative values count from the end (-1 = last day).';
COMMENT ON COLUMN recurring_rule.by_set_position IS
    'Set position for the "nth weekday" pattern (e.g. by_set_position = 1, by_day_of_week = MO means first Monday).';
COMMENT ON COLUMN recurring_rule.by_month_of_year IS
    'Month of year for yearly rules (1 = January, 12 = December).';
COMMENT ON COLUMN recurring_rule.series_count IS
    'Total number of occurrences in the series, if known.';
COMMENT ON COLUMN recurring_rule.series_until IS
    'Last possible occurrence in the series, exclusive.';
COMMENT ON COLUMN recurring_rule.timezone IS
    'IANA timezone the rule is evaluated in.';
COMMENT ON COLUMN recurring_rule.rrule_text IS
    'Full RFC 5545 RRULE string for verbatim round-trip with iCalendar clients.';

CREATE INDEX recurring_rule_index_meeting_id
    ON recurring_rule(meeting_id);

-- ========================================================================
-- END 07_create_table_recurring_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 08_create_table_action_item.sql
-- ========================================================================

-- Action item — task assigned to an owner during the meeting with a due
-- date and a status. The dashboard surfaces overdue action items.

CREATE TABLE action_item (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_id UUID NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0
        CHECK (position >= 0),

    title VARCHAR(255) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    owner_name VARCHAR(255) NOT NULL DEFAULT '',
    owner_email VARCHAR(320) NOT NULL DEFAULT '',
    due_date DATE,
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', 'urgent', '')),
    status VARCHAR(20) NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'in-progress', 'blocked', 'done', 'cancelled')),
    completed_at TIMESTAMPTZ,
    external_reference VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_action_item_updated_at
    BEFORE UPDATE ON action_item
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE action_item IS
    'A task assigned during the meeting to a named owner with a due date, priority, and status.';
COMMENT ON COLUMN action_item.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN action_item.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN action_item.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN action_item.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN action_item.meeting_id IS
    'Foreign key to the parent meeting.';
COMMENT ON COLUMN action_item.position IS
    'Zero-based ordinal of the action item in the list.';
COMMENT ON COLUMN action_item.title IS
    'Short imperative title of the action.';
COMMENT ON COLUMN action_item.description IS
    'Free-text description, acceptance criteria, or context for the action.';
COMMENT ON COLUMN action_item.owner_name IS
    'Name of the person responsible for completing the action.';
COMMENT ON COLUMN action_item.owner_email IS
    'Email address of the owner for follow-up.';
COMMENT ON COLUMN action_item.due_date IS
    'Date by which the action should be completed.';
COMMENT ON COLUMN action_item.priority IS
    'Priority: low, medium, high, urgent.';
COMMENT ON COLUMN action_item.status IS
    'Workflow status: open, in-progress, blocked, done, cancelled.';
COMMENT ON COLUMN action_item.completed_at IS
    'Timestamp the action was marked done.';
COMMENT ON COLUMN action_item.external_reference IS
    'External ticket or issue reference (e.g. JIRA-1234, GH-456).';

CREATE INDEX action_item_index_meeting_id
    ON action_item(meeting_id);
CREATE INDEX action_item_index_meeting_id_position
    ON action_item(meeting_id, position);
CREATE INDEX action_item_index_due_date
    ON action_item(due_date);
CREATE INDEX action_item_index_status
    ON action_item(status);

-- ========================================================================
-- END 08_create_table_action_item.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 09_create_table_meeting_output.sql
-- ========================================================================

-- Meeting output — a tangible deliverable produced by the meeting:
-- a document, a decision, a piece of data, a recording.

CREATE TABLE meeting_output (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_id UUID NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0
        CHECK (position >= 0),

    title VARCHAR(255) NOT NULL DEFAULT '',
    kind VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (kind IN ('document', 'decision', 'data', 'recording', 'minutes', 'slides', 'agreement', 'other', '')),
    url VARCHAR(500) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    owner_name VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_meeting_output_updated_at
    BEFORE UPDATE ON meeting_output
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE meeting_output IS
    'A tangible deliverable produced by the meeting: document, decision, data, recording, minutes, slides, agreement.';
COMMENT ON COLUMN meeting_output.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN meeting_output.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN meeting_output.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN meeting_output.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN meeting_output.meeting_id IS
    'Foreign key to the parent meeting.';
COMMENT ON COLUMN meeting_output.position IS
    'Zero-based ordinal of the output in the list.';
COMMENT ON COLUMN meeting_output.title IS
    'Short title of the output.';
COMMENT ON COLUMN meeting_output.kind IS
    'Kind of output: document, decision, data, recording, minutes, slides, agreement, other.';
COMMENT ON COLUMN meeting_output.url IS
    'URL of the output artefact, if any (document, recording, repository).';
COMMENT ON COLUMN meeting_output.description IS
    'Free-text description of the output and its content.';
COMMENT ON COLUMN meeting_output.owner_name IS
    'Person responsible for the output post-meeting.';

CREATE INDEX meeting_output_index_meeting_id
    ON meeting_output(meeting_id);
CREATE INDEX meeting_output_index_meeting_id_position
    ON meeting_output(meeting_id, position);

-- ========================================================================
-- END 09_create_table_meeting_output.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 10_create_table_meeting_outcome.sql
-- ========================================================================

-- Meeting outcome — the impact or change that results from the meeting:
-- goal reached, risk identified, alignment achieved, decision recorded.
-- Distinct from meeting_output: outputs are *things*, outcomes are *changes*.

CREATE TABLE meeting_outcome (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_id UUID NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0
        CHECK (position >= 0),

    title VARCHAR(255) NOT NULL DEFAULT '',
    category VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (category IN (
            'goal-reached', 'risk-identified', 'risk-mitigated',
            'alignment-achieved', 'decision', 'blocker-cleared',
            'blocker-raised', 'commitment', 'no-outcome', 'other', ''
        )),
    description TEXT NOT NULL DEFAULT '',
    impact VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (impact IN ('low', 'medium', 'high', 'strategic', '')),
    related_action_item_id UUID REFERENCES action_item(id) ON DELETE SET NULL
);

CREATE TRIGGER trigger_meeting_outcome_updated_at
    BEFORE UPDATE ON meeting_outcome
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE meeting_outcome IS
    'The impact or change resulting from the meeting: goal reached, risk identified, alignment achieved, decision recorded. Distinct from meeting_output: outputs are things, outcomes are changes.';
COMMENT ON COLUMN meeting_outcome.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN meeting_outcome.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN meeting_outcome.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN meeting_outcome.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN meeting_outcome.meeting_id IS
    'Foreign key to the parent meeting.';
COMMENT ON COLUMN meeting_outcome.position IS
    'Zero-based ordinal of the outcome in the list.';
COMMENT ON COLUMN meeting_outcome.title IS
    'Short title summarising the outcome.';
COMMENT ON COLUMN meeting_outcome.category IS
    'Outcome category: goal-reached, risk-identified, risk-mitigated, alignment-achieved, decision, blocker-cleared, blocker-raised, commitment, no-outcome, other.';
COMMENT ON COLUMN meeting_outcome.description IS
    'Free-text description of the outcome.';
COMMENT ON COLUMN meeting_outcome.impact IS
    'Subjective impact rating: low, medium, high, strategic.';
COMMENT ON COLUMN meeting_outcome.related_action_item_id IS
    'Optional foreign key to an action_item that captures the follow-up needed for this outcome.';

CREATE INDEX meeting_outcome_index_meeting_id
    ON meeting_outcome(meeting_id);
CREATE INDEX meeting_outcome_index_meeting_id_position
    ON meeting_outcome(meeting_id, position);

-- ========================================================================
-- END 10_create_table_meeting_outcome.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 11_create_table_meeting_grade.sql
-- ========================================================================

-- Computed and signed-off validation result for a meeting. Stores the
-- derived counts and completion status produced by validateMeeting(),
-- plus the organiser's sign-off.

CREATE TABLE meeting_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_id UUID NOT NULL UNIQUE
        REFERENCES meeting(id) ON DELETE CASCADE,

    duration_minutes INTEGER
        CHECK (duration_minutes IS NULL OR duration_minutes BETWEEN 0 AND 1440),
    agenda_item_count INTEGER NOT NULL DEFAULT 0
        CHECK (agenda_item_count >= 0),
    participant_count INTEGER NOT NULL DEFAULT 0
        CHECK (participant_count >= 0),
    accepted_count INTEGER NOT NULL DEFAULT 0
        CHECK (accepted_count >= 0),
    declined_count INTEGER NOT NULL DEFAULT 0
        CHECK (declined_count >= 0),
    attended_count INTEGER NOT NULL DEFAULT 0
        CHECK (attended_count >= 0),
    action_item_count INTEGER NOT NULL DEFAULT 0
        CHECK (action_item_count >= 0),
    output_count INTEGER NOT NULL DEFAULT 0
        CHECK (output_count >= 0),
    outcome_count INTEGER NOT NULL DEFAULT 0
        CHECK (outcome_count >= 0),

    completion_status VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (completion_status IN ('planned', 'in-progress', 'complete', 'incomplete', '')),
    overall_health VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (overall_health IN ('green', 'amber', 'red', '')),

    override_reason VARCHAR(500) NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',

    signed_by VARCHAR(255) NOT NULL DEFAULT '',
    signed_at TIMESTAMPTZ,
    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_meeting_grade_updated_at
    BEFORE UPDATE ON meeting_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE meeting_grade IS
    'Computed and signed-off validation result for a meeting. One-to-one with meeting. Stores the derived counts and completion status from validateMeeting() plus the organiser sign-off.';
COMMENT ON COLUMN meeting_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN meeting_grade.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN meeting_grade.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN meeting_grade.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN meeting_grade.meeting_id IS
    'Foreign key to the parent meeting row (unique, 1:1).';
COMMENT ON COLUMN meeting_grade.duration_minutes IS
    'Derived duration in minutes from actual_start_at to actual_end_at, or scheduled fallback.';
COMMENT ON COLUMN meeting_grade.agenda_item_count IS
    'Derived count of agenda_item rows.';
COMMENT ON COLUMN meeting_grade.participant_count IS
    'Derived count of participant rows.';
COMMENT ON COLUMN meeting_grade.accepted_count IS
    'Derived count of participants with response_status = accepted.';
COMMENT ON COLUMN meeting_grade.declined_count IS
    'Derived count of participants with response_status = declined.';
COMMENT ON COLUMN meeting_grade.attended_count IS
    'Derived count of participants with attendance_status = present or late or remote.';
COMMENT ON COLUMN meeting_grade.action_item_count IS
    'Derived count of action_item rows.';
COMMENT ON COLUMN meeting_grade.output_count IS
    'Derived count of meeting_output rows.';
COMMENT ON COLUMN meeting_grade.outcome_count IS
    'Derived count of meeting_outcome rows.';
COMMENT ON COLUMN meeting_grade.completion_status IS
    'Completion status derived by validateMeeting: planned, in-progress, complete, incomplete.';
COMMENT ON COLUMN meeting_grade.overall_health IS
    'Overall health: green (no flags), amber (low/medium flags), red (high-priority flag fired).';
COMMENT ON COLUMN meeting_grade.override_reason IS
    'Reason the organiser overrode the engine-computed completion status, if any.';
COMMENT ON COLUMN meeting_grade.notes IS
    'Free-text organiser sign-off notes.';
COMMENT ON COLUMN meeting_grade.signed_by IS
    'Name or identifier of the organiser who signed off.';
COMMENT ON COLUMN meeting_grade.signed_at IS
    'Timestamp of the organiser electronic signature.';
COMMENT ON COLUMN meeting_grade.graded_at IS
    'Timestamp when the engine last computed the result.';

CREATE INDEX meeting_grade_index_meeting_id
    ON meeting_grade(meeting_id);

-- ========================================================================
-- END 11_create_table_meeting_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 12_create_table_meeting_grade_rule.sql
-- ========================================================================

-- Audit trail of every validation rule that fired for this meeting.

CREATE TABLE meeting_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_grade_id UUID NOT NULL
        REFERENCES meeting_grade(id) ON DELETE CASCADE,
    rule_id VARCHAR(50) NOT NULL DEFAULT '',
    instrument VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (instrument IN (
            'invitation', 'agenda', 'participants', 'resources',
            'recurrence', 'summary', 'action-items', 'outputs',
            'outcomes', 'composite', ''
        )),
    grade VARCHAR(10) NOT NULL DEFAULT '',
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX index_meeting_grade_rule_grade_id
    ON meeting_grade_rule(meeting_grade_id);

CREATE TRIGGER trigger_meeting_grade_rule_updated_at
    BEFORE UPDATE ON meeting_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE meeting_grade_rule IS
    'Audit trail of every validation rule that fired for this meeting, across the validation instruments (invitation, agenda, participants, resources, recurrence, summary, action-items, outputs, outcomes, composite).';
COMMENT ON COLUMN meeting_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN meeting_grade_rule.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN meeting_grade_rule.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN meeting_grade_rule.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN meeting_grade_rule.meeting_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN meeting_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-SUMMARY-OVER-LIMIT, R-NO-AGENDA).';
COMMENT ON COLUMN meeting_grade_rule.instrument IS
    'Validation instrument the rule belongs to.';
COMMENT ON COLUMN meeting_grade_rule.grade IS
    'Grade contributed by this rule (e.g. red for blocking, amber for warning).';
COMMENT ON COLUMN meeting_grade_rule.category IS
    'Category for grouping rules in the report (e.g. data-quality, completeness, scheduling).';
COMMENT ON COLUMN meeting_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 12_create_table_meeting_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 13_create_table_meeting_grade_flag.sql
-- ========================================================================

-- Non-blocking validation flags that fire independently of the
-- completion status. Surfaced in the dashboard.

CREATE TABLE meeting_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    meeting_grade_id UUID NOT NULL
        REFERENCES meeting_grade(id) ON DELETE CASCADE,
    flag_id VARCHAR(50) NOT NULL DEFAULT '',
    category VARCHAR(50) NOT NULL DEFAULT ''
        CHECK (category IN (
            'summary-over-limit',
            'no-organizer',
            'no-participants',
            'no-agenda',
            'no-outcomes',
            'no-summary',
            'start-after-end',
            'recurring-without-until',
            'action-item-overdue',
            'low-acceptance-rate',
            'low-attendance-rate',
            'over-running',
            'conflicting-resource',
            'confidential-content',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX index_meeting_grade_flag_grade_id
    ON meeting_grade_flag(meeting_grade_id);

CREATE TRIGGER trigger_meeting_grade_flag_updated_at
    BEFORE UPDATE ON meeting_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE meeting_grade_flag IS
    'Non-blocking validation flags that fire independently of the completion status. Surfaced in the dashboard for the organiser to address.';
COMMENT ON COLUMN meeting_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN meeting_grade_flag.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN meeting_grade_flag.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN meeting_grade_flag.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN meeting_grade_flag.meeting_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN meeting_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-SUMMARY-OVER-LIMIT-001).';
COMMENT ON COLUMN meeting_grade_flag.category IS
    'Flag category: summary-over-limit, no-participants, no-agenda, start-after-end, etc.';
COMMENT ON COLUMN meeting_grade_flag.priority IS
    'Flag priority: low, medium, or high.';
COMMENT ON COLUMN meeting_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN meeting_grade_flag.suggested_action IS
    'Suggested action for the organiser (e.g. "shorten summary to 250 characters").';

-- ========================================================================
-- END 13_create_table_meeting_grade_flag.sql
-- ========================================================================
