<!ELEMENT meeting (id,created_at,updated_at,deleted_at,organizer_id,status,title,purpose,long_description,category,visibility,scheduled_start_at,scheduled_end_at,timezone,location,video_url,phone_number,dial_in_code,joining_instructions,calendar_uid,summary,actual_start_at,actual_end_at,overall_result,additional_notes,signed_by_name,signed_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT organizer_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT purpose (#PCDATA)>
<!ELEMENT long_description (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT visibility (#PCDATA)>
<!ELEMENT scheduled_start_at (#PCDATA)>
<!ELEMENT scheduled_end_at (#PCDATA)>
<!ELEMENT timezone (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT video_url (#PCDATA)>
<!ELEMENT phone_number (#PCDATA)>
<!ELEMENT dial_in_code (#PCDATA)>
<!ELEMENT joining_instructions (#PCDATA)>
<!ELEMENT calendar_uid (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT actual_start_at (#PCDATA)>
<!ELEMENT actual_end_at (#PCDATA)>
<!ELEMENT overall_result (#PCDATA)>
<!ELEMENT additional_notes (#PCDATA)>
<!ELEMENT signed_by_name (#PCDATA)>
<!ELEMENT signed_at (#PCDATA)>
