//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clinicians;
pub mod national_early_warning_score_2_grade_flags;
pub mod national_early_warning_score_2_grade_rules;
pub mod national_early_warning_score_2_grades;
pub mod national_early_warning_score_2s;
pub mod patients;
pub mod users;
