<!ELEMENT national_early_warning_score_2_grade (id,created_at,updated_at,deleted_at,national_early_warning_score_2_id,aggregate_score,respiratory_rate_score,spo2_score,oxygen_score,blood_pressure_score,pulse_score,consciousness_score,temperature_score,any_single_parameter_three,risk_band,monitoring_frequency,recommendation,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT national_early_warning_score_2_id (#PCDATA)>
<!ELEMENT aggregate_score (#PCDATA)>
<!ELEMENT respiratory_rate_score (#PCDATA)>
<!ELEMENT spo2_score (#PCDATA)>
<!ELEMENT oxygen_score (#PCDATA)>
<!ELEMENT blood_pressure_score (#PCDATA)>
<!ELEMENT pulse_score (#PCDATA)>
<!ELEMENT consciousness_score (#PCDATA)>
<!ELEMENT temperature_score (#PCDATA)>
<!ELEMENT any_single_parameter_three (#PCDATA)>
<!ELEMENT risk_band (#PCDATA)>
<!ELEMENT monitoring_frequency (#PCDATA)>
<!ELEMENT recommendation (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
