<!ELEMENT national_early_warning_score_2 (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,observation_at,ward_or_location,spo2_scale,spo2_scale2_endorsed,respiratory_rate,spo2,on_oxygen,oxygen_device,oxygen_flow_rate_l_min,inspired_oxygen_fraction_percent,systolic_blood_pressure,pulse,consciousness_acvpu,temperature,is_under_16,is_pregnant,has_spinal_cord_injury,clinical_notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT observation_at (#PCDATA)>
<!ELEMENT ward_or_location (#PCDATA)>
<!ELEMENT spo2_scale (#PCDATA)>
<!ELEMENT spo2_scale2_endorsed (#PCDATA)>
<!ELEMENT respiratory_rate (#PCDATA)>
<!ELEMENT spo2 (#PCDATA)>
<!ELEMENT on_oxygen (#PCDATA)>
<!ELEMENT oxygen_device (#PCDATA)>
<!ELEMENT oxygen_flow_rate_l_min (#PCDATA)>
<!ELEMENT inspired_oxygen_fraction_percent (#PCDATA)>
<!ELEMENT systolic_blood_pressure (#PCDATA)>
<!ELEMENT pulse (#PCDATA)>
<!ELEMENT consciousness_acvpu (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ELEMENT is_under_16 (#PCDATA)>
<!ELEMENT is_pregnant (#PCDATA)>
<!ELEMENT has_spinal_cord_injury (#PCDATA)>
<!ELEMENT clinical_notes (#PCDATA)>
