  

  // Sample FP92A applications for standalone development.
  export const SAMPLE_APPLICATIONS = [
    {
      certificateNumber: "FP92A-000123",
      patientName: "Margaret Hughes",
      nhsNumber: "943 476 5919",
      conditions: ["myxoedema"],
      outcome: "eligible",
      validFrom: "2025-09-12",
      validUntil: "2030-09-12",
      status: "issued",
    },
    {
      certificateNumber: "FP92A-000124",
      patientName: "James Patel",
      nhsNumber: "412 887 2210",
      conditions: ["diabetes-mellitus-not-diet-only"],
      outcome: "eligible",
      validFrom: "2025-10-04",
      validUntil: "2030-10-04",
      status: "posted",
    },
    {
      certificateNumber: "",
      patientName: "Aisha Khan",
      nhsNumber: "501 234 7782",
      conditions: ["diabetes-mellitus-not-diet-only"],
      outcome: "ineligible",
      validFrom: "",
      validUntil: "",
      status: "rejected",
    },
    {
      certificateNumber: "",
      patientName: "Sean O'Connor",
      nhsNumber: "667 113 0099",
      conditions: ["epilepsy-on-anticonvulsant", "myasthenia-gravis"],
      outcome: "eligible",
      validFrom: "2026-01-15",
      validUntil: "2031-01-15",
      status: "ready-to-post",
    },
    {
      certificateNumber: "",
      patientName: "Eleanor Davies",
      nhsNumber: "210 558 4476",
      conditions: ["cancer-or-effects"],
      outcome: "requires-clarification",
      validFrom: "",
      validUntil: "",
      status: "draft",
    },
    {
      certificateNumber: "FP92A-000098",
      patientName: "Robert Singh",
      nhsNumber: "330 119 6611",
      conditions: ["permanent-fistula"],
      outcome: "eligible",
      validFrom: "2020-04-22",
      validUntil: "2025-04-22",
      status: "expired",
    },
    {
      certificateNumber: "FP92A-000142",
      patientName: "Yusuf Ahmed",
      nhsNumber: "789 224 0017",
      conditions: ["hypoadrenalism"],
      outcome: "eligible",
      validFrom: "2026-02-09",
      validUntil: "2031-02-09",
      status: "issued",
    },
    {
      certificateNumber: "",
      patientName: "Catherine Lin",
      nhsNumber: "112 998 5512",
      conditions: ["continuing-physical-disability"],
      outcome: "eligible",
      validFrom: "2026-03-01",
      validUntil: "2031-03-01",
      status: "ready-to-post",
    },
  ];
