<!ELEMENT biopsy_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,biopsy_site,biopsy_method,laterality,primary_indication,clinical_question,relevant_history,lesion_description,imaging_guidance_required,taking_anticoagulant,anticoagulant_agent,taking_antiplatelet,antiplatelet_agent,inr,platelet_count,bleeding_disorder,immunosuppressed,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT biopsy_site (#PCDATA)>
<!ELEMENT biopsy_method (#PCDATA)>
<!ELEMENT laterality (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT lesion_description (#PCDATA)>
<!ELEMENT imaging_guidance_required (#PCDATA)>
<!ELEMENT taking_anticoagulant (#PCDATA)>
<!ELEMENT anticoagulant_agent (#PCDATA)>
<!ELEMENT taking_antiplatelet (#PCDATA)>
<!ELEMENT antiplatelet_agent (#PCDATA)>
<!ELEMENT inr (#PCDATA)>
<!ELEMENT platelet_count (#PCDATA)>
<!ELEMENT bleeding_disorder (#PCDATA)>
<!ELEMENT immunosuppressed (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
