<!ELEMENT application (id,created_at,updated_at,deleted_at,patient_id,practitioner_id,status,application_kind,previous_certificate_number,previous_certificate_expiry_date,completed_date,posted_date,received_by_nhsbsa_date,certificate_number,valid_from,valid_until,practitioner_signature_present,practitioner_declaration_text,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT practitioner_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT application_kind (#PCDATA)>
<!ELEMENT previous_certificate_number (#PCDATA)>
<!ELEMENT previous_certificate_expiry_date (#PCDATA)>
<!ELEMENT completed_date (#PCDATA)>
<!ELEMENT posted_date (#PCDATA)>
<!ELEMENT received_by_nhsbsa_date (#PCDATA)>
<!ELEMENT certificate_number (#PCDATA)>
<!ELEMENT valid_from (#PCDATA)>
<!ELEMENT valid_until (#PCDATA)>
<!ELEMENT practitioner_signature_present (#PCDATA)>
<!ELEMENT practitioner_declaration_text (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
