-- schema.sql
-- Combined schema for form: architecture-decision-record
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (7):
--   - 00_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_author.sql
--   - 03_create_table_organization.sql
--   - 04_create_table_architecture_decision_record.sql
--   - 05_create_table_architecture_decision_record_position.sql
--   - 06_create_table_architecture_decision_record_note.sql


-- ========================================================================
-- BEGIN 00_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators for GIN indexes on text columns.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_author.sql
-- ========================================================================

-- Author of an architecture decision record.

CREATE TABLE author (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT '' CHECK (role IN (
        'architect',
        'principal-engineer',
        'staff-engineer',
        'engineering-manager',
        'cto',
        'product-manager',
        'security-officer',
        'compliance-officer',
        'consultant',
        'other',
        ''
    )),
    organization_name TEXT NOT NULL DEFAULT '',
    team_name TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_author_updated_at
    BEFORE UPDATE ON author
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE author IS
    'Author of an architecture decision record (the architect or decision-maker).';
COMMENT ON COLUMN author.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN author.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN author.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN author.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN author.name IS
    'Author name.';
COMMENT ON COLUMN author.email IS
    'Author email address.';
COMMENT ON COLUMN author.phone IS
    'Author phone number.';
COMMENT ON COLUMN author.role IS
    'Author role within the organization.';
COMMENT ON COLUMN author.organization_name IS
    'Free-text organization name; for richer context use the organization table.';
COMMENT ON COLUMN author.team_name IS
    'Team within the organization.';

CREATE INDEX author_name_index_gin_trgm
    ON author
    USING GIN ((name) gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_author.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_organization.sql
-- ========================================================================

-- Organization context for an architecture decision record.

CREATE TABLE organization (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    legal_name TEXT NOT NULL DEFAULT '',
    industry TEXT NOT NULL DEFAULT '',
    domain TEXT NOT NULL DEFAULT '',
    country_as_iso_3166_1_alpha_2 CHAR(2),
    description TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_organization_updated_at
    BEFORE UPDATE ON organization
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE organization IS
    'Organization context (company, team, or program) under which an ADR is written.';
COMMENT ON COLUMN organization.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN organization.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN organization.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN organization.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN organization.name IS
    'Organization display name.';
COMMENT ON COLUMN organization.legal_name IS
    'Organization legal name, if different from display name.';
COMMENT ON COLUMN organization.industry IS
    'Industry such as healthcare, fintech, retail, public-sector.';
COMMENT ON COLUMN organization.domain IS
    'Primary internet domain such as example.com.';
COMMENT ON COLUMN organization.country_as_iso_3166_1_alpha_2 IS
    'Country of registration as ISO 3166-1 alpha-2 code.';
COMMENT ON COLUMN organization.description IS
    'Free-text description of the organization, e.g. mission or scope.';

CREATE INDEX organization_name_index_gin_trgm
    ON organization
    USING GIN ((name) gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_organization.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_architecture_decision_record.sql
-- ========================================================================

-- Main architecture decision record table.
-- Captures the 14 sections of the Tyree & Akerman ADR template
-- (Tyree, J. and Akerman, A., "Architecture Decisions: Demystifying
-- Architecture", IEEE Software, March/April 2005).
--
-- Sections held directly on this row as text:
--   issue, decision, assumptions, constraints, argument, implications,
--   related_decisions, related_requirements, related_artifacts,
--   related_principles
--
-- Sections held on child tables:
--   positions  -> architecture_decision_record_position
--   notes      -> architecture_decision_record_note

CREATE TABLE architecture_decision_record (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    author_id UUID REFERENCES author(id) ON DELETE SET NULL,
    organization_id UUID REFERENCES organization(id) ON DELETE SET NULL,

    -- Identification
    slug TEXT NOT NULL DEFAULT '',
    number INTEGER,
    title TEXT NOT NULL,
    decision_date DATE,

    -- Tyree & Akerman section 3: Status
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
        'pending',
        'decided',
        'approved',
        'superseded',
        'deprecated',
        ''
    )),

    -- Tyree & Akerman section 4: Group
    decision_group TEXT NOT NULL DEFAULT '' CHECK (decision_group IN (
        'business',
        'data',
        'integration',
        'presentation',
        'security',
        'infrastructure',
        'operations',
        'governance',
        'other',
        ''
    )),

    -- Tyree & Akerman section 1: Issue
    issue TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 2: Decision
    decision TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 5: Assumptions
    assumptions TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 6: Constraints
    constraints TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 8: Argument (rationale)
    argument TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 9: Implications
    implications TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 10: Related Decisions
    related_decisions TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 11: Related Requirements
    related_requirements TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 12: Related Artifacts
    related_artifacts TEXT NOT NULL DEFAULT '',

    -- Tyree & Akerman section 13: Related Principles
    related_principles TEXT NOT NULL DEFAULT '',

    -- Sign-off
    signed_off_by TEXT NOT NULL DEFAULT '',
    signed_off_at TIMESTAMPTZ
);

CREATE TRIGGER trigger_architecture_decision_record_updated_at
    BEFORE UPDATE ON architecture_decision_record
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE architecture_decision_record IS
    'Architecture decision record (Tyree & Akerman 14-section template).';
COMMENT ON COLUMN architecture_decision_record.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN architecture_decision_record.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN architecture_decision_record.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN architecture_decision_record.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN architecture_decision_record.author_id IS
    'Foreign key to author.id; the architect or decision-maker.';
COMMENT ON COLUMN architecture_decision_record.organization_id IS
    'Foreign key to organization.id; the org context.';
COMMENT ON COLUMN architecture_decision_record.slug IS
    'URL-safe identifier such as "use-postgres-for-primary-storage".';
COMMENT ON COLUMN architecture_decision_record.number IS
    'Sequential ADR number, e.g. 0042; optional, may be assigned post-merge.';
COMMENT ON COLUMN architecture_decision_record.title IS
    'Short human-readable title summarising the decision.';
COMMENT ON COLUMN architecture_decision_record.decision_date IS
    'Date on which the decision was made (status transitions to decided/approved).';
COMMENT ON COLUMN architecture_decision_record.status IS
    'Status: pending, decided, approved, superseded, deprecated.';
COMMENT ON COLUMN architecture_decision_record.decision_group IS
    'Tyree & Akerman section 4: organising group such as data, integration, security.';
COMMENT ON COLUMN architecture_decision_record.issue IS
    'Tyree & Akerman section 1: the architectural design issue being addressed.';
COMMENT ON COLUMN architecture_decision_record.decision IS
    'Tyree & Akerman section 2: the position chosen, stated clearly.';
COMMENT ON COLUMN architecture_decision_record.assumptions IS
    'Tyree & Akerman section 5: environmental factors influencing the decision.';
COMMENT ON COLUMN architecture_decision_record.constraints IS
    'Tyree & Akerman section 6: environmental limits imposed by the decision.';
COMMENT ON COLUMN architecture_decision_record.argument IS
    'Tyree & Akerman section 8: rationale for the chosen position.';
COMMENT ON COLUMN architecture_decision_record.implications IS
    'Tyree & Akerman section 9: consequences, follow-on decisions, scope/schedule impact.';
COMMENT ON COLUMN architecture_decision_record.related_decisions IS
    'Tyree & Akerman section 10: other ADRs this one depends on or supersedes.';
COMMENT ON COLUMN architecture_decision_record.related_requirements IS
    'Tyree & Akerman section 11: business or functional requirements addressed.';
COMMENT ON COLUMN architecture_decision_record.related_artifacts IS
    'Tyree & Akerman section 12: designs, models, scope documents impacted.';
COMMENT ON COLUMN architecture_decision_record.related_principles IS
    'Tyree & Akerman section 13: enterprise principles this aligns with or breaks.';
COMMENT ON COLUMN architecture_decision_record.signed_off_by IS
    'Name of the person who signed off the decision.';
COMMENT ON COLUMN architecture_decision_record.signed_off_at IS
    'Timestamp when the decision was signed off.';

CREATE INDEX architecture_decision_record_author_id_index
    ON architecture_decision_record(author_id);

CREATE INDEX architecture_decision_record_organization_id_index
    ON architecture_decision_record(organization_id);

CREATE INDEX architecture_decision_record_status_index
    ON architecture_decision_record(status);

CREATE UNIQUE INDEX architecture_decision_record_slug_unique_index
    ON architecture_decision_record(slug)
    WHERE slug <> '' AND deleted_at IS NULL;

CREATE INDEX architecture_decision_record_title_index_gin_trgm
    ON architecture_decision_record
    USING GIN ((title) gin_trgm_ops);

-- ========================================================================
-- END 04_create_table_architecture_decision_record.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_architecture_decision_record_position.sql
-- ========================================================================

-- Tyree & Akerman section 7: Positions.
-- A position is a viable alternative considered for the decision.
-- Each ADR typically has multiple positions; exactly one is_chosen=true
-- (this is enforced at the application layer, not by SQL constraint, because
-- a draft ADR may legitimately have zero chosen positions).

CREATE TABLE architecture_decision_record_position (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    architecture_decision_record_id UUID NOT NULL
        REFERENCES architecture_decision_record(id) ON DELETE CASCADE,

    ordinal INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    model_or_diagram_url TEXT NOT NULL DEFAULT '',
    is_chosen BOOLEAN NOT NULL DEFAULT FALSE,
    pros TEXT NOT NULL DEFAULT '',
    cons TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_architecture_decision_record_position_updated_at
    BEFORE UPDATE ON architecture_decision_record_position
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE architecture_decision_record_position IS
    'Tyree & Akerman section 7: a viable alternative considered for the decision.';
COMMENT ON COLUMN architecture_decision_record_position.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN architecture_decision_record_position.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN architecture_decision_record_position.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN architecture_decision_record_position.architecture_decision_record_id IS
    'Foreign key to architecture_decision_record.id.';
COMMENT ON COLUMN architecture_decision_record_position.ordinal IS
    'Display order; lower numbers appear first.';
COMMENT ON COLUMN architecture_decision_record_position.name IS
    'Short name of the position, e.g. "Use PostgreSQL".';
COMMENT ON COLUMN architecture_decision_record_position.description IS
    'Description of what this alternative would entail.';
COMMENT ON COLUMN architecture_decision_record_position.model_or_diagram_url IS
    'URL to a supporting model, diagram, or prototype.';
COMMENT ON COLUMN architecture_decision_record_position.is_chosen IS
    'TRUE if this is the position selected by the decision.';
COMMENT ON COLUMN architecture_decision_record_position.pros IS
    'Newline-separated list of advantages.';
COMMENT ON COLUMN architecture_decision_record_position.cons IS
    'Newline-separated list of disadvantages.';

CREATE INDEX architecture_decision_record_position_adr_id_index
    ON architecture_decision_record_position(architecture_decision_record_id);

CREATE INDEX architecture_decision_record_position_chosen_index
    ON architecture_decision_record_position(architecture_decision_record_id, is_chosen);

-- ========================================================================
-- END 05_create_table_architecture_decision_record_position.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_architecture_decision_record_note.sql
-- ========================================================================

-- Tyree & Akerman section 14: Notes.
-- Append-only discussion log captured during socialisation of the decision.
-- Each note is timestamped and attributed; notes are not edited after writing.

CREATE TABLE architecture_decision_record_note (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    architecture_decision_record_id UUID NOT NULL
        REFERENCES architecture_decision_record(id) ON DELETE CASCADE,

    noted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    noted_by TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL
);

CREATE TRIGGER trigger_architecture_decision_record_note_updated_at
    BEFORE UPDATE ON architecture_decision_record_note
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE architecture_decision_record_note IS
    'Tyree & Akerman section 14: append-only discussion notes captured during socialisation.';
COMMENT ON COLUMN architecture_decision_record_note.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN architecture_decision_record_note.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN architecture_decision_record_note.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN architecture_decision_record_note.architecture_decision_record_id IS
    'Foreign key to architecture_decision_record.id.';
COMMENT ON COLUMN architecture_decision_record_note.noted_at IS
    'Timestamp when the note was made (may differ from created_at if backdated).';
COMMENT ON COLUMN architecture_decision_record_note.noted_by IS
    'Name of the person who made the note.';
COMMENT ON COLUMN architecture_decision_record_note.body IS
    'Note body text.';

CREATE INDEX architecture_decision_record_note_adr_id_index
    ON architecture_decision_record_note(architecture_decision_record_id);

CREATE INDEX architecture_decision_record_note_noted_at_index
    ON architecture_decision_record_note(architecture_decision_record_id, noted_at);

-- ========================================================================
-- END 06_create_table_architecture_decision_record_note.sql
-- ========================================================================
