//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clinicians;
pub mod diabetes_eye_screening_grade_flags;
pub mod diabetes_eye_screening_grade_rules;
pub mod diabetes_eye_screening_grades;
pub mod diabetes_eye_screenings;
pub mod patients;
pub mod users;
