<!ELEMENT paediatric_early_warning_score_grade (id,created_at,updated_at,deleted_at,paediatric_early_warning_score_id,aggregate_score,max_parameter_score,respiratory_rate_score,respiratory_effort_score,oxygen_saturation_score,supplemental_oxygen_score,heart_rate_score,capillary_refill_score,consciousness_score,risk_band,single_parameter_trigger,concern_trigger,monitoring_frequency,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT paediatric_early_warning_score_id (#PCDATA)>
<!ELEMENT aggregate_score (#PCDATA)>
<!ELEMENT max_parameter_score (#PCDATA)>
<!ELEMENT respiratory_rate_score (#PCDATA)>
<!ELEMENT respiratory_effort_score (#PCDATA)>
<!ELEMENT oxygen_saturation_score (#PCDATA)>
<!ELEMENT supplemental_oxygen_score (#PCDATA)>
<!ELEMENT heart_rate_score (#PCDATA)>
<!ELEMENT capillary_refill_score (#PCDATA)>
<!ELEMENT consciousness_score (#PCDATA)>
<!ELEMENT risk_band (#PCDATA)>
<!ELEMENT single_parameter_trigger (#PCDATA)>
<!ELEMENT concern_trigger (#PCDATA)>
<!ELEMENT monitoring_frequency (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
