mod users;

mod patients;
mod practitioners;
mod pharmacology_waiting_list_cards;
mod pharmacology_waiting_list_card_appointments;
mod pharmacology_waiting_list_card_grades;
mod pharmacology_waiting_list_card_grade_rules;
mod pharmacology_waiting_list_card_grade_flags;