mod auth;
mod prepare_data;

pub mod patient;
pub mod clinician;
pub mod recognition_of_stroke_in_the_emergency_room;
pub mod recognition_of_stroke_in_the_emergency_room_grade;
pub mod recognition_of_stroke_in_the_emergency_room_grade_rule;
pub mod recognition_of_stroke_in_the_emergency_room_grade_flag;