<!ELEMENT plastic_surg_waiting_list_card_grade_rule (id,created_at,updated_at,deleted_at,plastic_surg_waiting_list_card_grade_id,rule_id,instrument,band,category,description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT plastic_surg_waiting_list_card_grade_id (#PCDATA)>
<!ELEMENT rule_id (#PCDATA)>
<!ELEMENT instrument (#PCDATA)>
<!ELEMENT band (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT description (#PCDATA)>
