//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clinicians;
pub mod grace_score_for_acute_coronary_syndrome_grade_flags;
pub mod grace_score_for_acute_coronary_syndrome_grade_rules;
pub mod grace_score_for_acute_coronary_syndrome_grades;
pub mod grace_score_for_acute_coronary_syndromes;
pub mod patients;
pub mod users;
