pub mod _entities;
pub mod users;
pub mod patients;
pub mod clinicians;
pub mod medical_practices;
pub mod united_kingdom_statement_of_fitness_for_works;
pub mod united_kingdom_statement_of_fitness_for_work_grades;
pub mod united_kingdom_statement_of_fitness_for_work_grade_rules;
pub mod united_kingdom_statement_of_fitness_for_work_grade_flags;
