logger:
  enable: false
  level: warn

server:
  port: 5150
  host: http://localhost

database:
  uri: postgres://postgres:postgres@localhost:5432/international_certificate_of_vaccination_or_prophylaxis_test
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 4
  auto_migrate: true
  dangerously_truncate: true
  dangerously_recreate: true

workers:
  mode: ForegroundBlocking
