<!ELEMENT patient_room_readiness_checklist (id,created_at,updated_at,deleted_at,building_name_or_number,room_name_or_number,patient_cot_mattress_side_railings,attendant_cot_mattress,call_bell,cardiac_table_iv_stand,hot_kettle_glasses,linen_patient_dress,landline_numbers,refrigerator_fan,television_remote,dustbin,bath_towel_handtowels,wc_dustbins,washbasin_and_fittings,bucket_and_mug,geyser,soap_dispenser,toilet_kit,window_glass_grooves,sidewalls,curtain_blind,chair_sofa,wall_seepage_water_leakage,electricity_points_lights,ceiling_tiles,door_knobs_stopper,inspector_name,inspector_email,inspection_date,inspection_time)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT building_name_or_number (#PCDATA)>
<!ELEMENT room_name_or_number (#PCDATA)>
<!ELEMENT patient_cot_mattress_side_railings (#PCDATA)>
<!ELEMENT attendant_cot_mattress (#PCDATA)>
<!ELEMENT call_bell (#PCDATA)>
<!ELEMENT cardiac_table_iv_stand (#PCDATA)>
<!ELEMENT hot_kettle_glasses (#PCDATA)>
<!ELEMENT linen_patient_dress (#PCDATA)>
<!ELEMENT landline_numbers (#PCDATA)>
<!ELEMENT refrigerator_fan (#PCDATA)>
<!ELEMENT television_remote (#PCDATA)>
<!ELEMENT dustbin (#PCDATA)>
<!ELEMENT bath_towel_handtowels (#PCDATA)>
<!ELEMENT wc_dustbins (#PCDATA)>
<!ELEMENT washbasin_and_fittings (#PCDATA)>
<!ELEMENT bucket_and_mug (#PCDATA)>
<!ELEMENT geyser (#PCDATA)>
<!ELEMENT soap_dispenser (#PCDATA)>
<!ELEMENT toilet_kit (#PCDATA)>
<!ELEMENT window_glass_grooves (#PCDATA)>
<!ELEMENT sidewalls (#PCDATA)>
<!ELEMENT curtain_blind (#PCDATA)>
<!ELEMENT chair_sofa (#PCDATA)>
<!ELEMENT wall_seepage_water_leakage (#PCDATA)>
<!ELEMENT electricity_points_lights (#PCDATA)>
<!ELEMENT ceiling_tiles (#PCDATA)>
<!ELEMENT door_knobs_stopper (#PCDATA)>
<!ELEMENT inspector_name (#PCDATA)>
<!ELEMENT inspector_email (#PCDATA)>
<!ELEMENT inspection_date (#PCDATA)>
<!ELEMENT inspection_time (#PCDATA)>
