<!ELEMENT quick_sequential_organ_failure_assessment_grade (id,created_at,updated_at,deleted_at,quick_sequential_organ_failure_assessment_id,respiratory_rate_point,mentation_point,systolic_blood_pressure_point,total_score,risk_band,threshold_met,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT quick_sequential_organ_failure_assessment_id (#PCDATA)>
<!ELEMENT respiratory_rate_point (#PCDATA)>
<!ELEMENT mentation_point (#PCDATA)>
<!ELEMENT systolic_blood_pressure_point (#PCDATA)>
<!ELEMENT total_score (#PCDATA)>
<!ELEMENT risk_band (#PCDATA)>
<!ELEMENT threshold_met (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
