<!ELEMENT timi_risk_score_for_acute_coronary_syndrome (id,created_at,updated_at,deleted_at,patient_id,clinician_id,clinician_name,clinician_role,assessed_at,care_setting,working_diagnosis,patient_identifier,sex,age_over_65,three_or_more_cad_risk_factors,known_cad_stenosis,aspirin_use_prior_7_days,two_or_more_angina_episodes_24h,st_deviation,positive_cardiac_marker,clinical_note)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT clinician_name (#PCDATA)>
<!ELEMENT clinician_role (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT working_diagnosis (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT age_over_65 (#PCDATA)>
<!ELEMENT three_or_more_cad_risk_factors (#PCDATA)>
<!ELEMENT known_cad_stenosis (#PCDATA)>
<!ELEMENT aspirin_use_prior_7_days (#PCDATA)>
<!ELEMENT two_or_more_angina_episodes_24h (#PCDATA)>
<!ELEMENT st_deviation (#PCDATA)>
<!ELEMENT positive_cardiac_marker (#PCDATA)>
<!ELEMENT clinical_note (#PCDATA)>
