//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
pub use super::waterlow_pressure_ulcer_risk_assessment_grade_flags::Entity as WaterlowPressureUlcerRiskAssessmentGradeFlags;
pub use super::waterlow_pressure_ulcer_risk_assessment_grade_rules::Entity as WaterlowPressureUlcerRiskAssessmentGradeRules;
pub use super::waterlow_pressure_ulcer_risk_assessment_grades::Entity as WaterlowPressureUlcerRiskAssessmentGrades;
pub use super::waterlow_pressure_ulcer_risk_assessments::Entity as WaterlowPressureUlcerRiskAssessments;
