<!ELEMENT arc42_documentation (id,created_at,updated_at,deleted_at,architecture_id,author_name,author_role,document_date,introduction,business_context_description,technical_context_description,solution_strategy_summary,top_level_decomposition_summary,building_block_overview,runtime_overview,deployment_overview,crosscutting_overview,quality_tree_summary,recommendation,additional_notes,signed_by,signed_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT architecture_id (#PCDATA)>
<!ELEMENT author_name (#PCDATA)>
<!ELEMENT author_role (#PCDATA)>
<!ELEMENT document_date (#PCDATA)>
<!ELEMENT introduction (#PCDATA)>
<!ELEMENT business_context_description (#PCDATA)>
<!ELEMENT technical_context_description (#PCDATA)>
<!ELEMENT solution_strategy_summary (#PCDATA)>
<!ELEMENT top_level_decomposition_summary (#PCDATA)>
<!ELEMENT building_block_overview (#PCDATA)>
<!ELEMENT runtime_overview (#PCDATA)>
<!ELEMENT deployment_overview (#PCDATA)>
<!ELEMENT crosscutting_overview (#PCDATA)>
<!ELEMENT quality_tree_summary (#PCDATA)>
<!ELEMENT recommendation (#PCDATA)>
<!ELEMENT additional_notes (#PCDATA)>
<!ELEMENT signed_by (#PCDATA)>
<!ELEMENT signed_at (#PCDATA)>
