<!ELEMENT united_kingdom_statement_of_fitness_for_work_grade (id,created_at,updated_at,deleted_at,united_kingdom_statement_of_fitness_for_work_id,fitness_category,adaptation_intensity,adaptation_count,period_days,period_compliance,recommendation,is_within_first_six_months_of_condition,is_valid,grader_notes,graded_at,clinician_override,clinician_override_reason,clinician_final_recommendation)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT united_kingdom_statement_of_fitness_for_work_id (#PCDATA)>
<!ELEMENT fitness_category (#PCDATA)>
<!ELEMENT adaptation_intensity (#PCDATA)>
<!ELEMENT adaptation_count (#PCDATA)>
<!ELEMENT period_days (#PCDATA)>
<!ELEMENT period_compliance (#PCDATA)>
<!ELEMENT recommendation (#PCDATA)>
<!ELEMENT is_within_first_six_months_of_condition (#PCDATA)>
<!ELEMENT is_valid (#PCDATA)>
<!ELEMENT grader_notes (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
<!ELEMENT clinician_override (#PCDATA)>
<!ELEMENT clinician_override_reason (#PCDATA)>
<!ELEMENT clinician_final_recommendation (#PCDATA)>
