mod users;

mod patients;
mod practitioners;
mod ophthalmology_waiting_list_cards;
mod ophthalmology_waiting_list_card_appointments;
mod ophthalmology_waiting_list_card_grades;
mod ophthalmology_waiting_list_card_grade_rules;
mod ophthalmology_waiting_list_card_grade_flags;