//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::allergies::Entity as Allergies;
pub use super::clinicians::Entity as Clinicians;
pub use super::medications::Entity as Medications;
pub use super::patient_allergies::Entity as PatientAllergies;
pub use super::patient_medications::Entity as PatientMedications;
pub use super::patients::Entity as Patients;
pub use super::pre_operative_assessment_by_clinician_grades::Entity as PreOperativeAssessmentByClinicianGrades;
pub use super::pre_operative_assessment_by_clinicians::Entity as PreOperativeAssessmentByClinicians;
pub use super::users::Entity as Users;
