mod users;

mod patients;
mod clinicians;
mod padua_venous_thromboembolism_risk_assessments;
mod padua_venous_thromboembolism_risk_assessment_grades;
mod padua_venous_thromboembolism_risk_assessment_grade_rules;
mod padua_venous_thromboembolism_risk_assessment_grade_flags;