<!ELEMENT cystoscopy_test_result (id,created_at,updated_at,deleted_at,patient_id,clinician_id,originating_request_reference,report_status,performed_date,reported_date,procedure,anaesthesia,clinical_history,bladder_tumour,inflammation_cystitis,bladder_stones,urethral_stricture,trabeculation,prostatic_enlargement,normal_examination,tumour_size_mm,tumour_appearance,biopsy_taken,complication,findings_narrative,impression,reporting_category,recommended_follow_up,critical_result_communicated,reported_to)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT originating_request_reference (#PCDATA)>
<!ELEMENT report_status (#PCDATA)>
<!ELEMENT performed_date (#PCDATA)>
<!ELEMENT reported_date (#PCDATA)>
<!ELEMENT procedure (#PCDATA)>
<!ELEMENT anaesthesia (#PCDATA)>
<!ELEMENT clinical_history (#PCDATA)>
<!ELEMENT bladder_tumour (#PCDATA)>
<!ELEMENT inflammation_cystitis (#PCDATA)>
<!ELEMENT bladder_stones (#PCDATA)>
<!ELEMENT urethral_stricture (#PCDATA)>
<!ELEMENT trabeculation (#PCDATA)>
<!ELEMENT prostatic_enlargement (#PCDATA)>
<!ELEMENT normal_examination (#PCDATA)>
<!ELEMENT tumour_size_mm (#PCDATA)>
<!ELEMENT tumour_appearance (#PCDATA)>
<!ELEMENT biopsy_taken (#PCDATA)>
<!ELEMENT complication (#PCDATA)>
<!ELEMENT findings_narrative (#PCDATA)>
<!ELEMENT impression (#PCDATA)>
<!ELEMENT reporting_category (#PCDATA)>
<!ELEMENT recommended_follow_up (#PCDATA)>
<!ELEMENT critical_result_communicated (#PCDATA)>
<!ELEMENT reported_to (#PCDATA)>
