<!ELEMENT diabetes_podiatry_assessment (id,created_at,updated_at,deleted_at,patient_id,clinician_id,assessed_at,assessment_setting,diabetes_type,years_since_diagnosis,on_renal_replacement_therapy,visual_acuity_impairment,self_care_ability,footwear_appropriate,right_neuropathy_status,right_pulses_status,right_deformity,right_callus,right_skin_breakdown,right_active_ulcer,right_ulcer_severity,right_previous_ulcer,right_previous_amputation,right_suspected_charcot,left_neuropathy_status,left_pulses_status,left_deformity,left_callus,left_skin_breakdown,left_active_ulcer,left_ulcer_severity,left_previous_ulcer,left_previous_amputation,left_suspected_charcot,clinical_context)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT assessment_setting (#PCDATA)>
<!ELEMENT diabetes_type (#PCDATA)>
<!ELEMENT years_since_diagnosis (#PCDATA)>
<!ELEMENT on_renal_replacement_therapy (#PCDATA)>
<!ELEMENT visual_acuity_impairment (#PCDATA)>
<!ELEMENT self_care_ability (#PCDATA)>
<!ELEMENT footwear_appropriate (#PCDATA)>
<!ELEMENT right_neuropathy_status (#PCDATA)>
<!ELEMENT right_pulses_status (#PCDATA)>
<!ELEMENT right_deformity (#PCDATA)>
<!ELEMENT right_callus (#PCDATA)>
<!ELEMENT right_skin_breakdown (#PCDATA)>
<!ELEMENT right_active_ulcer (#PCDATA)>
<!ELEMENT right_ulcer_severity (#PCDATA)>
<!ELEMENT right_previous_ulcer (#PCDATA)>
<!ELEMENT right_previous_amputation (#PCDATA)>
<!ELEMENT right_suspected_charcot (#PCDATA)>
<!ELEMENT left_neuropathy_status (#PCDATA)>
<!ELEMENT left_pulses_status (#PCDATA)>
<!ELEMENT left_deformity (#PCDATA)>
<!ELEMENT left_callus (#PCDATA)>
<!ELEMENT left_skin_breakdown (#PCDATA)>
<!ELEMENT left_active_ulcer (#PCDATA)>
<!ELEMENT left_ulcer_severity (#PCDATA)>
<!ELEMENT left_previous_ulcer (#PCDATA)>
<!ELEMENT left_previous_amputation (#PCDATA)>
<!ELEMENT left_suspected_charcot (#PCDATA)>
<!ELEMENT clinical_context (#PCDATA)>
