<!ELEMENT agile_checklist_grade (id,created_at,updated_at,deleted_at,agile_checklist_id,answered_count,teams_yes_count,teams_applicable_count,teams_percent,stakeholders_yes_count,stakeholders_applicable_count,stakeholders_percent,practices_yes_count,practices_applicable_count,practices_percent,overall_percent,teams_band,stakeholders_band,practices_band,maturity,top_action_1,top_action_2,top_action_3,coach_notes,signed_at,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT agile_checklist_id (#PCDATA)>
<!ELEMENT answered_count (#PCDATA)>
<!ELEMENT teams_yes_count (#PCDATA)>
<!ELEMENT teams_applicable_count (#PCDATA)>
<!ELEMENT teams_percent (#PCDATA)>
<!ELEMENT stakeholders_yes_count (#PCDATA)>
<!ELEMENT stakeholders_applicable_count (#PCDATA)>
<!ELEMENT stakeholders_percent (#PCDATA)>
<!ELEMENT practices_yes_count (#PCDATA)>
<!ELEMENT practices_applicable_count (#PCDATA)>
<!ELEMENT practices_percent (#PCDATA)>
<!ELEMENT overall_percent (#PCDATA)>
<!ELEMENT teams_band (#PCDATA)>
<!ELEMENT stakeholders_band (#PCDATA)>
<!ELEMENT practices_band (#PCDATA)>
<!ELEMENT maturity (#PCDATA)>
<!ELEMENT top_action_1 (#PCDATA)>
<!ELEMENT top_action_2 (#PCDATA)>
<!ELEMENT top_action_3 (#PCDATA)>
<!ELEMENT coach_notes (#PCDATA)>
<!ELEMENT signed_at (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
