[workspace]
members = [".", "migration"]

[workspace.dependencies]
loco-rs = { version = "0.16", default-features = false, features = [
  "auth_jwt",
  "bg_pg",
  "cache_inmem",
  "cli",
  "with-db",
] }

[package]
name = "objectives_and_key_results_tracker"
version = "0.1.0"
edition = "2024"
publish = false
default-run = "objectives_and_key_results_tracker-cli"

[dependencies]
loco-rs = { workspace = true }
migration = { path = "migration" }
sea-orm = { version = "1.1", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
tokio = { version = "1.45", default-features = false, features = ["rt-multi-thread"] }
async-trait = { version = "0.1" }
axum = { version = "0.8" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6", features = ["v4", "serde"] }
tracing = { version = "0.1" }
include_dir = { version = "0.7" }
opentelemetry = "0.27"
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio", "metrics"] }
opentelemetry-otlp = { version = "0.27", features = ["grpc-tonic", "metrics", "trace"] }
tracing-opentelemetry = "0.28"
axum-prometheus = "0.7"

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
serial_test = { version = "3" }
rstest = { version = "0.25" }

[lib]
name = "objectives_and_key_results_tracker"
path = "src/lib.rs"

[[bin]]
name = "objectives_and_key_results_tracker-cli"
path = "src/bin/main.rs"
required-features = []
