//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::colonoscopy_test_request_grade_flags::Entity as ColonoscopyTestRequestGradeFlags;
pub use super::colonoscopy_test_request_grade_rules::Entity as ColonoscopyTestRequestGradeRules;
pub use super::colonoscopy_test_request_grades::Entity as ColonoscopyTestRequestGrades;
pub use super::colonoscopy_test_requests::Entity as ColonoscopyTestRequests;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
