mod users;

mod patients;
mod clinicians;
mod medical_certificate_of_cause_of_deaths;
mod medical_certificate_of_cause_of_death_grades;
mod medical_certificate_of_cause_of_death_grade_rules;
mod medical_certificate_of_cause_of_death_grade_flags;