//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::resp_med_waiting_list_card_appointments::Entity as RespMedWaitingListCardAppointments;
pub use super::resp_med_waiting_list_card_grade_flags::Entity as RespMedWaitingListCardGradeFlags;
pub use super::resp_med_waiting_list_card_grade_rules::Entity as RespMedWaitingListCardGradeRules;
pub use super::resp_med_waiting_list_card_grades::Entity as RespMedWaitingListCardGrades;
pub use super::resp_med_waiting_list_cards::Entity as RespMedWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
