//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::electroencephalogram_test_request_grade_flags::Entity as ElectroencephalogramTestRequestGradeFlags;
pub use super::electroencephalogram_test_request_grade_rules::Entity as ElectroencephalogramTestRequestGradeRules;
pub use super::electroencephalogram_test_request_grades::Entity as ElectroencephalogramTestRequestGrades;
pub use super::electroencephalogram_test_requests::Entity as ElectroencephalogramTestRequests;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
