-- schema.sql
-- Combined schema for form: fluid-balance-chart
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (9):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_fluid_balance_chart.sql
--   - 05_create_table_fluid_balance_chart_entry.sql
--   - 06_create_table_fluid_balance_chart_grade.sql
--   - 07_create_table_fluid_balance_chart_grade_rule.sql
--   - 08_create_table_fluid_balance_chart_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators used by free-text search GIN indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information.

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    hospital_mrn VARCHAR(50),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    allergies_summary TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient demographic information used by the fluid balance chart record.';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Full patient name as recorded on the wristband.';
COMMENT ON COLUMN patient.birth_date IS
    'Date of birth.';
COMMENT ON COLUMN patient.sex IS
    'Sex recorded for clinical purposes: female, male, intersex, or unknown.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.hospital_mrn IS
    'Local hospital medical record number (MRN).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height in centimetres.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight in kilograms.';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI), kg/m^2.';
COMMENT ON COLUMN patient.allergies_summary IS
    'Free-text summary of known allergies.';

CREATE INDEX patient_name_trgm_idx
    ON patient
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Clinician employee information used to identify the charting professional
-- who records the fluid balance chart (nurse, doctor, healthcare assistant).

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN ('nurse', 'doctor', 'healthcare-assistant', 'other', '')),
    registration_body VARCHAR(20) NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'GPhC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician identifying information for the charting professional who records the fluid balance chart.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Clinician full name as recorded in the rota.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code.';
COMMENT ON COLUMN clinician.role IS
    'Primary clinical role: nurse, doctor, healthcare-assistant, or other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Professional registration body: GMC, NMC, HCPC, GPhC, or other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Professional registration number issued by the registration body.';

CREATE INDEX clinician_name_trgm_idx
    ON clinician
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_fluid_balance_chart.sql
-- ========================================================================

-- Parent fluid balance chart header. Records the charting context, patient
-- identification, charting period, and patient weight (which enables the
-- mL/kg/h urine output rate). Timed intake and output volumes are held in the
-- fluid_balance_chart_entry child table that cascades from this parent, and the
-- computed grade cascades 1:1 from it.

CREATE TABLE fluid_balance_chart (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE RESTRICT,
    clinician_id UUID REFERENCES clinician(id) ON DELETE RESTRICT,

    clinician_name TEXT NOT NULL DEFAULT '',
    clinician_role VARCHAR(30) NOT NULL DEFAULT '' CHECK (clinician_role IN ('nurse', 'doctor', 'healthcare-assistant', 'other', '')),
    patient_identifier TEXT NOT NULL DEFAULT '',
    ward_or_unit TEXT NOT NULL DEFAULT '',

    chart_start_at TIMESTAMPTZ,
    chart_period_hours NUMERIC(6,2),
    weight_kg NUMERIC(5,1),
    clinical_note TEXT NOT NULL DEFAULT ''
);

CREATE INDEX fluid_balance_chart_patient_id_idx
    ON fluid_balance_chart (patient_id);
CREATE INDEX fluid_balance_chart_clinician_id_idx
    ON fluid_balance_chart (clinician_id);

CREATE TRIGGER trigger_fluid_balance_chart_updated_at
    BEFORE UPDATE ON fluid_balance_chart
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE fluid_balance_chart IS
    'Parent fluid balance chart header: charting context, patient identification, charting period, and patient weight enabling the mL/kg/h urine output rate.';
COMMENT ON COLUMN fluid_balance_chart.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN fluid_balance_chart.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN fluid_balance_chart.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN fluid_balance_chart.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN fluid_balance_chart.patient_id IS
    'Foreign key to the patient this chart is for (restricted delete).';
COMMENT ON COLUMN fluid_balance_chart.clinician_id IS
    'Foreign key to the charting clinician (restricted delete); optional.';
COMMENT ON COLUMN fluid_balance_chart.clinician_name IS
    'Name of the charting clinician as entered on the chart.';
COMMENT ON COLUMN fluid_balance_chart.clinician_role IS
    'Role of the charting clinician: nurse, doctor, healthcare-assistant, or other.';
COMMENT ON COLUMN fluid_balance_chart.patient_identifier IS
    'Local patient identifier as entered on the chart.';
COMMENT ON COLUMN fluid_balance_chart.ward_or_unit IS
    'Ward or unit name where the chart is being kept.';
COMMENT ON COLUMN fluid_balance_chart.chart_start_at IS
    'Date and time the charting period starts.';
COMMENT ON COLUMN fluid_balance_chart.chart_period_hours IS
    'Charting period in hours (default 24); used to scale balance thresholds and compute the mL/kg/h rate.';
COMMENT ON COLUMN fluid_balance_chart.weight_kg IS
    'Patient weight in kilograms; enables the urine output rate in mL/kg/h.';
COMMENT ON COLUMN fluid_balance_chart.clinical_note IS
    'Free-text summary note for the chart.';

-- ========================================================================
-- END 04_create_table_fluid_balance_chart.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_fluid_balance_chart_entry.sql
-- ========================================================================

-- Timed intake and output line items for a fluid balance chart. Each recorded
-- volume is one row and cascades from the parent fluid_balance_chart. A row
-- carries the time it was recorded, its direction (intake or output), the fluid
-- category, an optional route or description, and the volume in millilitres.

CREATE TABLE fluid_balance_chart_entry (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    fluid_balance_chart_id UUID NOT NULL REFERENCES fluid_balance_chart(id) ON DELETE CASCADE,

    entry_at TIMESTAMPTZ,
    direction VARCHAR(10) NOT NULL DEFAULT '' CHECK (direction IN ('intake', 'output', '')),
    category VARCHAR(20) NOT NULL DEFAULT '' CHECK (category IN ('oral', 'iv', 'enteral', 'blood-products', 'other-intake', 'urine', 'drains', 'vomit-ng', 'stool', 'insensible-other', '')),
    description TEXT NOT NULL DEFAULT '',
    volume_ml NUMERIC(8,2)
);

CREATE INDEX fluid_balance_chart_entry_chart_id_idx
    ON fluid_balance_chart_entry (fluid_balance_chart_id);

CREATE TRIGGER trigger_fluid_balance_chart_entry_updated_at
    BEFORE UPDATE ON fluid_balance_chart_entry
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE fluid_balance_chart_entry IS
    'Timed intake and output line items for a fluid balance chart; cascades from the parent chart.';
COMMENT ON COLUMN fluid_balance_chart_entry.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN fluid_balance_chart_entry.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN fluid_balance_chart_entry.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN fluid_balance_chart_entry.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN fluid_balance_chart_entry.fluid_balance_chart_id IS
    'Foreign key to the parent fluid balance chart.';
COMMENT ON COLUMN fluid_balance_chart_entry.entry_at IS
    'Date and time the volume was recorded.';
COMMENT ON COLUMN fluid_balance_chart_entry.direction IS
    'Direction of the volume: intake or output.';
COMMENT ON COLUMN fluid_balance_chart_entry.category IS
    'Fluid category: intake (oral, iv, enteral, blood-products, other-intake) or output (urine, drains, vomit-ng, stool, insensible-other).';
COMMENT ON COLUMN fluid_balance_chart_entry.description IS
    'Optional route or free-text description of the recorded volume.';
COMMENT ON COLUMN fluid_balance_chart_entry.volume_ml IS
    'Recorded volume in millilitres; null when not recorded.';

-- ========================================================================
-- END 05_create_table_fluid_balance_chart_entry.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_fluid_balance_chart_grade.sql
-- ========================================================================

-- Computed grading result for a fluid balance chart. Stores the reconciled
-- intake/output totals, the net balance, urine output and its mL/kg/h rate, the
-- observed hours and weight used in the calculation, and the classified fluid
-- status (Balanced / Positive / Negative / Oliguria). One row per chart (1:1).

CREATE TABLE fluid_balance_chart_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    fluid_balance_chart_id UUID NOT NULL UNIQUE
        REFERENCES fluid_balance_chart(id) ON DELETE CASCADE,

    total_intake_ml NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_output_ml NUMERIC(10,2) NOT NULL DEFAULT 0,
    net_balance_ml NUMERIC(10,2) NOT NULL DEFAULT 0,
    urine_output_ml NUMERIC(10,2) NOT NULL DEFAULT 0,
    hours_observed NUMERIC(6,2),
    weight_kg NUMERIC(5,1),
    urine_output_ml_kg_h NUMERIC(8,4),
    fluid_status VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (fluid_status IN ('balanced', 'positive', 'negative', 'oliguria', '')),
    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_fluid_balance_chart_grade_updated_at
    BEFORE UPDATE ON fluid_balance_chart_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE fluid_balance_chart_grade IS
    'Computed grading result for a fluid balance chart: intake/output totals, net balance, urine output rate, and the classified fluid status; 1:1 with the chart.';
COMMENT ON COLUMN fluid_balance_chart_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN fluid_balance_chart_grade.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN fluid_balance_chart_grade.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN fluid_balance_chart_grade.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN fluid_balance_chart_grade.fluid_balance_chart_id IS
    'Foreign key to the parent fluid balance chart (unique, 1:1).';
COMMENT ON COLUMN fluid_balance_chart_grade.total_intake_ml IS
    'Sum of all recorded intake volumes in millilitres.';
COMMENT ON COLUMN fluid_balance_chart_grade.total_output_ml IS
    'Sum of all recorded output volumes in millilitres.';
COMMENT ON COLUMN fluid_balance_chart_grade.net_balance_ml IS
    'Net balance in millilitres (total intake minus total output); positive is a net gain.';
COMMENT ON COLUMN fluid_balance_chart_grade.urine_output_ml IS
    'Total urine output in millilitres (sum of output entries with category urine).';
COMMENT ON COLUMN fluid_balance_chart_grade.hours_observed IS
    'Hours over which the chart was observed (chart period, or the span of entries); null when unknown.';
COMMENT ON COLUMN fluid_balance_chart_grade.weight_kg IS
    'Patient weight in kilograms used for the mL/kg/h calculation; null when unknown.';
COMMENT ON COLUMN fluid_balance_chart_grade.urine_output_ml_kg_h IS
    'Urine output rate in millilitres per kilogram per hour; null when weight or hours are unknown.';
COMMENT ON COLUMN fluid_balance_chart_grade.fluid_status IS
    'Classified fluid status: balanced, positive, negative, or oliguria.';
COMMENT ON COLUMN fluid_balance_chart_grade.graded_at IS
    'Timestamp when the engine last computed the grade.';

-- ========================================================================
-- END 06_create_table_fluid_balance_chart_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_fluid_balance_chart_grade_rule.sql
-- ========================================================================

-- Audit trail of every classification rule that fired during grading. Each row
-- records one rule firing with a category and a human-readable description.

CREATE TABLE fluid_balance_chart_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    fluid_balance_chart_grade_id UUID NOT NULL
        REFERENCES fluid_balance_chart_grade(id) ON DELETE CASCADE,

    rule_id VARCHAR(40) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX fluid_balance_chart_grade_rule_grade_id_idx
    ON fluid_balance_chart_grade_rule (fluid_balance_chart_grade_id);

CREATE TRIGGER trigger_fluid_balance_chart_grade_rule_updated_at
    BEFORE UPDATE ON fluid_balance_chart_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE fluid_balance_chart_grade_rule IS
    'Audit trail of every classification rule that fired during grading: category and description.';
COMMENT ON COLUMN fluid_balance_chart_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN fluid_balance_chart_grade_rule.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN fluid_balance_chart_grade_rule.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN fluid_balance_chart_grade_rule.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN fluid_balance_chart_grade_rule.fluid_balance_chart_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN fluid_balance_chart_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-STATUS-OLIGURIA-01).';
COMMENT ON COLUMN fluid_balance_chart_grade_rule.category IS
    'Subject category (e.g. fluid-status, threshold-scaling).';
COMMENT ON COLUMN fluid_balance_chart_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 07_create_table_fluid_balance_chart_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 08_create_table_fluid_balance_chart_grade_flag.sql
-- ========================================================================

-- Flagged issues raised independently of the fluid-status classification, with a
-- priority and a suggested action for the clinical team.

CREATE TABLE fluid_balance_chart_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    fluid_balance_chart_grade_id UUID NOT NULL
        REFERENCES fluid_balance_chart_grade(id) ON DELETE CASCADE,

    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(30) NOT NULL DEFAULT ''
        CHECK (category IN (
            'fluid-overload',
            'dehydration',
            'oliguria',
            'anuria',
            'incomplete-recording',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX fluid_balance_chart_grade_flag_grade_id_idx
    ON fluid_balance_chart_grade_flag (fluid_balance_chart_grade_id);

CREATE TRIGGER trigger_fluid_balance_chart_grade_flag_updated_at
    BEFORE UPDATE ON fluid_balance_chart_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE fluid_balance_chart_grade_flag IS
    'Flagged issues raised independently of the fluid-status classification, with priority and a suggested action for the clinical team.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.fluid_balance_chart_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-FLUID-OVERLOAD-001).';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.category IS
    'Flag category: fluid-overload, dehydration, oliguria, anuria, incomplete-recording, or other.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN fluid_balance_chart_grade_flag.suggested_action IS
    'Suggested clinical action (e.g. "review for pulmonary or peripheral oedema").';

-- ========================================================================
-- END 08_create_table_fluid_balance_chart_grade_flag.sql
-- ========================================================================
