<!ELEMENT outpatient_outcome_operational (id,created_at,updated_at,deleted_at,outpatient_outcome_id,referral_date,appointment_date,wait_time_days,service_target_days,nhs_attendance_outcome)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT outpatient_outcome_id (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT appointment_date (#PCDATA)>
<!ELEMENT wait_time_days (#PCDATA)>
<!ELEMENT service_target_days (#PCDATA)>
<!ELEMENT nhs_attendance_outcome (#PCDATA)>
