mod users;

mod patients;
mod practitioners;
mod podiatric_surg_waiting_list_cards;
mod podiatric_surg_waiting_list_card_appointments;
mod podiatric_surg_waiting_list_card_grades;
mod podiatric_surg_waiting_list_card_grade_rules;
mod podiatric_surg_waiting_list_card_grade_flags;