-- schema.sql
-- Combined schema for form: grace-score-for-acute-coronary-syndrome
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (8):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_grace_score_for_acute_coronary_syndrome.sql
--   - 05_create_table_grace_score_for_acute_coronary_syndrome_grade.sql
--   - 06_create_table_grace_score_for_acute_coronary_syndrome_grade_rule.sql
--   - 07_create_table_grace_score_for_acute_coronary_syndrome_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators used by free-text search GIN indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information.

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    hospital_mrn VARCHAR(50),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    allergies_summary TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient demographic information used by the GRACE assessment record.';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Full patient name.';
COMMENT ON COLUMN patient.birth_date IS
    'Date of birth.';
COMMENT ON COLUMN patient.sex IS
    'Sex recorded for clinical purposes: female, male, intersex, or unknown.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.hospital_mrn IS
    'Local hospital medical record number (MRN).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height in centimetres.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight in kilograms.';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI), kg/m^2.';
COMMENT ON COLUMN patient.allergies_summary IS
    'Free-text summary of known allergies.';

CREATE INDEX patient_name_trgm_idx
    ON patient
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Clinician employee information used to identify the assessing
-- clinician (emergency physician, acute physician, cardiologist, nurse).

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN ('emergency-physician', 'acute-physician', 'cardiologist', 'nurse', 'other', '')),
    registration_body VARCHAR(20) NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'GPhC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician identifying information for the assessing clinician.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Clinician full name.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code.';
COMMENT ON COLUMN clinician.role IS
    'Primary clinical role: emergency-physician, acute-physician, cardiologist, nurse, or other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Professional registration body: GMC, NMC, HCPC, GPhC, or other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Professional registration number issued by the registration body.';

CREATE INDEX clinician_name_trgm_idx
    ON clinician
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_grace_score_for_acute_coronary_syndrome.sql
-- ========================================================================

-- Main GRACE assessment record: assessment context, patient
-- identification, and the eight GRACE variable inputs (age, heart rate,
-- systolic blood pressure, serum creatinine, Killip class, cardiac
-- arrest at admission, ST-segment deviation, elevated cardiac enzymes).
-- The computed grade, fired rules, and flags live in dedicated child
-- tables.

CREATE TABLE grace_score_for_acute_coronary_syndrome (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE RESTRICT,
    clinician_id UUID REFERENCES clinician(id) ON DELETE RESTRICT,

    -- Step 1: assessment context
    clinician_name VARCHAR(255) NOT NULL DEFAULT '',
    clinician_role VARCHAR(30) NOT NULL DEFAULT '' CHECK (clinician_role IN ('emergency-physician', 'acute-physician', 'cardiologist', 'nurse', 'other', '')),
    assessed_at TIMESTAMPTZ,
    care_setting VARCHAR(30) NOT NULL DEFAULT '' CHECK (care_setting IN ('emergency-department', 'acute-medical-unit', 'coronary-care-unit', 'cardiology-ward', 'other', '')),
    presentation_type VARCHAR(20) NOT NULL DEFAULT '' CHECK (presentation_type IN ('nstemi', 'unstable-angina', 'stemi', '')),

    -- Step 2: patient identification
    patient_identifier VARCHAR(100) NOT NULL DEFAULT '',
    age_years INT,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),

    -- Step 3: heart rate (variable 2)
    heart_rate INT,

    -- Step 4: systolic blood pressure (variable 3)
    systolic_blood_pressure INT,

    -- Step 5: serum creatinine (variable 4)
    serum_creatinine NUMERIC(6,2),
    serum_creatinine_unit VARCHAR(10) NOT NULL DEFAULT '' CHECK (serum_creatinine_unit IN ('mg/dL', 'umol/L', '')),

    -- Step 6: Killip class (variable 5)
    killip_class VARCHAR(3) NOT NULL DEFAULT '' CHECK (killip_class IN ('I', 'II', 'III', 'IV', '')),

    -- Step 7: cardiac arrest at admission (variable 6)
    cardiac_arrest_at_admission VARCHAR(3) NOT NULL DEFAULT '' CHECK (cardiac_arrest_at_admission IN ('yes', 'no', '')),

    -- Step 8: ST-segment deviation (variable 7)
    st_segment_deviation VARCHAR(3) NOT NULL DEFAULT '' CHECK (st_segment_deviation IN ('yes', 'no', '')),

    -- Step 9: elevated cardiac enzymes / troponin (variable 8)
    elevated_cardiac_enzymes VARCHAR(3) NOT NULL DEFAULT '' CHECK (elevated_cardiac_enzymes IN ('yes', 'no', '')),

    -- Step 10: clinician free-text note
    clinical_note TEXT NOT NULL DEFAULT ''
);

CREATE INDEX grace_score_for_acute_coronary_syndrome_patient_id_idx
    ON grace_score_for_acute_coronary_syndrome (patient_id);
CREATE INDEX grace_score_for_acute_coronary_syndrome_clinician_id_idx
    ON grace_score_for_acute_coronary_syndrome (clinician_id);

CREATE TRIGGER trigger_grace_score_for_acute_coronary_syndrome_updated_at
    BEFORE UPDATE ON grace_score_for_acute_coronary_syndrome
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE grace_score_for_acute_coronary_syndrome IS
    'Main GRACE assessment record: assessment context, patient identification, and the eight GRACE variable inputs (age, heart rate, systolic blood pressure, serum creatinine, Killip class, cardiac arrest at admission, ST-segment deviation, elevated cardiac enzymes).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.patient_id IS
    'Foreign key to the patient being assessed (delete restricted).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.clinician_id IS
    'Foreign key to the assessing clinician (optional; delete restricted).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.clinician_name IS
    'Name of the assessing clinician as recorded on the assessment.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.clinician_role IS
    'Role of the assessing clinician: emergency-physician, acute-physician, cardiologist, nurse, or other.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.assessed_at IS
    'Date and time the assessment was performed.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.care_setting IS
    'Care setting: emergency-department, acute-medical-unit, coronary-care-unit, cardiology-ward, or other.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.presentation_type IS
    'Acute coronary syndrome presentation: nstemi, unstable-angina, or stemi.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.patient_identifier IS
    'Local patient identifier as recorded on the assessment.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.age_years IS
    'Variable 1 — patient age in whole years.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.sex IS
    'Patient sex recorded for the assessment: female, male, intersex, or unknown.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.heart_rate IS
    'Variable 2 — admission heart rate in beats per minute.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.systolic_blood_pressure IS
    'Variable 3 — admission systolic blood pressure in mmHg (inverse weight: lower pressure scores higher).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.serum_creatinine IS
    'Variable 4 — measured serum creatinine (raw value; unit held separately). Normalised to mg/dL before banding.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.serum_creatinine_unit IS
    'Unit for the serum creatinine value: mg/dL or umol/L (umol/L divided by 88.4 to obtain mg/dL).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.killip_class IS
    'Variable 5 — Killip class of heart-failure severity: I, II, III, or IV.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.cardiac_arrest_at_admission IS
    'Variable 6 — cardiac arrest at admission: yes or no.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.st_segment_deviation IS
    'Variable 7 — ST-segment deviation on the admission ECG: yes or no.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.elevated_cardiac_enzymes IS
    'Variable 8 — elevated cardiac enzymes / troponin: yes or no.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome.clinical_note IS
    'Free-text clinical note recorded with the assessment.';

-- ========================================================================
-- END 04_create_table_grace_score_for_acute_coronary_syndrome.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_grace_score_for_acute_coronary_syndrome_grade.sql
-- ========================================================================

-- Computed GRACE grading result. Stores the weighted point total, the
-- in-hospital and 6-month mortality risk bands, the overall risk
-- category (worse of the two, max-band rule), and the derived
-- invasive-strategy recommendation.

CREATE TABLE grace_score_for_acute_coronary_syndrome_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    grace_score_for_acute_coronary_syndrome_id UUID NOT NULL UNIQUE
        REFERENCES grace_score_for_acute_coronary_syndrome(id) ON DELETE CASCADE,

    grace_score INT,
    in_hospital_risk_band VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (in_hospital_risk_band IN ('low', 'intermediate', 'high', '')),
    six_month_risk_band VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (six_month_risk_band IN ('low', 'intermediate', 'high', '')),
    overall_band VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (overall_band IN ('low', 'intermediate', 'high', '')),
    invasive_strategy TEXT NOT NULL DEFAULT '',

    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_grace_score_for_acute_coronary_syndrome_grade_updated_at
    BEFORE UPDATE ON grace_score_for_acute_coronary_syndrome_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE grace_score_for_acute_coronary_syndrome_grade IS
    'Computed GRACE grading result: weighted point total, in-hospital and 6-month mortality risk bands, overall risk category (max-band rule), and the derived invasive-strategy recommendation.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.grace_score_for_acute_coronary_syndrome_id IS
    'Foreign key to the parent assessment (unique, 1:1).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.grace_score IS
    'Weighted GRACE point total summed across the eight variable contributions.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.in_hospital_risk_band IS
    'In-hospital mortality band: low (<=108), intermediate (109-140), or high (>140).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.six_month_risk_band IS
    'Six-month mortality band: low (<=88), intermediate (89-118), or high (>118).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.overall_band IS
    'Overall risk category: the worse of the in-hospital and six-month bands (max-band rule).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.invasive_strategy IS
    'Derived invasive-strategy recommendation keyed on the overall risk category (e.g. early angiography within 24 h for high risk).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade.graded_at IS
    'Timestamp when the engine last computed the grade.';

-- ========================================================================
-- END 05_create_table_grace_score_for_acute_coronary_syndrome_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_grace_score_for_acute_coronary_syndrome_grade_rule.sql
-- ========================================================================

-- Audit trail of every grading rule (per-variable point contributor)
-- that fired during GRACE computation. Each row records one contributor
-- with the GRACE variable it belongs to, the points it contributed, and
-- a human-readable description.

CREATE TABLE grace_score_for_acute_coronary_syndrome_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    grace_score_for_acute_coronary_syndrome_grade_id UUID NOT NULL
        REFERENCES grace_score_for_acute_coronary_syndrome_grade(id) ON DELETE CASCADE,

    rule_id VARCHAR(40) NOT NULL,
    variable VARCHAR(20) NOT NULL
        CHECK (variable IN ('age', 'heart-rate', 'systolic-bp', 'creatinine', 'killip', 'cardiac-arrest', 'st-deviation', 'cardiac-enzymes', 'band')),
    points INT,
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX grace_score_for_acute_coronary_syndrome_grade_rule_grade_id_idx
    ON grace_score_for_acute_coronary_syndrome_grade_rule (grace_score_for_acute_coronary_syndrome_grade_id);

CREATE TRIGGER trigger_grace_score_for_acute_coronary_syndrome_grade_rule_updated_at
    BEFORE UPDATE ON grace_score_for_acute_coronary_syndrome_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE grace_score_for_acute_coronary_syndrome_grade_rule IS
    'Audit trail of every grading rule (per-variable point contributor) that fired during GRACE computation: GRACE variable, points contributed, category, and description.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.grace_score_for_acute_coronary_syndrome_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-AGE-BAND-04).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.variable IS
    'GRACE variable the contributor belongs to: age, heart-rate, systolic-bp, creatinine, killip, cardiac-arrest, st-deviation, cardiac-enzymes, or band.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.points IS
    'Weighted points contributed by this variable to the GRACE total.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.category IS
    'Subject category (e.g. weighted-band, mortality-band).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 06_create_table_grace_score_for_acute_coronary_syndrome_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_grace_score_for_acute_coronary_syndrome_grade_flag.sql
-- ========================================================================

-- Red-flag issues that fire independently of the total score, with
-- priority and a suggested action for the clinical team.

CREATE TABLE grace_score_for_acute_coronary_syndrome_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    grace_score_for_acute_coronary_syndrome_grade_id UUID NOT NULL
        REFERENCES grace_score_for_acute_coronary_syndrome_grade(id) ON DELETE CASCADE,

    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT ''
        CHECK (category IN (
            'high-risk-early-angiography',
            'cardiac-arrest',
            'killip-2-plus',
            'hypotension',
            'renal-impairment',
            'st-segment-deviation',
            'incomplete',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX grace_score_for_acute_coronary_syndrome_grade_flag_grade_id_idx
    ON grace_score_for_acute_coronary_syndrome_grade_flag (grace_score_for_acute_coronary_syndrome_grade_id);

CREATE TRIGGER trigger_grace_score_for_acute_coronary_syndrome_grade_flag_updated_at
    BEFORE UPDATE ON grace_score_for_acute_coronary_syndrome_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE grace_score_for_acute_coronary_syndrome_grade_flag IS
    'Red-flag issues that fire independently of the total score, with priority and a suggested action for the clinical team.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.grace_score_for_acute_coronary_syndrome_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-HIGH-RISK-EARLY-ANGIOGRAPHY-001).';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.category IS
    'Flag category (see CHECK constraint for enumeration): high-risk-early-angiography, cardiac-arrest, killip-2-plus, hypotension, renal-impairment, st-segment-deviation, incomplete, or other.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN grace_score_for_acute_coronary_syndrome_grade_flag.suggested_action IS
    'Suggested clinical action (e.g. "arrange coronary angiography within 24 h").';

-- ========================================================================
-- END 07_create_table_grace_score_for_acute_coronary_syndrome_grade_flag.sql
-- ========================================================================
