<!ELEMENT lumbar_puncture_test_result (id,created_at,updated_at,deleted_at,patient_id,clinician_id,originating_request_reference,report_status,performed_date,reported_date,clinical_history,opening_pressure_cmh2o,csf_appearance,csf_white_cell_count,csf_red_cell_count,csf_protein_g_l,csf_glucose_mmol_l,csf_serum_glucose_ratio,csf_lactate_mmol_l,gram_stain_result,culture_result,pcr_result,oligoclonal_bands,xanthochromia,raised_protein,pleocytosis,low_glucose,bacterial_meningitis_pattern,viral_pattern,subarachnoid_haemorrhage_suggested,normal_csf,findings_narrative,impression,reporting_category,recommended_follow_up,critical_result_communicated,reported_to)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT originating_request_reference (#PCDATA)>
<!ELEMENT report_status (#PCDATA)>
<!ELEMENT performed_date (#PCDATA)>
<!ELEMENT reported_date (#PCDATA)>
<!ELEMENT clinical_history (#PCDATA)>
<!ELEMENT opening_pressure_cmh2o (#PCDATA)>
<!ELEMENT csf_appearance (#PCDATA)>
<!ELEMENT csf_white_cell_count (#PCDATA)>
<!ELEMENT csf_red_cell_count (#PCDATA)>
<!ELEMENT csf_protein_g_l (#PCDATA)>
<!ELEMENT csf_glucose_mmol_l (#PCDATA)>
<!ELEMENT csf_serum_glucose_ratio (#PCDATA)>
<!ELEMENT csf_lactate_mmol_l (#PCDATA)>
<!ELEMENT gram_stain_result (#PCDATA)>
<!ELEMENT culture_result (#PCDATA)>
<!ELEMENT pcr_result (#PCDATA)>
<!ELEMENT oligoclonal_bands (#PCDATA)>
<!ELEMENT xanthochromia (#PCDATA)>
<!ELEMENT raised_protein (#PCDATA)>
<!ELEMENT pleocytosis (#PCDATA)>
<!ELEMENT low_glucose (#PCDATA)>
<!ELEMENT bacterial_meningitis_pattern (#PCDATA)>
<!ELEMENT viral_pattern (#PCDATA)>
<!ELEMENT subarachnoid_haemorrhage_suggested (#PCDATA)>
<!ELEMENT normal_csf (#PCDATA)>
<!ELEMENT findings_narrative (#PCDATA)>
<!ELEMENT impression (#PCDATA)>
<!ELEMENT reporting_category (#PCDATA)>
<!ELEMENT recommended_follow_up (#PCDATA)>
<!ELEMENT critical_result_communicated (#PCDATA)>
<!ELEMENT reported_to (#PCDATA)>
