<!ELEMENT agile_consulting_scorecard_for_hiring_help (id,created_at,updated_at,deleted_at,organization_id,respondent_id,status,assessment_date,submitted_at,finalized_at,m1_done,m1_evidence,m2_done,m2_evidence,m3_done,m3_evidence,m4_done,m4_evidence,p1_done,p1_evidence,p2_done,p2_evidence,p3_done,p3_evidence,p4_done,p4_evidence,p5_done,p5_evidence,p6_done,p6_evidence,p7_done,p7_evidence,p8_done,p8_evidence,p9_done,p9_evidence,p10_done,p10_evidence,p11_done,p11_evidence,p12_done,p12_evidence)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT organization_id (#PCDATA)>
<!ELEMENT respondent_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT assessment_date (#PCDATA)>
<!ELEMENT submitted_at (#PCDATA)>
<!ELEMENT finalized_at (#PCDATA)>
<!ELEMENT m1_done (#PCDATA)>
<!ELEMENT m1_evidence (#PCDATA)>
<!ELEMENT m2_done (#PCDATA)>
<!ELEMENT m2_evidence (#PCDATA)>
<!ELEMENT m3_done (#PCDATA)>
<!ELEMENT m3_evidence (#PCDATA)>
<!ELEMENT m4_done (#PCDATA)>
<!ELEMENT m4_evidence (#PCDATA)>
<!ELEMENT p1_done (#PCDATA)>
<!ELEMENT p1_evidence (#PCDATA)>
<!ELEMENT p2_done (#PCDATA)>
<!ELEMENT p2_evidence (#PCDATA)>
<!ELEMENT p3_done (#PCDATA)>
<!ELEMENT p3_evidence (#PCDATA)>
<!ELEMENT p4_done (#PCDATA)>
<!ELEMENT p4_evidence (#PCDATA)>
<!ELEMENT p5_done (#PCDATA)>
<!ELEMENT p5_evidence (#PCDATA)>
<!ELEMENT p6_done (#PCDATA)>
<!ELEMENT p6_evidence (#PCDATA)>
<!ELEMENT p7_done (#PCDATA)>
<!ELEMENT p7_evidence (#PCDATA)>
<!ELEMENT p8_done (#PCDATA)>
<!ELEMENT p8_evidence (#PCDATA)>
<!ELEMENT p9_done (#PCDATA)>
<!ELEMENT p9_evidence (#PCDATA)>
<!ELEMENT p10_done (#PCDATA)>
<!ELEMENT p10_evidence (#PCDATA)>
<!ELEMENT p11_done (#PCDATA)>
<!ELEMENT p11_evidence (#PCDATA)>
<!ELEMENT p12_done (#PCDATA)>
<!ELEMENT p12_evidence (#PCDATA)>
