import type { MedifAssessment } from './types.js';

export function createEmptyAssessment(): MedifAssessment {
  return {
    submitter: {
      submitterName: '',
      submitterRole: '',
      submitterEmail: '',
      submitterPhone: '',
      submitterOrganisation: '',
      airlineBookingReference: '',
    },
    passenger: {
      firstName: '',
      lastName: '',
      dateOfBirth: '',
      sex: '',
      nationality: '',
      passportNumber: '',
      nationalHealthId: '',
      address: '',
      emergencyContactName: '',
      emergencyContactPhone: '',
    },
    trip: {
      airlineIataCode: '',
      airlineName: '',
      outboundFlightNumber: '',
      outboundDate: '',
      outboundOriginIata: '',
      outboundDestinationIata: '',
      returnFlightNumber: '',
      returnDate: '',
      cabinClass: '',
      sectorDurationMinutes: null,
      transitAirportsIata: '',
      specialAssistanceCodes: '',
    },
    reasons: {
      reasonEquipment: '',
      reasonRecentAcuteEvent: '',
      reasonUnstableCondition: '',
      reasonCommunicableDisease: '',
      reasonPregnancy: '',
      reasonMobilityEscort: '',
      reasonPsychiatric: '',
    },
    physician: {
      physicianName: '',
      specialty: '',
      registrationBody: '',
      registrationNumber: '',
      clinic: '',
      email: '',
      phone: '',
      address: '',
      signatureDate: '',
    },
    diagnosis: {
      primaryDiagnosis: '',
      icd10Codes: '',
      diagnosisDate: '',
      currentTreatment: '',
      lastAdmissionDate: '',
      lastDischargeDate: '',
      lastSpecialistReviewDate: '',
    },
    cardiovascular: {
      restingSystolicBp: null,
      restingDiastolicBp: null,
      restingHeartRate: null,
      nyhaClass: '',
      recentMiDate: '',
      recentStentDate: '',
      onAnticoagulant: '',
      pacemakerOrIcd: '',
      exerciseToleranceMetres: null,
      unstableAngina: '',
    },
    respiratory: {
      restingSpo2Percent: null,
      predictedInflightSpo2Percent: null,
      hypoxicChallengeResult: '',
      recentPneumothoraxDate: '',
      asthmaSeverity: '',
      copdSeverity: '',
      cpapOrBipapUse: '',
      recentPulmonaryEmbolismDate: '',
    },
    recentEvents: {
      lastSurgeryDate: '',
      lastSurgerySite: '',
      cabinGasRisk: '',
      recentFractureCast: '',
      recentDvtDate: '',
      scubaDivingWithin24h: '',
      recentStrokeDate: '',
    },
    pregnancy: {
      isPregnant: '',
      gestationWeeks: null,
      pregnancyType: '',
      pregnancyComplications: '',
      expectedDeliveryDate: '',
      obstetricianContact: '',
    },
    communicable: {
      communicableDiseaseStatus: '',
      lastSymptomDate: '',
      isolationRequired: '',
      vaccinationStatus: '',
      currentAntimicrobials: '',
    },
    inflightNeeds: {
      requiresSupplementalOxygen: '',
      oxygenFlowRateLpm: null,
      oxygenDuration: '',
      requiresPoc: '',
      pocMakeModel: '',
      pocBatteryHours: null,
      requiresStretcher: '',
      requiresIncubator: '',
      requiresIvPump: '',
      requiresMedicalEscort: '',
      requiresExtraSeat: '',
      requiresAccessibleLavatory: '',
      wheelchairType: '',
      accompanyingCarer: '',
    },
    cabinMeds: {
      regularMedications: '',
      controlledDrugs: '',
      dangerousGoodsBatteryDeclaration: '',
      sharpsInCabin: '',
      refrigeratedMedication: '',
      customsDocumentationAvailable: '',
      haemoglobinGPerL: null,
    },
    signoff: {
      physicianDeclaration: '',
      physicianSignatureName: '',
      physicianSignatureDate: '',
      validUntilDate: '',
      additionalNotes: '',
    },
  };
}
