<!ELEMENT travel_vaccinations (id,created_at,updated_at,deleted_at,assessment_id,travel_planned,travel_destination,hepatitis_a,hepatitis_b,typhoid,yellow_fever,rabies,japanese_encephalitis)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT assessment_id (#PCDATA)>
<!ELEMENT travel_planned (#PCDATA)>
<!ELEMENT travel_destination (#PCDATA)>
<!ELEMENT hepatitis_a (#PCDATA)>
<!ELEMENT hepatitis_b (#PCDATA)>
<!ELEMENT typhoid (#PCDATA)>
<!ELEMENT yellow_fever (#PCDATA)>
<!ELEMENT rabies (#PCDATA)>
<!ELEMENT japanese_encephalitis (#PCDATA)>
