mod users;

mod patients;
mod practitioners;
mod resp_med_waiting_list_cards;
mod resp_med_waiting_list_card_appointments;
mod resp_med_waiting_list_card_grades;
mod resp_med_waiting_list_card_grade_rules;
mod resp_med_waiting_list_card_grade_flags;