<!ELEMENT center (id,created_at,updated_at,deleted_at,name,who_designation_reference,national_authority_reference,email,phone,postal_address_as_full_text,country_as_iso_3166_1_alpha_2,country_as_iso_3166_1_alpha_3,postcode,uniform_stamp_image_data_url,authorised_diseases,designation_valid_from,designation_valid_until)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT who_designation_reference (#PCDATA)>
<!ELEMENT national_authority_reference (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT postal_address_as_full_text (#PCDATA)>
<!ELEMENT country_as_iso_3166_1_alpha_2 (#PCDATA)>
<!ELEMENT country_as_iso_3166_1_alpha_3 (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT uniform_stamp_image_data_url (#PCDATA)>
<!ELEMENT authorised_diseases (#PCDATA)>
<!ELEMENT designation_valid_from (#PCDATA)>
<!ELEMENT designation_valid_until (#PCDATA)>
