<!ELEMENT international_certificate_of_vaccination_or_prophylaxis_entry (id,created_at,updated_at,deleted_at,international_certificate_of_vaccination_or_prophylaxis_id,entry_index,disease,disease_other_label,disease_as_snomed_ct,disease_as_icd_11,vaccine_or_prophylaxis_name,vaccine_as_snomed_ct,vaccine_as_atc,manufacturer,manufacturer_country_as_iso_3166_1_alpha_3,batch_number,lot_expiry_date,route,anatomical_site,dose_amount_value,dose_amount_unit,dose_sequence,dose_sequence_total,vaccination_date,vaccination_time,administered_by_clinician_id,administering_clinician_signature_data_url,administering_clinician_professional_status,validity_starts_on,validity_ends_on,validity_is_lifetime,centre_id,centre_stamp_image_data_url,centre_stamp_applied,adverse_event,adverse_event_notes,entry_valid,entry_notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT international_certificate_of_vaccination_or_prophylaxis_id (#PCDATA)>
<!ELEMENT entry_index (#PCDATA)>
<!ELEMENT disease (#PCDATA)>
<!ELEMENT disease_other_label (#PCDATA)>
<!ELEMENT disease_as_snomed_ct (#PCDATA)>
<!ELEMENT disease_as_icd_11 (#PCDATA)>
<!ELEMENT vaccine_or_prophylaxis_name (#PCDATA)>
<!ELEMENT vaccine_as_snomed_ct (#PCDATA)>
<!ELEMENT vaccine_as_atc (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT manufacturer_country_as_iso_3166_1_alpha_3 (#PCDATA)>
<!ELEMENT batch_number (#PCDATA)>
<!ELEMENT lot_expiry_date (#PCDATA)>
<!ELEMENT route (#PCDATA)>
<!ELEMENT anatomical_site (#PCDATA)>
<!ELEMENT dose_amount_value (#PCDATA)>
<!ELEMENT dose_amount_unit (#PCDATA)>
<!ELEMENT dose_sequence (#PCDATA)>
<!ELEMENT dose_sequence_total (#PCDATA)>
<!ELEMENT vaccination_date (#PCDATA)>
<!ELEMENT vaccination_time (#PCDATA)>
<!ELEMENT administered_by_clinician_id (#PCDATA)>
<!ELEMENT administering_clinician_signature_data_url (#PCDATA)>
<!ELEMENT administering_clinician_professional_status (#PCDATA)>
<!ELEMENT validity_starts_on (#PCDATA)>
<!ELEMENT validity_ends_on (#PCDATA)>
<!ELEMENT validity_is_lifetime (#PCDATA)>
<!ELEMENT centre_id (#PCDATA)>
<!ELEMENT centre_stamp_image_data_url (#PCDATA)>
<!ELEMENT centre_stamp_applied (#PCDATA)>
<!ELEMENT adverse_event (#PCDATA)>
<!ELEMENT adverse_event_notes (#PCDATA)>
<!ELEMENT entry_valid (#PCDATA)>
<!ELEMENT entry_notes (#PCDATA)>
