<!ELEMENT patient (id,created_at,updated_at,deleted_at,surname,given_names,birth_date,sex,nationality_as_iso_3166_1_alpha_3,travel_document_kind,travel_document_number,travel_document_issuer_as_iso_3166_1_alpha_3,email,phone,postal_address_as_full_text,country_as_iso_3166_1_alpha_2,postcode,consented_to_data_sharing,signature_image_data_url)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT given_names (#PCDATA)>
<!ELEMENT birth_date (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT nationality_as_iso_3166_1_alpha_3 (#PCDATA)>
<!ELEMENT travel_document_kind (#PCDATA)>
<!ELEMENT travel_document_number (#PCDATA)>
<!ELEMENT travel_document_issuer_as_iso_3166_1_alpha_3 (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT postal_address_as_full_text (#PCDATA)>
<!ELEMENT country_as_iso_3166_1_alpha_2 (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT consented_to_data_sharing (#PCDATA)>
<!ELEMENT signature_image_data_url (#PCDATA)>
