<!ELEMENT signature_witness (id,created_at,updated_at,deleted_at,hipaa_authorization_id,individual_signature_confirmed,individual_signature_image_uri,signature_date,signed_at_location,parent_guardian_co_signature_required,parent_guardian_name,parent_guardian_signature_confirmed,parent_guardian_signature_date,witness_name,witness_signature_confirmed,witness_date,witness_role)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT hipaa_authorization_id (#PCDATA)>
<!ELEMENT individual_signature_confirmed (#PCDATA)>
<!ELEMENT individual_signature_image_uri (#PCDATA)>
<!ELEMENT signature_date (#PCDATA)>
<!ELEMENT signed_at_location (#PCDATA)>
<!ELEMENT parent_guardian_co_signature_required (#PCDATA)>
<!ELEMENT parent_guardian_name (#PCDATA)>
<!ELEMENT parent_guardian_signature_confirmed (#PCDATA)>
<!ELEMENT parent_guardian_signature_date (#PCDATA)>
<!ELEMENT witness_name (#PCDATA)>
<!ELEMENT witness_signature_confirmed (#PCDATA)>
<!ELEMENT witness_date (#PCDATA)>
<!ELEMENT witness_role (#PCDATA)>
