<!ELEMENT angiography_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,angiography_type,body_region,primary_indication,clinical_question,relevant_history,contrast_required,egfr,contrast_allergy,diabetes,metformin,taking_anticoagulant,anticoagulant_agent,taking_antiplatelet,bleeding_disorder,pregnancy_status,urgency,ir_me_r_justification,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT angiography_type (#PCDATA)>
<!ELEMENT body_region (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT contrast_required (#PCDATA)>
<!ELEMENT egfr (#PCDATA)>
<!ELEMENT contrast_allergy (#PCDATA)>
<!ELEMENT diabetes (#PCDATA)>
<!ELEMENT metformin (#PCDATA)>
<!ELEMENT taking_anticoagulant (#PCDATA)>
<!ELEMENT anticoagulant_agent (#PCDATA)>
<!ELEMENT taking_antiplatelet (#PCDATA)>
<!ELEMENT bleeding_disorder (#PCDATA)>
<!ELEMENT pregnancy_status (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT ir_me_r_justification (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
