import type { Arc42Documentation } from './types.js';

export function createEmptyDocumentation(): Arc42Documentation {
  return {
    architecture: { name: '', version: '', owner: '', status: '', description: '' },
    authorName: '',
    authorRole: '',
    documentDate: '',
    introduction: '',
    businessGoals: [],
    qualityGoals: [],
    stakeholders: [],
    constraintItems: [],
    businessContextDescription: '',
    technicalContextDescription: '',
    contextPartners: [],
    solutionStrategySummary: '',
    technologyDecisions: [],
    topLevelDecompositionSummary: '',
    qualityStrategies: [],
    buildingBlockOverview: '',
    buildingBlocks: [],
    runtimeOverview: '',
    runtimeScenarios: [],
    deploymentOverview: '',
    deploymentNodes: [],
    crosscuttingOverview: '',
    crosscuttingConcepts: [],
    architecturalDecisions: [],
    qualityTreeSummary: '',
    qualityScenarios: [],
    riskItems: [],
    glossaryTerms: [],
    recommendation: '',
    additionalNotes: '',
    signedBy: '',
    signedAt: '',
    finalMaturityOverride: '',
    finalMaturityOverrideReason: '',
  };
}
