//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::abdominal_aortic_aneurysm_screening_grade_flags::Entity as AbdominalAorticAneurysmScreeningGradeFlags;
pub use super::abdominal_aortic_aneurysm_screening_grade_rules::Entity as AbdominalAorticAneurysmScreeningGradeRules;
pub use super::abdominal_aortic_aneurysm_screening_grades::Entity as AbdominalAorticAneurysmScreeningGrades;
pub use super::abdominal_aortic_aneurysm_screenings::Entity as AbdominalAorticAneurysmScreenings;
pub use super::clinicians::Entity as Clinicians;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
