<!ELEMENT dietic_assessment_grade_rule (id,created_at,updated_at,deleted_at,dietic_assessment_grade_id,rule_id,instrument,component,score,band,category,description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT dietic_assessment_grade_id (#PCDATA)>
<!ELEMENT rule_id (#PCDATA)>
<!ELEMENT instrument (#PCDATA)>
<!ELEMENT component (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT band (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT description (#PCDATA)>
