<!ELEMENT modified_early_warning_score (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,observation_at,care_setting,ward_or_location,systolic_blood_pressure,heart_rate,respiratory_rate,temperature,consciousness_avpu,previous_mews_score,clinical_notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT observation_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT ward_or_location (#PCDATA)>
<!ELEMENT systolic_blood_pressure (#PCDATA)>
<!ELEMENT heart_rate (#PCDATA)>
<!ELEMENT respiratory_rate (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ELEMENT consciousness_avpu (#PCDATA)>
<!ELEMENT previous_mews_score (#PCDATA)>
<!ELEMENT clinical_notes (#PCDATA)>
