<!ELEMENT tumor_marker_test_result (id,created_at,updated_at,deleted_at,patient_id,clinician_id,originating_request_reference,report_status,performed_date,reported_date,specimen_condition,clinical_history,known_cancer_site,psa,ca125,ca19_9,carcinoembryonic_antigen_cea,alpha_fetoprotein_afp,beta_hcg,ca15_3,lactate_dehydrogenase_ldh,calcitonin,chromogranin_a,previous_value,trend,comparison_with_previous,overall_result_status,markedly_elevated,findings_narrative,impression,reporting_category,recommended_follow_up,critical_result_communicated,reported_to)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT originating_request_reference (#PCDATA)>
<!ELEMENT report_status (#PCDATA)>
<!ELEMENT performed_date (#PCDATA)>
<!ELEMENT reported_date (#PCDATA)>
<!ELEMENT specimen_condition (#PCDATA)>
<!ELEMENT clinical_history (#PCDATA)>
<!ELEMENT known_cancer_site (#PCDATA)>
<!ELEMENT psa (#PCDATA)>
<!ELEMENT ca125 (#PCDATA)>
<!ELEMENT ca19_9 (#PCDATA)>
<!ELEMENT carcinoembryonic_antigen_cea (#PCDATA)>
<!ELEMENT alpha_fetoprotein_afp (#PCDATA)>
<!ELEMENT beta_hcg (#PCDATA)>
<!ELEMENT ca15_3 (#PCDATA)>
<!ELEMENT lactate_dehydrogenase_ldh (#PCDATA)>
<!ELEMENT calcitonin (#PCDATA)>
<!ELEMENT chromogranin_a (#PCDATA)>
<!ELEMENT previous_value (#PCDATA)>
<!ELEMENT trend (#PCDATA)>
<!ELEMENT comparison_with_previous (#PCDATA)>
<!ELEMENT overall_result_status (#PCDATA)>
<!ELEMENT markedly_elevated (#PCDATA)>
<!ELEMENT findings_narrative (#PCDATA)>
<!ELEMENT impression (#PCDATA)>
<!ELEMENT reporting_category (#PCDATA)>
<!ELEMENT recommended_follow_up (#PCDATA)>
<!ELEMENT critical_result_communicated (#PCDATA)>
<!ELEMENT reported_to (#PCDATA)>
