import type { PatientRow } from './types.ts';

/** Sample patient referrals for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		patientName: 'Smith, Jane',
		dateOfBirth: '1972-03-14',
		sex: 'F',
		initiatingFacility: 'Riverside Community Hospital',
		referralFacility: 'St Mary Tertiary Care Centre',
		modeOfTransfer: 'road',
		primaryDiagnosis: 'Acute myocardial infarction',
		transferStatus: 'feedback-received',
		urgentFlagCount: 2,
		departureTime: '2026-04-12T08:30:00Z',
		arrivalTime: '2026-04-12T09:55:00Z',
	},
	{
		id: '2',
		patientName: 'Patel, Priya',
		dateOfBirth: '1989-11-02',
		sex: 'F',
		initiatingFacility: 'Greenfield District Hospital',
		referralFacility: 'University Teaching Hospital',
		modeOfTransfer: 'air',
		primaryDiagnosis: 'Severe traumatic brain injury',
		transferStatus: 'arrived',
		urgentFlagCount: 3,
		departureTime: '2026-04-13T13:05:00Z',
		arrivalTime: '2026-04-13T14:40:00Z',
	},
	{
		id: '3',
		patientName: 'Jones, Margaret',
		dateOfBirth: '1955-06-21',
		sex: 'F',
		initiatingFacility: 'Coastal Rural Clinic',
		referralFacility: 'Regional Referral Hospital',
		modeOfTransfer: 'sea',
		primaryDiagnosis: 'Septic shock',
		transferStatus: 'in-transit',
		urgentFlagCount: 2,
		departureTime: '2026-04-14T09:50:00Z',
		arrivalTime: null,
	},
	{
		id: '4',
		patientName: 'Williams, David',
		dateOfBirth: '1968-09-08',
		sex: 'M',
		initiatingFacility: 'Northbridge Urgent Care',
		referralFacility: 'Central Trauma Centre',
		modeOfTransfer: 'road',
		primaryDiagnosis: 'Polytrauma — motor vehicle collision',
		transferStatus: 'in-transit',
		urgentFlagCount: 1,
		departureTime: '2026-04-15T07:20:00Z',
		arrivalTime: null,
	},
	{
		id: '5',
		patientName: 'Brown, Sarah',
		dateOfBirth: '1991-01-30',
		sex: 'F',
		initiatingFacility: 'Eastside Maternity Clinic',
		referralFacility: 'University Teaching Hospital',
		modeOfTransfer: 'road',
		primaryDiagnosis: 'Severe postpartum haemorrhage',
		transferStatus: 'arrived',
		urgentFlagCount: 3,
		departureTime: '2026-04-16T15:45:00Z',
		arrivalTime: '2026-04-16T16:25:00Z',
	},
	{
		id: '6',
		patientName: 'Taylor, James',
		dateOfBirth: '1980-07-19',
		sex: 'M',
		initiatingFacility: 'Lakeside Community Hospital',
		referralFacility: 'Cardiac Specialist Centre',
		modeOfTransfer: 'road',
		primaryDiagnosis: 'Unstable angina',
		transferStatus: 'feedback-received',
		urgentFlagCount: 0,
		departureTime: '2026-04-17T10:10:00Z',
		arrivalTime: '2026-04-17T11:35:00Z',
	},
	{
		id: '7',
		patientName: 'Davies, Helen',
		dateOfBirth: '1947-12-04',
		sex: 'F',
		initiatingFacility: 'Riverside Community Hospital',
		referralFacility: 'Stroke Unit — Central',
		modeOfTransfer: 'road',
		primaryDiagnosis: 'Acute ischaemic stroke',
		transferStatus: 'initiated',
		urgentFlagCount: 1,
		departureTime: '2026-04-18T13:00:00Z',
		arrivalTime: null,
	},
	{
		id: '8',
		patientName: 'Wilson, Robert',
		dateOfBirth: '1962-04-27',
		sex: 'M',
		initiatingFacility: 'Highland Remote Clinic',
		referralFacility: 'Regional Referral Hospital',
		modeOfTransfer: 'air',
		primaryDiagnosis: 'Massive pulmonary embolism',
		transferStatus: 'in-transit',
		urgentFlagCount: 2,
		departureTime: '2026-04-19T14:55:00Z',
		arrivalTime: null,
	},
	{
		id: '9',
		patientName: 'Evans, Catherine',
		dateOfBirth: '1996-10-12',
		sex: 'F',
		initiatingFacility: 'Westgate Family Practice',
		referralFacility: 'University Teaching Hospital',
		modeOfTransfer: 'road',
		primaryDiagnosis: 'Diabetic ketoacidosis',
		transferStatus: 'arrived',
		urgentFlagCount: 1,
		departureTime: '2026-04-20T10:00:00Z',
		arrivalTime: '2026-04-20T11:10:00Z',
	},
	{
		id: '10',
		patientName: 'Thomas, Michael',
		dateOfBirth: '1958-08-15',
		sex: 'M',
		initiatingFacility: 'Island Coastal Clinic',
		referralFacility: 'Central Trauma Centre',
		modeOfTransfer: 'sea',
		primaryDiagnosis: 'Penetrating chest trauma',
		transferStatus: 'feedback-received',
		urgentFlagCount: 3,
		departureTime: '2026-04-21T09:00:00Z',
		arrivalTime: '2026-04-21T11:45:00Z',
	},
	{
		id: '11',
		patientName: 'Robinson, Emma',
		dateOfBirth: '2003-02-09',
		sex: 'F',
		initiatingFacility: 'Greenfield District Hospital',
		referralFacility: 'Regional Referral Hospital',
		modeOfTransfer: 'road',
		primaryDiagnosis: 'Status epilepticus',
		transferStatus: 'initiated',
		urgentFlagCount: 1,
		departureTime: '2026-04-22T14:00:00Z',
		arrivalTime: null,
	},
	{
		id: '12',
		patientName: 'Clark, George',
		dateOfBirth: '1944-05-25',
		sex: 'M',
		initiatingFacility: 'Northbridge Urgent Care',
		referralFacility: 'Cardiac Specialist Centre',
		modeOfTransfer: 'air',
		primaryDiagnosis: 'Aortic dissection',
		transferStatus: 'arrived',
		urgentFlagCount: 2,
		departureTime: '2026-04-23T11:25:00Z',
		arrivalTime: '2026-04-23T12:30:00Z',
	},
];
