//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod anaesthetics_waiting_list_card_appointments;
pub mod anaesthetics_waiting_list_card_grade_flags;
pub mod anaesthetics_waiting_list_card_grade_rules;
pub mod anaesthetics_waiting_list_card_grades;
pub mod anaesthetics_waiting_list_cards;
pub mod patients;
pub mod practitioners;
pub mod users;
