//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::anaesthetics_waiting_list_card_appointments::Entity as AnaestheticsWaitingListCardAppointments;
pub use super::anaesthetics_waiting_list_card_grade_flags::Entity as AnaestheticsWaitingListCardGradeFlags;
pub use super::anaesthetics_waiting_list_card_grade_rules::Entity as AnaestheticsWaitingListCardGradeRules;
pub use super::anaesthetics_waiting_list_card_grades::Entity as AnaestheticsWaitingListCardGrades;
pub use super::anaesthetics_waiting_list_cards::Entity as AnaestheticsWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
