<!ELEMENT casualty_card_demographics (id,created_at,updated_at,deleted_at,casualty_card_id,address,postcode,phone,email,ethnicity,preferred_language,interpreter_required)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT casualty_card_id (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT ethnicity (#PCDATA)>
<!ELEMENT preferred_language (#PCDATA)>
<!ELEMENT interpreter_required (#PCDATA)>
