<!ELEMENT casualty_card_arrival_triage (id,created_at,updated_at,deleted_at,casualty_card_id,attendance_category,arrival_mode,referral_source,ambulance_incident_number,triage_time,triage_nurse,mts_flowchart,mts_category,mts_discriminator)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT casualty_card_id (#PCDATA)>
<!ELEMENT attendance_category (#PCDATA)>
<!ELEMENT arrival_mode (#PCDATA)>
<!ELEMENT referral_source (#PCDATA)>
<!ELEMENT ambulance_incident_number (#PCDATA)>
<!ELEMENT triage_time (#PCDATA)>
<!ELEMENT triage_nurse (#PCDATA)>
<!ELEMENT mts_flowchart (#PCDATA)>
<!ELEMENT mts_category (#PCDATA)>
<!ELEMENT mts_discriminator (#PCDATA)>
