<!ELEMENT microbiology_culture_test_result (id,created_at,updated_at,deleted_at,patient_id,clinician_id,originating_request_reference,report_status,performed_date,reported_date,specimen_type,specimen_site_detail,specimen_condition,clinical_history,gram_stain_result,culture_result,organism_isolated,second_organism_isolated,colony_count,antibiotic_sensitivities,resistance_mrsa,resistance_esbl,resistance_cpe,c_difficile_toxin,acid_fast_bacilli,pcr_result,critical_organism,findings_narrative,impression,reporting_category,recommended_follow_up,critical_result_communicated,reported_to)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT originating_request_reference (#PCDATA)>
<!ELEMENT report_status (#PCDATA)>
<!ELEMENT performed_date (#PCDATA)>
<!ELEMENT reported_date (#PCDATA)>
<!ELEMENT specimen_type (#PCDATA)>
<!ELEMENT specimen_site_detail (#PCDATA)>
<!ELEMENT specimen_condition (#PCDATA)>
<!ELEMENT clinical_history (#PCDATA)>
<!ELEMENT gram_stain_result (#PCDATA)>
<!ELEMENT culture_result (#PCDATA)>
<!ELEMENT organism_isolated (#PCDATA)>
<!ELEMENT second_organism_isolated (#PCDATA)>
<!ELEMENT colony_count (#PCDATA)>
<!ELEMENT antibiotic_sensitivities (#PCDATA)>
<!ELEMENT resistance_mrsa (#PCDATA)>
<!ELEMENT resistance_esbl (#PCDATA)>
<!ELEMENT resistance_cpe (#PCDATA)>
<!ELEMENT c_difficile_toxin (#PCDATA)>
<!ELEMENT acid_fast_bacilli (#PCDATA)>
<!ELEMENT pcr_result (#PCDATA)>
<!ELEMENT critical_organism (#PCDATA)>
<!ELEMENT findings_narrative (#PCDATA)>
<!ELEMENT impression (#PCDATA)>
<!ELEMENT reporting_category (#PCDATA)>
<!ELEMENT recommended_follow_up (#PCDATA)>
<!ELEMENT critical_result_communicated (#PCDATA)>
<!ELEMENT reported_to (#PCDATA)>
