<!ELEMENT eye_prescription_lens_recommendation (id,created_at,updated_at,deleted_at,eye_prescription_id,lens_type,material,refractive_index,aspheric,coating_anti_reflective,coating_scratch_resistant,coating_hydrophobic,coating_blue_light,coating_photochromic,coating_polarised,coating_uv_400,tint_description,tint_percent,dispenser_notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT eye_prescription_id (#PCDATA)>
<!ELEMENT lens_type (#PCDATA)>
<!ELEMENT material (#PCDATA)>
<!ELEMENT refractive_index (#PCDATA)>
<!ELEMENT aspheric (#PCDATA)>
<!ELEMENT coating_anti_reflective (#PCDATA)>
<!ELEMENT coating_scratch_resistant (#PCDATA)>
<!ELEMENT coating_hydrophobic (#PCDATA)>
<!ELEMENT coating_blue_light (#PCDATA)>
<!ELEMENT coating_photochromic (#PCDATA)>
<!ELEMENT coating_polarised (#PCDATA)>
<!ELEMENT coating_uv_400 (#PCDATA)>
<!ELEMENT tint_description (#PCDATA)>
<!ELEMENT tint_percent (#PCDATA)>
<!ELEMENT dispenser_notes (#PCDATA)>
