<!ELEMENT eye_prescription_ocular_health_finding (id,created_at,updated_at,deleted_at,eye_prescription_id,slit_lamp_right,slit_lamp_left,fundus_right,fundus_left,intraocular_pressure_right_mmhg,intraocular_pressure_left_mmhg,cup_to_disc_ratio_right,cup_to_disc_ratio_left,oct_performed,oct_findings,fields_performed,fields_findings,pathology_flag,refer_ophthalmology,referral_reason)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT eye_prescription_id (#PCDATA)>
<!ELEMENT slit_lamp_right (#PCDATA)>
<!ELEMENT slit_lamp_left (#PCDATA)>
<!ELEMENT fundus_right (#PCDATA)>
<!ELEMENT fundus_left (#PCDATA)>
<!ELEMENT intraocular_pressure_right_mmhg (#PCDATA)>
<!ELEMENT intraocular_pressure_left_mmhg (#PCDATA)>
<!ELEMENT cup_to_disc_ratio_right (#PCDATA)>
<!ELEMENT cup_to_disc_ratio_left (#PCDATA)>
<!ELEMENT oct_performed (#PCDATA)>
<!ELEMENT oct_findings (#PCDATA)>
<!ELEMENT fields_performed (#PCDATA)>
<!ELEMENT fields_findings (#PCDATA)>
<!ELEMENT pathology_flag (#PCDATA)>
<!ELEMENT refer_ophthalmology (#PCDATA)>
<!ELEMENT referral_reason (#PCDATA)>
