pub mod _entities;
pub mod users;
pub mod patients;
pub mod practitioners;
pub mod cardiology_waiting_list_cards;
pub mod cardiology_waiting_list_card_appointments;
pub mod cardiology_waiting_list_card_grades;
pub mod cardiology_waiting_list_card_grade_rules;
pub mod cardiology_waiting_list_card_grade_flags;
