<!ELEMENT learning_disability_annual_health_check_grade (id,created_at,updated_at,deleted_at,learning_disability_annual_health_check_id,status,completeness_percent,health_action_plan_complete,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT learning_disability_annual_health_check_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT completeness_percent (#PCDATA)>
<!ELEMENT health_action_plan_complete (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
