mod users;

mod assessors;
mod products;
mod suppliers;
mod uk_nhs_digital_technology_assessment_criteria;
mod uk_nhs_digital_technology_assessment_criteria_grade_flags;
mod uk_nhs_digital_technology_assessment_criteria_grade_rules;
mod uk_nhs_digital_technology_assessment_criteria_grades;
