<!ELEMENT worker (id,created_at,updated_at,deleted_at,name,email,phone,postal_address_as_full_text,country_as_iso_3166_1_alpha_2,postcode,employee_reference,job_title,department,employment_type,work_pattern,work_location,employment_start_date)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT postal_address_as_full_text (#PCDATA)>
<!ELEMENT country_as_iso_3166_1_alpha_2 (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT employee_reference (#PCDATA)>
<!ELEMENT job_title (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT employment_type (#PCDATA)>
<!ELEMENT work_pattern (#PCDATA)>
<!ELEMENT work_location (#PCDATA)>
<!ELEMENT employment_start_date (#PCDATA)>
