//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::dexa_bone_density_test_request_grade_flags::Entity as DexaBoneDensityTestRequestGradeFlags;
pub use super::dexa_bone_density_test_request_grade_rules::Entity as DexaBoneDensityTestRequestGradeRules;
pub use super::dexa_bone_density_test_request_grades::Entity as DexaBoneDensityTestRequestGrades;
pub use super::dexa_bone_density_test_requests::Entity as DexaBoneDensityTestRequests;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
