<!ELEMENT wells_score_for_pulmonary_embolism (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,patient_identifier,assessed_at,care_setting,age_band,haemodynamic_status,clinical_signs_of_dvt,pe_most_likely,heart_rate_over_100,immobilisation_or_surgery,previous_dvt_pe,haemoptysis,malignancy,clinical_notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT age_band (#PCDATA)>
<!ELEMENT haemodynamic_status (#PCDATA)>
<!ELEMENT clinical_signs_of_dvt (#PCDATA)>
<!ELEMENT pe_most_likely (#PCDATA)>
<!ELEMENT heart_rate_over_100 (#PCDATA)>
<!ELEMENT immobilisation_or_surgery (#PCDATA)>
<!ELEMENT previous_dvt_pe (#PCDATA)>
<!ELEMENT haemoptysis (#PCDATA)>
<!ELEMENT malignancy (#PCDATA)>
<!ELEMENT clinical_notes (#PCDATA)>
