//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::assessments::Entity as Assessments;
pub use super::clinicians::Entity as Clinicians;
pub use super::grades::Entity as Grades;
pub use super::grading_fired_rules::Entity as GradingFiredRules;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
