-- schema.sql
-- Combined schema for form: alcohol-use-disorders-identification-test-consumption
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (8):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_audit_c.sql
--   - 05_create_table_audit_c_grade.sql
--   - 06_create_table_audit_c_grade_rule.sql
--   - 07_create_table_audit_c_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators used by free-text search GIN indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information.

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    hospital_mrn VARCHAR(50),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    allergies_summary TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient demographic information used by the AUDIT-C assessment record.';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Full patient name.';
COMMENT ON COLUMN patient.birth_date IS
    'Date of birth.';
COMMENT ON COLUMN patient.sex IS
    'Sex recorded for clinical purposes: female, male, intersex, or unknown.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.hospital_mrn IS
    'Local hospital medical record number (MRN).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height in centimetres.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight in kilograms.';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI), kg/m^2.';
COMMENT ON COLUMN patient.allergies_summary IS
    'Free-text summary of known allergies.';

CREATE INDEX patient_name_trgm_idx
    ON patient
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Clinician employee information used to identify the clinician who
-- administered the AUDIT-C screen (GP, nurse, healthcare assistant).

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN ('gp', 'nurse', 'healthcare-assistant', 'other', '')),
    registration_body VARCHAR(20) NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'GPhC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician identifying information for the clinician who administered the AUDIT-C screen.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Clinician full name.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code.';
COMMENT ON COLUMN clinician.role IS
    'Primary clinical role: gp, nurse, healthcare-assistant, or other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Professional registration body: GMC, NMC, HCPC, GPhC, or other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Professional registration number issued by the registration body.';

CREATE INDEX clinician_name_trgm_idx
    ON clinician
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_audit_c.sql
-- ========================================================================

-- Main AUDIT-C assessment record: assessment context, patient
-- identification, and the three scored consumption item inputs (Q1
-- frequency of drinking, Q2 typical quantity, Q3 frequency of heavy
-- episodic drinking). The computed grade, fired rules, and flags live
-- in dedicated child tables.
--
-- Uses the short table base `audit_c` because the form slug
-- (alcohol-use-disorders-identification-test-consumption) would exceed
-- PostgreSQL's 63-byte identifier limit for derived table, index, and
-- trigger names.

CREATE TABLE audit_c (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE RESTRICT,
    clinician_id UUID REFERENCES clinician(id) ON DELETE RESTRICT,

    -- Step 1: assessment context
    clinician_name VARCHAR(255) NOT NULL DEFAULT '',
    clinician_role VARCHAR(30) NOT NULL DEFAULT '' CHECK (clinician_role IN ('gp', 'nurse', 'healthcare-assistant', 'other', '')),
    assessed_at TIMESTAMPTZ,
    care_setting VARCHAR(30) NOT NULL DEFAULT '' CHECK (care_setting IN ('primary-care', 'emergency-department', 'health-check', 'inpatient', 'other', '')),
    administration_mode VARCHAR(20) NOT NULL DEFAULT '' CHECK (administration_mode IN ('self-completed', 'interview', '')),

    -- Step 2: patient identification
    patient_identifier VARCHAR(100) NOT NULL DEFAULT '',
    age_band VARCHAR(10) NOT NULL DEFAULT '' CHECK (age_band IN ('16-24', '25-39', '40-59', '60-74', '75-plus', '')),
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),

    -- Step 3: Q1 — frequency of drinking (item 1); response point value 0-4
    item_1_frequency SMALLINT CHECK (item_1_frequency BETWEEN 0 AND 4),

    -- Step 4: Q2 — typical quantity in UK units on a drinking day (item 2); response point value 0-4
    item_2_quantity SMALLINT CHECK (item_2_quantity BETWEEN 0 AND 4),

    -- Step 5: Q3 — frequency of heavy episodic (binge) drinking (item 3); response point value 0-4
    item_3_binge_frequency SMALLINT CHECK (item_3_binge_frequency BETWEEN 0 AND 4),

    -- Step 6: clinician free-text note
    context TEXT NOT NULL DEFAULT ''
);

CREATE INDEX audit_c_patient_id_idx
    ON audit_c (patient_id);
CREATE INDEX audit_c_clinician_id_idx
    ON audit_c (clinician_id);

CREATE TRIGGER trigger_audit_c_updated_at
    BEFORE UPDATE ON audit_c
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE audit_c IS
    'Main AUDIT-C assessment record: assessment context, patient identification, and the three scored consumption item inputs (Q1 frequency of drinking, Q2 typical quantity, Q3 frequency of heavy episodic drinking). Uses the short table base audit_c to stay within PostgreSQL identifier limits.';
COMMENT ON COLUMN audit_c.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN audit_c.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN audit_c.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN audit_c.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN audit_c.patient_id IS
    'Foreign key to the patient being screened (delete restricted).';
COMMENT ON COLUMN audit_c.clinician_id IS
    'Foreign key to the administering clinician (optional; delete restricted).';
COMMENT ON COLUMN audit_c.clinician_name IS
    'Name of the administering clinician as recorded on the assessment.';
COMMENT ON COLUMN audit_c.clinician_role IS
    'Role of the administering clinician: gp, nurse, healthcare-assistant, or other.';
COMMENT ON COLUMN audit_c.assessed_at IS
    'Date and time the AUDIT-C screen was administered.';
COMMENT ON COLUMN audit_c.care_setting IS
    'Care setting: primary-care, emergency-department, health-check, inpatient, or other.';
COMMENT ON COLUMN audit_c.administration_mode IS
    'How the screen was administered: self-completed by the patient or by interview.';
COMMENT ON COLUMN audit_c.patient_identifier IS
    'Local patient identifier as recorded on the assessment.';
COMMENT ON COLUMN audit_c.age_band IS
    'Adult age band: 16-24, 25-39, 40-59, 60-74, or 75-plus.';
COMMENT ON COLUMN audit_c.sex IS
    'Patient sex recorded for the assessment: female, male, intersex, or unknown. Selects the Q3 heavy-episode threshold (>= 6 units female, >= 8 units male) and the sex-specific low-cut flag.';
COMMENT ON COLUMN audit_c.item_1_frequency IS
    'Q1 (item 1) — chosen response point value (0-4) for how often the patient drinks; null when unanswered.';
COMMENT ON COLUMN audit_c.item_2_quantity IS
    'Q2 (item 2) — chosen response point value (0-4) for the typical number of UK units on a drinking day; null when unanswered.';
COMMENT ON COLUMN audit_c.item_3_binge_frequency IS
    'Q3 (item 3) — chosen response point value (0-4) for how often the patient has a heavy episodic (binge) drinking session; null when unanswered.';
COMMENT ON COLUMN audit_c.context IS
    'Free-text clinical note recorded with the assessment.';

-- ========================================================================
-- END 04_create_table_audit_c.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_audit_c_grade.sql
-- ========================================================================

-- Computed AUDIT-C grading result. Stores the summed total (0-12), the
-- derived risk band, and whether the total meets the positive-screen
-- cut (>= 5).

CREATE TABLE audit_c_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    audit_c_id UUID NOT NULL UNIQUE
        REFERENCES audit_c(id) ON DELETE CASCADE,

    total_score INT,
    risk_band VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (risk_band IN ('lower', 'increasing', 'higher', 'possible-dependence', '')),
    positive_screen VARCHAR(3) NOT NULL DEFAULT ''
        CHECK (positive_screen IN ('yes', 'no', '')),

    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_audit_c_grade_updated_at
    BEFORE UPDATE ON audit_c_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE audit_c_grade IS
    'Computed AUDIT-C grading result (1:1 with audit_c): summed total (0-12), derived risk band, and positive-screen indicator (total >= 5).';
COMMENT ON COLUMN audit_c_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN audit_c_grade.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN audit_c_grade.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN audit_c_grade.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN audit_c_grade.audit_c_id IS
    'Foreign key to the parent assessment (unique, 1:1).';
COMMENT ON COLUMN audit_c_grade.total_score IS
    'Summed AUDIT-C score across the three consumption items (0-12); a missing item contributes 0.';
COMMENT ON COLUMN audit_c_grade.risk_band IS
    'Derived risk band: lower (0-4), increasing (5-7), higher (8-10), or possible-dependence (11-12).';
COMMENT ON COLUMN audit_c_grade.positive_screen IS
    'Positive-screen indicator: yes when total_score >= 5 (UK default cut), otherwise no.';
COMMENT ON COLUMN audit_c_grade.graded_at IS
    'Timestamp when the engine last computed the grade.';

-- ========================================================================
-- END 05_create_table_audit_c_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_audit_c_grade_rule.sql
-- ========================================================================

-- Audit trail of every grading rule that fired during AUDIT-C
-- computation. Each row records one rule firing with the item it
-- belongs to, the points it contributed, and a human-readable
-- description.

CREATE TABLE audit_c_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    audit_c_grade_id UUID NOT NULL
        REFERENCES audit_c_grade(id) ON DELETE CASCADE,

    rule_id VARCHAR(40) NOT NULL,
    item VARCHAR(20) NOT NULL
        CHECK (item IN ('frequency', 'quantity', 'binge-frequency', 'band')),
    points INT,
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX audit_c_grade_rule_grade_id_idx
    ON audit_c_grade_rule (audit_c_grade_id);

CREATE TRIGGER trigger_audit_c_grade_rule_updated_at
    BEFORE UPDATE ON audit_c_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE audit_c_grade_rule IS
    'Audit trail of every grading rule that fired during AUDIT-C computation: item, points contributed, category, and description.';
COMMENT ON COLUMN audit_c_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN audit_c_grade_rule.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN audit_c_grade_rule.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN audit_c_grade_rule.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN audit_c_grade_rule.audit_c_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN audit_c_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-FREQUENCY-3POINT-01).';
COMMENT ON COLUMN audit_c_grade_rule.item IS
    'Scored item the rule belongs to: frequency (Q1), quantity (Q2), binge-frequency (Q3), or band (total risk band).';
COMMENT ON COLUMN audit_c_grade_rule.points IS
    'Points (0-4) contributed by this rule for its item.';
COMMENT ON COLUMN audit_c_grade_rule.category IS
    'Subject category (e.g. item-score, band).';
COMMENT ON COLUMN audit_c_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 06_create_table_audit_c_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_audit_c_grade_flag.sql
-- ========================================================================

-- Red-flag issues that fire independently of the total score, with
-- priority and a suggested action for the clinical team.

CREATE TABLE audit_c_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    audit_c_grade_id UUID NOT NULL
        REFERENCES audit_c_grade(id) ON DELETE CASCADE,

    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT ''
        CHECK (category IN (
            'brief-intervention',
            'high-consumption',
            'dependence-indicators',
            'escalate-full-audit',
            'incomplete',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX audit_c_grade_flag_grade_id_idx
    ON audit_c_grade_flag (audit_c_grade_id);

CREATE TRIGGER trigger_audit_c_grade_flag_updated_at
    BEFORE UPDATE ON audit_c_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE audit_c_grade_flag IS
    'Red-flag issues that fire independently of the total score, with priority and a suggested action for the clinical team.';
COMMENT ON COLUMN audit_c_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN audit_c_grade_flag.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN audit_c_grade_flag.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN audit_c_grade_flag.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN audit_c_grade_flag.audit_c_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN audit_c_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-ESCALATE-FULL-AUDIT-001).';
COMMENT ON COLUMN audit_c_grade_flag.category IS
    'Flag category (see CHECK constraint for enumeration).';
COMMENT ON COLUMN audit_c_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN audit_c_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN audit_c_grade_flag.suggested_action IS
    'Suggested clinical action (e.g. "complete the full 10-item AUDIT and deliver a brief intervention").';

-- ========================================================================
-- END 07_create_table_audit_c_grade_flag.sql
-- ========================================================================
