<!ELEMENT tumor_marker_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,psa,ca125,ca19_9,carcinoembryonic_antigen_cea,alpha_fetoprotein_afp,beta_hcg,ca15_3,lactate_dehydrogenase_ldh,calcitonin,chromogranin_a,primary_indication,clinical_details,known_cancer_site,on_treatment,previous_marker_value,previous_marker_date,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT psa (#PCDATA)>
<!ELEMENT ca125 (#PCDATA)>
<!ELEMENT ca19_9 (#PCDATA)>
<!ELEMENT carcinoembryonic_antigen_cea (#PCDATA)>
<!ELEMENT alpha_fetoprotein_afp (#PCDATA)>
<!ELEMENT beta_hcg (#PCDATA)>
<!ELEMENT ca15_3 (#PCDATA)>
<!ELEMENT lactate_dehydrogenase_ldh (#PCDATA)>
<!ELEMENT calcitonin (#PCDATA)>
<!ELEMENT chromogranin_a (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_details (#PCDATA)>
<!ELEMENT known_cancer_site (#PCDATA)>
<!ELEMENT on_treatment (#PCDATA)>
<!ELEMENT previous_marker_value (#PCDATA)>
<!ELEMENT previous_marker_date (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
