//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::partogram_grade_flags::Entity as PartogramGradeFlags;
pub use super::partogram_grade_rules::Entity as PartogramGradeRules;
pub use super::partogram_grades::Entity as PartogramGrades;
pub use super::partogram_observations::Entity as PartogramObservations;
pub use super::partograms::Entity as Partograms;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
