-- schema.sql
-- Combined schema for form: pet-scan-test-request
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (8):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_pet_scan_test_request.sql
--   - 05_create_table_pet_scan_test_request_grade.sql
--   - 06_create_table_pet_scan_test_request_grade_rule.sql
--   - 07_create_table_pet_scan_test_request_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- pg_trgm provides gin_trgm_ops for trigram GIN indexes on text columns.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    waist_as_cm NUMERIC(5,1),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    waist_height_ratio NUMERIC(4,1),
    vo2_max  NUMERIC(4,1)
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Name.';
COMMENT ON COLUMN patient.birth_date IS
    'Birth date.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as full text.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2 format, such as for validating the postal address.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code, such as for validating the postal address.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.waist_as_cm IS
    'Waist circumference measurement in cm, such as for calculating waist-height ratio (WHR).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height measurement in cm, such as for calculating waist-height ratio (WHR).';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI) measurement.';
COMMENT ON COLUMN patient.waist_height_ratio IS
    'Waist-height ratio (WHR) measurement.';
COMMENT ON COLUMN patient.vo2_max IS
    'VO2 max measurement.';

CREATE INDEX patient_index_gto
    ON patient
    USING GIN ((
        name
    ) gin_trgm_ops);

COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight as kg.';

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Requesting clinician (referrer) information.

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role TEXT NOT NULL DEFAULT '' CHECK (role IN ('radiologist', 'nuclear-medicine-physician', 'oncologist', 'gp', 'hospital-doctor', 'technologist', 'other', '')),
    registration_body TEXT NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT '',
    united_kingdom_nhs_number CHAR(12) UNIQUE
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Requesting clinician (referrer) who completes the PET scan request.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Name.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as full text.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2 format, such as for validating the postal address.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code, such as for validating the postal address.';
COMMENT ON COLUMN clinician.role IS
    'Clinician role: radiologist, nuclear-medicine-physician, oncologist, gp, hospital-doctor, technologist, other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Clinician registration body: GMC, NMC, HCPC, other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Clinician registration number.';
COMMENT ON COLUMN clinician.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';

CREATE INDEX clinician_index_gto
    ON clinician
    USING GIN ((
        name
    ) gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_pet_scan_test_request.sql
-- ========================================================================

-- PET-CT scan request (referral) — the source-of-truth record.

CREATE TABLE pet_scan_test_request (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,
    clinician_id UUID NOT NULL REFERENCES clinician(id) ON DELETE CASCADE,

    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'submitted', 'vetted', 'scheduled', 'rejected', '')),
    site_name VARCHAR(255) NOT NULL DEFAULT '',
    setting VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (setting IN ('outpatient', 'inpatient', 'community', 'emergency', '')),
    referral_date DATE,
    requested_by_date DATE,

    -- Requested examination
    scan_type VARCHAR(30) NOT NULL DEFAULT ''
        CHECK (scan_type IN ('fdg-pet-ct', 'psma-pet', 'dotatate-pet', 'amyloid-pet', 'cardiac-pet', 'other', '')),
    primary_indication VARCHAR(40) NOT NULL DEFAULT ''
        CHECK (primary_indication IN ('cancer-staging', 'cancer-restaging', 'treatment-response', 'suspected-recurrence', 'solitary-pulmonary-nodule', 'lymphoma', 'cardiac-viability', 'infection-inflammation', 'neurology-dementia', 'other', '')),
    clinical_question VARCHAR(1000) NOT NULL DEFAULT '',
    relevant_history VARCHAR(1000) NOT NULL DEFAULT '',
    primary_tumour_site VARCHAR(255) NOT NULL DEFAULT '',

    -- Patient preparation / safety
    diabetes BOOLEAN NOT NULL DEFAULT FALSE,
    blood_glucose_mmol_l NUMERIC(4,1)
        CHECK (blood_glucose_mmol_l IS NULL OR blood_glucose_mmol_l BETWEEN 0 AND 60),
    pregnancy_status VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (pregnancy_status IN ('not-pregnant', 'pregnant', 'possible', 'unknown', 'not-applicable', '')),
    breastfeeding BOOLEAN NOT NULL DEFAULT FALSE,
    egfr NUMERIC(5,1)
        CHECK (egfr IS NULL OR egfr BETWEEN 0 AND 200),
    recent_chemo_radiotherapy VARCHAR(1000) NOT NULL DEFAULT '',
    claustrophobia BOOLEAN NOT NULL DEFAULT FALSE,
    weight_kg NUMERIC(5,1)
        CHECK (weight_kg IS NULL OR weight_kg BETWEEN 0 AND 500),

    -- Requester / triage / justification
    urgency VARCHAR(15) NOT NULL DEFAULT 'routine'
        CHECK (urgency IN ('routine', 'urgent', 'emergency', '')),
    ir_me_r_justification VARCHAR(1000) NOT NULL DEFAULT '',
    supervising_consultant VARCHAR(255) NOT NULL DEFAULT '',
    requester_contact VARCHAR(255) NOT NULL DEFAULT '',
    notes VARCHAR(1000) NOT NULL DEFAULT ''
);

CREATE INDEX index_pet_scan_test_request_patient_id
    ON pet_scan_test_request(patient_id);
CREATE INDEX index_pet_scan_test_request_clinician_id
    ON pet_scan_test_request(clinician_id);

CREATE TRIGGER trigger_pet_scan_test_request_updated_at
    BEFORE UPDATE ON pet_scan_test_request
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE pet_scan_test_request IS
    'PET-CT scan request (referral). Captures the requested tracer / scan type, the clinical indication and question, primary tumour site, FDG-PET patient-preparation and safety data (glucose control, pregnancy, breastfeeding, renal function), IR(ME)R justification, and triage urgency.';
COMMENT ON COLUMN pet_scan_test_request.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN pet_scan_test_request.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN pet_scan_test_request.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN pet_scan_test_request.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN pet_scan_test_request.patient_id IS
    'Foreign key to the patient.';
COMMENT ON COLUMN pet_scan_test_request.clinician_id IS
    'Foreign key to the requesting clinician (referrer).';
COMMENT ON COLUMN pet_scan_test_request.status IS
    'Request lifecycle status: draft, submitted, vetted, scheduled, rejected.';
COMMENT ON COLUMN pet_scan_test_request.site_name IS
    'Name of the requesting site or clinic.';
COMMENT ON COLUMN pet_scan_test_request.setting IS
    'Care setting: outpatient, inpatient, community, emergency.';
COMMENT ON COLUMN pet_scan_test_request.referral_date IS
    'Date the referral was made.';
COMMENT ON COLUMN pet_scan_test_request.requested_by_date IS
    'Date by which the scan is requested to be performed.';
COMMENT ON COLUMN pet_scan_test_request.scan_type IS
    'Requested PET tracer / scan type: fdg-pet-ct, psma-pet, dotatate-pet, amyloid-pet, cardiac-pet, other.';
COMMENT ON COLUMN pet_scan_test_request.primary_indication IS
    'Primary clinical indication, used for appropriateness scoring.';
COMMENT ON COLUMN pet_scan_test_request.clinical_question IS
    'Specific clinical question the scan should answer (highest-value field).';
COMMENT ON COLUMN pet_scan_test_request.relevant_history IS
    'Relevant medical, oncological, and treatment history.';
COMMENT ON COLUMN pet_scan_test_request.primary_tumour_site IS
    'Primary tumour site or suspected primary, where applicable.';
COMMENT ON COLUMN pet_scan_test_request.diabetes IS
    'Whether the patient has diabetes (affects FDG glucose control / preparation).';
COMMENT ON COLUMN pet_scan_test_request.blood_glucose_mmol_l IS
    'Most-recent blood glucose in mmol/L; FDG uptake needs glucose control, typically below 11 mmol/L.';
COMMENT ON COLUMN pet_scan_test_request.pregnancy_status IS
    'Pregnancy status: not-pregnant, pregnant, possible, unknown, not-applicable.';
COMMENT ON COLUMN pet_scan_test_request.breastfeeding IS
    'Whether the patient is currently breastfeeding (radiopharmaceutical precaution).';
COMMENT ON COLUMN pet_scan_test_request.egfr IS
    'Estimated glomerular filtration rate (mL/min/1.73m2), for any iodinated CT contrast.';
COMMENT ON COLUMN pet_scan_test_request.recent_chemo_radiotherapy IS
    'Recent chemotherapy / radiotherapy details and dates (affect timing and uptake).';
COMMENT ON COLUMN pet_scan_test_request.claustrophobia IS
    'Whether the patient has claustrophobia (may need support or sedation).';
COMMENT ON COLUMN pet_scan_test_request.weight_kg IS
    'Patient weight in kg, used for tracer dosing and table limits.';
COMMENT ON COLUMN pet_scan_test_request.urgency IS
    'Requested triage urgency: routine, urgent, emergency.';
COMMENT ON COLUMN pet_scan_test_request.ir_me_r_justification IS
    'IR(ME)R justification statement supporting the radiation exposure.';
COMMENT ON COLUMN pet_scan_test_request.supervising_consultant IS
    'Name of the supervising / responsible consultant.';
COMMENT ON COLUMN pet_scan_test_request.requester_contact IS
    'Contact details (bleep / phone) for the requester.';
COMMENT ON COLUMN pet_scan_test_request.notes IS
    'Free-text additional notes.';

-- ========================================================================
-- END 04_create_table_pet_scan_test_request.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_pet_scan_test_request_grade.sql
-- ========================================================================

-- Computed grading result for a PET-CT scan request (four-axis engine).

CREATE TABLE pet_scan_test_request_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    pet_scan_test_request_id UUID NOT NULL UNIQUE
        REFERENCES pet_scan_test_request(id) ON DELETE CASCADE,

    -- Axis A: appropriateness (ACR Appropriateness Criteria / RCR iRefer 1-9 scale)
    appropriateness_score INTEGER
        CHECK (appropriateness_score IS NULL OR appropriateness_score BETWEEN 1 AND 9),
    appropriateness_band VARCHAR(25) NOT NULL DEFAULT ''
        CHECK (appropriateness_band IN ('usually-appropriate', 'may-be-appropriate', 'usually-not-appropriate', '')),

    -- Axis B: preparation safety and radiation dose
    prep_safety_band VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (prep_safety_band IN ('ok', 'caution', 'contraindicated', '')),
    radiation_dose_band VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (radiation_dose_band IN ('low', 'moderate', 'high', '')),

    -- Axis C: request completeness
    completeness_percent INTEGER
        CHECK (completeness_percent IS NULL OR completeness_percent BETWEEN 0 AND 100),

    -- Axis D: triage priority
    triage_tier VARCHAR(15) NOT NULL DEFAULT ''
        CHECK (triage_tier IN ('routine', 'urgent', 'emergency', '')),
    target_timeframe VARCHAR(50) NOT NULL DEFAULT '',

    recommendation VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (recommendation IN ('accept', 'query-referrer', 'redirect', 'reject', '')),
    clinician_notes TEXT NOT NULL DEFAULT '',
    signed_at TIMESTAMPTZ,
    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_pet_scan_test_request_grade_updated_at
    BEFORE UPDATE ON pet_scan_test_request_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE pet_scan_test_request_grade IS
    'Computed four-axis grading result: appropriateness (ACR / RCR iRefer 1-9), preparation safety and radiation dose, request completeness, and triage priority.';
COMMENT ON COLUMN pet_scan_test_request_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN pet_scan_test_request_grade.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN pet_scan_test_request_grade.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN pet_scan_test_request_grade.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN pet_scan_test_request_grade.pet_scan_test_request_id IS
    'Foreign key to the parent request (unique, 1:1).';
COMMENT ON COLUMN pet_scan_test_request_grade.appropriateness_score IS
    'ACR Appropriateness Criteria / RCR iRefer score (1-9).';
COMMENT ON COLUMN pet_scan_test_request_grade.appropriateness_band IS
    'Appropriateness band: usually-appropriate (7-9), may-be-appropriate (4-6), usually-not-appropriate (1-3).';
COMMENT ON COLUMN pet_scan_test_request_grade.prep_safety_band IS
    'Preparation / safety band driven by glucose control, pregnancy, and breastfeeding: ok, caution, contraindicated.';
COMMENT ON COLUMN pet_scan_test_request_grade.radiation_dose_band IS
    'Relative radiation-dose band for the requested study: low, moderate, high.';
COMMENT ON COLUMN pet_scan_test_request_grade.completeness_percent IS
    'Request completeness as a percentage of mandatory fields (0-100).';
COMMENT ON COLUMN pet_scan_test_request_grade.triage_tier IS
    'Assigned triage tier: routine, urgent, emergency.';
COMMENT ON COLUMN pet_scan_test_request_grade.target_timeframe IS
    'Target timeframe for the scan implied by the triage tier.';
COMMENT ON COLUMN pet_scan_test_request_grade.recommendation IS
    'Vetting recommendation: accept, query-referrer, redirect, reject.';
COMMENT ON COLUMN pet_scan_test_request_grade.clinician_notes IS
    'Free-text vetting notes.';
COMMENT ON COLUMN pet_scan_test_request_grade.signed_at IS
    'Timestamp of vetting clinician electronic signature.';
COMMENT ON COLUMN pet_scan_test_request_grade.graded_at IS
    'Timestamp when the engine last computed the result.';

-- ========================================================================
-- END 05_create_table_pet_scan_test_request_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_pet_scan_test_request_grade_rule.sql
-- ========================================================================

-- Audit trail of every scoring rule that fired for a PET-CT scan request.

CREATE TABLE pet_scan_test_request_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    pet_scan_test_request_grade_id UUID NOT NULL
        REFERENCES pet_scan_test_request_grade(id) ON DELETE CASCADE,
    rule_id VARCHAR(40) NOT NULL,
    axis VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (axis IN ('appropriateness', 'safety', 'completeness', 'triage', '')),
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX index_pet_scan_test_request_grade_rule_grade_id
    ON pet_scan_test_request_grade_rule(pet_scan_test_request_grade_id);

CREATE TRIGGER trigger_pet_scan_test_request_grade_rule_updated_at
    BEFORE UPDATE ON pet_scan_test_request_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE pet_scan_test_request_grade_rule IS
    'Audit trail of every appropriateness / safety / completeness / triage rule that fired for this request.';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.pet_scan_test_request_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-APPROP-STAGING-01).';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.axis IS
    'Scoring axis the rule belongs to: appropriateness, safety, completeness, triage.';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.category IS
    'Category or indication the rule relates to.';
COMMENT ON COLUMN pet_scan_test_request_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 06_create_table_pet_scan_test_request_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_pet_scan_test_request_grade_flag.sql
-- ========================================================================

-- Safety-critical flags for a PET-CT scan request, independent of the axes.

CREATE TABLE pet_scan_test_request_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    pet_scan_test_request_grade_id UUID NOT NULL
        REFERENCES pet_scan_test_request_grade(id) ON DELETE CASCADE,
    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(40) NOT NULL DEFAULT ''
        CHECK (category IN (
            'pregnancy',
            'breastfeeding',
            'uncontrolled-glucose',
            'high-radiation-dose',
            'missing-indication',
            'missing-clinical-question',
            'missing-glucose',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX index_pet_scan_test_request_grade_flag_grade_id
    ON pet_scan_test_request_grade_flag(pet_scan_test_request_grade_id);

CREATE TRIGGER trigger_pet_scan_test_request_grade_flag_updated_at
    BEFORE UPDATE ON pet_scan_test_request_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE pet_scan_test_request_grade_flag IS
    'Safety-critical flags that fire independently of the four axes, with priority and a suggested action for the imaging team.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.pet_scan_test_request_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-UNCONTROLLED-GLUCOSE-001).';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.category IS
    'Flag category.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN pet_scan_test_request_grade_flag.suggested_action IS
    'Suggested clinical action (e.g. "recheck glucose and reschedule if above 11 mmol/L").';

-- ========================================================================
-- END 07_create_table_pet_scan_test_request_grade_flag.sql
-- ========================================================================
