-- schema.sql
-- Combined schema for form: wells-score-for-pulmonary-embolism
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (8):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_wells_score_for_pulmonary_embolism.sql
--   - 05_create_table_wells_score_for_pulmonary_embolism_grade.sql
--   - 06_create_table_wells_score_for_pulmonary_embolism_grade_rule.sql
--   - 07_create_table_wells_score_for_pulmonary_embolism_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators used by free-text search GIN indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information.

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    hospital_mrn VARCHAR(50),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    allergies_summary TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient demographic information used by the Wells PE assessment record.';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Full patient name as recorded on the wristband.';
COMMENT ON COLUMN patient.birth_date IS
    'Date of birth.';
COMMENT ON COLUMN patient.sex IS
    'Sex recorded for clinical purposes: female, male, intersex, or unknown.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.hospital_mrn IS
    'Local hospital medical record number (MRN).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height in centimetres.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight in kilograms.';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI), kg/m^2.';
COMMENT ON COLUMN patient.allergies_summary IS
    'Free-text summary of known allergies.';

CREATE INDEX patient_name_trgm_idx
    ON patient
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Clinician employee information used to identify the assessing
-- clinician (doctor, nurse, physician-associate).

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN ('doctor', 'nurse', 'physician-associate', 'other', '')),
    registration_body VARCHAR(20) NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'GPhC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician identifying information for the assessing clinician.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Clinician full name as recorded in the rota.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code.';
COMMENT ON COLUMN clinician.role IS
    'Primary clinical role: doctor, nurse, physician-associate, or other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Professional registration body: GMC, NMC, HCPC, GPhC, or other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Professional registration number issued by the registration body.';

CREATE INDEX clinician_name_trgm_idx
    ON clinician
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_wells_score_for_pulmonary_embolism.sql
-- ========================================================================

-- Main Wells PE assessment record: identification, context, and the seven
-- weighted clinical criterion inputs. Each criterion is a yes/no/'' enum,
-- scored as present only when 'yes' and contributing its weight (+3, +1.5, or
-- +1). The computed score, bands, fired rules, and flags live in dedicated
-- child tables.

CREATE TABLE wells_score_for_pulmonary_embolism (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE RESTRICT,
    clinician_id UUID REFERENCES clinician(id) ON DELETE RESTRICT,

    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'amended', 'signed', '')),

    -- Context and identification
    patient_identifier VARCHAR(64) NOT NULL DEFAULT '',
    assessed_at TIMESTAMPTZ,
    care_setting VARCHAR(30) NOT NULL DEFAULT '' CHECK (care_setting IN ('emergency-department', 'acute-medical-unit', 'ambulatory', 'other', '')),
    age_band VARCHAR(10) NOT NULL DEFAULT '' CHECK (age_band IN ('18-39', '40-64', '65-74', '75-84', '85-plus', '')),
    haemodynamic_status VARCHAR(10) NOT NULL DEFAULT '' CHECK (haemodynamic_status IN ('stable', 'unstable', '')),

    -- Criterion inputs (each scored by its weight when 'yes')
    clinical_signs_of_dvt VARCHAR(5) NOT NULL DEFAULT '' CHECK (clinical_signs_of_dvt IN ('yes', 'no', '')),
    pe_most_likely VARCHAR(5) NOT NULL DEFAULT '' CHECK (pe_most_likely IN ('yes', 'no', '')),
    heart_rate_over_100 VARCHAR(5) NOT NULL DEFAULT '' CHECK (heart_rate_over_100 IN ('yes', 'no', '')),
    immobilisation_or_surgery VARCHAR(5) NOT NULL DEFAULT '' CHECK (immobilisation_or_surgery IN ('yes', 'no', '')),
    previous_dvt_pe VARCHAR(5) NOT NULL DEFAULT '' CHECK (previous_dvt_pe IN ('yes', 'no', '')),
    haemoptysis VARCHAR(5) NOT NULL DEFAULT '' CHECK (haemoptysis IN ('yes', 'no', '')),
    malignancy VARCHAR(5) NOT NULL DEFAULT '' CHECK (malignancy IN ('yes', 'no', '')),

    clinical_notes TEXT NOT NULL DEFAULT ''
);

CREATE INDEX wells_score_for_pulmonary_embolism_patient_id_idx
    ON wells_score_for_pulmonary_embolism (patient_id);
CREATE INDEX wells_score_for_pulmonary_embolism_clinician_id_idx
    ON wells_score_for_pulmonary_embolism (clinician_id);

CREATE TRIGGER trigger_wells_score_for_pulmonary_embolism_updated_at
    BEFORE UPDATE ON wells_score_for_pulmonary_embolism
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE wells_score_for_pulmonary_embolism IS
    'Main Wells PE assessment record: identification, context, and the seven weighted clinical criterion inputs.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.patient_id IS
    'Foreign key to the patient being assessed (restricts delete).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.clinician_id IS
    'Foreign key to the assessing clinician (restricts delete).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.status IS
    'Workflow status: draft, submitted, amended, or signed.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.patient_identifier IS
    'Local patient identifier as recorded at the point of assessment.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.assessed_at IS
    'Date and time the assessment was carried out.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.care_setting IS
    'Care setting: emergency-department, acute-medical-unit, ambulatory, or other.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.age_band IS
    'Adult age band: 18-39, 40-64, 65-74, 75-84, or 85-plus.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.haemodynamic_status IS
    'Haemodynamic status: stable or unstable (unstable suggests massive PE).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.clinical_signs_of_dvt IS
    'Criterion 1 (+3): clinical signs and symptoms of DVT.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.pe_most_likely IS
    'Criterion 2 (+3): PE is the number-one diagnosis, or equally likely.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.heart_rate_over_100 IS
    'Criterion 3 (+1.5): heart rate greater than 100 beats per minute.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.immobilisation_or_surgery IS
    'Criterion 4 (+1.5): immobilisation for at least 3 days, or surgery in the previous 4 weeks.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.previous_dvt_pe IS
    'Criterion 5 (+1.5): previous, objectively diagnosed DVT or PE.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.haemoptysis IS
    'Criterion 6 (+1): haemoptysis.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.malignancy IS
    'Criterion 7 (+1): malignancy on treatment, treated within 6 months, or palliative.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism.clinical_notes IS
    'Free-text clinical notes captured alongside the assessment.';

-- ========================================================================
-- END 04_create_table_wells_score_for_pulmonary_embolism.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_wells_score_for_pulmonary_embolism_grade.sql
-- ========================================================================

-- Computed Wells PE grading result. Stores the engine-computed total score,
-- the two-level band (likely/unlikely) that drives the recommended pathway,
-- the informational three-level band (low/moderate/high), and the recommended
-- diagnostic pathway. One-to-one with the parent assessment.

CREATE TABLE wells_score_for_pulmonary_embolism_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    wells_score_for_pulmonary_embolism_id UUID NOT NULL UNIQUE
        REFERENCES wells_score_for_pulmonary_embolism(id) ON DELETE CASCADE,

    wells_score NUMERIC(4,1),
    two_level_band VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (two_level_band IN ('likely', 'unlikely', '')),
    three_level_band VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (three_level_band IN ('low', 'moderate', 'high', '')),
    recommended_pathway TEXT NOT NULL DEFAULT '',
    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_wells_score_for_pulmonary_embolism_grade_updated_at
    BEFORE UPDATE ON wells_score_for_pulmonary_embolism_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE wells_score_for_pulmonary_embolism_grade IS
    'Computed Wells PE grading result: total score, two-level band, three-level band, and recommended diagnostic pathway. One-to-one with the parent assessment.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.wells_score_for_pulmonary_embolism_id IS
    'Foreign key to the parent assessment (unique, 1:1).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.wells_score IS
    'Total Wells score computed by the engine, range 0..12.5 (weights include 1.5-point items).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.two_level_band IS
    'Two-level band: likely (score > 4) or unlikely (score <= 4).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.three_level_band IS
    'Informational three-level band: low (< 2), moderate (2-6), or high (> 6).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.recommended_pathway IS
    'Recommended diagnostic pathway: CTPA when PE likely, otherwise D-dimer.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade.graded_at IS
    'Timestamp when the engine last computed the grade.';

-- ========================================================================
-- END 05_create_table_wells_score_for_pulmonary_embolism_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_wells_score_for_pulmonary_embolism_grade_rule.sql
-- ========================================================================

-- Audit trail of every grading rule that fired during Wells-score
-- computation. Each row records one criterion or banding firing with the
-- instrument that produced it, the points it contributed, the band it
-- informed, and a human-readable description.

CREATE TABLE wells_score_for_pulmonary_embolism_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    wells_score_for_pulmonary_embolism_grade_id UUID NOT NULL
        REFERENCES wells_score_for_pulmonary_embolism_grade(id) ON DELETE CASCADE,

    rule_id VARCHAR(40) NOT NULL,
    instrument VARCHAR(20) NOT NULL
        CHECK (instrument IN ('criterion', 'two-level', 'three-level', 'composite')),
    points NUMERIC(4,1) NOT NULL DEFAULT 0,
    band VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (band IN ('likely', 'unlikely', 'low', 'moderate', 'high', '')),
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX wells_score_for_pulmonary_embolism_grade_rule_grade_id_idx
    ON wells_score_for_pulmonary_embolism_grade_rule (wells_score_for_pulmonary_embolism_grade_id);

CREATE TRIGGER trigger_wells_score_for_pulmonary_embolism_grade_rule_updated_at
    BEFORE UPDATE ON wells_score_for_pulmonary_embolism_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE wells_score_for_pulmonary_embolism_grade_rule IS
    'Audit trail of every grading rule that fired during Wells-score computation: instrument, points, band, category, and description.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.wells_score_for_pulmonary_embolism_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-DVT-SIGNS-01).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.instrument IS
    'Scoring instrument the rule belongs to: criterion, two-level, three-level, or composite.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.points IS
    'Points contributed by this rule (+3, +1.5, or +1 for a criterion).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.band IS
    'Stratification band informed by this rule: likely, unlikely, low, moderate, or high.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.category IS
    'Subject category (e.g. clinical-sign, gestalt, tachycardia, immobilisation, malignancy).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 06_create_table_wells_score_for_pulmonary_embolism_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_wells_score_for_pulmonary_embolism_grade_flag.sql
-- ========================================================================

-- Clinically significant flags that fire independently of the total score,
-- with priority and a suggested action for the assessing team.

CREATE TABLE wells_score_for_pulmonary_embolism_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    wells_score_for_pulmonary_embolism_grade_id UUID NOT NULL
        REFERENCES wells_score_for_pulmonary_embolism_grade(id) ON DELETE CASCADE,

    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(30) NOT NULL DEFAULT ''
        CHECK (category IN (
            'pe-likely-ctpa',
            'pe-unlikely-d-dimer',
            'haemodynamic-instability',
            'incomplete-assessment',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX wells_score_for_pulmonary_embolism_grade_flag_grade_id_idx
    ON wells_score_for_pulmonary_embolism_grade_flag (wells_score_for_pulmonary_embolism_grade_id);

CREATE TRIGGER trigger_wells_score_for_pulmonary_embolism_grade_flag_updated_at
    BEFORE UPDATE ON wells_score_for_pulmonary_embolism_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE wells_score_for_pulmonary_embolism_grade_flag IS
    'Clinically significant flags that fire independently of the total score, with priority and a suggested action for the assessing team.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.wells_score_for_pulmonary_embolism_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-PE-LIKELY-CTPA-001).';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.category IS
    'Flag category: pe-likely-ctpa, pe-unlikely-d-dimer, haemodynamic-instability, incomplete-assessment, or other.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN wells_score_for_pulmonary_embolism_grade_flag.suggested_action IS
    'Suggested clinical action (e.g. "arrange immediate CTPA", "arrange a D-dimer and consider the PERC rule").';

-- ========================================================================
-- END 07_create_table_wells_score_for_pulmonary_embolism_grade_flag.sql
-- ========================================================================
