use loco_rs::schema::*;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "hospital_number",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "indication_for_surgery",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "anaesthetist_name",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "previous_surgeries",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "previous_anaesthetic_issues",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "previous_anaesthetic_issues_details",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "family_history_anaesthetic_complications",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "family_history_anaesthetic_complications_details",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "urinalysis_findings",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "living_situation",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "support_at_home",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "mobility_status",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "falls_risk_within_year",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "vte_risk_level",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "covid_screening_result",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discharge_destination",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "follow_up_requirements",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "social_services_involvement",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "reablement_physiotherapy_needs",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "consent_status",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "interpreter_required",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discussion_procedure",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discussion_anaesthetic",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discussion_risks_benefits",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        add_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discussion_alternatives",
            ColType::StringWithDefault(String::new()),
        )
        .await?;
        Ok(())
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discussion_alternatives",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discussion_risks_benefits",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discussion_anaesthetic",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discussion_procedure",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "interpreter_required",
        )
        .await?;
        remove_column(m, "pre_operative_assessment_by_clinicians", "consent_status").await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "reablement_physiotherapy_needs",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "social_services_involvement",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "follow_up_requirements",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "discharge_destination",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "covid_screening_result",
        )
        .await?;
        remove_column(m, "pre_operative_assessment_by_clinicians", "vte_risk_level").await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "falls_risk_within_year",
        )
        .await?;
        remove_column(m, "pre_operative_assessment_by_clinicians", "mobility_status").await?;
        remove_column(m, "pre_operative_assessment_by_clinicians", "support_at_home").await?;
        remove_column(m, "pre_operative_assessment_by_clinicians", "living_situation").await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "urinalysis_findings",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "family_history_anaesthetic_complications_details",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "family_history_anaesthetic_complications",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "previous_anaesthetic_issues_details",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "previous_anaesthetic_issues",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "previous_surgeries",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "anaesthetist_name",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "indication_for_surgery",
        )
        .await?;
        remove_column(
            m,
            "pre_operative_assessment_by_clinicians",
            "hospital_number",
        )
        .await?;
        Ok(())
    }
}
