// Sample dashboard rows. In production this would come from the backend
// API; the static dashboard inlines them so the page works via file://.
export const SAMPLE_ISSUES = [
  {
    id: 'ISSUE-2026-0001',
    status: 'open',
    compositePriority: 'critical',
    scoreByPriorityRank: 1,
    scoreBySeverityOfImpact: 5,
    scoreByMagnitudeOfDamage: 9,
    scoreByHarmGrade: 4,
    scoreByFailureCondition: 'A',
    scoreByMoscowRequirement: 1,
    scoreByFrequencyPercent: 100,
    ccSummary: 'Infusion-pump dosing error after firmware update',
    systemName: 'ward-9-pumps',
    environment: 'field',
    ptAssignees: 'medical-devices oncall',
    reportedAt: '2026-05-07T08:14:00Z',
    issueCategory: 'medical-device',
  },
  {
    id: 'ISSUE-2026-0002',
    status: 'in-progress',
    compositePriority: 'critical',
    scoreByPriorityRank: 1,
    scoreBySeverityOfImpact: 5,
    scoreByMagnitudeOfDamage: 8,
    scoreByHarmGrade: 0,
    scoreByFailureCondition: 'B',
    scoreByMoscowRequirement: 1,
    scoreByFrequencyPercent: 95,
    ccSummary: 'Production database read replica lagging > 30 minutes',
    systemName: 'orders-db',
    environment: 'production',
    ptAssignees: 'sre-oncall',
    reportedAt: '2026-05-08T02:11:00Z',
    issueCategory: 'service-outage',
  },
  {
    id: 'ISSUE-2026-0003',
    status: 'in-progress',
    compositePriority: 'high',
    scoreByPriorityRank: 2,
    scoreBySeverityOfImpact: 4,
    scoreByMagnitudeOfDamage: 6,
    scoreByHarmGrade: 1,
    scoreByFailureCondition: 'C',
    scoreByMoscowRequirement: 2,
    scoreByFrequencyPercent: 35,
    ccSummary: 'Login endpoint returning 500 for SSO users in EU region',
    systemName: 'auth-service',
    environment: 'production',
    ptAssignees: 'identity-team',
    reportedAt: '2026-05-06T14:02:00Z',
    issueCategory: 'security',
  },
  {
    id: 'ISSUE-2026-0004',
    status: 'open',
    compositePriority: 'high',
    scoreByPriorityRank: 2,
    scoreBySeverityOfImpact: 3,
    scoreByMagnitudeOfDamage: 5,
    scoreByHarmGrade: 2,
    scoreByFailureCondition: 'C',
    scoreByMoscowRequirement: 2,
    scoreByFrequencyPercent: 12,
    ccSummary: 'Triage chatbot routing minor self-harm concerns to FAQ',
    systemName: 'support-chat',
    environment: 'production',
    ptAssignees: 'safety-officer',
    reportedAt: '2026-05-05T17:33:00Z',
    issueCategory: 'clinical-safety',
  },
  {
    id: 'ISSUE-2026-0005',
    status: 'open',
    compositePriority: 'moderate',
    scoreByPriorityRank: 3,
    scoreBySeverityOfImpact: 3,
    scoreByMagnitudeOfDamage: 4,
    scoreByHarmGrade: 0,
    scoreByFailureCondition: 'C',
    scoreByMoscowRequirement: 3,
    scoreByFrequencyPercent: 20,
    ccSummary: 'Dashboard CSV export missing the Frequency % column',
    systemName: 'reports-ui',
    environment: 'production',
    ptAssignees: 'analytics-team',
    reportedAt: '2026-05-04T09:48:00Z',
    issueCategory: 'software-defect',
  },
  {
    id: 'ISSUE-2026-0006',
    status: 'resolved',
    compositePriority: 'moderate',
    scoreByPriorityRank: 3,
    scoreBySeverityOfImpact: 2,
    scoreByMagnitudeOfDamage: 3,
    scoreByHarmGrade: 0,
    scoreByFailureCondition: 'D',
    scoreByMoscowRequirement: 2,
    scoreByFrequencyPercent: 8,
    ccSummary: 'Slow GraphQL response on /reporters list',
    systemName: 'api-gateway',
    environment: 'staging',
    ptAssignees: 'platform-team',
    reportedAt: '2026-05-03T11:20:00Z',
    issueCategory: 'performance',
  },
  {
    id: 'ISSUE-2026-0007',
    status: 'closed',
    compositePriority: 'low',
    scoreByPriorityRank: 5,
    scoreBySeverityOfImpact: 1,
    scoreByMagnitudeOfDamage: 1,
    scoreByHarmGrade: 0,
    scoreByFailureCondition: 'E',
    scoreByMoscowRequirement: 4,
    scoreByFrequencyPercent: 0.5,
    ccSummary: 'Typo in footer copyright year on the About page',
    systemName: 'marketing-site',
    environment: 'production',
    ptAssignees: 'content-team',
    reportedAt: '2026-05-01T16:00:00Z',
    issueCategory: 'software-defect',
  },
  {
    id: 'ISSUE-2026-0008',
    status: 'blocked',
    compositePriority: 'high',
    scoreByPriorityRank: 2,
    scoreBySeverityOfImpact: 4,
    scoreByMagnitudeOfDamage: 7,
    scoreByHarmGrade: 0,
    scoreByFailureCondition: 'B',
    scoreByMoscowRequirement: 1,
    scoreByFrequencyPercent: 60,
    ccSummary: 'Backups failing on tenant shard 14 — vendor support pending',
    systemName: 'backup-service',
    environment: 'production',
    ptAssignees: 'sre-oncall',
    reportedAt: '2026-05-02T03:55:00Z',
    issueCategory: 'data-protection',
  },
  {
    id: 'ISSUE-2026-0009',
    status: 'open',
    compositePriority: 'critical',
    scoreByPriorityRank: 1,
    scoreBySeverityOfImpact: 5,
    scoreByMagnitudeOfDamage: 10,
    scoreByHarmGrade: 0,
    scoreByFailureCondition: 'B',
    scoreByMoscowRequirement: 1,
    scoreByFrequencyPercent: 100,
    ccSummary: 'Region us-east-2 unreachable — full customer outage',
    systemName: 'edge-router',
    environment: 'production',
    ptAssignees: 'sre-oncall',
    reportedAt: '2026-05-08T06:42:00Z',
    issueCategory: 'service-outage',
  },
  {
    id: 'ISSUE-2026-0010',
    status: 'in-progress',
    compositePriority: 'moderate',
    scoreByPriorityRank: 3,
    scoreBySeverityOfImpact: 3,
    scoreByMagnitudeOfDamage: 4,
    scoreByHarmGrade: 0,
    scoreByFailureCondition: 'D',
    scoreByMoscowRequirement: 2,
    scoreByFrequencyPercent: 18,
    ccSummary: 'Rust crate build flake under cargo test --release',
    systemName: 'ci-runner',
    environment: 'dev',
    ptAssignees: 'platform-team',
    reportedAt: '2026-05-04T22:08:00Z',
    issueCategory: 'process',
  },
];
