use loco_rs::schema::*;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        create_table(m, "medical_operation_notes",
            &[
            
            ("id", ColType::PkAuto),
            
            ("deleted_at", ColType::TimestampWithTimeZoneNull),
            ("status", ColType::String),
            ("hospital_name", ColType::String),
            ("theatre_number", ColType::String),
            ("list_type", ColType::String),
            ("case_start_at", ColType::TimestampWithTimeZoneNull),
            ("anaesthesia_start_at", ColType::TimestampWithTimeZoneNull),
            ("knife_to_skin_at", ColType::TimestampWithTimeZoneNull),
            ("end_of_surgery_at", ColType::TimestampWithTimeZoneNull),
            ("case_end_at", ColType::TimestampWithTimeZoneNull),
            ("consent_status", ColType::String),
            ("side_marked", ColType::String),
            ("sign_in_completed", ColType::String),
            ("asa_physical_status", ColType::String),
            ("pre_operative_diagnosis", ColType::Text),
            ("post_operative_diagnosis", ColType::Text),
            ("indication", ColType::Text),
            ("urgency", ColType::String),
            ("laterality", ColType::String),
            ("anaesthesia_type", ColType::String),
            ("airway_management", ColType::String),
            ("induction_agent", ColType::String),
            ("maintenance_agent", ColType::String),
            ("neuromuscular_blockade", ColType::String),
            ("regional_block_description", ColType::String),
            ("invasive_monitoring", ColType::Text),
            ("intraop_crystalloid_ml", ColType::IntegerNull),
            ("intraop_colloid_ml", ColType::IntegerNull),
            ("intraop_blood_ml", ColType::IntegerNull),
            ("intraop_urine_ml", ColType::IntegerNull),
            ("anaesthetic_event", ColType::String),
            ("anaesthetic_event_description", ColType::Text),
            ("patient_position", ColType::String),
            ("pressure_area_protection_notes", ColType::Text),
            ("prep_solution", ColType::String),
            ("drape_type", ColType::String),
            ("surgical_approach", ColType::String),
            ("incision_type", ColType::String),
            ("incision_length_cm", ColType::DoubleNull),
            ("table_tilt", ColType::String),
            ("tourniquet_used", ColType::String),
            ("tourniquet_site", ColType::String),
            ("tourniquet_pressure_mmhg", ColType::IntegerNull),
            ("tourniquet_on_at", ColType::TimestampWithTimeZoneNull),
            ("tourniquet_off_at", ColType::TimestampWithTimeZoneNull),
            ("converted_to_open", ColType::String),
            ("conversion_reason", ColType::Text),
            ("operative_findings_summary", ColType::Text),
            ("pathology_found", ColType::Text),
            ("anatomical_anomalies", ColType::Text),
            ("intraop_photographs_taken", ColType::String),
            ("frozen_section_requested", ColType::String),
            ("swab_count_first_agreed", ColType::String),
            ("swab_count_final_agreed", ColType::String),
            ("needle_count_first_agreed", ColType::String),
            ("needle_count_final_agreed", ColType::String),
            ("instrument_count_first_agreed", ColType::String),
            ("instrument_count_final_agreed", ColType::String),
            ("count_discrepancy_resolution", ColType::Text),
            ("estimated_blood_loss_ml", ColType::IntegerNull),
            ("transfusion_given", ColType::String),
            ("prbc_units", ColType::IntegerNull),
            ("ffp_units", ColType::IntegerNull),
            ("platelet_units", ColType::IntegerNull),
            ("cryoprecipitate_units", ColType::IntegerNull),
            ("cell_salvage_ml", ColType::IntegerNull),
            ("massive_haemorrhage_protocol_activated", ColType::String),
            ("never_event_flagged", ColType::String),
            ("never_event_description", ColType::Text),
            ("equipment_problem", ColType::String),
            ("equipment_problem_description", ColType::Text),
            ("recovery_destination", ColType::String),
            ("monitoring_frequency", ColType::String),
            ("iv_fluids_plan", ColType::String),
            ("analgesia_plan", ColType::Text),
            ("antibiotic_plan", ColType::String),
            ("vte_prophylaxis_plan", ColType::String),
            ("diet_plan", ColType::String),
            ("mobilisation_plan", ColType::String),
            ("wound_care_plan", ColType::Text),
            ("follow_up_plan", ColType::Text),
            ("special_instructions", ColType::Text),
            ("sign_out_completed", ColType::String),
            ("debrief_completed", ColType::String),
            ("surgeon_override_grade", ColType::String),
            ("surgeon_override_reason", ColType::Text),
            ("attestation_text", ColType::Text),
            ("electronic_signature", ColType::Text),
            ("dictated_at", ColType::TimestampWithTimeZoneNull),
            ("signed_at", ColType::TimestampWithTimeZoneNull),
            ],
            &[
            ("patient", ""),
            ("clinicians", "lead_surgeon_id"),
            ]
        ).await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        drop_table(m, "medical_operation_notes").await
    }
}
