<!ELEMENT architecture_decision_record (id,created_at,updated_at,deleted_at,author_id,organization_id,slug,number,title,decision_date,status,decision_group,issue,decision,assumptions,constraints,argument,implications,related_decisions,related_requirements,related_artifacts,related_principles,signed_off_by,signed_off_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT author_id (#PCDATA)>
<!ELEMENT organization_id (#PCDATA)>
<!ELEMENT slug (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT decision_date (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT decision_group (#PCDATA)>
<!ELEMENT issue (#PCDATA)>
<!ELEMENT decision (#PCDATA)>
<!ELEMENT assumptions (#PCDATA)>
<!ELEMENT constraints (#PCDATA)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT implications (#PCDATA)>
<!ELEMENT related_decisions (#PCDATA)>
<!ELEMENT related_requirements (#PCDATA)>
<!ELEMENT related_artifacts (#PCDATA)>
<!ELEMENT related_principles (#PCDATA)>
<!ELEMENT signed_off_by (#PCDATA)>
<!ELEMENT signed_off_at (#PCDATA)>
