<!ELEMENT cystoscopy_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,procedure,primary_indication,clinical_question,relevant_history,symptom_haematuria,symptom_dysuria,symptom_frequency,symptom_retention,visible_haematuria,current_uti,taking_anticoagulant,anticoagulant_agent,taking_antiplatelet,previous_bladder_cancer,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT procedure (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT symptom_haematuria (#PCDATA)>
<!ELEMENT symptom_dysuria (#PCDATA)>
<!ELEMENT symptom_frequency (#PCDATA)>
<!ELEMENT symptom_retention (#PCDATA)>
<!ELEMENT visible_haematuria (#PCDATA)>
<!ELEMENT current_uti (#PCDATA)>
<!ELEMENT taking_anticoagulant (#PCDATA)>
<!ELEMENT anticoagulant_agent (#PCDATA)>
<!ELEMENT taking_antiplatelet (#PCDATA)>
<!ELEMENT previous_bladder_cancer (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
