<!ELEMENT inpatient_clinical_note_medication_change (id,created_at,updated_at,deleted_at,inpatient_clinical_note_id,sort_order,drug_name,action,dose,route,frequency,indication,is_antimicrobial,review_date,stop_date,dmd_code,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT inpatient_clinical_note_id (#PCDATA)>
<!ELEMENT sort_order (#PCDATA)>
<!ELEMENT drug_name (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT dose (#PCDATA)>
<!ELEMENT route (#PCDATA)>
<!ELEMENT frequency (#PCDATA)>
<!ELEMENT indication (#PCDATA)>
<!ELEMENT is_antimicrobial (#PCDATA)>
<!ELEMENT review_date (#PCDATA)>
<!ELEMENT stop_date (#PCDATA)>
<!ELEMENT dmd_code (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
