use super::types::{AssessmentData, TriState};

/// Declarative rule definition. Each rule resolves to a tri-state value:
///   "yes" = performed correctly (awards `points`)
///   "no"  = not performed / failed (0 points, counts toward max)
///   "na"  = not applicable (excluded from both numerator and denominator)
///   ""    = unanswered (excluded from both numerator and denominator)
///
/// `critical = true` means any "no" forces an automatic Fail outcome.
pub struct PsychomotorRule {
    pub id: &'static str,
    pub step: u32,
    pub category: &'static str,
    pub label: &'static str,
    pub critical: bool,
    pub points: u32,
    pub evaluate: fn(&AssessmentData) -> TriState,
}

/// Normalise a TriState string into one of "yes" / "no" / "na" / "".
fn norm(v: &str) -> TriState {
    match v {
        "yes" | "no" | "na" => v.to_string(),
        _ => String::new(),
    }
}

/// All NREMT EMT Psychomotor Skills Examination rules.
pub fn all_rules() -> Vec<PsychomotorRule> {
    vec![
        // --- Step 2: Scene Size-Up -------------------------------------
        PsychomotorRule {
            id: "EMT-SS-PPE",
            step: 2,
            category: "Scene Size-Up",
            label: "Takes or verbalizes appropriate body-substance / PPE precautions.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.scene_size_up.ppe_precautions),
        },
        PsychomotorRule {
            id: "EMT-SS-SAFE",
            step: 2,
            category: "Scene Size-Up",
            label: "Determines the scene / situation is safe before approaching the patient.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.scene_size_up.scene_safe),
        },
        PsychomotorRule {
            id: "EMT-SS-MOI-NOI",
            step: 2,
            category: "Scene Size-Up",
            label: "Determines the mechanism of injury / nature of illness (MOI/NOI).",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.scene_size_up.mechanism_or_nature),
        },
        PsychomotorRule {
            id: "EMT-SS-PATIENTS",
            step: 2,
            category: "Scene Size-Up",
            label: "Determines the number of patients on scene.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.scene_size_up.number_of_patients),
        },
        PsychomotorRule {
            id: "EMT-SS-RESOURCES",
            step: 2,
            category: "Scene Size-Up",
            label: "Requests additional EMS / ALS / fire / law-enforcement resources as needed.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.scene_size_up.additional_resources),
        },
        PsychomotorRule {
            id: "EMT-SS-CSPINE",
            step: 2,
            category: "Scene Size-Up",
            label: "Considers stabilization of the spine when indicated by MOI.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.scene_size_up.considers_cspine),
        },
        // --- Step 3: Primary Survey ------------------------------------
        PsychomotorRule {
            id: "EMT-PS-IMPRESSION",
            step: 3,
            category: "Primary Survey",
            label: "Verbalizes a general impression of the patient.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.primary_survey.general_impression),
        },
        PsychomotorRule {
            id: "EMT-PS-MENTAL",
            step: 3,
            category: "Primary Survey",
            label: "Determines responsiveness / level of consciousness (AVPU).",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.primary_survey.mental_status),
        },
        PsychomotorRule {
            id: "EMT-PS-AIRWAY",
            step: 3,
            category: "Primary Survey",
            label: "Assesses airway and initiates appropriate airway management.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.primary_survey.airway),
        },
        PsychomotorRule {
            id: "EMT-PS-BREATHING",
            step: 3,
            category: "Primary Survey",
            label: "Assesses breathing and initiates appropriate ventilatory support.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.primary_survey.breathing),
        },
        PsychomotorRule {
            id: "EMT-PS-OXYGEN",
            step: 3,
            category: "Primary Survey",
            label: "Provides appropriate oxygen therapy when indicated.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.primary_survey.oxygen_therapy),
        },
        PsychomotorRule {
            id: "EMT-PS-CIRCULATION",
            step: 3,
            category: "Primary Survey",
            label: "Assesses circulation, controls major bleeding, and manages shock.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.primary_survey.circulation),
        },
        PsychomotorRule {
            id: "EMT-PS-TRANSPORT",
            step: 3,
            category: "Primary Survey",
            label: "Identifies patient priority and makes a transport urgency decision.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.primary_survey.transport_priority),
        },
        // --- Step 4: History & Secondary Assessment -------------------
        PsychomotorRule {
            id: "EMT-HX-CC",
            step: 4,
            category: "History",
            label: "Elicits the chief complaint clearly.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.chief_complaint),
        },
        PsychomotorRule {
            id: "EMT-HX-OPQRST",
            step: 4,
            category: "History",
            label: "Obtains OPQRST history of the present illness.",
            critical: false,
            points: 2,
            evaluate: |d| norm(&d.history_secondary_assessment.history_onset_opqrst),
        },
        PsychomotorRule {
            id: "EMT-HX-SAMPLE-S",
            step: 4,
            category: "SAMPLE History",
            label: "SAMPLE — Signs / Symptoms.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.sample_signs_symptoms),
        },
        PsychomotorRule {
            id: "EMT-HX-SAMPLE-A",
            step: 4,
            category: "SAMPLE History",
            label: "SAMPLE — Allergies.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.sample_allergies),
        },
        PsychomotorRule {
            id: "EMT-HX-SAMPLE-M",
            step: 4,
            category: "SAMPLE History",
            label: "SAMPLE — Medications.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.sample_medications),
        },
        PsychomotorRule {
            id: "EMT-HX-SAMPLE-P",
            step: 4,
            category: "SAMPLE History",
            label: "SAMPLE — Past pertinent medical / surgical history.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.sample_past_history),
        },
        PsychomotorRule {
            id: "EMT-HX-SAMPLE-L",
            step: 4,
            category: "SAMPLE History",
            label: "SAMPLE — Last oral intake.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.sample_last_intake),
        },
        PsychomotorRule {
            id: "EMT-HX-SAMPLE-E",
            step: 4,
            category: "SAMPLE History",
            label: "SAMPLE — Events leading up to the illness.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.sample_events),
        },
        PsychomotorRule {
            id: "EMT-SA-FOCUSED",
            step: 4,
            category: "Secondary Assessment",
            label: "Performs a focused / detailed physical exam appropriate to the chief complaint.",
            critical: false,
            points: 2,
            evaluate: |d| norm(&d.history_secondary_assessment.focused_exam),
        },
        PsychomotorRule {
            id: "EMT-SA-VITALS-BP",
            step: 4,
            category: "Baseline Vitals",
            label: "Obtains baseline blood pressure.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.baseline_vitals_bp),
        },
        PsychomotorRule {
            id: "EMT-SA-VITALS-PULSE",
            step: 4,
            category: "Baseline Vitals",
            label: "Obtains baseline pulse rate and quality.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.baseline_vitals_pulse),
        },
        PsychomotorRule {
            id: "EMT-SA-VITALS-RESP",
            step: 4,
            category: "Baseline Vitals",
            label: "Obtains baseline respiratory rate and quality.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.baseline_vitals_respirations),
        },
        PsychomotorRule {
            id: "EMT-SA-FIELD-IMPRESSION",
            step: 4,
            category: "Secondary Assessment",
            label: "States a field impression / working diagnosis.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.field_impression),
        },
        PsychomotorRule {
            id: "EMT-SA-INTERVENTIONS",
            step: 4,
            category: "Secondary Assessment",
            label: "Initiates appropriate interventions and verbalizes care plan.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.history_secondary_assessment.interventions),
        },
        // --- Step 5: Reassessment --------------------------------------
        PsychomotorRule {
            id: "EMT-RA-MENTAL",
            step: 5,
            category: "Reassessment",
            label: "Repeats mental-status assessment.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.reassessment.repeats_mental_status),
        },
        PsychomotorRule {
            id: "EMT-RA-AIRWAY",
            step: 5,
            category: "Reassessment",
            label: "Repeats airway assessment.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.reassessment.repeats_airway),
        },
        PsychomotorRule {
            id: "EMT-RA-BREATHING",
            step: 5,
            category: "Reassessment",
            label: "Repeats breathing assessment.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.reassessment.repeats_breathing),
        },
        PsychomotorRule {
            id: "EMT-RA-CIRCULATION",
            step: 5,
            category: "Reassessment",
            label: "Repeats circulation assessment.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.reassessment.repeats_circulation),
        },
        PsychomotorRule {
            id: "EMT-RA-VITALS",
            step: 5,
            category: "Reassessment",
            label: "Repeats and records vital signs.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.reassessment.repeats_vitals),
        },
        PsychomotorRule {
            id: "EMT-RA-FOCUSED",
            step: 5,
            category: "Reassessment",
            label: "Repeats focused assessment regarding patient complaint or injuries.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.reassessment.repeats_focused_exam),
        },
        PsychomotorRule {
            id: "EMT-RA-EVAL-INT",
            step: 5,
            category: "Reassessment",
            label: "Evaluates effectiveness of interventions and adjusts as needed.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.reassessment.evaluates_interventions),
        },
        PsychomotorRule {
            id: "EMT-RA-TRANSPORT-INT",
            step: 5,
            category: "Reassessment",
            label: "Manages and reassesses transport interventions en route.",
            critical: false,
            points: 1,
            evaluate: |d| norm(&d.reassessment.transport_interventions),
        },
        PsychomotorRule {
            id: "EMT-RA-FIFTEEN-MIN",
            step: 5,
            category: "Reassessment",
            label: "Provides patient hand-off / radio report within 15 minutes of arrival on scene.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.reassessment.fifteen_minute_call),
        },
        // --- Step 6: Critical Criteria Review --------------------------
        PsychomotorRule {
            id: "EMT-CC-DANGEROUS",
            step: 6,
            category: "Critical Criteria",
            label: "Did NOT perform any dangerous or harmful intervention.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.critical_criteria_review.dangerous_intervention),
        },
        PsychomotorRule {
            id: "EMT-CC-SPINAL",
            step: 6,
            category: "Critical Criteria",
            label: "Provided spinal protection when indicated by MOI.",
            critical: true,
            points: 1,
            evaluate: |d| norm(&d.critical_criteria_review.spinal_protection),
        },
    ]
}
