mod users;

mod patients;
mod clinicians;
mod caprini_venous_thromboembolism_risk_assessments;
mod caprini_venous_thromboembolism_risk_assessment_grades;
mod caprini_venous_thromboembolism_risk_assessment_grade_rules;
mod caprini_venous_thromboembolism_risk_assessment_grade_flags;