//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::plastic_surg_waiting_list_card_appointments::Entity as PlasticSurgWaitingListCardAppointments;
pub use super::plastic_surg_waiting_list_card_grade_flags::Entity as PlasticSurgWaitingListCardGradeFlags;
pub use super::plastic_surg_waiting_list_card_grade_rules::Entity as PlasticSurgWaitingListCardGradeRules;
pub use super::plastic_surg_waiting_list_card_grades::Entity as PlasticSurgWaitingListCardGrades;
pub use super::plastic_surg_waiting_list_cards::Entity as PlasticSurgWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
