mod users;

mod patients;
mod practitioners;
mod stomatology_waiting_list_cards;
mod stomatology_waiting_list_card_appointments;
mod stomatology_waiting_list_card_grades;
mod stomatology_waiting_list_card_grade_rules;
mod stomatology_waiting_list_card_grade_flags;