<!ELEMENT has_bled_score_for_major_bleeding_risk (id,created_at,updated_at,deleted_at,patient_id,clinician_id,clinician_name,clinician_role,assessed_at,care_setting,anticoagulation_status,cha_ds_vasc_score,patient_identifier,age_years,sex,hypertension_uncontrolled,abnormal_renal_function,abnormal_liver_function,stroke_history,bleeding_history,labile_inr)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT clinician_name (#PCDATA)>
<!ELEMENT clinician_role (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT anticoagulation_status (#PCDATA)>
<!ELEMENT cha_ds_vasc_score (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT age_years (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT hypertension_uncontrolled (#PCDATA)>
<!ELEMENT abnormal_renal_function (#PCDATA)>
<!ELEMENT abnormal_liver_function (#PCDATA)>
<!ELEMENT stroke_history (#PCDATA)>
<!ELEMENT bleeding_history (#PCDATA)>
<!ELEMENT labile_inr (#PCDATA)>
