<!ELEMENT has_bled_score_for_major_bleeding_risk_grade (id,created_at,updated_at,deleted_at,has_bled_score_for_major_bleeding_risk_id,hypertension_points,renal_points,liver_points,stroke_points,bleeding_points,labile_inr_points,elderly_points,drugs_points,alcohol_points,total_score,risk_band,modifiable_factors,graded_at)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT has_bled_score_for_major_bleeding_risk_id (#PCDATA)>
<!ELEMENT hypertension_points (#PCDATA)>
<!ELEMENT renal_points (#PCDATA)>
<!ELEMENT liver_points (#PCDATA)>
<!ELEMENT stroke_points (#PCDATA)>
<!ELEMENT bleeding_points (#PCDATA)>
<!ELEMENT labile_inr_points (#PCDATA)>
<!ELEMENT elderly_points (#PCDATA)>
<!ELEMENT drugs_points (#PCDATA)>
<!ELEMENT alcohol_points (#PCDATA)>
<!ELEMENT total_score (#PCDATA)>
<!ELEMENT risk_band (#PCDATA)>
<!ELEMENT modifiable_factors (#PCDATA)>
<!ELEMENT graded_at (#PCDATA)>
