<!ELEMENT confusion_assessment_method (id,created_at,updated_at,deleted_at,patient_id,clinician_id,assessor_name,assessor_role,assessed_at,ward_unit,cam_variant,patient_identifier,age_band,sex,cognitive_baseline,collateral_source,feature_acute_onset_fluctuating,onset_timing,feature_inattention,attention_test,feature_disorganised_thinking,feature_altered_consciousness,consciousness_level,rass_score,motoric_subtype,hallucinations,delusions,sleep_wake_disturbance,deliriogenic_medication,deliriogenic_medication_detail,suspected_precipitants,recommended_actions,clinical_note)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT assessor_name (#PCDATA)>
<!ELEMENT assessor_role (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT ward_unit (#PCDATA)>
<!ELEMENT cam_variant (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT age_band (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT cognitive_baseline (#PCDATA)>
<!ELEMENT collateral_source (#PCDATA)>
<!ELEMENT feature_acute_onset_fluctuating (#PCDATA)>
<!ELEMENT onset_timing (#PCDATA)>
<!ELEMENT feature_inattention (#PCDATA)>
<!ELEMENT attention_test (#PCDATA)>
<!ELEMENT feature_disorganised_thinking (#PCDATA)>
<!ELEMENT feature_altered_consciousness (#PCDATA)>
<!ELEMENT consciousness_level (#PCDATA)>
<!ELEMENT rass_score (#PCDATA)>
<!ELEMENT motoric_subtype (#PCDATA)>
<!ELEMENT hallucinations (#PCDATA)>
<!ELEMENT delusions (#PCDATA)>
<!ELEMENT sleep_wake_disturbance (#PCDATA)>
<!ELEMENT deliriogenic_medication (#PCDATA)>
<!ELEMENT deliriogenic_medication_detail (#PCDATA)>
<!ELEMENT suspected_precipitants (#PCDATA)>
<!ELEMENT recommended_actions (#PCDATA)>
<!ELEMENT clinical_note (#PCDATA)>
