use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.create_table(
            Table::create()
                .table(Alias::new("neurodiversity_adjustment_responses"))
                .if_not_exists()
                .col(
                    ColumnDef::new(Alias::new("id"))
                        .uuid()
                        .not_null()
                        .default(Expr::cust("gen_random_uuid()"))
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(Alias::new("created_at"))
                        .timestamp_with_time_zone()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Alias::new("updated_at"))
                        .timestamp_with_time_zone()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Alias::new("deleted_at"))
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(ColumnDef::new(Alias::new("worker_id")).uuid().not_null())
                .col(ColumnDef::new(Alias::new("manager_id")).uuid().not_null())
                .col(
                    ColumnDef::new(Alias::new("response_status"))
                        .string()
                        .not_null()
                        .default("draft"),
                )
                .col(
                    ColumnDef::new(Alias::new("request_reference"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("handling_method"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(ColumnDef::new(Alias::new("assessed_date")).date().null())
                .col(ColumnDef::new(Alias::new("responded_date")).date().null())
                .col(ColumnDef::new(Alias::new("effective_date")).date().null())
                .col(
                    ColumnDef::new(Alias::new("overall_decision"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("decision_rationale"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("decline_reason_category"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_working_environment"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_equipment_technology"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_working_arrangements"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_communication"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_support_mentoring"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_recruitment_process"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_policy_dress"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_other"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("agreed_adjustments_detail"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("alternative_adjustments_detail"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("trial_period"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("trial_period_weeks"))
                        .integer()
                        .null(),
                )
                .col(
                    ColumnDef::new(Alias::new("review_scheduled"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(ColumnDef::new(Alias::new("review_date")).date().null())
                .col(
                    ColumnDef::new(Alias::new("occupational_health_referred"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("access_to_work_referred"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("support_resources_detail"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("responsibilities_detail"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("point_of_contact"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("escalated"))
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(Alias::new("escalation_detail"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .col(
                    ColumnDef::new(Alias::new("notes"))
                        .string()
                        .not_null()
                        .default(""),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_neurodiversity_adjustment_responses_worker_id")
                        .from(
                            Alias::new("neurodiversity_adjustment_responses"),
                            Alias::new("worker_id"),
                        )
                        .to(Alias::new("workers"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::Cascade)
                        .on_update(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_neurodiversity_adjustment_responses_manager_id")
                        .from(
                            Alias::new("neurodiversity_adjustment_responses"),
                            Alias::new("manager_id"),
                        )
                        .to(Alias::new("managers"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::Cascade)
                        .on_update(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

        m.create_index(
            Index::create()
                .if_not_exists()
                .name("index_neurodiversity_adjustment_response_worker_id")
                .table(Alias::new("neurodiversity_adjustment_responses"))
                .col(Alias::new("worker_id"))
                .to_owned(),
        )
        .await?;

        m.create_index(
            Index::create()
                .if_not_exists()
                .name("index_neurodiversity_adjustment_response_manager_id")
                .table(Alias::new("neurodiversity_adjustment_responses"))
                .col(Alias::new("manager_id"))
                .to_owned(),
        )
        .await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.drop_table(
            Table::drop()
                .table(Alias::new("neurodiversity_adjustment_responses"))
                .to_owned(),
        )
        .await
    }
}
