<!ELEMENT application_eligible_condition (id,created_at,updated_at,deleted_at,application_id,eligible_condition_id,diagnosis_date,snomed_ct_code,icd10_code,treatment_detail,fistula_site,appliance_type,substitution_therapy,on_substitution_therapy,diabetes_treatment_mode,anticonvulsant,continuous_anticonvulsant_therapy,cannot_leave_home_unaided,disability_carer_detail,disability_expected_to_be_permanent,cancer_site,cancer_treatment_phase,histology_confirmed,practitioner_attestation_notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT application_id (#PCDATA)>
<!ELEMENT eligible_condition_id (#PCDATA)>
<!ELEMENT diagnosis_date (#PCDATA)>
<!ELEMENT snomed_ct_code (#PCDATA)>
<!ELEMENT icd10_code (#PCDATA)>
<!ELEMENT treatment_detail (#PCDATA)>
<!ELEMENT fistula_site (#PCDATA)>
<!ELEMENT appliance_type (#PCDATA)>
<!ELEMENT substitution_therapy (#PCDATA)>
<!ELEMENT on_substitution_therapy (#PCDATA)>
<!ELEMENT diabetes_treatment_mode (#PCDATA)>
<!ELEMENT anticonvulsant (#PCDATA)>
<!ELEMENT continuous_anticonvulsant_therapy (#PCDATA)>
<!ELEMENT cannot_leave_home_unaided (#PCDATA)>
<!ELEMENT disability_carer_detail (#PCDATA)>
<!ELEMENT disability_expected_to_be_permanent (#PCDATA)>
<!ELEMENT cancer_site (#PCDATA)>
<!ELEMENT cancer_treatment_phase (#PCDATA)>
<!ELEMENT histology_confirmed (#PCDATA)>
<!ELEMENT practitioner_attestation_notes (#PCDATA)>
