//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::clinicians::Entity as Clinicians;
pub use super::histopathology_test_request_grade_flags::Entity as HistopathologyTestRequestGradeFlags;
pub use super::histopathology_test_request_grade_rules::Entity as HistopathologyTestRequestGradeRules;
pub use super::histopathology_test_request_grades::Entity as HistopathologyTestRequestGrades;
pub use super::histopathology_test_requests::Entity as HistopathologyTestRequests;
pub use super::patients::Entity as Patients;
pub use super::users::Entity as Users;
