<!ELEMENT wells_score_for_deep_vein_thrombosis (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,patient_identifier,assessed_at,care_setting,age_band,symptomatic_leg,active_cancer,paralysis_or_immobilisation,recently_bedridden_or_surgery,localised_tenderness,entire_leg_swollen,calf_swelling_over_3cm,pitting_oedema,collateral_superficial_veins,previously_documented_dvt,alternative_diagnosis_as_likely,clinical_notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT age_band (#PCDATA)>
<!ELEMENT symptomatic_leg (#PCDATA)>
<!ELEMENT active_cancer (#PCDATA)>
<!ELEMENT paralysis_or_immobilisation (#PCDATA)>
<!ELEMENT recently_bedridden_or_surgery (#PCDATA)>
<!ELEMENT localised_tenderness (#PCDATA)>
<!ELEMENT entire_leg_swollen (#PCDATA)>
<!ELEMENT calf_swelling_over_3cm (#PCDATA)>
<!ELEMENT pitting_oedema (#PCDATA)>
<!ELEMENT collateral_superficial_veins (#PCDATA)>
<!ELEMENT previously_documented_dvt (#PCDATA)>
<!ELEMENT alternative_diagnosis_as_likely (#PCDATA)>
<!ELEMENT clinical_notes (#PCDATA)>
