mod users;

mod patients;
mod practitioners;
mod anaesthetics_waiting_list_cards;
mod anaesthetics_waiting_list_card_appointments;
mod anaesthetics_waiting_list_card_grades;
mod anaesthetics_waiting_list_card_grade_rules;
mod anaesthetics_waiting_list_card_grade_flags;