<!ELEMENT ct_scan_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,body_region,primary_indication,clinical_question,relevant_history,contrast_required,pregnancy_status,egfr,previous_contrast_reaction,iodine_contrast_allergy,metformin,diabetes,renal_impairment,weight_kg,relevant_previous_imaging,urgency,supervising_consultant,ir_me_r_justification,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT body_region (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT contrast_required (#PCDATA)>
<!ELEMENT pregnancy_status (#PCDATA)>
<!ELEMENT egfr (#PCDATA)>
<!ELEMENT previous_contrast_reaction (#PCDATA)>
<!ELEMENT iodine_contrast_allergy (#PCDATA)>
<!ELEMENT metformin (#PCDATA)>
<!ELEMENT diabetes (#PCDATA)>
<!ELEMENT renal_impairment (#PCDATA)>
<!ELEMENT weight_kg (#PCDATA)>
<!ELEMENT relevant_previous_imaging (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT ir_me_r_justification (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
