<!ELEMENT sleep_study_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,study_type,primary_indication,clinical_question,relevant_history,epworth_score,stop_bang_score,body_mass_index,neck_circumference_cm,witnessed_apnoeas,occupational_driver,cardiovascular_disease,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT study_type (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT epworth_score (#PCDATA)>
<!ELEMENT stop_bang_score (#PCDATA)>
<!ELEMENT body_mass_index (#PCDATA)>
<!ELEMENT neck_circumference_cm (#PCDATA)>
<!ELEMENT witnessed_apnoeas (#PCDATA)>
<!ELEMENT occupational_driver (#PCDATA)>
<!ELEMENT cardiovascular_disease (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
