<!ELEMENT history_and_physical_examination (id,created_at,updated_at,deleted_at,patient_id,clinician_id,clerked_at,clinician_role,registration_number,care_setting,admission_source,patient_identifier,age_band,sex,presenting_complaint,history_of_presenting_complaint,past_medical_surgical_history,drug_history,allergy_status,allergy_detail,family_history,social_history,systems_review,temperature,heart_rate,respiratory_rate,systolic_blood_pressure,oxygen_saturation,consciousness_level,exam_cardiovascular,exam_respiratory,exam_abdominal,exam_neurological,exam_other,investigations,impression,red_flag_findings,management_plan,clinical_note)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT clerked_at (#PCDATA)>
<!ELEMENT clinician_role (#PCDATA)>
<!ELEMENT registration_number (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT admission_source (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT age_band (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT presenting_complaint (#PCDATA)>
<!ELEMENT history_of_presenting_complaint (#PCDATA)>
<!ELEMENT past_medical_surgical_history (#PCDATA)>
<!ELEMENT drug_history (#PCDATA)>
<!ELEMENT allergy_status (#PCDATA)>
<!ELEMENT allergy_detail (#PCDATA)>
<!ELEMENT family_history (#PCDATA)>
<!ELEMENT social_history (#PCDATA)>
<!ELEMENT systems_review (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ELEMENT heart_rate (#PCDATA)>
<!ELEMENT respiratory_rate (#PCDATA)>
<!ELEMENT systolic_blood_pressure (#PCDATA)>
<!ELEMENT oxygen_saturation (#PCDATA)>
<!ELEMENT consciousness_level (#PCDATA)>
<!ELEMENT exam_cardiovascular (#PCDATA)>
<!ELEMENT exam_respiratory (#PCDATA)>
<!ELEMENT exam_abdominal (#PCDATA)>
<!ELEMENT exam_neurological (#PCDATA)>
<!ELEMENT exam_other (#PCDATA)>
<!ELEMENT investigations (#PCDATA)>
<!ELEMENT impression (#PCDATA)>
<!ELEMENT red_flag_findings (#PCDATA)>
<!ELEMENT management_plan (#PCDATA)>
<!ELEMENT clinical_note (#PCDATA)>
