use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.create_table(
            Table::create()
                .table(Alias::new("cardiology_responses"))
                .if_not_exists()
                .col(
                    ColumnDef::new(Alias::new("id"))
                        .uuid()
                        .not_null()
                        .default(Expr::cust("gen_random_uuid()"))
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(Alias::new("created_at"))
                        .timestamp_with_time_zone()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Alias::new("updated_at"))
                        .timestamp_with_time_zone()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Alias::new("deleted_at"))
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(ColumnDef::new(Alias::new("patient_id")).uuid().not_null())
                .col(ColumnDef::new(Alias::new("clinician_id")).uuid().not_null())
                .col(
                    ColumnDef::new(Alias::new("originating_request_reference"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("response_status"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("consultation_type"))
                        .string()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("assessed_date")).date().null())
                .col(ColumnDef::new(Alias::new("responded_date")).date().null())
                .col(
                    ColumnDef::new(Alias::new("clinical_summary"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("examination_findings"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("investigations_performed"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("ischaemia_or_cad"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("significant_arrhythmia"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("reduced_ejection_fraction"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("significant_valve_disease"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("structural_abnormality"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("uncontrolled_hypertension"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("non_cardiac_cause"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("primary_diagnosis_category"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("diagnosis_narrative"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("lv_ejection_fraction_percent"))
                        .double()
                        .null(),
                )
                .col(
                    ColumnDef::new(Alias::new("management_plan"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("medication_changes"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("recommended_follow_up"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("critical_result"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("critical_result_communicated"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("reported_to"))
                        .string()
                        .not_null(),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_cardiology_responses_patient_id")
                        .from(Alias::new("cardiology_responses"), Alias::new("patient_id"))
                        .to(Alias::new("patients"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::Cascade)
                        .on_update(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_cardiology_responses_clinician_id")
                        .from(
                            Alias::new("cardiology_responses"),
                            Alias::new("clinician_id"),
                        )
                        .to(Alias::new("clinicians"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::Cascade)
                        .on_update(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

        m.create_index(
            Index::create()
                .if_not_exists()
                .name("index_cardiology_response_patient_id")
                .table(Alias::new("cardiology_responses"))
                .col(Alias::new("patient_id"))
                .to_owned(),
        )
        .await?;

        m.create_index(
            Index::create()
                .if_not_exists()
                .name("index_cardiology_response_clinician_id")
                .table(Alias::new("cardiology_responses"))
                .col(Alias::new("clinician_id"))
                .to_owned(),
        )
        .await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.drop_table(
            Table::drop()
                .table(Alias::new("cardiology_responses"))
                .to_owned(),
        )
        .await
    }
}
