//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::endocrinology_waiting_list_card_appointments::Entity as EndocrinologyWaitingListCardAppointments;
pub use super::endocrinology_waiting_list_card_grade_flags::Entity as EndocrinologyWaitingListCardGradeFlags;
pub use super::endocrinology_waiting_list_card_grade_rules::Entity as EndocrinologyWaitingListCardGradeRules;
pub use super::endocrinology_waiting_list_card_grades::Entity as EndocrinologyWaitingListCardGrades;
pub use super::endocrinology_waiting_list_cards::Entity as EndocrinologyWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
