//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::trop_med_waiting_list_card_appointments::Entity as TropMedWaitingListCardAppointments;
pub use super::trop_med_waiting_list_card_grade_flags::Entity as TropMedWaitingListCardGradeFlags;
pub use super::trop_med_waiting_list_card_grade_rules::Entity as TropMedWaitingListCardGradeRules;
pub use super::trop_med_waiting_list_card_grades::Entity as TropMedWaitingListCardGrades;
pub use super::trop_med_waiting_list_cards::Entity as TropMedWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
