#!/bin/sh
set -euf

form_kebab_case=united-states-hipaa-authorization-form
form_snake_case=united_states_hipaa_authorization_form

createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_development" || :
createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_test" || :
createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_production" || :

loco new --name "${form_snake_case}" --db postgres --bg async --assets none -a
cd "${form_snake_case}"

# Pin time to a version compatible with cookie 0.18.1 (a fresh loco
# starter otherwise resolves time 0.3.52, which fails to compile).
cargo update -p time --precise 0.3.47

cargo loco generate scaffold patient \
    deleted_at:tstz \
    name:string! \
    birth_date:date \
    social_security_number:string! \
    street_address:text! \
    city:string! \
    state:string! \
    zip_code:string! \
    phone:string! \
    email:string! \
    --api

cargo loco generate scaffold hipaa_authorization \
    deleted_at:tstz \
    patient:references \
    status:string! \
    state_template:string! \
    revoked_at:tstz \
    revocation_method:string! \
    --api

cargo loco generate scaffold signer \
    deleted_at:tstz \
    hipaa_authorization:references \
    relationship:string! \
    representative_name:string! \
    representative_authority_description:text! \
    representative_authority_proof_attached:string! \
    --api

cargo loco generate scaffold disclosing_source \
    deleted_at:tstz \
    hipaa_authorization:references \
    identification_mode:string! \
    specific_persons_or_organizations:text! \
    class_description:text! \
    is_va_facility:string! \
    is_part_2_program:string! \
    --api

cargo loco generate scaffold authorized_recipient \
    deleted_at:tstz \
    hipaa_authorization:references \
    recipient_name:string! \
    recipient_organization:string! \
    recipient_role:string! \
    recipient_address:text! \
    recipient_phone:string! \
    recipient_email:string! \
    recipient_relationship_to_patient:string! \
    --api

cargo loco generate scaffold records_to_disclose \
    deleted_at:tstz \
    hipaa_authorization:references \
    include_medical_health:string! \
    medical_health_initials:string! \
    include_mental_health:string! \
    mental_health_initials:string! \
    include_substance_use:string! \
    substance_use_initials:string! \
    part2_redisclosure_notice_included:string! \
    include_hiv_aids:string! \
    hiv_aids_initials:string! \
    hiv_aids_state_consent_included:string! \
    include_psychotherapy_notes:string! \
    include_genetic_information:string! \
    include_reproductive_health:string! \
    section_7332_notice_included:string! \
    date_range_specified:string! \
    date_from:date \
    date_to:date \
    other_description:text! \
    --api

cargo loco generate scaffold purpose_of_disclosure \
    deleted_at:tstz \
    hipaa_authorization:references \
    purposes:text! \
    primary_purpose:string! \
    other_details:text! \
    --api

cargo loco generate scaffold expiration \
    deleted_at:tstz \
    hipaa_authorization:references \
    kind:string! \
    expiration_date:date \
    expiration_event:text! \
    duration_months:int \
    duration_label:string! \
    --api

cargo loco generate scaffold patient_rights_acknowledgement \
    deleted_at:tstz \
    hipaa_authorization:references \
    acknowledged_right_to_revoke:string! \
    acknowledged_revocation_procedure:string! \
    acknowledged_no_conditioning:string! \
    acknowledged_redisclosure_warning:string! \
    acknowledged_right_to_copy:string! \
    acknowledged_right_to_inspect_disclosed:string! \
    --api

cargo loco generate scaffold signature_witness \
    deleted_at:tstz \
    hipaa_authorization:references \
    individual_signature_confirmed:string! \
    individual_signature_image_uri:text! \
    signature_date:date \
    signed_at_location:text! \
    parent_guardian_co_signature_required:string! \
    parent_guardian_name:string! \
    parent_guardian_signature_confirmed:string! \
    parent_guardian_signature_date:date \
    witness_name:string! \
    witness_signature_confirmed:string! \
    witness_date:date \
    witness_role:string! \
    --api

cargo loco generate scaffold validation_result \
    deleted_at:tstz \
    hipaa_authorization:references \
    validity_status:string! \
    completeness_score:int! \
    completeness_status:string! \
    validated_at:tstz \
    validator_version:string! \
    --api

cargo loco generate scaffold validation_fired_rule \
    deleted_at:tstz \
    validation_result:references \
    rule_id:string! \
    citation:string! \
    domain:string! \
    description:text! \
    priority:string! \
    --api

cargo loco generate scaffold validation_additional_flag \
    deleted_at:tstz \
    validation_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --api
