<!ELEMENT blood_cross_match_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,request_type,component,units_required,primary_indication,clinical_details,patient_blood_group,known_antibodies,antibody_detail,previous_transfusion,previous_transfusion_reaction,pregnant,sample_collected,collection_datetime,two_sample_rule_met,required_by_datetime,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT request_type (#PCDATA)>
<!ELEMENT component (#PCDATA)>
<!ELEMENT units_required (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_details (#PCDATA)>
<!ELEMENT patient_blood_group (#PCDATA)>
<!ELEMENT known_antibodies (#PCDATA)>
<!ELEMENT antibody_detail (#PCDATA)>
<!ELEMENT previous_transfusion (#PCDATA)>
<!ELEMENT previous_transfusion_reaction (#PCDATA)>
<!ELEMENT pregnant (#PCDATA)>
<!ELEMENT sample_collected (#PCDATA)>
<!ELEMENT collection_datetime (#PCDATA)>
<!ELEMENT two_sample_rule_met (#PCDATA)>
<!ELEMENT required_by_datetime (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
