mod users;

mod patients;
mod practitioners;
mod urology_waiting_list_cards;
mod urology_waiting_list_card_appointments;
mod urology_waiting_list_card_grades;
mod urology_waiting_list_card_grade_rules;
mod urology_waiting_list_card_grade_flags;