use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.create_table(
            Table::create()
                .table(Alias::new("neurodiversity_adjustment_requests"))
                .if_not_exists()
                .col(
                    ColumnDef::new(Alias::new("id"))
                        .uuid()
                        .not_null()
                        .default(Expr::cust("gen_random_uuid()"))
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(Alias::new("created_at"))
                        .timestamp_with_time_zone()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Alias::new("updated_at"))
                        .timestamp_with_time_zone()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Alias::new("deleted_at"))
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(ColumnDef::new(Alias::new("worker_id")).uuid().not_null())
                .col(ColumnDef::new(Alias::new("manager_id")).uuid().not_null())
                .col(ColumnDef::new(Alias::new("status")).string().not_null())
                .col(
                    ColumnDef::new(Alias::new("requested_by"))
                        .string()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("request_date")).date().null())
                .col(
                    ColumnDef::new(Alias::new("requested_start_date"))
                        .date()
                        .null(),
                )
                .col(
                    ColumnDef::new(Alias::new("condition_adhd"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("condition_autism"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("condition_dyslexia"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("condition_dyspraxia"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("condition_dyscalculia"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("condition_tourettes"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("condition_other"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("condition_other_detail"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("diagnosis_status"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("considers_disability"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("substantial_long_term_impact"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("disclosure_consent"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("difficulty_concentration"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("difficulty_written_communication"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("difficulty_organisation_time"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("difficulty_sensory_overload"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("difficulty_balance_coordination"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("difficulty_social_communication"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("difficulty_memory"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("difficulty_burnout_wellbeing"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("tasks_situations_affected"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("worker_strengths"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustment_working_environment"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustment_equipment_technology"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustment_working_arrangements"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustment_communication"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustment_support_mentoring"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustment_recruitment_process"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustment_policy_dress"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustment_other"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("adjustments_requested_detail"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("supporting_evidence_type"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("occupational_health_involved"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("access_to_work_involved"))
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("current_impact"))
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Alias::new("at_risk_of_absence"))
                        .boolean()
                        .not_null(),
                )
                .col(ColumnDef::new(Alias::new("urgency")).string().not_null())
                .col(ColumnDef::new(Alias::new("notes")).string().not_null())
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_neurodiversity_adjustment_requests_worker_id")
                        .from(
                            Alias::new("neurodiversity_adjustment_requests"),
                            Alias::new("worker_id"),
                        )
                        .to(Alias::new("workers"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::Cascade)
                        .on_update(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_neurodiversity_adjustment_requests_manager_id")
                        .from(
                            Alias::new("neurodiversity_adjustment_requests"),
                            Alias::new("manager_id"),
                        )
                        .to(Alias::new("managers"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::Cascade)
                        .on_update(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

        m.create_index(
            Index::create()
                .if_not_exists()
                .name("index_neurodiversity_adjustment_request_worker_id")
                .table(Alias::new("neurodiversity_adjustment_requests"))
                .col(Alias::new("worker_id"))
                .to_owned(),
        )
        .await?;

        m.create_index(
            Index::create()
                .if_not_exists()
                .name("index_neurodiversity_adjustment_request_manager_id")
                .table(Alias::new("neurodiversity_adjustment_requests"))
                .col(Alias::new("manager_id"))
                .to_owned(),
        )
        .await
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.drop_table(
            Table::drop()
                .table(Alias::new("neurodiversity_adjustment_requests"))
                .to_owned(),
        )
        .await
    }
}
