<!ELEMENT mental_state_examination (id,created_at,updated_at,deleted_at,patient_id,clinician_id,clinician_name,clinician_role,assessed_at,care_setting,assessment_reason,patient_identifier,age_band,sex,appearance_grooming,appearance_eye_contact,appearance_rapport,appearance_psychomotor,appearance_abnormal_movements,appearance_notes,speech_rate,speech_volume,speech_quantity,speech_fluency,speech_notes,mood_subjective,mood_descriptor,affect_range,affect_congruence,affect_reactivity,emotion_notes,hallucinations_present,command_hallucinations,illusions,depersonalisation,derealisation,perception_notes,thought_form,delusions,obsessions,suicidal_ideation,homicidal_ideation,self_harm_thoughts,thought_notes,insight_level,treatment_understanding,judgement,insight_notes,orientation,attention,memory,cognitive_impression,cognition_notes,clinical_formulation)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT clinician_name (#PCDATA)>
<!ELEMENT clinician_role (#PCDATA)>
<!ELEMENT assessed_at (#PCDATA)>
<!ELEMENT care_setting (#PCDATA)>
<!ELEMENT assessment_reason (#PCDATA)>
<!ELEMENT patient_identifier (#PCDATA)>
<!ELEMENT age_band (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT appearance_grooming (#PCDATA)>
<!ELEMENT appearance_eye_contact (#PCDATA)>
<!ELEMENT appearance_rapport (#PCDATA)>
<!ELEMENT appearance_psychomotor (#PCDATA)>
<!ELEMENT appearance_abnormal_movements (#PCDATA)>
<!ELEMENT appearance_notes (#PCDATA)>
<!ELEMENT speech_rate (#PCDATA)>
<!ELEMENT speech_volume (#PCDATA)>
<!ELEMENT speech_quantity (#PCDATA)>
<!ELEMENT speech_fluency (#PCDATA)>
<!ELEMENT speech_notes (#PCDATA)>
<!ELEMENT mood_subjective (#PCDATA)>
<!ELEMENT mood_descriptor (#PCDATA)>
<!ELEMENT affect_range (#PCDATA)>
<!ELEMENT affect_congruence (#PCDATA)>
<!ELEMENT affect_reactivity (#PCDATA)>
<!ELEMENT emotion_notes (#PCDATA)>
<!ELEMENT hallucinations_present (#PCDATA)>
<!ELEMENT command_hallucinations (#PCDATA)>
<!ELEMENT illusions (#PCDATA)>
<!ELEMENT depersonalisation (#PCDATA)>
<!ELEMENT derealisation (#PCDATA)>
<!ELEMENT perception_notes (#PCDATA)>
<!ELEMENT thought_form (#PCDATA)>
<!ELEMENT delusions (#PCDATA)>
<!ELEMENT obsessions (#PCDATA)>
<!ELEMENT suicidal_ideation (#PCDATA)>
<!ELEMENT homicidal_ideation (#PCDATA)>
<!ELEMENT self_harm_thoughts (#PCDATA)>
<!ELEMENT thought_notes (#PCDATA)>
<!ELEMENT insight_level (#PCDATA)>
<!ELEMENT treatment_understanding (#PCDATA)>
<!ELEMENT judgement (#PCDATA)>
<!ELEMENT insight_notes (#PCDATA)>
<!ELEMENT orientation (#PCDATA)>
<!ELEMENT attention (#PCDATA)>
<!ELEMENT memory (#PCDATA)>
<!ELEMENT cognitive_impression (#PCDATA)>
<!ELEMENT cognition_notes (#PCDATA)>
<!ELEMENT clinical_formulation (#PCDATA)>
