//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "medical_operation_note_implants")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub category: String,
    pub name: String,
    pub size_or_gauge: String,
    pub quantity: i32,
    pub manufacturer: String,
    pub lot_number: String,
    pub serial_number: String,
    pub batch_number: String,
    pub expiry_date: Option<Date>,
    pub udi_di: String,
    pub implant_site: String,
    pub registry_required: String,
    pub registry_submitted: String,
    #[sea_orm(column_type = "Text")]
    pub notes: String,
    pub medical_operation_note_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::medical_operation_notes::Entity",
        from = "Column::MedicalOperationNoteId",
        to = "super::medical_operation_notes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MedicalOperationNotes,
}

impl Related<super::medical_operation_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalOperationNotes.def()
    }
}
