//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clinicians;
pub mod medical_operation_note_complications;
pub mod medical_operation_note_drains;
pub mod medical_operation_note_grade_flags;
pub mod medical_operation_note_grade_rules;
pub mod medical_operation_note_grades;
pub mod medical_operation_note_implants;
pub mod medical_operation_note_procedures;
pub mod medical_operation_note_specimens;
pub mod medical_operation_note_steps;
pub mod medical_operation_note_team_members;
pub mod medical_operation_notes;
pub mod patients;
pub mod users;
