<!ELEMENT microbiology_culture_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,specimen_type,specimen_site_detail,test_culture_and_sensitivity,test_gram_stain,test_acid_fast_bacilli_tb,test_fungal_culture,test_pcr_molecular,test_c_difficile_toxin,test_mrsa_screen,primary_indication,clinical_details,fever,current_antibiotics,antibiotic_name,recent_travel,immunocompromised,specimen_collected,collection_datetime,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT specimen_type (#PCDATA)>
<!ELEMENT specimen_site_detail (#PCDATA)>
<!ELEMENT test_culture_and_sensitivity (#PCDATA)>
<!ELEMENT test_gram_stain (#PCDATA)>
<!ELEMENT test_acid_fast_bacilli_tb (#PCDATA)>
<!ELEMENT test_fungal_culture (#PCDATA)>
<!ELEMENT test_pcr_molecular (#PCDATA)>
<!ELEMENT test_c_difficile_toxin (#PCDATA)>
<!ELEMENT test_mrsa_screen (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_details (#PCDATA)>
<!ELEMENT fever (#PCDATA)>
<!ELEMENT current_antibiotics (#PCDATA)>
<!ELEMENT antibiotic_name (#PCDATA)>
<!ELEMENT recent_travel (#PCDATA)>
<!ELEMENT immunocompromised (#PCDATA)>
<!ELEMENT specimen_collected (#PCDATA)>
<!ELEMENT collection_datetime (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
