<!ELEMENT medical_operation_note_specimen (id,created_at,updated_at,deleted_at,medical_operation_note_id,label,specimen_type,anatomical_site,container,fixative,destination,urgency,label_verified,chain_of_custody_documented,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT medical_operation_note_id (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT specimen_type (#PCDATA)>
<!ELEMENT anatomical_site (#PCDATA)>
<!ELEMENT container (#PCDATA)>
<!ELEMENT fixative (#PCDATA)>
<!ELEMENT destination (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT label_verified (#PCDATA)>
<!ELEMENT chain_of_custody_documented (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
