<!ELEMENT medical_operation_note_implant (id,created_at,updated_at,deleted_at,medical_operation_note_id,category,name,size_or_gauge,quantity,manufacturer,lot_number,serial_number,batch_number,expiry_date,udi_di,implant_site,registry_required,registry_submitted,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT medical_operation_note_id (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT size_or_gauge (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT lot_number (#PCDATA)>
<!ELEMENT serial_number (#PCDATA)>
<!ELEMENT batch_number (#PCDATA)>
<!ELEMENT expiry_date (#PCDATA)>
<!ELEMENT udi_di (#PCDATA)>
<!ELEMENT implant_site (#PCDATA)>
<!ELEMENT registry_required (#PCDATA)>
<!ELEMENT registry_submitted (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
