-- schema.sql
-- Combined schema for form: rockall-score-for-upper-gastrointestinal-bleeding
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (8):
--   - 00_create_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 02_create_table_patient.sql
--   - 03_create_table_clinician.sql
--   - 04_create_table_rockall_score_for_upper_gastrointestinal_bleeding.sql
--   - 05_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade.sql
--   - 06_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.sql
--   - 07_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.sql


-- ========================================================================
-- BEGIN 00_create_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm provides trigram operators used by free-text search GIN indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========================================================================
-- END 00_create_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 02_create_table_patient.sql
-- ========================================================================

-- Patient demographic information.

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    hospital_mrn VARCHAR(50),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    allergies_summary TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient demographic information used by the Rockall assessment record.';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN patient.name IS
    'Full patient name.';
COMMENT ON COLUMN patient.birth_date IS
    'Date of birth.';
COMMENT ON COLUMN patient.sex IS
    'Sex recorded for clinical purposes: female, male, intersex, or unknown.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.hospital_mrn IS
    'Local hospital medical record number (MRN).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height in centimetres.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight in kilograms.';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI), kg/m^2.';
COMMENT ON COLUMN patient.allergies_summary IS
    'Free-text summary of known allergies.';

CREATE INDEX patient_name_trgm_idx
    ON patient
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 02_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 03_create_table_clinician.sql
-- ========================================================================

-- Clinician employee information used to identify the assessing
-- clinician (doctor, nurse, gastroenterologist, endoscopist).

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role VARCHAR(40) NOT NULL DEFAULT '' CHECK (role IN ('doctor', 'nurse', 'gastroenterologist', 'endoscopist', 'other', '')),
    registration_body VARCHAR(20) NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'GPhC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician identifying information for the assessing clinician.';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN clinician.name IS
    'Clinician full name.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as a single text block.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code.';
COMMENT ON COLUMN clinician.role IS
    'Primary clinical role: doctor, nurse, gastroenterologist, endoscopist, or other.';
COMMENT ON COLUMN clinician.registration_body IS
    'Professional registration body: GMC, NMC, HCPC, GPhC, or other.';
COMMENT ON COLUMN clinician.registration_number IS
    'Professional registration number issued by the registration body.';

CREATE INDEX clinician_name_trgm_idx
    ON clinician
    USING GIN (name gin_trgm_ops);

-- ========================================================================
-- END 03_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_rockall_score_for_upper_gastrointestinal_bleeding.sql
-- ========================================================================

-- Main Rockall assessment record: assessment context, patient
-- identification, the three clinical parameter inputs (age, shock
-- derived from systolic blood pressure and pulse, comorbidity), and
-- the two endoscopic parameter inputs (diagnosis, stigmata of recent
-- haemorrhage) recorded only when endoscopy has been performed. The
-- computed grade, fired rules, and flags live in dedicated child
-- tables.

CREATE TABLE rockall_score_for_upper_gastrointestinal_bleeding (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE RESTRICT,
    clinician_id UUID REFERENCES clinician(id) ON DELETE RESTRICT,

    -- Step 1: assessment context
    clinician_name VARCHAR(255) NOT NULL DEFAULT '',
    clinician_role VARCHAR(20) NOT NULL DEFAULT '' CHECK (clinician_role IN ('doctor', 'nurse', 'gastroenterologist', 'endoscopist', 'other', '')),
    assessed_at TIMESTAMPTZ,
    care_setting VARCHAR(20) NOT NULL DEFAULT '' CHECK (care_setting IN ('emergency-department', 'ward', 'endoscopy-unit', 'other', '')),
    presenting_complaint TEXT NOT NULL DEFAULT '',

    -- Step 2: patient identification
    patient_identifier VARCHAR(100) NOT NULL DEFAULT '',
    age_years INT,
    sex VARCHAR(20) NOT NULL DEFAULT '' CHECK (sex IN ('female', 'male', 'intersex', 'unknown', '')),

    -- Step 3: shock — derived from the two vital signs (clinical parameter)
    systolic_blood_pressure_mmhg INT,
    heart_rate_bpm INT,

    -- Step 4: comorbidity (clinical parameter)
    comorbidity VARCHAR(20) NOT NULL DEFAULT '' CHECK (comorbidity IN ('none', 'major', 'severe', '')),

    -- Step 5: endoscopy gate
    endoscopy_performed VARCHAR(10) NOT NULL DEFAULT '' CHECK (endoscopy_performed IN ('yes', 'no', '')),

    -- Step 6: diagnosis (endoscopic parameter; full score only)
    diagnosis VARCHAR(30) NOT NULL DEFAULT '' CHECK (diagnosis IN ('mallory-weiss-or-none', 'all-other', 'upper-gi-malignancy', '')),

    -- Step 7: stigmata of recent haemorrhage (endoscopic parameter; full score only)
    stigmata_recent_haemorrhage VARCHAR(20) NOT NULL DEFAULT '' CHECK (stigmata_recent_haemorrhage IN ('none-or-dark-spot', 'high-risk', '')),

    -- Step 8: clinician free-text note
    clinical_note TEXT NOT NULL DEFAULT ''
);

CREATE INDEX rockall_score_for_upper_gastrointestinal_bleeding_patient_id_idx
    ON rockall_score_for_upper_gastrointestinal_bleeding (patient_id);
CREATE INDEX rockall_score_for_upper_gastrointestinal_bleeding_clinician_id_idx
    ON rockall_score_for_upper_gastrointestinal_bleeding (clinician_id);

CREATE TRIGGER trigger_rockall_score_for_upper_gastrointestinal_bleeding_updated_at
    BEFORE UPDATE ON rockall_score_for_upper_gastrointestinal_bleeding
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE rockall_score_for_upper_gastrointestinal_bleeding IS
    'Main Rockall assessment record: assessment context, patient identification, the three clinical parameter inputs (age, shock, comorbidity), and the two endoscopic parameter inputs (diagnosis, stigmata of recent haemorrhage).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.deleted_at IS
    'Timestamp when the record was deleted a.k.a. soft-removed.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.patient_id IS
    'Foreign key to the patient being assessed (delete restricted).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.clinician_id IS
    'Foreign key to the assessing clinician (optional; delete restricted).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.clinician_name IS
    'Name of the assessing clinician as recorded on the assessment.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.clinician_role IS
    'Role of the assessing clinician: doctor, nurse, gastroenterologist, endoscopist, or other.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.assessed_at IS
    'Date and time the assessment was performed.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.care_setting IS
    'Care setting: emergency-department, ward, endoscopy-unit, or other.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.presenting_complaint IS
    'Presenting complaint free text (e.g. haematemesis, melaena, coffee-ground vomiting).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.patient_identifier IS
    'Local patient identifier as recorded on the assessment.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.age_years IS
    'Clinical parameter — patient age in whole years; scores 0 (<60), 1 (60-79), or 2 (>=80).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.sex IS
    'Patient sex recorded for the assessment: female, male, intersex, or unknown.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.systolic_blood_pressure_mmhg IS
    'Clinical parameter (shock) — systolic blood pressure in mmHg; SBP < 100 scores 2 (hypotension).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.heart_rate_bpm IS
    'Clinical parameter (shock) — pulse in beats per minute; HR >= 100 scores 1 (tachycardia) when not hypotensive.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.comorbidity IS
    'Clinical parameter — comorbidity: none (0), major (cardiac failure / ischaemic heart disease / any major comorbidity, 2), or severe (renal failure / liver failure / disseminated malignancy, 3).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.endoscopy_performed IS
    'Whether endoscopy has been performed (yes / no); gates computation of the full post-endoscopy score.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.diagnosis IS
    'Endoscopic parameter (full score only) — diagnosis: mallory-weiss-or-none (0), all-other (1), or upper-gi-malignancy (2).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.stigmata_recent_haemorrhage IS
    'Endoscopic parameter (full score only) — stigmata of recent haemorrhage: none-or-dark-spot (0) or high-risk (blood in upper GI tract, adherent clot, or visible / spurting vessel, 2).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding.clinical_note IS
    'Free-text clinical note recorded with the assessment.';

-- ========================================================================
-- END 04_create_table_rockall_score_for_upper_gastrointestinal_bleeding.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade.sql
-- ========================================================================

-- Computed Rockall grading result. Stores each parameter's points, the
-- pre-endoscopy clinical score (0-7), the full post-endoscopy score
-- (0-11, null when endoscopy has not been performed), and the derived
-- risk band.

CREATE TABLE rockall_score_for_upper_gastrointestinal_bleeding_grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    rockall_score_for_upper_gastrointestinal_bleeding_id UUID NOT NULL UNIQUE
        REFERENCES rockall_score_for_upper_gastrointestinal_bleeding(id) ON DELETE CASCADE,

    age_points INT,
    shock_points INT,
    comorbidity_points INT,
    clinical_score INT,
    diagnosis_points INT,
    stigmata_points INT,
    full_score INT,
    risk_band VARCHAR(20) NOT NULL DEFAULT ''
        CHECK (risk_band IN ('low', 'intermediate', 'high', 'clinical-only', '')),

    graded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_rockall_score_for_upper_gastrointestinal_bleeding_grade_updated_at
    BEFORE UPDATE ON rockall_score_for_upper_gastrointestinal_bleeding_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE rockall_score_for_upper_gastrointestinal_bleeding_grade IS
    'Computed Rockall grading result: per-parameter points, the pre-endoscopy clinical score (0-7), the full post-endoscopy score (0-11 or null), and the derived risk band.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.rockall_score_for_upper_gastrointestinal_bleeding_id IS
    'Foreign key to the parent assessment (unique, 1:1).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.age_points IS
    'Points (0-2) awarded for the age parameter.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.shock_points IS
    'Points (0-2) awarded for the shock parameter, derived from systolic blood pressure and pulse.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.comorbidity_points IS
    'Points (0, 2, or 3) awarded for the comorbidity parameter.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.clinical_score IS
    'Pre-endoscopy clinical Rockall score: age + shock + comorbidity points (0-7).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.diagnosis_points IS
    'Points (0-2) awarded for the diagnosis parameter (full score only).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.stigmata_points IS
    'Points (0 or 2) awarded for the stigmata-of-recent-haemorrhage parameter (full score only).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.full_score IS
    'Full post-endoscopy Rockall score: clinical + diagnosis + stigmata points (0-11); null when endoscopy has not been performed.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.risk_band IS
    'Derived risk band: low (full <= 2, or clinical 0), intermediate (full 3-4), high (full >= 5), or clinical-only (no endoscopy and clinical > 0).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade.graded_at IS
    'Timestamp when the engine last computed the grade.';

-- ========================================================================
-- END 05_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.sql
-- ========================================================================

-- Audit trail of every grading rule that fired during Rockall
-- computation. Each row records one rule firing with the parameter it
-- belongs to, the points it contributed, and a human-readable
-- description.

CREATE TABLE rockall_score_for_upper_gastrointestinal_bleeding_grade_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    rockall_score_for_upper_gastrointestinal_bleeding_grade_id UUID NOT NULL
        REFERENCES rockall_score_for_upper_gastrointestinal_bleeding_grade(id) ON DELETE CASCADE,

    rule_id VARCHAR(40) NOT NULL,
    parameter VARCHAR(20) NOT NULL
        CHECK (parameter IN ('age', 'shock', 'comorbidity', 'diagnosis', 'stigmata', 'band')),
    points INT,
    category VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX rockall_score_for_upper_gastrointestinal_bleeding_grade_rule_grade_id_idx
    ON rockall_score_for_upper_gastrointestinal_bleeding_grade_rule (rockall_score_for_upper_gastrointestinal_bleeding_grade_id);

CREATE TRIGGER trigger_rockall_score_for_upper_gastrointestinal_bleeding_grade_rule_updated_at
    BEFORE UPDATE ON rockall_score_for_upper_gastrointestinal_bleeding_grade_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE rockall_score_for_upper_gastrointestinal_bleeding_grade_rule IS
    'Audit trail of every grading rule that fired during Rockall computation: parameter, points contributed, category, and description.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.rockall_score_for_upper_gastrointestinal_bleeding_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.rule_id IS
    'Stable rule identifier (e.g. R-AGE-2POINT-01).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.parameter IS
    'Scored parameter the rule belongs to: age, shock, comorbidity, diagnosis, stigmata, or band.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.points IS
    'Points contributed by this rule for its parameter.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.category IS
    'Subject category (e.g. threshold-band, risk-band).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.description IS
    'Human-readable description of why the rule fired.';

-- ========================================================================
-- END 06_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.sql
-- ========================================================================

-- Red-flag issues that fire independently of the total score, with
-- priority and a suggested action for the clinical team.

CREATE TABLE rockall_score_for_upper_gastrointestinal_bleeding_grade_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    rockall_score_for_upper_gastrointestinal_bleeding_grade_id UUID NOT NULL
        REFERENCES rockall_score_for_upper_gastrointestinal_bleeding_grade(id) ON DELETE CASCADE,

    flag_id VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT ''
        CHECK (category IN (
            'high-mortality-risk',
            'shock',
            'high-risk-stigmata',
            'upper-gi-malignancy',
            'incomplete',
            'other',
            ''
        )),
    priority VARCHAR(10) NOT NULL DEFAULT ''
        CHECK (priority IN ('low', 'medium', 'high', '')),
    description VARCHAR(500) NOT NULL DEFAULT '',
    suggested_action VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE INDEX rockall_score_for_upper_gastrointestinal_bleeding_grade_flag_grade_id_idx
    ON rockall_score_for_upper_gastrointestinal_bleeding_grade_flag (rockall_score_for_upper_gastrointestinal_bleeding_grade_id);

CREATE TRIGGER trigger_rockall_score_for_upper_gastrointestinal_bleeding_grade_flag_updated_at
    BEFORE UPDATE ON rockall_score_for_upper_gastrointestinal_bleeding_grade_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE rockall_score_for_upper_gastrointestinal_bleeding_grade_flag IS
    'Red-flag issues that fire independently of the total score, with priority and a suggested action for the clinical team.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.created_at IS
    'Timestamp when the row was created.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.updated_at IS
    'Timestamp when the row was most recently updated.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.deleted_at IS
    'Timestamp when the row was soft-deleted.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.rockall_score_for_upper_gastrointestinal_bleeding_grade_id IS
    'Foreign key to the parent grade.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.flag_id IS
    'Stable flag identifier (e.g. F-HIGH-MORTALITY-RISK-001).';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.category IS
    'Flag category: high-mortality-risk, shock, high-risk-stigmata, upper-gi-malignancy, incomplete, or other.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.priority IS
    'Priority: low, medium, high.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.description IS
    'Human-readable description of what fired the flag.';
COMMENT ON COLUMN rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.suggested_action IS
    'Suggested clinical action (e.g. "admit, monitor, arrange endoscopic intervention").';

-- ========================================================================
-- END 07_create_table_rockall_score_for_upper_gastrointestinal_bleeding_grade_flag.sql
-- ========================================================================
