<!ELEMENT genetic_test_result (id,created_at,updated_at,deleted_at,patient_id,clinician_id,originating_request_reference,report_status,performed_date,reported_date,test_type,genes_tested,sample_type,clinical_history,inheritance_pattern,variants_detected,variant_classification,zygosity,pathogenic_variant_found,vus_found,carrier_status_positive,secondary_finding,no_clinically_significant_variant,interpretation,impression,reporting_category,recommended_cascade_testing,recommended_follow_up,critical_result_communicated,reported_to)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT originating_request_reference (#PCDATA)>
<!ELEMENT report_status (#PCDATA)>
<!ELEMENT performed_date (#PCDATA)>
<!ELEMENT reported_date (#PCDATA)>
<!ELEMENT test_type (#PCDATA)>
<!ELEMENT genes_tested (#PCDATA)>
<!ELEMENT sample_type (#PCDATA)>
<!ELEMENT clinical_history (#PCDATA)>
<!ELEMENT inheritance_pattern (#PCDATA)>
<!ELEMENT variants_detected (#PCDATA)>
<!ELEMENT variant_classification (#PCDATA)>
<!ELEMENT zygosity (#PCDATA)>
<!ELEMENT pathogenic_variant_found (#PCDATA)>
<!ELEMENT vus_found (#PCDATA)>
<!ELEMENT carrier_status_positive (#PCDATA)>
<!ELEMENT secondary_finding (#PCDATA)>
<!ELEMENT no_clinically_significant_variant (#PCDATA)>
<!ELEMENT interpretation (#PCDATA)>
<!ELEMENT impression (#PCDATA)>
<!ELEMENT reporting_category (#PCDATA)>
<!ELEMENT recommended_cascade_testing (#PCDATA)>
<!ELEMENT recommended_follow_up (#PCDATA)>
<!ELEMENT critical_result_communicated (#PCDATA)>
<!ELEMENT reported_to (#PCDATA)>
