<!ELEMENT electroencephalogram_test_request (id,created_at,updated_at,deleted_at,patient_id,clinician_id,status,site_name,setting,referral_date,requested_by_date,eeg_type,primary_indication,clinical_question,relevant_history,seizure_frequency,first_seizure,known_epilepsy,current_antiepileptics,recent_seizure,suspected_status_epilepticus,urgency,supervising_consultant,requester_contact,notes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT patient_id (#PCDATA)>
<!ELEMENT clinician_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT site_name (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT referral_date (#PCDATA)>
<!ELEMENT requested_by_date (#PCDATA)>
<!ELEMENT eeg_type (#PCDATA)>
<!ELEMENT primary_indication (#PCDATA)>
<!ELEMENT clinical_question (#PCDATA)>
<!ELEMENT relevant_history (#PCDATA)>
<!ELEMENT seizure_frequency (#PCDATA)>
<!ELEMENT first_seizure (#PCDATA)>
<!ELEMENT known_epilepsy (#PCDATA)>
<!ELEMENT current_antiepileptics (#PCDATA)>
<!ELEMENT recent_seizure (#PCDATA)>
<!ELEMENT suspected_status_epilepticus (#PCDATA)>
<!ELEMENT urgency (#PCDATA)>
<!ELEMENT supervising_consultant (#PCDATA)>
<!ELEMENT requester_contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
