mod users;

mod patients;
mod practitioners;
mod gi_surgery_waiting_list_cards;
mod gi_surgery_waiting_list_card_appointments;
mod gi_surgery_waiting_list_card_grades;
mod gi_surgery_waiting_list_card_grade_rules;
mod gi_surgery_waiting_list_card_grade_flags;