mod users;

mod patients;
mod practitioners;
mod lab_med_waiting_list_cards;
mod lab_med_waiting_list_card_appointments;
mod lab_med_waiting_list_card_grades;
mod lab_med_waiting_list_card_grade_rules;
mod lab_med_waiting_list_card_grade_flags;