mod users;

mod patients;
mod practitioners;
mod internal_med_waiting_list_cards;
mod internal_med_waiting_list_card_appointments;
mod internal_med_waiting_list_card_grades;
mod internal_med_waiting_list_card_grade_rules;
mod internal_med_waiting_list_card_grade_flags;