mod users;

mod patients;
mod practitioners;
mod clin_neurophys_waiting_list_cards;
mod clin_neurophys_waiting_list_card_appointments;
mod clin_neurophys_waiting_list_card_grades;
mod clin_neurophys_waiting_list_card_grade_rules;
mod clin_neurophys_waiting_list_card_grade_flags;