<!ELEMENT model_for_end_stage_liver_disease_score_grade_rule (id,created_at,updated_at,deleted_at,model_for_end_stage_liver_disease_score_grade_id,rule_id,component,contribution,category,description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>
<!ELEMENT deleted_at (#PCDATA)>
<!ELEMENT model_for_end_stage_liver_disease_score_grade_id (#PCDATA)>
<!ELEMENT rule_id (#PCDATA)>
<!ELEMENT component (#PCDATA)>
<!ELEMENT contribution (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT description (#PCDATA)>
