import type { FitNoteSummary } from '$lib/types.js';

/**
 * Twelve realistic fit-note records covering every recommendation, both
 * fitness categories, all five adaptation intensities, and a representative
 * spread of period-compliance bands and safety-flag counts.
 *
 * Mirrors `front-end-dashboard-with-html/js/sample-data.js` row-for-row so
 * the HTML and SvelteKit dashboards show identical demo content.
 */
export const SAMPLE_FIT_NOTES: FitNoteSummary[] = [
  {
    id: 'FN001',
    patientName: 'Alice Smith',
    nhsNumber: '123 456 7890',
    issuerProfession: 'doctor',
    issuerName: 'Dr B Adams',
    assessmentDate: '2026-04-20',
    diagnosis: 'Lower back pain, mechanical',
    fitnessCategory: 'may_be_fit',
    adaptationIntensity: 'light',
    adaptationCount: 1,
    periodDays: 14,
    periodCompliance: 'compliant',
    recommendation: 'standard',
    safetyFlagCount: 1,
  },
  {
    id: 'FN002',
    patientName: 'Bob Jones',
    nhsNumber: '234 567 8901',
    issuerProfession: 'doctor',
    issuerName: 'Dr C Patel',
    assessmentDate: '2026-04-21',
    diagnosis: 'Acute bronchitis',
    fitnessCategory: 'not_fit',
    adaptationIntensity: '',
    adaptationCount: 0,
    periodDays: 5,
    periodCompliance: 'self_cert_range',
    recommendation: 'standard',
    safetyFlagCount: 1,
  },
  {
    id: 'FN003',
    patientName: 'Carol Lee',
    nhsNumber: '345 678 9012',
    issuerProfession: 'occupational_therapist',
    issuerName: 'Ms D Williams (OT)',
    assessmentDate: '2026-04-22',
    diagnosis: 'Post-operative recovery, shoulder',
    fitnessCategory: 'may_be_fit',
    adaptationIntensity: 'substantial',
    adaptationCount: 3,
    periodDays: 28,
    periodCompliance: 'compliant',
    recommendation: 'refer_occupational_health',
    safetyFlagCount: 2,
  },
  {
    id: 'FN004',
    patientName: 'David Brown',
    nhsNumber: '456 789 0123',
    issuerProfession: 'doctor',
    issuerName: 'Dr E Khan',
    assessmentDate: '2026-04-22',
    diagnosis: 'Multiple sclerosis flare',
    fitnessCategory: 'not_fit',
    adaptationIntensity: '',
    adaptationCount: 0,
    periodDays: 90,
    periodCompliance: 'long_term',
    recommendation: 'refer_access_to_work',
    safetyFlagCount: 3,
  },
  {
    id: 'FN005',
    patientName: 'Eshan Patel',
    nhsNumber: '567 890 1234',
    issuerProfession: 'physiotherapist',
    issuerName: 'Mr F O\u2019Connor (Physio)',
    assessmentDate: '2026-04-23',
    diagnosis: 'Achilles tendinopathy',
    fitnessCategory: 'may_be_fit',
    adaptationIntensity: 'moderate',
    adaptationCount: 2,
    periodDays: 21,
    periodCompliance: 'compliant',
    recommendation: 'standard',
    safetyFlagCount: 1,
  },
  {
    id: 'FN006',
    patientName: 'Fiona Murphy',
    nhsNumber: '678 901 2345',
    issuerProfession: 'doctor',
    issuerName: 'Dr G Hassan',
    assessmentDate: '2026-04-24',
    diagnosis: 'Depressive episode, moderate',
    fitnessCategory: 'not_fit',
    adaptationIntensity: '',
    adaptationCount: 0,
    periodDays: 56,
    periodCompliance: 'long_term',
    recommendation: 'refer_occupational_health',
    safetyFlagCount: 3,
  },
  {
    id: 'FN007',
    patientName: 'Grace Nguyen',
    nhsNumber: '789 012 3456',
    issuerProfession: 'nurse',
    issuerName: 'Ms H Ito (RN)',
    assessmentDate: '2026-04-24',
    diagnosis: 'Viral gastroenteritis',
    fitnessCategory: 'not_fit',
    adaptationIntensity: '',
    adaptationCount: 0,
    periodDays: 4,
    periodCompliance: 'self_cert_range',
    recommendation: 'standard',
    safetyFlagCount: 2,
  },
  {
    id: 'FN008',
    patientName: 'Henry Rossi',
    nhsNumber: '890 123 4567',
    issuerProfession: 'doctor',
    issuerName: 'Dr I Johansson',
    assessmentDate: '2026-04-25',
    diagnosis: 'Stage III colorectal cancer',
    fitnessCategory: 'not_fit',
    adaptationIntensity: '',
    adaptationCount: 0,
    periodDays: 200,
    periodCompliance: 'very_long_term',
    recommendation: 'refer_access_to_work',
    safetyFlagCount: 4,
  },
  {
    id: 'FN009',
    patientName: 'Isabel Okafor',
    nhsNumber: '901 234 5678',
    issuerProfession: 'doctor',
    issuerName: 'Dr J Kowalski',
    assessmentDate: '2026-04-25',
    diagnosis: 'Migraine with aura',
    fitnessCategory: 'may_be_fit',
    adaptationIntensity: 'comprehensive',
    adaptationCount: 4,
    periodDays: 42,
    periodCompliance: 'long_term',
    recommendation: 'refer_occupational_health',
    safetyFlagCount: 2,
  },
  {
    id: 'FN010',
    patientName: 'Jamal Khan',
    nhsNumber: '012 345 6789',
    issuerProfession: 'pharmacist',
    issuerName: 'Mr K Lopez (Pharm)',
    assessmentDate: '2026-04-26',
    diagnosis: '',
    fitnessCategory: 'not_fit',
    adaptationIntensity: '',
    adaptationCount: 0,
    periodDays: 14,
    periodCompliance: 'compliant',
    recommendation: 'review_for_validity',
    safetyFlagCount: 3,
  },
  {
    id: 'FN011',
    patientName: 'Kathleen Wilson',
    nhsNumber: '135 791 2468',
    issuerProfession: 'doctor',
    issuerName: 'Dr L Martinez',
    assessmentDate: '2026-04-27',
    diagnosis: 'COPD, exacerbation',
    fitnessCategory: 'not_fit',
    adaptationIntensity: '',
    adaptationCount: 0,
    periodDays: 120,
    periodCompliance: 'exceeds_initial_max',
    recommendation: 'refer_employment_advisor',
    safetyFlagCount: 4,
  },
  {
    id: 'FN012',
    patientName: 'Liam Davies',
    nhsNumber: '246 802 1357',
    issuerProfession: 'doctor',
    issuerName: 'Dr M Nakamura',
    assessmentDate: '2026-04-28',
    diagnosis: 'Carpal tunnel syndrome, right',
    fitnessCategory: 'may_be_fit',
    adaptationIntensity: 'moderate',
    adaptationCount: 2,
    periodDays: 10,
    periodCompliance: 'compliant',
    recommendation: 'standard',
    safetyFlagCount: 0,
  },
];
