//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::prev_med_waiting_list_card_appointments::Entity as PrevMedWaitingListCardAppointments;
pub use super::prev_med_waiting_list_card_grade_flags::Entity as PrevMedWaitingListCardGradeFlags;
pub use super::prev_med_waiting_list_card_grade_rules::Entity as PrevMedWaitingListCardGradeRules;
pub use super::prev_med_waiting_list_card_grades::Entity as PrevMedWaitingListCardGrades;
pub use super::prev_med_waiting_list_cards::Entity as PrevMedWaitingListCards;
pub use super::patients::Entity as Patients;
pub use super::practitioners::Entity as Practitioners;
pub use super::users::Entity as Users;
