mod users;

mod patients;
mod practitioners;
mod vasc_surgery_waiting_list_cards;
mod vasc_surgery_waiting_list_card_appointments;
mod vasc_surgery_waiting_list_card_grades;
mod vasc_surgery_waiting_list_card_grade_rules;
mod vasc_surgery_waiting_list_card_grade_flags;