mod users;

mod patients;
mod practitioners;
mod nephrology_waiting_list_cards;
mod nephrology_waiting_list_card_appointments;
mod nephrology_waiting_list_card_grades;
mod nephrology_waiting_list_card_grade_rules;
mod nephrology_waiting_list_card_grade_flags;