mod users;

mod patients;
mod practitioners;
mod oncology_waiting_list_cards;
mod oncology_waiting_list_card_appointments;
mod oncology_waiting_list_card_grades;
mod oncology_waiting_list_card_grade_rules;
mod oncology_waiting_list_card_grade_flags;