#!/bin/sh
set -euf

form_kebab_case=united-kingdom-statement-of-fitness-for-work
form_snake_case=united_kingdom_statement_of_fitness_for_work

createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_development" || :
createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_test" || :
createdb --host=localhost --port=5432 --username=loco --owner=loco "${form_snake_case}_production" || :

loco new --name "${form_kebab_case}" --db postgres --bg async --assets none
cd "${form_kebab_case}"

cargo loco generate scaffold patient \
    deleted_at:ts \
    name:string! \
    birth_date:date \
    email:text \
    phone:text \
    postal_address_as_full_text:text \
    country_as_iso_3166_1_alpha_2:string \
    postcode:text \
    united_kingdom_nhs_number:string^ \
    employer_name:text \
    occupation:text \
    --api

cargo loco generate scaffold clinician \
    deleted_at:ts \
    name:text! \
    email:text \
    phone:text \
    postal_address_as_full_text:text \
    country_as_iso_3166_1_alpha_2:string \
    postcode:text \
    profession:text! \
    registration_body:text! \
    registration_number:text! \
    is_private_practice:string! \
    --api

cargo loco generate scaffold medical_practice \
    deleted_at:ts \
    name:text! \
    postal_address_as_full_text:text! \
    country_as_iso_3166_1_alpha_2:string \
    postcode:text \
    phone:text \
    email:text \
    ods_code:text \
    setting:text! \
    --api

cargo loco generate scaffold united_kingdom_statement_of_fitness_for_work \
    deleted_at:ts \
    patient:references \
    clinician:references \
    medical_practice:references \
    status:string! \
    assessment_date:date \
    assessment_method:string! \
    general_fitness_considered:string! \
    diagnosis_text:text! \
    diagnosis_snomed_code:string! \
    diagnosis_snomed_display:string! \
    diagnosis_category:string! \
    condition_first_recorded_date:date \
    is_automatic_disability:string! \
    is_non_medical:string! \
    fitness_for_work:string! \
    adaptation_phased_return:string! \
    adaptation_altered_hours:string! \
    adaptation_amended_duties:string! \
    adaptation_workplace_adaptations:string! \
    comments:text! \
    period_type:string! \
    period_duration_value:int \
    period_duration_unit:string! \
    period_from:date \
    period_to:date \
    will_assess_again:string! \
    planned_review_date:date \
    issued_at:ts \
    issued_via:string! \
    issue_setting:string! \
    united_kingdom_statement_of_fitness_for_work:references \
    safeguarding_concern:string! \
    safeguarding_notes:text! \
    clinician_signature_svg:text! \
    clinician_signed_at:ts \
    --api

cargo loco generate scaffold united_kingdom_statement_of_fitness_for_work_grade \
    deleted_at:ts \
    united_kingdom_statement_of_fitness_for_work:references \
    fitness_category:string! \
    adaptation_intensity:string! \
    adaptation_count:int! \
    period_days:int \
    period_compliance:string! \
    recommendation:string! \
    is_within_first_six_months_of_condition:string! \
    is_valid:string! \
    grader_notes:text! \
    graded_at:ts! \
    clinician_override:string! \
    clinician_override_reason:string! \
    clinician_final_recommendation:string! \
    --api

cargo loco generate scaffold united_kingdom_statement_of_fitness_for_work_grade_rule \
    deleted_at:ts \
    united_kingdom_statement_of_fitness_for_work_grade:references \
    rule_id:string! \
    rule_set:string! \
    severity:string! \
    description:string! \
    --api

cargo loco generate scaffold united_kingdom_statement_of_fitness_for_work_grade_flag \
    deleted_at:ts \
    united_kingdom_statement_of_fitness_for_work_grade:references \
    flag_id:string! \
    category:string! \
    priority:string! \
    description:string! \
    suggested_action:string! \
    --api
