//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clinicians;
pub mod newborn_and_infant_physical_examination_grade_flags;
pub mod newborn_and_infant_physical_examination_grade_rules;
pub mod newborn_and_infant_physical_examination_grades;
pub mod newborn_and_infant_physical_examinations;
pub mod patients;
pub mod users;
