-- schema.sql
-- Combined schema for form: ergonomic-assessment
--
-- Auto-generated by bin/generate-sql-combined.py from the numbered
-- migration files in this directory. Do not edit by hand — re-run
-- the generator after changing any NN-*.sql file.
--
-- Source files (12):
--   - 00_extensions.sql
--   - 01_create_function_set_updated_at.sql
--   - 04_create_table_ergonomic_assessment.sql
--   - 05_create_table_reba_rule.sql
--   - 06_create_table_grade.sql
--   - 07_create_table_grading_fired_rule.sql
--   - 08_create_table_grading_additional_flag.sql
--   - 10_create_table_patient.sql
--   - 11_create_table_clinician.sql
--   - 90_create_table_grade.sql
--   - 91_create_table_grading_fired_rule.sql
--   - 92_create_table_grading_additional_flag.sql


-- ========================================================================
-- BEGIN 00_extensions.sql
-- ========================================================================

-- pgcrypto provides gen_random_uuid() for UUID primary key generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ========================================================================
-- END 00_extensions.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 01_create_function_set_updated_at.sql
-- ========================================================================

-- set_updated_at() is a reusable trigger function that sets the updated_at
-- column to the current timestamp whenever a row is modified.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that sets updated_at to now() on every UPDATE.';

-- ========================================================================
-- END 01_create_function_set_updated_at.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 04_create_table_ergonomic_assessment.sql
-- ========================================================================

CREATE TABLE assessment (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    -- Foreign key to the patient this assessment belongs to
    patient_id          UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,
    -- Assessment status tracking
    status              TEXT NOT NULL DEFAULT 'in_progress'
                        CHECK (status IN ('in_progress', 'completed', 'reviewed'))
);

-- Index for the most common query: all assessments for a patient
CREATE INDEX index_assessment_patient_id ON assessment(patient_id);

-- Auto-update updated_at on every row change
CREATE TRIGGER trigger_assessment_updated_at
    BEFORE UPDATE ON assessment
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE assessment IS
    'A single ergonomic assessment visit. Child tables hold section-specific data.';
COMMENT ON COLUMN assessment.patient_id IS
    'FK to patient. One patient may have many assessments.';
COMMENT ON COLUMN assessment.status IS
    'Workflow status: in_progress (patient filling in), completed (submitted), reviewed (clinician signed off).';
COMMENT ON COLUMN assessment.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN assessment.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN assessment.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN assessment.deleted_at IS
    'Timestamp when this row was deleted.';

-- ========================================================================
-- END 04_create_table_ergonomic_assessment.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 05_create_table_reba_rule.sql
-- ========================================================================

CREATE TABLE reba_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    -- Human-readable rule code (e.g. 'DM-001'). Stable identifier.
    code TEXT NOT NULL UNIQUE,
    -- Body system or category
    system          TEXT NOT NULL,
    -- Human-readable description
    description     TEXT NOT NULL,
    -- Score contribution when rule fires
    score           INTEGER NOT NULL CHECK (score >= 0 AND score <= 15)
);

COMMENT ON TABLE reba_rule IS
    'Reference table of REBA scoring rules. Each rule has an ID, system, description, and score contribution.';
COMMENT ON COLUMN reba_rule.code IS
    'Human-readable rule code (e.g. DM-001). UNIQUE stable identifier used by application code and audit records.';
COMMENT ON COLUMN reba_rule.system IS
    'Body system or assessment category, e.g. Neck, Trunk, Workstation, Repetition, Manual Handling.';
COMMENT ON COLUMN reba_rule.description IS
    'Human-readable description of the condition this rule detects.';
COMMENT ON COLUMN reba_rule.score IS
    'REBA score contribution when the rule fires (0-15).';

COMMENT ON COLUMN reba_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN reba_rule.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN reba_rule.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN reba_rule.deleted_at IS
    'Timestamp when this row was deleted.';
-- ─── Seed REBA rules ─────────────────────────────────────
INSERT INTO reba_rule (code, system, description, score) VALUES
    ('NECK-001', 'Neck', 'Neck flexed 0-20 degrees', 1),
    ('NECK-002', 'Neck', 'Neck flexed >20 degrees', 2),
    ('NECK-003', 'Neck', 'Neck extended', 2),
    ('NECK-004', 'Neck', 'Neck twisted or side-bending', 3),
    ('TRUNK-001', 'Trunk', 'Trunk upright (neutral)', 1),
    ('TRUNK-002', 'Trunk', 'Trunk flexed 0-20 degrees', 2),
    ('TRUNK-003', 'Trunk', 'Trunk flexed 20-60 degrees', 3),
    ('TRUNK-004', 'Trunk', 'Trunk flexed >60 degrees', 4),
    ('TRUNK-005', 'Trunk', 'Trunk twisted', 3),
    ('SHLDR-001', 'Shoulder', 'Shoulders raised or hunched', 2),
    ('SHLDR-002', 'Shoulder', 'Arms abducted', 2),
    ('SHLDR-003', 'Shoulder', 'Arms flexed forward', 3),
    ('WRIST-001', 'Wrist', 'Wrist flexed', 2),
    ('WRIST-002', 'Wrist', 'Wrist extended', 2),
    ('WRIST-003', 'Wrist', 'Wrist ulnar deviation', 3),
    ('WRIST-004', 'Wrist', 'Wrist radial deviation', 2),
    ('POST-001', 'Posture', 'Slouched sitting posture', 2),
    ('POST-002', 'Posture', 'Leaning forward while sitting', 2),
    ('POST-003', 'Posture', 'Asymmetric standing posture', 2),
    ('WS-001', 'Workstation', 'Desk height incorrect', 1),
    ('WS-002', 'Workstation', 'Monitor not at eye level', 1),
    ('WS-003', 'Workstation', 'Keyboard placement incorrect', 1),
    ('WS-004', 'Workstation', 'Mouse awkward reach', 1),
    ('REP-001', 'Repetition', 'Constant repetitive tasks', 2),
    ('REP-002', 'Repetition', 'Frequent repetitive tasks', 1),
    ('REP-003', 'Repetition', 'Heavy force required', 3),
    ('REP-004', 'Repetition', 'Moderate force required', 2),
    ('MH-001', 'Manual Handling', 'Heavy load lifting (>20kg)', 3),
    ('MH-002', 'Manual Handling', 'Moderate load lifting (10-20kg)', 2),
    ('MH-003', 'Manual Handling', 'Frequent lifting required', 2),
    ('MH-004', 'Manual Handling', 'Heavy push/pull forces', 2),
    ('VIB-001', 'Vibration', 'Vibration exposure present', 2),
    ('SYM-001', 'Symptoms', 'Severe pain (8-10)', 3),
    ('SYM-002', 'Symptoms', 'Moderate pain (5-7)', 2),
    ('SYM-003', 'Symptoms', 'Unable to work due to symptoms', 3),
    ('SYM-004', 'Symptoms', 'Severe impact on work', 2);

-- ========================================================================
-- END 05_create_table_reba_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 06_create_table_grade.sql
-- ========================================================================

CREATE TABLE grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    assessment_id           UUID NOT NULL UNIQUE REFERENCES assessment(id) ON DELETE CASCADE,
    -- Computed REBA score (1-15)
    reba_score              INTEGER NOT NULL CHECK (reba_score >= 1 AND reba_score <= 15),
    -- Risk level derived from REBA score
    risk_level              TEXT NOT NULL
                            CHECK (risk_level IN (
                                'Negligible risk', 'Low risk', 'Medium risk',
                                'High risk', 'Very high risk'
                            )),
    -- Optional clinician override
    reba_score_override     INTEGER CHECK (reba_score_override IS NULL OR (reba_score_override >= 1 AND reba_score_override <= 15)),
    override_reason         TEXT NOT NULL DEFAULT '',
    -- When the grading was computed
    graded_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- If override is set,
    a reason must be provided
    CONSTRAINT chk_override_reason CHECK (
        reba_score_override IS NULL OR override_reason != ''
    )
);

CREATE TRIGGER trigger_grade_updated_at
    BEFORE UPDATE ON grade
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE grade IS
    'Computed REBA grading result for an assessment. Includes optional clinician override.';
COMMENT ON COLUMN grade.reba_score IS
    'Computed REBA score (1-15), sum of fired rule scores clamped to range.';
COMMENT ON COLUMN grade.risk_level IS
    'Risk level derived from REBA score: Negligible, Low, Medium, High, or Very high risk.';
COMMENT ON COLUMN grade.reba_score_override IS
    'Clinician override of the computed REBA score. NULL if no override.';
COMMENT ON COLUMN grade.override_reason IS
    'Required reason text when reba_score_override is set.';
COMMENT ON COLUMN grade.graded_at IS
    'Timestamp when the REBA grading was computed.';

COMMENT ON COLUMN grade.assessment_id IS
    'Foreign key to the assessment table.';
COMMENT ON COLUMN grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grade.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN grade.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN grade.deleted_at IS
    'Timestamp when this row was deleted.';

-- ========================================================================
-- END 06_create_table_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 07_create_table_grading_fired_rule.sql
-- ========================================================================

CREATE TABLE grading_fired_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    grade_id   UUID NOT NULL REFERENCES grade(id) ON DELETE CASCADE,
    -- The rule that fired
    rule_id             TEXT NOT NULL REFERENCES reba_rule(id),
    -- Denormalized fields from the rule at time of grading
    system              TEXT NOT NULL,
    description         TEXT NOT NULL,
    score               INTEGER NOT NULL CHECK (score >= 0 AND score <= 15),
    -- Prevent duplicate rule entries per grading
    CONSTRAINT uq_grading_fired_rule UNIQUE (grade_id, rule_id)
);

CREATE INDEX index_grading_fired_rule_result ON grading_fired_rule(grade_id);

COMMENT ON TABLE grading_fired_rule IS
    'Denormalized record of each REBA rule that fired during grading. Preserves exact context for clinical audit.';
COMMENT ON COLUMN grading_fired_rule.grade_id IS
    'FK to the grading result this fired rule belongs to.';
COMMENT ON COLUMN grading_fired_rule.rule_id IS
    'FK to the REBA rule that fired.';
COMMENT ON COLUMN grading_fired_rule.system IS
    'Body system or category (denormalized from reba_rule at grading time).';
COMMENT ON COLUMN grading_fired_rule.description IS
    'Rule description (denormalized from reba_rule at grading time).';
COMMENT ON COLUMN grading_fired_rule.score IS
    'Score contribution (denormalized from reba_rule at grading time).';

COMMENT ON COLUMN grading_fired_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grading_fired_rule.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN grading_fired_rule.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN grading_fired_rule.deleted_at IS
    'Timestamp when this row was deleted.';

-- ========================================================================
-- END 07_create_table_grading_fired_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 08_create_table_grading_additional_flag.sql
-- ========================================================================

CREATE TABLE grading_additional_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    grade_id   UUID NOT NULL REFERENCES grade(id) ON DELETE CASCADE,
    -- Flag identifier (e.g. FLAG-POSTURE-001, FLAG-RSI-001)
    flag_id             TEXT NOT NULL,
    -- Category of the flag
    category            TEXT NOT NULL,
    -- Human-readable alert message
    message             TEXT NOT NULL,
    -- Priority level
    priority            TEXT NOT NULL
                        CHECK (priority IN ('high', 'medium', 'low')),
    -- Prevent duplicate flags per grading
    CONSTRAINT uq_grading_additional_flag UNIQUE (grade_id, flag_id)
);

CREATE INDEX index_grading_additional_flag_result ON grading_additional_flag(grade_id);

COMMENT ON TABLE grading_additional_flag IS
    'Additional safety flags raised during grading, independent of REBA score. Actionable alerts for clinician review.';
COMMENT ON COLUMN grading_additional_flag.flag_id IS
    'Flag identifier, e.g. FLAG-POSTURE-001, FLAG-RSI-001, FLAG-MANUAL-001.';
COMMENT ON COLUMN grading_additional_flag.category IS
    'Category of the flag, e.g. Posture, Medical History, Manual Handling, Symptoms, Psychosocial.';
COMMENT ON COLUMN grading_additional_flag.message IS
    'Human-readable alert message describing the flagged condition.';
COMMENT ON COLUMN grading_additional_flag.priority IS
    'Flag priority: high (urgent action), medium (review needed), low (informational).';

COMMENT ON COLUMN grading_additional_flag.grade_id IS
    'Foreign key to the grade table.';
COMMENT ON COLUMN grading_additional_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grading_additional_flag.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN grading_additional_flag.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN grading_additional_flag.deleted_at IS
    'Timestamp when this row was deleted.';

-- ========================================================================
-- END 08_create_table_grading_additional_flag.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 10_create_table_patient.sql
-- ========================================================================

-- Patient demographic information

CREATE TABLE patient (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    united_kingdom_nhs_number VARCHAR(20) UNIQUE,
    waist_as_cm NUMERIC(5,1),
    height_as_cm NUMERIC(5,1),
    weight_as_kg NUMERIC(5,1),
    body_mass_index NUMERIC(4,1),
    waist_height_ratio NUMERIC(4,1),
    vo2_max  NUMERIC(4,1)
);

CREATE TRIGGER trigger_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Patient';
COMMENT ON COLUMN patient.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN patient.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN patient.updated_at IS
    'Timestamp when the record was deleted a.k.a. soft-deleted.';
COMMENT ON COLUMN patient.name IS
    'Name.';
COMMENT ON COLUMN patient.birth_date IS
    'Birth date.';
COMMENT ON COLUMN patient.email IS
    'Email address.';
COMMENT ON COLUMN patient.phone IS
    'Phone number.';
COMMENT ON COLUMN patient.postal_address_as_full_text IS
    'Postal address as full text.';
COMMENT ON COLUMN patient.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2 format, such as for validating the postal address.';
COMMENT ON COLUMN patient.postcode IS
    'Postal code, such as for validating the postal address.';
COMMENT ON COLUMN patient.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';
COMMENT ON COLUMN patient.waist_as_cm IS
    'Waist circumference measurement in cm, such as for calculating waist-height ratio (WHR).';
COMMENT ON COLUMN patient.height_as_cm IS
    'Height measurement in cm, such as for calculating waist-height ratio (WHR).';
COMMENT ON COLUMN patient.body_mass_index IS
    'Body mass index (BMI) measurement.';
COMMENT ON COLUMN patient.waist_height_ratio IS
    'Waist-height ratio (WHR) measurement.';
COMMENT ON COLUMN patient.vo2_max IS
    'VO2 max measurement.';

CREATE INDEX patient_index_gto
    ON patient
    USING GIN ((
        name
    ) gin_trgm_ops);

-- ========================================================================
-- END 10_create_table_patient.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 11_create_table_clinician.sql
-- ========================================================================

-- Clinician employee information provided by the employer.

CREATE TABLE clinician (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    postal_address_as_full_text TEXT,
    country_as_iso_3166_1_alpha_2 CHAR(2),
    postcode TEXT,
    role TEXT NOT NULL DEFAULT '' CHECK (clinician_role IN ( 'anaesthetist', 'surgeon', 'preop-nurse', 'perioperative-physician', 'geriatrician', 'pharmacist', 'other', '' )),
    registration_body TEXT NOT NULL DEFAULT '' CHECK (registration_body IN ('GMC', 'NMC', 'HCPC', 'GPhC', 'other', '')),
    registration_number TEXT NOT NULL DEFAULT '',
    united_kingdom_nhs_number CHAR(12)UNIQUE
);

CREATE TRIGGER trigger_clinician_updated_at
    BEFORE UPDATE ON clinician
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE clinician IS
    'Clinician';
COMMENT ON COLUMN clinician.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN clinician.created_at IS
    'Timestamp when the record was created.';
COMMENT ON COLUMN clinician.updated_at IS
    'Timestamp when the record was updated most-recently.';
COMMENT ON COLUMN clinician.name IS
    'Name.';
COMMENT ON COLUMN clinician.email IS
    'Email address.';
COMMENT ON COLUMN clinician.phone IS
    'Phone number.';
COMMENT ON COLUMN clinician.postal_address_as_full_text IS
    'Postal address as full text.';
COMMENT ON COLUMN clinician.country_as_iso_3166_1_alpha_2 IS
    'Country as ISO 3166-1 alpha-2 format, such as for validating the postal address.';
COMMENT ON COLUMN clinician.postcode IS
    'Postal code, such as for validating the postal address.';
COMMENT ON COLUMN clinician.role IS
    'Clinician role.';
COMMENT ON COLUMN clinician.registration_body IS
    'Clinician registration body.';
COMMENT ON COLUMN clinician.registration_number IS
    'Clinician registration number.';
COMMENT ON COLUMN clinician.united_kingdom_nhs_number IS
    'United Kingdom NHS number, unique per person.';

CREATE INDEX clinician_index_gto
    ON clinician
    USING GIN ((
        name
    ) gin_trgm_ops);

-- ========================================================================
-- END 11_create_table_clinician.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 90_create_table_grade.sql
-- ========================================================================

CREATE TABLE grade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    assessment_id           UUID NOT NULL UNIQUE REFERENCES assessment(id) ON DELETE CASCADE,
    -- Computed REBA score (1-15)
    reba_score              INTEGER NOT NULL CHECK (reba_score >= 1 AND reba_score <= 15),
    -- Risk level derived from REBA score
    risk_level              TEXT NOT NULL
                            CHECK (risk_level IN (
                                'Negligible risk', 'Low risk', 'Medium risk',
                                'High risk', 'Very high risk'
                            )),
    -- Optional clinician override
    reba_score_override     INTEGER CHECK (reba_score_override IS NULL OR (reba_score_override >= 1 AND reba_score_override <= 15)),
    override_reason         TEXT NOT NULL DEFAULT '',
    -- When the grading was computed
    graded_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- If override is set,
    a reason must be provided
    CONSTRAINT chk_override_reason CHECK (
        reba_score_override IS NULL OR override_reason != ''
    )
);

CREATE TRIGGER trigger_grade_updated_at
    BEFORE UPDATE ON grade
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE grade IS
    'Computed REBA grading result for an assessment. Includes optional clinician override.';
COMMENT ON COLUMN grade.reba_score IS
    'Computed REBA score (1-15), sum of fired rule scores clamped to range.';
COMMENT ON COLUMN grade.risk_level IS
    'Risk level derived from REBA score: Negligible, Low, Medium, High, or Very high risk.';
COMMENT ON COLUMN grade.reba_score_override IS
    'Clinician override of the computed REBA score. NULL if no override.';
COMMENT ON COLUMN grade.override_reason IS
    'Required reason text when reba_score_override is set.';
COMMENT ON COLUMN grade.graded_at IS
    'Timestamp when the REBA grading was computed.';

COMMENT ON COLUMN grade.assessment_id IS
    'Foreign key to the assessment table.';
COMMENT ON COLUMN grade.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grade.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN grade.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN grade.deleted_at IS
    'Timestamp when this row was deleted.';

-- ========================================================================
-- END 90_create_table_grade.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 91_create_table_grading_fired_rule.sql
-- ========================================================================

CREATE TABLE grading_fired_rule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    grade_id   UUID NOT NULL REFERENCES grade(id) ON DELETE CASCADE,
    -- The rule that fired
    rule_id             TEXT NOT NULL REFERENCES reba_rule(id),
    -- Denormalized fields from the rule at time of grading
    system              TEXT NOT NULL,
    description         TEXT NOT NULL,
    score               INTEGER NOT NULL CHECK (score >= 0 AND score <= 15),
    -- Prevent duplicate rule entries per grading
    CONSTRAINT uq_grading_fired_rule UNIQUE (grade_id, rule_id)
);

CREATE INDEX index_grading_fired_rule_result ON grading_fired_rule(grade_id);

COMMENT ON TABLE grading_fired_rule IS
    'Denormalized record of each REBA rule that fired during grading. Preserves exact context for clinical audit.';
COMMENT ON COLUMN grading_fired_rule.grade_id IS
    'FK to the grading result this fired rule belongs to.';
COMMENT ON COLUMN grading_fired_rule.rule_id IS
    'FK to the REBA rule that fired.';
COMMENT ON COLUMN grading_fired_rule.system IS
    'Body system or category (denormalized from reba_rule at grading time).';
COMMENT ON COLUMN grading_fired_rule.description IS
    'Rule description (denormalized from reba_rule at grading time).';
COMMENT ON COLUMN grading_fired_rule.score IS
    'Score contribution (denormalized from reba_rule at grading time).';

COMMENT ON COLUMN grading_fired_rule.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grading_fired_rule.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN grading_fired_rule.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN grading_fired_rule.deleted_at IS
    'Timestamp when this row was deleted.';

-- ========================================================================
-- END 91_create_table_grading_fired_rule.sql
-- ========================================================================

-- ========================================================================
-- BEGIN 92_create_table_grading_additional_flag.sql
-- ========================================================================

CREATE TABLE grading_additional_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    grade_id   UUID NOT NULL REFERENCES grade(id) ON DELETE CASCADE,
    -- Flag identifier (e.g. FLAG-POSTURE-001, FLAG-RSI-001)
    flag_id             TEXT NOT NULL,
    -- Category of the flag
    category            TEXT NOT NULL,
    -- Human-readable alert message
    message             TEXT NOT NULL,
    -- Priority level
    priority            TEXT NOT NULL
                        CHECK (priority IN ('high', 'medium', 'low')),
    -- Prevent duplicate flags per grading
    CONSTRAINT uq_grading_additional_flag UNIQUE (grade_id, flag_id)
);

CREATE INDEX index_grading_additional_flag_result ON grading_additional_flag(grade_id);

COMMENT ON TABLE grading_additional_flag IS
    'Additional safety flags raised during grading, independent of REBA score. Actionable alerts for clinician review.';
COMMENT ON COLUMN grading_additional_flag.flag_id IS
    'Flag identifier, e.g. FLAG-POSTURE-001, FLAG-RSI-001, FLAG-MANUAL-001.';
COMMENT ON COLUMN grading_additional_flag.category IS
    'Category of the flag, e.g. Posture, Medical History, Manual Handling, Symptoms, Psychosocial.';
COMMENT ON COLUMN grading_additional_flag.message IS
    'Human-readable alert message describing the flagged condition.';
COMMENT ON COLUMN grading_additional_flag.priority IS
    'Flag priority: high (urgent action), medium (review needed), low (informational).';

COMMENT ON COLUMN grading_additional_flag.grade_id IS
    'Foreign key to the grade table.';
COMMENT ON COLUMN grading_additional_flag.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN grading_additional_flag.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN grading_additional_flag.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN grading_additional_flag.deleted_at IS
    'Timestamp when this row was deleted.';

-- ========================================================================
-- END 92_create_table_grading_additional_flag.sql
-- ========================================================================

COMMENT ON COLUMN grade.a IS
    'A.';
COMMENT ON COLUMN patient.deleted_at IS
    'Soft-delete timestamp; NULL when the row is live.';
COMMENT ON COLUMN patient.weight_as_kg IS
    'Weight as kg.';
COMMENT ON COLUMN clinician.deleted_at IS
    'Soft-delete timestamp; NULL when the row is live.';
COMMENT ON COLUMN grade.a IS
    'A.';
